### ISSUE TITLE
An Efficient Way to Trap Signals and Errors

### ISSUE THREAD

**Issue by loretoparisi** [nodejs/help#1003]
I have an express server that handles tcp connections to `Redis`, `mysql`, `couchbase` drivers. I have defined an error handler to trap exceptions in order to gracefully exit:

```javascript
Platform.prototype.addExitHandler = function (exitCallback) {
            var self = this;
            process.stdin.resume(); //so the program will not close instantly
            const trapHandler = function (options, error) {
                self.logger.warn("addExitHandler process:%d trapped: %s", process.pid, options.type);
                if (error) {
                    self.logger.error("trapped error code:%d message:%s stack:%@:\n%@", error.code, error.message, error.stack);
                }
                return process.emit('cleanup',error);
            }//exitHandler
            var signalsOptions = {
                // custom handler
                'cleanup': { params: { type: 'cleanup' }, callback: exitCallback },
                // catch app is closing 
                'exit': { params: { type: 'exit' }, callback: trapHandler },
                // catches ctrl+c event
                'SIGINT': { params: { type: 'sigint' }, callback: trapHandler },
                // catches uncaught exceptions
                'uncaughtException': { params: { type: 'uncaughtException' }, callback: trapHandler }
            };
            Object.keys(signalsOptions).forEach(signal => {
                var params = signalsOptions[signal].params;
                var callback = signalsOptions[signal].callback;
                process.on(signal, callback.bind(null, params));
            });
        }//addExitHandler
```

So for `SIGINT`, `uncaughtException` and `exit` I trap the error and forward to the `trapHandler`. Then I log the `error` if any and fire a `cleanup` event in order to run a gracefully exit on the client modules before exit.
What happens is **(1)**: While I have the `error` variable defined in the `trapHandler` when I forward the error to the `cleanup` signal like:

```javascript
process.emit('cleanup',error);
```

I will loose the error in the callback:
```javascript
self.platform.addExitHandler(function (error) {
                    self.logger.error("process:%d error code:%d message:%s stack:%@:\n%@", process.pid, error.code, error.message, error.stack);

try { // exit gracefully
process.exit(0)
}
catch (error => { 
  self.logger.error("process:%d error code:%d message:%s stack:%@:\n%@", process.pid, error.code, error.message, error.stack);
process.exit(1)
})
}); 
```

**(2)** I do not get the source error i.e. the error is not chained:

```
 [Thu Nov 30 2017 10:19:05 GMT+0000 (UTC)] trapped error code:ECONNRESET message:read ECONNRESET stack:Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at Pipe.onread (net.js:615:25):
```

Thus I cannot take actions based on this error format.
Is there any way to safely check where (which module) this error is coming from (redis, mysql, etc,.)?

**(3)** In the case of error emitted by `net.js` I do not have enough information about this network error: like which port? which ip? etc. Without this information I cannot know if the `ECONNRESET` of the example above was raised by `mysql` or `redis` or something else.

Originally posted to https://github.com/nodejs/node/issues/17398

**Comment by gireeshpunathil** [comment]
@loretoparisi - Your code looks good to me, and I am able to see the errors correctly displayed when used your code and threw an exception. Here is the output:

```trace
Error: fd
    at Object.<anonymous> (/home/gireesh/support/1003.js:42:7)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
addExitHandler process:40793 trapped: uncaughtException
trapped error code:NaN message:fd stack:%@:
%@ Error: fd
    at Object.<anonymous> (/home/gireesh/support/1003.js:42:7)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
AEH: process:40793 error code:NaN message:fd stack:%@:
%@ Error: fd
    at Object.<anonymous> (/home/gireesh/support/1003.js:42:7)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
0
addExitHandler process:40793 trapped: exit
AEH: process:40793 error code:NaN message:undefined stack:%@:
%@ undefined
```


Only one observation I hvae in the code is: process.on 'uncaughtException', 'exit' , and 'SIGNALS' - all three emit different types of responses to the callback: an Error object, an error code (number) and nothing, in that order. So based on the type (which you are anyways capturing, you may make the judgements accordingly). Sources and stack traces make meaning only for Error objects, exit and signals are process wide events that does not have an origin.

Hope this helps.

**Comment by loretoparisi** [comment]
@gireeshpunathil thanks for your suggestions! 

I have slightly modified the code above with a better handling of the `Error` object in the processing callbacks:

```javascript
addExitHandler = function (params, exitCallback) {
            var self = this;
            var options={
                ignoreUncaughtException: false
            };
            for (var attrname in params) { options[attrname] = params[attrname]; }

            process.stdin.resume(); //so the program will not close instantly
            const trapHandler = function (params, error) {
                self.logger.warn("addExitHandler process:%d trapped: %s", process.pid, params.type);
                if (error) {
                    self.logger.error("trapped error code:%d message:%s stack:%@:\n%@", error.code, error.message, error.stack);
                }
                if(params.type == 'uncaughtException') { // uncaughtException
                    if( !params.options.ignoreUncaughtException ) { // forward uncaught
                        return process.emit('cleanup', error);
                    }
                } else { // exit | sigint
                    return process.emit('cleanup', error);    
                }
            }//trapHandler
            var signalsOptions = {
                // catch app is closing 
                'exit': { params: { type: 'exit', options: options }, callback: trapHandler },
                // catches ctrl+c event
                'SIGINT': { params: { type: 'sigint', options: options }, callback: trapHandler },
                // catches uncaught exceptions
                'uncaughtException': { params: { type: 'uncaughtException', options: options }, callback: trapHandler }
            };
            // register signal handlers
            Object.keys(signalsOptions).forEach(signal => {
                var params = signalsOptions[signal].params;
                var callback = signalsOptions[signal].callback;
                process.on(signal, callback.bind(null, params));
            });
            // register cleanup handler
            process.on('cleanup', function () {
                var args=arguments;
                if (!args && args.length>0 ) {
                    if( typeof( args[0] ) == 'object') { // forward error
                        exitCallback.apply(this, [ args[0] ]);
                    } else {
                        var error = new Error('cleanup');
                        exitCallback.apply(this, [error]);     
                    }
                } else { // defaults error
                    var error = new Error('cleanup');
                    exitCallback.apply(this, [error]); 
                }
            });
        }//addExitHandler
```

As you can see this time I have added a guard on the `cleanup` since the args check was not ok before:

```javascript
// register cleanup handler
process.on('cleanup', function () {
                var args=arguments;
                if (args && args.length>0 ) {
                    if( typeof( args[0] ) == 'object') { // forward error
                        exitCallback.apply(this, [ args[0] ]);
                    } else {
                        var error = new Error('cleanup');
                        exitCallback.apply(this, [error]);     
                    }
                } else { // defaults error
                    var error = new Error('cleanup');
                    exitCallback.apply(this, [error]); 
                }
            });
```

So now, for the module that is installing this handler, you could do like

```javascript
addExitHandler({
                        ignoreUncaughtException: true
                    }, function (error) {
                    try {
                        // try to gracefully exit!!!
                        if(error) self.logger.error("Master:%d error code:%d message:%s stack:%@:\n%@", process.pid, error.code, error.message, error.stack);

                         // Redis connection issues: ignore since auto reconnect is by defaults...
                        if(error.code == 'ECONNRESET' || 
                            error.code == 'ETIMEDOUT' ||
                            error.code == 'NR_CLOSED' ||
                            error.code == 'UNCERTAIN_STATE') {
                            return;
                        }
                         // deallocate resources before exit
                    } catch (error) {
                        self.logger.error("exitHandler error:\n%@", error.stack);
                        return process.exit(1);
                    }
                });
```

**Comment by gireeshpunathil** [comment]
@loretoparisi - looks much better now. The only betterment I see is on the prints: based on the params.type, you could decide what to print: error.stack / error.code / error.

**Comment by gireeshpunathil** [comment]
@loretoparisi - just to confirm: is there any thing outstanding on this issue? Are we good to close?

**Comment by loretoparisi** [comment]
@gireeshpunathil thank you for your help, I can definitively close it.
