### ISSUE TITLE
Connect ECONNREFUSED Docker Softlayer 

### ISSUE THREAD

**Issue by pedro-pinho** [nodejs/help#1033]
* **Node.js Version**: 6.12.0
* **OS**: Linux
* **Scope (install, code, runtime, meta, other?)**: docker
* **Module (and version) (if relevant)**: node-red

I started a very simple docker container with node-red inside.
The image build successfuly and I can access it from my browser

The problem is I cannot install anything on it.
I tried entering the docker and executing npm install there, tried from Dockerfile and finally tried from the node-red editor, all of them with the same error

```
npm ERR! Linux 4.4.0-104-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--save-prefix=~" "--production" "node-red-node-watson@0.5.23"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 151.101.92.162:443
npm ERR!     at Object.exports._errnoException (util.js:1020:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1043:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
npm ERR!  { Error: connect ECONNREFUSED 151.101.92.162:443
npm ERR!     at Object.exports._errnoException (util.js:1020:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:1043:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '151.101.92.162',
npm ERR!   port: 443 }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/node-red/npm-debug.log
```
Steps to reproduce:
```
docker run -it -p 1880:1880 --name mynodered nodered/node-red-docker

docker exec -it mynodered /bin/bash

cd /data
npm install --save --save-prefix="~" --production node-red-node-watson@0.5.23
``` 

I do not use any proxy.

The output of my npm config list
```
; cli configs
user-agent = "npm/3.10.10 node/v6.12.0 linux x64"

; project config /usr/src/node-red/.npmrc
registry = "https://registry.npmjs.org/"

; userconfig /root/.npmrc

; node bin location = /usr/local/bin/node
; cwd = /usr/src/node-red
; HOME = /root
; "npm config ls -l" to show all defaults.
```

**Comment by lordKnighton** [comment]
@pedro-pinho Did you still need help with this, or do you have it going?

**Comment by pedro-pinho** [comment]
I found out that the problem was with my domain.

My softlayer lacked ssl, it was **http** and I was trying to install things on npm repo, that has **https** urls.
I added a ssl certificate on my server and it worked.
