### ISSUE TITLE
Error: listen EADDRINUSE :::5000

### ISSUE THREAD

**Issue by LAITONEN** [nodejs/help#1050]
* **Node.js Version**: v9.3.0
* **OS**: Sierra 10.12.4
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: Not sure what you mean by "module".

I am getting this error when starting up my server, regardless of port that I listen to in my node.js app.

events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5000
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at Server.setupListenHandle [as _listen2] (net.js:1379:14)
    at listenInCluster (net.js:1420:12)
    at Server.listen (net.js:1508:7)
    at Function.listen (/Users/UserName/workspace/ProjectOne/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/Users/UserName/workspace/ProjectOne/index.js:41:5)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

```js
const port = process.env.PORT || 5000;
app.listen(port, () => {
  console.log('Server initiated succesfully');
});
```
-->

**Tried:**

- killing processes running on different ports

- restarting the server

- restarting the computer (helps temporally)

**Comment by bnoordhuis** [comment]
`netstat` or `lsof` will tell you what process is listening on the port.  If it happens regardless of the port number, you might be starting two processes simultaneously.  If you listen on port 0, node will bind to a random available port number.

**Comment by nigelhanlon** [comment]
You should also look into the `PORT` variable in the environment. 'process.env.PORT' will override port 5000 in the code above unless it is undefined. 

Try using `PORT=9999 node myapp.js` and see if it helps.

**Comment by gireeshpunathil** [comment]
closing due to inactivity, please re-open if it is still outstanding

**Comment by mikebutak** [comment]
@bnoordhuis  I tried you suggestion of port 0.  Node starts listening on port 0 but I can't get anything to load on localhost:0  

Maybe I misunderstand you.

Thanks for any tips.  I'm stumped

**Comment by bnoordhuis** [comment]
@mikebutak The crux is this:

> If you listen on port 0, node will bind to a random available port number.

`server.listen(0, () => console.log(server.address().port))` prints the port number.

**Comment by mikebutak** [comment]
Thanks Ben!

**Comment by shamsheer7** [comment]
Try this:
1 - killall -9 node
2 - ps ax

**Comment by debaosuidecl** [comment]
I have this same problem on my Linux server
I tried checking for the process ID and running the kill command... but the PID keeps changing.
It may be due to the nginx I have installed..
I also tried changing the ports. whatever port I changed it to I kept having the same error

`{ Error: listen EADDRINUSE :::2900
`
I also changed the port on this ngnix file using  `sudo nano /etc/nginx/sites-available/default`
to the port of my application

I tried running killall -9 node
it told me there were no processes to kill

I am honestly tired and I don't know what to do.
Please help!

**Comment by satyapriyakaur** [comment]
> I have this same problem on my Linux server
> I tried checking for the process ID and running the kill command... but the PID keeps changing.
> It may be due to the nginx I have installed..
> I also tried changing the ports. whatever port I changed it to I kept having the same error
> 
> `{ Error: listen EADDRINUSE :::2900 `
> I also changed the port on this ngnix file using `sudo nano /etc/nginx/sites-available/default`
> to the port of my application
> 
> I tried running killall -9 node
> it told me there were no processes to kill
> 
> I am honestly tired and I don't know what to do.
> Please help!



> I have this same problem on my Linux server
> I tried checking for the process ID and running the kill command... but the PID keeps changing.
> It may be due to the nginx I have installed..
> I also tried changing the ports. whatever port I changed it to I kept having the same error
> 
> `{ Error: listen EADDRINUSE :::2900 `
> I also changed the port on this ngnix file using `sudo nano /etc/nginx/sites-available/default`
> to the port of my application
> 
> I tried running killall -9 node
> it told me there were no processes to kill
> 
> I am honestly tired and I don't know what to do.
> Please help!

do you get the solution?? i am facing the same issue

**Comment by kouqhar** [comment]
All you need to do is change the port number. E.g maybe from port 5000 change it to port 5500 or any port of your choosing.

**Comment by TrendSonic** [comment]
Change the PORT and it works just fine...

**Comment by puranjay123** [comment]
In my case I got an Error as same program is running in another terminal try to close all the terminals or restart the program.

**Comment by rujiel** [comment]
How is changing the port number going to solve having a runaway process??
I'm seeing the same, none of the kill commands work on node. It just comes back with a different PID. This seems to be a problem arising out of cluster mode

**Comment by Shubh-RM** [comment]
I got the same error message ,I tried everything form changing port no. , to make separate directory for server and front end , restarting system, stopping node service but it was silly mistake  I wrote app.listen() method twice . 
God forgive me for my sin .

**Comment by VaraKare** [comment]
node:events:497
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE: address already in use :::5000

Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1920:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '::',
  port: 5000
}

got this type of error and I just changed the port to 5500 and worked out for me.
