### ISSUE TITLE
RangeError: Invalid string length

### ISSUE THREAD

**Issue by theShivaa** [nodejs/help#1061]
* **Node.js Version**: 8.90
* **OS**: Linux Ubuntu 16.04
* **Scope (install, code, runtime, meta, other?)**:runtime

This code works perfectly when the limit for Following C++ program is **20000000** but when I increase the limit to **30000000** it gives following error .While the maxBuffer is set to 2147483647 Bytes . And the resulting file size is only  360000000 Bytes.

**server.js**
```js
const express = require('express');
const path = require('path')
const exec = require('child_process').exec  ;
const app = express();
const bodyParser = require('body-parser');
app.use( bodyParser.json() );
app.use(bodyParser.urlencoded({     
    extended: true
}));


function runCompiled(file){
    var cmd="./" + file;
    return new Promise((resolve,reject)=>{
        exec(cmd, {timeout:10000,maxBuffer:2147483647},(error, stdout, stderr) => {
            if (error) {                   
                  reject(error);
            }
            var res=stdout.toString();
            resolve(res);
          });
    })
}

app.get('/sol',(req,res)=>{
      var file='Solution.out'
      runCompiled(file).then((result)=>{        
          res.send(result);
        }).catch((e)=>{
          res.status(400).send(e);
          }
      })
})

const port = process.env.PORT || 3002;
app.listen(port);

module.exports={app}


```
 **solution.cpp**
```js
#include<bits/stdc++.h>
using namespace std;
int main(){
   for(long i=0;i<30000000;i++)
       cout<<"hello world\t";
}
```

The error I got is :
```js
child_process.js:331
        _stdout += chunk;
                   ^
RangeError: Invalid string length
    at Socket.onChildStdout (child_process.js:331:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

Thank in advance for helping .

**Comment by vsemozhetbyt** [comment]
There is a limit for max string length in JavaScript. V8 has recently increased this limit:

Node.js 8.9.4 (V8 6.1): 268 435 440 UTF-16 code units
Node.js 9.4.0 (V8 6.2): 1 073 741 799 UTF-16 code units

See [buffer.constants.MAX_STRING_LENGTH](https://nodejs.org/api/buffer.html#buffer_buffer_constants_max_string_length)

**Comment by theShivaa** [comment]
@vsemozhetbyt  is there any work around to solve problem ?

**Comment by vsemozhetbyt** [comment]
@theShivaa Sorry, I do not know a universal workaround. You can try to upgrade to Node.js 9 if its limit suffices.

**Comment by theShivaa** [comment]
@vsemozhetbyt  thank for helping

**Comment by loretoparisi** [comment]
I'm getting this same error when executing a program via child_process

```javascript
                var kakasi = spawn(self._options.bin, args, {});
                if(self._options.debug) console.log( "echo \""+data+"\" | " + kakasi.spawnargs.join(' ') )
                args = [
                    data
                ];
                var echo = spawn('echo', args, {});

                echo.stdout.pipe( kakasi.stdin );
                var res='';
                kakasi.stdout.on('data', function(_data) {
                    try {
                        var data=new Buffer(_data,'utf-8');
                        res+=data.toString();
                    } catch(error) {} // ignore
                });
                kakasi.stdout.on('end', function(_) {
                    return resolve(res);
                });
                kakasi.on('error', function(error) {
                    return reject(error);
                });
```

For some crazy reason I'm getting from `stdout`a buffer greater than `buffer.constants.MAX_STRING_LENGTH`. So far I have fixed it adding a try catch but I don't get why this happens.
