### ISSUE TITLE
npm E404, profound.js@latest Not Found

### ISSUE THREAD

**Issue by mooregolfin** [nodejs/help#1064]
Node.js 8.9.4LTS
W7PROx86 and W7PROx64
Install
Profound.js

Unable to install profound.js from 'https://regisrty.npmjs.org' or 'http://registry.npmjs.org'
c:\Profound>npm install profound.js
npm ERR! code E404
npm ERR! 404 Not Found: profound.js@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dprobertm\AppData\Roaming\npm-cache\_logs\2018-01-11T19_11
_25_146Z-debug.log

LOG

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'profound.js' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose npm-session 5004581d3d9c08df
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 404 https://registry.npmjs.org/profound.js 749ms
8 silly fetchPackageMetaData error for profound.js@latest 404 Not Found: profound.js@latest
9 verbose stack Error: 404 Not Found: profound.js@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:42:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:789:20)
9 verbose stack     at tryOnImmediate (timers.js:751:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
10 verbose cwd c:\Profound
11 verbose Windows_NT 6.1.7601
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "profound.js"
13 verbose node v8.9.4
14 verbose npm  v5.6.0
15 error code E404
16 error 404 Not Found: profound.js@latest
17 verbose exit [ 1, true ]

**Comment by mooregolfin** [comment]
Profound support has resolved our issue,

**Comment by mooregolfin** [comment]
Third party vendor instructions were inaccurate

npm install profound.js (wrong)

npm install profoundjs (correct)
