### ISSUE TITLE
Error running Node on my WSL shell on my Window 10

### ISSUE THREAD

**Issue by molokoloco** [nodejs/help#1078]
* **Node.js Version**: node v8.9.4 and node v9.4.0
* **OS**: Win10 Pro
* **Scope (install, code, runtime, meta, other?)**: Terminal WSL linux on Windows
* **Module (and version) (if relevant)**:

Hello,
I cannot run Node on my WSL shell on my Window 10 PC.
Here the error:

```shell
juju@PCJuss:/mnt/f/www/api$ nvm use 8
Now using node v8.9.4 (npm v5.6.0)
juju@PCJuss:/mnt/f/www/api$ node
net.js:200
    this._handle.open(options.fd);
                 ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:200:18)
    at createWritableStdioStream (internal/process/stdio.js:164:16)
    at process.getStdout [as stdout] (internal/process/stdio.js:14:14)
    at console.js:246:38
    at NativeModule.compile (bootstrap_node.js:596:7)
    at Function.NativeModule.require (bootstrap_node.js:541:18)
    at setupGlobalConsole (bootstrap_node.js:310:41)
    at startup (bootstrap_node.js:70:7)
    at bootstrap_node.js:608:3
```

**Comment by vdeturckheim** [comment]
cc @nodejs/platform-windows

**Comment by bnoordhuis** [comment]
From `BUILDING.md`:
```
The Windows Subsystem for Linux (WSL) is not directly supported, but the
GNU/Linux build process and binaries should work. The community will only
address issues that reproduce on native GNU/Linux systems. Issues that only
reproduce on WSL should be reported in the
[WSL issue tracker](https://github.com/Microsoft/WSL/issues). Running the
Windows binary (`node.exe`) in WSL is not recommended, and will not work
without adjustment (such as stdio redirection).
```
I'll close this out.
