### ISSUE TITLE
Node.js Strict Mode

### ISSUE THREAD

**Issue by gbyrn** [nodejs/help#1079]
-------------------------------------
* Node.js Version: v9.4.0
* OS: Ubuntu 16.04
* Scope: Install/Runtime
* Module: Sublime Text 3
-------------------------------------
I have a test.js program that compiles, but when I run this in the terminal as:
     `node test.js`
I just get:
     	public static void main(String[] args){
	         ^^^^^^
SyntaxError: Unexpected strict mode reserved word
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)

I checked and "--use_strict" is set to false. Any ideas?

**Comment by vdeturckheim** [comment]
Hey @gbyrn , that's Java you are trying to run, not JavaScript

**Comment by vdeturckheim** [comment]
To prevent potential troll, I will lock this conversation, feel free to unlock it if it was not a good call :-)
