### ISSUE TITLE
Response not getting from End-point

### ISSUE THREAD

**Issue by VinoPalani** [nodejs/help#1097]
* **v9.4.0**:
* **Windows8**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Response not getting from End-point , Please find the fi.js file below . 

```js
var http = require("https");

var options = {
  "method": "POST",
  "hostname": [
    "BANKONE"
  ],
  "port": "8080",
  "path": [
    "UISERVLET",
    "uihttp"
  ],
  "headers": {}
};

var req = http.request(options, function (res) {
  var chunks = [];

  res.on("data", function (chunk) {
    chunks.push(chunk);
  });

  res.on("end", function () {
    var body = Buffer.concat(chunks);
    console.log(body.toString());
  });
});

req.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<UIXML xsi:schemaLocation=\"http://www.bankone.com/uixml Acctinq.xsd\" xmlns=\"http://www.bankone.com/uixml\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><Header>\r\n<RequestHeader>\r\n<MessageKey>\r\n<RequestUUID>Req_1548</RequestUUID>\r\n<ServiceRequestId>Acctinq</ServiceRequestId>\r\n<ServiceRequestVersion>10</ServiceRequestVersion>\r\n<ChannelId>BANK</ChannelId>\r\n<LanguageId></LanguageId>\r\n</MessageKey>\r\n<RequestMessageInfo>\r\n<BankId></BankId>\r\n<TimeZone></TimeZone>\r\n<EntityId></EntityId>\r\n<EntityType></EntityType>\r\n<ArmCorrelationId></ArmCorrelationId>\r\n<MessageDateTime>2018-00-14T17:31:49.548</MessageDateTime>\r\n</RequestMessageInfo>\r\n<Security>\r\n<Token>\r\n<PasswordToken>\r\n<UserId></UserId>\r\n<Password></Password>\r\n</PasswordToken>\r\n</Token>\r\n<FICertToken></FICertToken>\r\n<RealUserLoginSessionId></RealUserLoginSessionId>\r\n<RealUser></RealUser>\r\n<RealUserPwd></RealUserPwd>\r\n<SSOTransferToken></SSOTransferToken>\r\n</Security>\r\n</RequestHeader>\r\n</Header>\r\n<Body>\r\n<AcctInqRequest>\r\n<AcctInqRq>\r\n<AcctId>\r\n<AcctId>00017</AcctId>\r\n</AcctId>\r\n</AcctInqRq>\r\n</AcctInqRequest>\r\n</Body>\r\n</UIXML>\r\n");
req.end();
```

**Error on hit the request .**

D:\Vino\Node9.4.0\api>node fi.js
_http_client.js:74
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', `options.${name}`,
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options.hostname" property must be one of type string, undefined, or null. Received type object
    at validateHost (_http_client.js:74:11)
    at new ClientRequest (_http_client.js:138:29)
    at Object.request (https.js:245:10)
    at Object.<anonymous> (D:\Vino\Node9.4.0\api\fi.js:16:16)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)

**Comment by gireeshpunathil** [comment]
--- a/op.js
+++ b/op1.js
@@ -1,16 +1,11 @@
-var http = require("https");
+var http = require("http");
 
 var options = {
-  "method": "POST",
-  "hostname": [
-    "BANKONE"
-  ],
-  "port": "8080",
-  "path": [
-    "UISERVLET",
-    "uihttp"
-  ],
-  "headers": {}
+  method: "POST",
+  hostname: "BANKONE"
+  port: 8080,
+  path: "/UISERVLET",
+  headers: {}
 };

summary:

1. https -> http (I guess you want http, as 8080 is normally used. revert this if you are sure you want https)
2. remove quotes from the option keys
3. hostname is a string, not an array - the well known name of the server
4. path is also a string, not an array - a query string or a router path the server parses and understands.
5. port is a number, so you can omit the quotes.

**Comment by VinoPalani** [comment]
Followed the steps as mentioned, my actual end-point url as

"https://BANKONE:8200/UISERVLET/uihttp" 

Face an Error as
NPP_EXEC: "node"
CD: D:\Vino\Node9.4.0\api
Current directory: D:\Vino\Node9.4.0\api
node fi.js
Process started (PID=2816) >>>
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1003:13)
    at TCP.onread (net.js:620:25)
<<< Process finished (PID=2816). (Exit code 1)
================ READY ================

**Comment by gireeshpunathil** [comment]
ok, then revert the `https` but feed the `option` as:
```js
var options = {
  method: "POST",
  hostname: "BANKONE"
  port: 8200,
  path: "/UISERVLET/uihttp",
  headers: {}
};
```

**Comment by VinoPalani** [comment]
On change to HTTPS, certificate err as

NPP_EXEC: "node"
CD: D:\Vino\Node9.4.0\api
Current directory: D:\Vino\Node9.4.0\api
node fi.js
Process started (PID=2600) >>>
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1041:34)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
<<< Process finished (PID=2600). (Exit code 1)
================ READY ================

**Comment by gireeshpunathil** [comment]
ok, good - we passed the `semantic` error phase and now in the logical error phase. Sorry, I have not sufficient knowledge to solve this further, but expect a response from others soon.

/cc @nodejs/crypto

**Comment by bnoordhuis** [comment]
Look up the `.ca` property in the tls documentation; you need to provide your custom CA certificate.

**Comment by VinoPalani** [comment]
Thanks @gireeshpunathil  @bnoordhuis ,
After adding this "process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";" in top of code ,it worked.
But want to know 
1.how to setup this environment variable globally in windows.
2.how to make the working with custom certificate.

**Comment by bnoordhuis** [comment]
Don't do that, that's basically throwing away all security.  You might as well use HTTP instead of HTTPS.

> how to make the working with custom certificate.

I told you.  If anything is unclear, please be specific.

**Comment by gireeshpunathil** [comment]
ping @VinoPalani

**Comment by gireeshpunathil** [comment]
closing due to inactivity, please re-open if it is still outstanding, but with required data
