### ISSUE TITLE
Hi can anyone help with Node.js errors?

### ISSUE THREAD

**Issue by william6629** [nodejs/help#1151]
```js
SyntaxError: Unexpected end of JSON input

    at Object.parse (native)

at Client.client.on.message (/app/index.js:366:31)

    at emitOne (events.js:96:13)

    at Client.emit (events.js:188:7)

    at MessageCreateHandler.handle (/rbd/pnpm-volume/fcf73aac-d60d-4524-b59c-cd9510882ffa/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)

    at WebSocketPacketManager.handle (/rbd/pnpm-volume/fcf73aac-d60d-4524-b59c-cd9510882ffa/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)

    at WebSocketConnection.onPacket (/rbd/pnpm-volume/fcf73aac-d60d-4524-b59c-cd9510882ffa/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)

    at WebSocketConnection.onMessage (/rbd/pnpm-volume/fcf73aac-d60d-4524-b59c-cd9510882ffa/node_modules/.registry.npmjs.org/discord.js/11.3.2/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)

    at WebSocket.onMessage (/rbd/pnpm-volume/fcf73aac-d60d-4524-b59c-cd9510882ffa/node_modules/.registry.npmjs.org/ws/4.1.0/node_modules/ws/lib/event-target.js:120:16)

    at emitOne (events.js:96:13)

Can anyone help? Latest version of Node.js

**Comment by gireeshpunathil** [comment]
what are you trying to perform? please provide the full steps to reproduce this error, with the platform and the versions.

**Comment by gireeshpunathil** [comment]
ping @william6629

**Comment by gireeshpunathil** [comment]
closing due to inactivity, please re-open if it is still outstanding, but with required data
