### ISSUE TITLE
[feature-request] make node wrapping function an AsyncFunction and/or improve stack trace?

### ISSUE THREAD

**Issue by AyushG3112** [nodejs/help#1153]
* **Node.js Version**: v10.0.0-pre
* **OS**: Ubuntu 16.04.1 64-bit

All the code the repro file I created contains:

```js
await Promise.resolve(1);
```

Error:

```
(function (exports, require, module, __filename, __dirname) { await Promise.resolve(1);
                                                              ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:50:7)
    at createScript (vm.js:132:10)
    at Object.runInThisContext (vm.js:180:10)
    at Module._compile (module.js:638:28)
    at Object.Module._extensions..js (module.js:681:10)
    at Module.load (module.js:581:32)
    at tryModuleLoad (module.js:521:12)
    at Function.Module._load (module.js:513:3)
    at Function.Module.runMain (module.js:711:10)
    at startup (bootstrap_node.js:223:16)
```

Ofcourse, it is quite obvious what the error is, however, the stack trace does not signify where the error is, as it does not have the path to the file.

Also, is it possible to change the wrapping function to an `AsyncFunction` so that we can use await at the root level, right now I am having to have to wrap `await`s into an IIFE

**Comment by jsdeveloper97** [comment]
> The stack trace does not signify where the error is

The stack trace actually displays the exact line where the error is thrown. What you have there is a syntax error, your script cannot be even compiled (interpreted), so it cannot be executed and therefore it cannot be in the stack trace.

> It does not have the path to the file

It actually displays the path to the file which contains a syntax error (it is the first line of the node.js output). This is what I get when I try it (checked on windows):

```
C:\test\1.js:1
(function (exports, require, module, __filename, __dirname) { await Promise.resolve(1);
                                                              ^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (module.js:626:28)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
    at startup (bootstrap_node.js:193:16)
```

You see `C:\test\1.js:1`? It is the path to the file.

**Comment by gireeshpunathil** [comment]
Closing as answered.
