### ISSUE TITLE
Transform JS objects to JSON using transform stream

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1166]
Note there are many transform streams that do this:

> JSON -> JS

but I am looking to create a Node.js transform stream that can do:

> JS -> JSON

I have a readable stream:

```js  
  const readable = getReadableStream({objectMode:true});
```
the readable stream outputs Objects, not strings.

I need to create a transform stream which can filter some of those objects and convert the objects to JSON, like so:

```js
    const t = new Transform({
      objectMode: true,
      transform(chunk, encoding, cb) {
        if(chunk && chunk.marker === true){
           this.push(JSON.stringify(chunk));
         }
        cb();
      },
      flush(cb) {
        cb();
      }
    });
```

**however, for some reason my transform stream cannot accepts objects to the transform method, only string and buffer, what can I do?**

**Comment by addaleax** [comment]
Can you post a complete script that reproduces your issue?

Also, you might want `writableObjectMode: true`, not `objectMode: true`? It probably doesn’t make much of a difference.

**Comment by ORESoftware** [comment]
Yes, this example no longer works on Node v9.4.x:
http://codewinds.com/blog/2013-08-20-nodejs-transform-streams.html

Here is the code:

```js
var stream = require('stream');
var util = require('util');

// node v0.10+ use native Transform, else polyfill
var Transform = stream.Transform ||
  require('readable-stream').Transform;

/*
 * Filters an object stream properties
 *
 * @param filterProps array of props to filter
 */
function Filter(filterProps, options) {
  // allow use without new
  if (!(this instanceof Filter)) {
    return new Filter(filterProps, options);
  }

  // init Transform
  if (!options) options = {}; // ensure object
  options.objectMode = true; // forcing object mode
  Transform.call(this, options);
  this.filterProps = filterProps;
}
util.inherits(Filter, Transform);

/* filter each object's sensitive properties */
Filter.prototype._transform = function (obj, enc, cb) {
  var self = this;
  // determine what keys to keep
  var filteredKeys = Object.keys(obj).filter(
    function (key) {
      // only those keys not in this list
      return (self.filterProps.indexOf(key) === -1);
    }
  );

  // create clone with only these keys
  var filteredObj = filteredKeys.reduce(
    function (accum, key) {
      accum[key] = obj[key];
      return accum;
    },
    {}
  );

  // push the filtered obj out
  this.push(filteredObj);
  cb();
};


var filter = new Filter([ 'phone', 'email' ]);
filter.on('readable', function () {
    var obj;
    while (null !== (obj = filter.read())) {
      console.log(obj);
    }
  });
```

**Comment by ORESoftware** [comment]
the problem is right there, when I call

```js
readableStream.push({zoom:'bar'});
```
that throws this error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string/Buffer/Uint8Array
    at chunkInvalid (_stream_readable.js:287:10)
    at readableAddChunk (_stream_readable.js:225:12)
```

however if I just do:

```js
filter.write({zoom:'bar'})
```

then it works. Something is broken here :(

**Comment by ORESoftware** [comment]
so fucked up people, in order to get it to work, I have to listen to the readable event:

```js
   filter.on('readable', function () {
      var obj;
      while (null !== (obj = filter.read())) {
        console.log(obj);
      }
    });
```

does anyone know why that is?

**Comment by ORESoftware** [comment]
@addaleax I filed a bug for this
https://github.com/nodejs/node/issues/19399

unlikely that that will go somewhere, I am just looking for answers :(

**Comment by ORESoftware** [comment]
will reopen if I actually find a problem, shucks

**Comment by emmanuelvr** [comment]
I think this issue could have been solved if you just wrapped the `{zoom: 'bar'}` object with `JSON.stringify`
