### ISSUE TITLE
Error: Cannot find module 'nconf'

### ISSUE THREAD

**Issue by xedom** [nodejs/help#1169]
Someone can help me please?

i have:
- node.js v9.8.0
- mongo v3.2.11
- git clone git://github.com/NodeBB/NodeBB.git nodebb
- debian 9

error:
```
module.js:545
    throw err;
    ^

Error: Cannot find module 'nconf'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/nodebb/app.js:28:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by ORESoftware** [comment]
`npm install nconf`

nconf is an NPM module => https://www.npmjs.com/package/nconf

**Comment by xedom** [comment]
ok ,thanks
but now i have this problem:
http://prntscr.com/isdz7b

**Comment by SomeoneWeird** [comment]
If your project has an `package.json` in it, just run `npm install` to install all the dependencies it needs to function.

**Comment by xedom** [comment]
i have `package.json` into intall foldel, should i make:
```
cd intall/
npm install
```

**Comment by xedom** [comment]
i have made so: http://prntscr.com/ise5ew

**Comment by ukulanne** [comment]
Check the installation guide for nodebb https://docs.nodebb.org/installing/os/debian/

**Comment by gireeshpunathil** [comment]
@xedom - is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing, please re-open if this is still an issue
