### ISSUE TITLE
nodebb error

### ISSUE THREAD

**Issue by xedom** [nodejs/help#1174]
hi,
someone can help me?
```
Hit Ctrl-C to exit


    at eachOfLimit (/root/nodebb/node_modules/async/dist/async.js:1027:24)
    at /root/nodebb/node_modules/async/dist/async.js:1032:16
    at Object.reduce (/root/nodebb/node_modules/async/dist/async.js:2501:5)
    at fireFilterHook (/root/nodebb/src/plugins/hooks.js:107:9)
    at Object.Plugins.fireHook (/root/nodebb/src/plugins/hooks.js:87:4)
    at /root/nodebb/src/widgets/index.js:77:12
    at nextTask (/root/nodebb/node_modules/async/dist/async.js:5310:14)
    at next (/root/nodebb/node_modules/async/dist/async.js:5317:9)
    at /root/nodebb/node_modules/async/dist/async.js:958:16
    at async.waterfall.userLang (/root/nodebb/src/widgets/index.js:71:5)
```

**Comment by gireeshpunathil** [comment]
The message is probably coming from [here](https://github.com/NodeBB/NodeBB/blob/dbdc05404daeac7021b60f22f7c18588ca126cfd/src/cli/running.js#L113), the callstack and its reason, unknown.

You should raise it up with [nodebb project](https://github.com/NodeBB/NodeBB)

Hope this helps.
