### ISSUE TITLE
npm doesn't work for the stable release of nodejs v8.11.1.

### ISSUE THREAD

**Issue by luoshangyu** [nodejs/help#1241]
* **Node.js Version**: v8.11.1
* **OS**: CentOS
* **Scope (install, code, runtime, meta, other?)**: config
* **Module (and version) (if relevant)**: npm v5.6.9

```js
[root@localhost bin]# ./npm --version
module.js:549
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /export/servers/node-v8.11.1-linux-x64/bin/npm:19:21
    at Object.<anonymous> (/export/servers/node-v8.11.1-linux-x64/bin/npm:92:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by bnoordhuis** [comment]
See nodejs/node#19702 for a similar report.  You probably have two conflicting copies of npm on your machine.

**Comment by gireeshpunathil** [comment]
ping @luoshangyu - were you able to resolve it?

**Comment by gireeshpunathil** [comment]
closing as answered
