### ISSUE TITLE
Issue I am facing for the same.

### ISSUE THREAD

**Issue by kaushiklahiri** [nodejs/help#1268]
Team, I am getting this error, can some one help

module.js:471
    throw err;
    ^

Error: Cannot find module 'file-system'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/DivyamPrakash/sample_project/app3.js:4:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by advanceddeveloper** [comment]
If you want to use [file-system](https://www.npmjs.com/package/file-system) module from [npm](https://www.npmjs.com/), you should install it using `npm install file-system`. If you want to use node's native file system package, you should require it as `require('fs')`

**Comment by gireeshpunathil** [comment]
closing as answered.
