### ISSUE TITLE
version mismatch when compiling node.js addon

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1314]
I am on node.js version 10.1

I am having trouble building this project:
https://github.com/ORESoftware/modify-socket

I ran:

```
sudo node-gyp configure
sudo node-gyp build  # and I tried: sudo node-gyp rebuild
```

This commands run without errors.
Once I try to load my addon:

```js
const addon = require('../build/Release/run.node');
```

I am getting this error:

```
internal/modules/cjs/loader.js:707
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/oleg/WebstormProjects/oresoftware/modify_socket/build/Release/run.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/oleg/WebstormProjects/oresoftware/modify_socket/test/a.js:1:77)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)

```

I have seen that error all over the internet, but I tried various solutions, like removing node_modules and resinstalling (npm install and npm rebuild) and nothing has worked so far.

Here are docs for node-gyp:
https://github.com/nodejs/node-gyp

**Comment by gireeshpunathil** [comment]
can you please try this:
$ head -1 \`which node-gyp\`
and see if the node pointed by that and the node which you are using are different.

**Comment by gireeshpunathil** [comment]
was this cornered?

**Comment by ORESoftware** [comment]
I hit this issue every 6 months and I can never remember how I solve it lol. I can't remember now, but I did solve it. Thanks.
