### ISSUE TITLE
Creating bot on steam

### ISSUE THREAD

**Issue by CutteLighty** [nodejs/help#1333]
* **Node.js Version**: 8.11.2 LTS
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

```js
const SteamUser = require ('steam-user');
const config = require('./config.json');
const client = new SteamUser();

const LogOnOptions = {
    accountname: config.username,
    password: config.password
};

client.LogOn(LogOnOptions);

client.on('LoggedOn', () => {
    console.log('succesfully logged on.');
});
```
-->
SyntaxError: C:\Users\Unistar\Desktop\Bots\Bot 1\config.json: Unexpected token } in JSON at position 63
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Unistar\Desktop\Bots\Bot 1\bot.js:2:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**Comment by vsemozhetbyt** [comment]
It would be helpful to see the content of the `config.json`.

**Comment by CutteLighty** [comment]
{
	"username":"Actual name",
	"password":"Actual password",
}

**Comment by CutteLighty** [comment]
Removed them no difference still the same problem.

**Comment by vsemozhetbyt** [comment]
I mean, only the last comma was removed, right?

**Comment by CutteLighty** [comment]
now its
C:\Users\Unistar\Desktop\Bots\Bot 1>node bot.js
C:\Users\Unistar\Desktop\Bots\Bot 1\bot.js:10
client.LogOn(LogOnOptions);
       ^

TypeError: client.LogOn is not a function
    at Object.<anonymous> (C:\Users\Unistar\Desktop\Bots\Bot 1\bot.js:10:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by vsemozhetbyt** [comment]
It seems this new error is better to be posted in https://github.com/DoctorMcKay/node-steam-user

**Comment by shellberg** [comment]
A check on the [defined API](https://github.com/DoctorMcKay/node-steam-user) suggests the problem is the capitalisation of the method name.  Its `logOn()` not `LogOn()`.

**Comment by CutteLighty** [comment]
Solved
