### ISSUE TITLE
Unable to connect Node with mysql

### ISSUE THREAD

**Issue by sandeepjain2015** [nodejs/help#134]
```js
var express =require('express');
var mysql =require('mysql');
var app =express();
var connection =mysql.createConnection({
    host:'localhost',
    user:'root',
    password:'',
    database:'piwikdemo'
   
});
connection.connect(function(error){
    if(error){
        console.log(error);
    }else{
        console.log('Connected');
    }
});
```
For other than 'test' and 'piwikdemo'  script is showing following error
{ [Error: ER_BAD_DB_ERROR: Unknown database 'books']
  code: 'ER_BAD_DB_ERROR',
  errno: 1049,
  sqlState: '42000',
  fatal: true }

Please help

**Comment by julianduque** [comment]
@sandeepjain2015 from your error it seems the database `books` doesn't exist in your MySQL server

**Comment by abhayendra** [comment]
@sandeepjain2015  please check your database

**Comment by sandeepjain2015** [comment]
But in my database ,books database are present


mysql> show databases;
+---------------------+
| Database            |
+---------------------+
| information_schema  |
| appium              |
| auburnpublicschools |
| books               |
| circleflip          |
| codeigniter-test    |

**Comment by lordKnighton** [comment]
Are you sure you're mysql process is running?

**Comment by lordKnighton** [comment]
why don't you have a
```js
connection.end()
```
attached to you code?

**Comment by lordKnighton** [comment]
in this example, you don't need express
and are you using `$ npm install felixge/node-mysql`?

**Comment by mh-cbon** [comment]
should you need to connect via a socket file ? or the ip +port instead of localhost. [may this helps](http://stackoverflow.com/questions/3613704/mysql-show-current-connection-info)

**Comment by lordKnighton** [comment]
@sandeepjain2015 did you fix your error? 
==

 Error: 1049 SQLSTATE: 42000 (ER_BAD_DB_ERROR)

Message: Unknown database '%s'

shouldn't you be setting to 
 database:'books'
instead of piwikdemo

**Comment by lordKnighton** [comment]
@sandeepjain2015 you fixed this right? I'm trying to get this issue closed, If so. If not we will fix it.

**Comment by lordKnighton** [comment]
CC @sandeepjain2015 closing for now, If you need more help, feel free to reopen.

**Comment by joshuaoyerinde** [comment]
For other than 'test' and 'piwikdemo' script is showing following error
{ [Error: ER_BAD_DB_ERROR: Unknown database 'books']
code: 'ER_BAD_DB_ERROR',
errno: 1049,
sqlState: '42000',
fatal: true }

Please help

i have this same issue

**Comment by elmar001** [comment]
Same issue here with aws ec2 and mysql. Any solution?
```
Error connecting to the database: Error: ER_BAD_DB_ERROR: Unknown database 're-db'
    at Sequence._packetToError (/home/ec2-user/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/ec2-user/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/ec2-user/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/ec2-user/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/ec2-user/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/ec2-user/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/ec2-user/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/ec2-user/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    --------------------
    at Protocol._enqueue (/home/ec2-user/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/ec2-user/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/ec2-user/node_modules/mysql/lib/Connection.js:116:18)
    at Object.<anonymous> (/home/ec2-user/revish/index.js:13:12)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'ER_BAD_DB_ERROR',
  errno: 1049,
  sqlMessage: "Unknown database 're-db'",
  sqlState: '42000',
  fatal: true
}
```
