### ISSUE TITLE
callback is not a function

### ISSUE THREAD

**Issue by phaitonican** [nodejs/help#1348]
i tried to make a callback and it is telling me that callback is not a function... ?

```js
function getMembers(callback) {
  var result = [];
  mongodb.MongoClient.connect(uri, function(err, client) {

    if(err) throw err;
    let db2 = client.db('members');

    let members2 = db2.collection('members');

    members2.find({}).forEach(function(row) {
       result.push(row.member);
    }, function(err) {
       callback(result);
    });
  });
}

var callbackResults = function(results) {
  console.log(results);
}

getMembers(callbackResults);
```
-->

**Comment by ORESoftware** [comment]
```js

const {MongoClient} = require('mongodb');

function getMembers(cb) {
  
  const results = [];

    MongoClient.connect(uri, function(err, client) {

    if(err) {
      return cb(err);
    }
  
    let db = client.db('members');

    let members = db.collection('members');

    members.find({}).forEach(function(row) {
      results.push(row.member);
    }, 
      
      function(err) {
       cb(err, results);
    });
  });
}


getMembers(function(err, results){
  
});
```

**Comment by phaitonican** [comment]
thanks but getting:
(node:54820) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at SteemBotCore.handlePostOperation (/Users/phaitonican/steem-bot/src/core.js:28:26)
    at /Users/phaitonican/steem-bot/src/core.js:105:20
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:379:21
    at Array.forEach (<anonymous>)
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:378:40
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:353:25
    at Array.forEach (<anonymous>)
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:352:41
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/transports/http.js:99:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:54820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:54820) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:54820) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at SteemBotCore.handlePostOperation (/Users/phaitonican/steem-bot/src/core.js:28:26)
    at /Users/phaitonican/steem-bot/src/core.js:105:20
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:379:21
    at Array.forEach (<anonymous>)
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:378:40
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:353:25
    at Array.forEach (<anonymous>)
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/index.js:352:41
    at /Users/phaitonican/steem-bot/node_modules/steem/lib/api/transports/http.js:99:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:54820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
/Users/phaitonican/steem-bot/node_modules/mongodb/lib/utils.js:132
      throw err;
      ^

TypeError: callback is not a function
    at /Users/phaitonican/steem-bot/example/deposit.js:31:8
    at /Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:825:7
    at handleCallback (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/utils.js:128:55)
    at self.close (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:783:60)
    at handleCallback (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/utils.js:128:55)
    at completeClose (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:1043:14)
    at _endSession (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:1053:35)
    at Cursor._endSession (/Users/phaitonican/steem-bot/node_modules/mongodb-core/lib/cursor.js:190:5)
    at Cursor._endSession (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:217:59)
    at Cursor.close (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:1053:17)
    at /Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:783:21
    at result (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/utils.js:414:17)
    at executeCallback (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/utils.js:406:9)
    at handleCallback (/Users/phaitonican/steem-bot/node_modules/mongodb/lib/utils.js:128:55)
    at /Users/phaitonican/steem-bot/node_modules/mongodb/lib/cursor.js:723:5
    at handleCallback (/Users/phaitonican/steem-bot/node_modules/mongodb-core/lib/cursor.js:199:5)

**Comment by ORESoftware** [comment]
did you figure it out?

**Comment by phaitonican** [comment]
yes you were right i had an error somewhere else. thanks!

**Comment by SIMONNABUKO** [comment]
Please, I am also having the same error. I am using MongoDB atlas can someone help me?
Error: 
TypeError: callback is not a function
    at $initialConnection.$initialConnection.then.err (C:\Users\Simon\Desktop\devconnector\node_modules\mongoose\lib\connection.js:724:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Code:
`const express = require('express');
const mongoose = require('mongoose');
const app = express();

//import database configurations
db = require('./config/keys').mongoURI;
const users = require('./routes/api/users');
const profile = require('./routes/api/profile');
const posts = require('./routes/api/posts');
const bodyParser = require('body-parser');

//use body-parser middleware
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

//connect to the database
mongoose
  .connect(db, { useNewUrlParser: true }, { useUnifiedTopology: true })
  .then(() => console.log('MongoDB connected!'))
  .catch(err => {
    console.error('App starting error:', err);
  });
`
keys.js file: 
`module.exports = {
  mongoURI:
    'mongodb+srv://someone:xPjrVDEnV1TR@cluster0-pykvt.mongodb.net/test?retryWrites=true&w=majority'
};`
