### ISSUE TITLE
"TypeError: debug is not a function"

### ISSUE THREAD

**Issue by xoxo111** [nodejs/help#1353]
* **Node.js Version**:
* **Microsoft Windows 10 Home**:
* **install**:
* **[Version 10.0.17134.112]**:

Hello,
im trying to connect to server with the command "node (name).js". Unfortunately I get this error:

```
c:\Program Files\nodejs>node fractal_server.js
c:\Program Files\nodejs\fractal_server.js:855
        debug("db","Loading data starttime "+starttime+" "+table+" "+selectString);
        ^

TypeError: debug is not a function
    at loadBarData (c:\Program Files\nodejs\fractal_server.js:855:2)
    at Object.<anonymous> (c:\Program Files\nodejs\fractal_server.js:65:2)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```
Would be grateful if anybody can help or explain me the steps to solve the issue.

**Comment by trvsapjiac** [comment]
As suggested in comments on your [StackOverflow post](https://user-images.githubusercontent.com/40323326/41797304-d8891bb8-7669-11e8-9a14-ed365f9148db.png), you should provide the content of your `fractal_server.js` file. Otherwise, it is very unlikely that someone can guess what the problem in your script is.

**Comment by gireeshpunathil** [comment]
probably the code needs https://www.npmjs.com/package/debug . But of course, showing the code will help figuring out what went wrong

**Comment by lordKnighton** [comment]
Make sure you have debug in your package.json & in your dependency modules. 

But i agree with @gireeshpunathil, showing us some source code would be more descriptive.
