### ISSUE TITLE
 'watch_scss' errored after 138 μs

### ISSUE THREAD

**Issue by bmjbrown** [nodejs/help#1354]
C'watch_scss' errored after 140 μs
[13:26:52] ReferenceError: SCC_SRC is not defined
    at Gulp.<anonymous> (C:\Users\bmj_b\Projects\my-app\gulpfile.js:39:16)
    at module.exports (C:\Users\bmj_b\Projects\my-app\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\bmj_b\Projects\my-app\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\bmj_b\Projects\my-app\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\bmj_b\Projects\my-app\node_modules\orchestrator\index.js:134:8)
    at C:\Users\bmj_b\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:72:20
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by lordKnighton** [comment]
@bmjbrown are you making any progress with this? It looks like something isn't defined or out of scope(SCC_SRC)

**Comment by bmjbrown** [comment]
thanks and yes i did
