### ISSUE TITLE
when i type "node index.js" this is what happened, why?

### ISSUE THREAD

**Issue by Yazi01** [nodejs/help#1385]
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\x\Desktop\YazBot\index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by trvsapjiac** [comment]
As the error says, you are missing `index.js` file. Create the file and put some js code into it.

**Comment by gireeshpunathil** [comment]
ping @Yazi01 . Alternatively, please provide full steps to reproduce the error.

**Comment by gireeshpunathil** [comment]
closing due to inactivity

**Comment by pulkitgupta317** [comment]
This happened with me also.
It was happening because the file extension was hidden of the file and while creating the file.. created the file with name main.js thinking the extension will be .js but on saving the file....the name was main.js.txt. That is why the node was unable to find the module at the respective location.

Cheers!!
