### ISSUE TITLE
Critical Error: Command Injection with Package "open" as a dependency of cordova-browser

### ISSUE THREAD

**Issue by mayank-sharma-16** [nodejs/help#1396]
I'm very new to using node, but I haven't been able to start my app recently. When I enter `npm start` I just end up with an error as shown below. Furthermore, when I ran `npm audit` I got a critical vulnerability claiming that a package called "open", a dependency of cordova-browser, had a command injection error. I honestly have no idea what to do.

* **Node.js Version**: 6.2.0
* **OS**: macOS Sierra 10.12.6

`Error: Uncaught (in promise): cordova_not_available
    at c (http://localhost:8100/build/polyfills.js:3:19752)
    at c (http://localhost:8100/build/polyfills.js:3:19461)
    at http://localhost:8100/build/polyfills.js:3:20233
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4973:33)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)
    at r.runTask (http://localhost:8100/build/polyfills.js:3:10834)
    at o (http://localhost:8100/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (http://localhost:8100/build/polyfills.js:3:16823)
    at p (http://localhost:8100/build/polyfills.js:2:27648)`

 Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ open                                                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ cordova-browser                                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ cordova-browser > cordova-serve > open                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/663

**Comment by addaleax** [comment]
> When I enter `npm start` I just end up with an error as shown below.

It sounds like you’re using some kind of build tool to create your app. Do you think you could share steps that help other people reproduce what you’re seeing?

> Furthermore, when I ran `npm audit` I got a critical vulnerability claiming that a package called "open", a dependency of cordova-browser, had a command injection error. I honestly have no idea what to do.

It depends – is your version of `cordova-browser` up to date? If no, updating it would be a first step. If yes, you may want to open an issue/pull request with their packages for updating `open` as a dependency.

**Comment by gireeshpunathil** [comment]
ping @mayank-sharma-16 - is it resolved?
