### ISSUE TITLE
Error: spawn git ENOENT on windows 7

### ISSUE THREAD

**Issue by DrunkenPoney** [nodejs/help#1397]
* **Node.js Version**: v10.7.0
* **OS**: Windows 7 x64
* **Scope**: runtime
* **Module**: child_process

I was using a script I made which was working fine and for some reason now I get the following error. 
![image](https://user-images.githubusercontent.com/14944216/43293490-8eda3394-9108-11e8-8fb1-ac7aa4b887af.png)
Though, I'm not sure if this error is due to node, git or something else but it seems to come from node since I can run git from anywhere in my computer and the returned signal is ENOENT which I believe means it didn't find git.

The only thing I've done since the last time my script worked is updating node to the latest version (v10.7.0).

**Comment by gireeshpunathil** [comment]
@DrunkenPoney -  can you please:

 - show me the code snippet around invoking the child process?
 - print the value of the variable that holds the child process name?

**Comment by DrunkenPoney** [comment]
Here is the code invoking the child process:
```javascript
new Promise((resolve) => {
    let spawn = child_process.spawn('git', ['tag', '-l', '--sort=-version:refname'], {cwd: tmpdir});
    console.log(spawn);
    let data = '';
    spawn.stdout.on('data', d => data += d);
    spawn.stdout.on('close', () => resolve(data));
})
```

And the following is the value of the variable that holds the child process:
```javascript
ChildProcess {
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined,
  _closesNeeded: 3,
  _closesGot: 0,
  connected: false,
  signalCode: null,
  exitCode: null,
  killed: false,
  spawnfile: 'git',
  _handle: Process { owner: [Circular], onexit: [Function] },
  spawnargs: [ 'git', 'tag', '-l', '--sort=-version:refname' ],
  pid: undefined,
  stdin:
   Socket {
     connecting: false,
     _hadError: false,
     _handle: Pipe { owner: [Circular], onread: [Function: onread] },
     _parent: null,
     _host: null,
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     _events: { end: [Function: onReadableStreamEnd] },
     _eventsCount: 1,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: false,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: null,
     _server: null,
     [Symbol(asyncId)]: 9,
     [Symbol(lastWriteQueueSize)]: 0,
     [Symbol(timeout)]: null,
     [Symbol(kBytesRead)]: 0,
     [Symbol(kBytesWritten)]: 0 },
  stdout:
   Socket {
     connecting: false,
     _hadError: false,
     _handle:
      Pipe { owner: [Circular], onread: [Function: onread], reading: true },
     _parent: null,
     _host: null,
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events: { end: [Function: onReadableStreamEnd], close: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: null,
     _server: null,
     [Symbol(asyncId)]: 10,
     [Symbol(lastWriteQueueSize)]: 0,
     [Symbol(timeout)]: null,
     [Symbol(kBytesRead)]: 0,
     [Symbol(kBytesWritten)]: 0 },
  stderr:
   Socket {
     connecting: false,
     _hadError: false,
     _handle:
      Pipe { owner: [Circular], onread: [Function: onread], reading: true },
     _parent: null,
     _host: null,
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     _events: { end: [Function: onReadableStreamEnd], close: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        emitClose: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: null,
     _server: null,
     [Symbol(asyncId)]: 11,
     [Symbol(lastWriteQueueSize)]: 0,
     [Symbol(timeout)]: null,
     [Symbol(kBytesRead)]: 0,
     [Symbol(kBytesWritten)]: 0 },
  stdio:
   [ Socket {
       connecting: false,
       _hadError: false,
       _handle: [Pipe],
       _parent: null,
       _host: null,
       _readableState: [ReadableState],
       readable: false,
       _events: [Object],
       _eventsCount: 1,
       _maxListeners: undefined,
       _writableState: [WritableState],
       writable: true,
       allowHalfOpen: false,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 9,
       [Symbol(lastWriteQueueSize)]: 0,
       [Symbol(timeout)]: null,
       [Symbol(kBytesRead)]: 0,
       [Symbol(kBytesWritten)]: 0 },
     Socket {
       connecting: false,
       _hadError: false,
       _handle: [Pipe],
       _parent: null,
       _host: null,
       _readableState: [ReadableState],
       readable: true,
       _events: [Object],
       _eventsCount: 2,
       _maxListeners: undefined,
       _writableState: [WritableState],
       writable: false,
       allowHalfOpen: false,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 10,
       [Symbol(lastWriteQueueSize)]: 0,
       [Symbol(timeout)]: null,
       [Symbol(kBytesRead)]: 0,
       [Symbol(kBytesWritten)]: 0 },
     Socket {
       connecting: false,
       _hadError: false,
       _handle: [Pipe],
       _parent: null,
       _host: null,
       _readableState: [ReadableState],
       readable: true,
       _events: [Object],
       _eventsCount: 2,
       _maxListeners: undefined,
       _writableState: [WritableState],
       writable: false,
       allowHalfOpen: false,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 11,
       [Symbol(lastWriteQueueSize)]: 0,
       [Symbol(timeout)]: null,
       [Symbol(kBytesRead)]: 0,
       [Symbol(kBytesWritten)]: 0 } ] }
```

The full stack trace is the following:
```javascript
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

As you can see the stack trace does not tell me where is my code crashing and I don't understand why.

**Comment by gireeshpunathil** [comment]
thanks, can you please try with the full path of `git` in the argument list for `spawn` ?

**Comment by DrunkenPoney** [comment]
I just tried with the full path of git and I get the exact same result except of course for the `spawnfile` and `spawnargs` properties of the child process:
![image](https://user-images.githubusercontent.com/14944216/43334248-e1998a8e-919a-11e8-8850-e168469e7da5.png)

**Comment by DrunkenPoney** [comment]
Nobody has an idea of what's wrong?

**Comment by gireeshpunathil** [comment]
I don't have an idea what could be wrong.

This is how I would debug this, please see if you are able to follow this:

 - change `git` to some other command, such as `notepad.exe` and without any flags
 - see if it works. If so, bring back git, without any flags
 - if it does not work, launch it (node) through windgb, put a breakpoint in `uv_spawn` and run the code. When it hit the breakpoint, see what appears there in terms of parameters - the command line for `git`
 - based on the outcome of that, continue or change the debug stratgey

**Comment by aduh95** [comment]
Related to https://github.com/steveukx/git-js/issues/159, maybe you'll found some useful advice there

**Comment by gireeshpunathil** [comment]
ping @DrunkenPoney - were you able to follow the suggestion / resolve this issue?

**Comment by DrunkenPoney** [comment]
Sorry, I've been busy for the last month and half. I'm not at work actually. I'll check that next Monday

**Comment by gireeshpunathil** [comment]
ping @DrunkenPoney - is this still outstanding?

**Comment by DrunkenPoney** [comment]
@gireeshpunathil I can't reproduce it anymore and I don't find the project I was working on so I would say no

**Comment by gireeshpunathil** [comment]
ok, thanks for the info. So I will close this now. Please feel free to re-open if this issues comes up again!

**Comment by jonjonni** [comment]
Where to enter codes?
