### ISSUE TITLE
Internal module error - "Error: Cannot find module './transform'"

### ISSUE THREAD

**Issue by PankajMoolrajani** [nodejs/help#1437]
react-scripts start

internal/modules/cjs/loader.js:583
throw err;
^

Error: Cannot find module './transform'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
at Function.Module._load (internal/modules/cjs/loader.js:507:25)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object. (/mxr-web/node_modules/ajv-keywords/keywords/index.js:18:14)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mxr-web@0.1.0 start: react-scripts start
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mxr-web@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-08-16T02_49_24_858Z-debug.log

**Comment by ankur-anand** [comment]
You don't have [npm module transform](https://www.npmjs.com/package/transform) installed currently. try running npm install again or check with the react-script issue.

Currently, this issue is not related to Node.js.

**Comment by PankajMoolrajani** [comment]
true, it not nodejs issue. I was able to resolve it by removing package-lock.json, yarn.lock and doing npm install in the project
