### ISSUE TITLE
module.js:549     throw err;  Error:  Cannot find module 'C:\Y_ntt\Try-Angular-v4-master\dist\server.js'

### ISSUE THREAD

**Issue by gg-gg-v1** [nodejs/help#1441]
* **node js version -> v8.11.3
npm versin -> 5.6.0**:
* **Windows 8**:
 
**My Goal: Basically I am trying to convert my angular 5 app to universal app (for SEO purpose) using this link**

https://github.com/angular/angular-cli/wiki/stories-universal-rendering#step-5-setup-a-webpack-config-to-handle-this-node-serverts-file-and-serve-your-application

After running ng build command, I entered the command node dist/server.js and I got the following error.

C:\Y_ntt\Try-Angular-v4-master>node dist/server.js
module.js:549
throw err;
^

Error: Cannot find module 'C:\Y_ntt\Try-Angular-v4-master\dist\server.js'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:612:3

my dist folder content
![error](https://user-images.githubusercontent.com/7572667/44296244-5ce5cd80-a2d8-11e8-86bd-81794eb9e762.PNG)

apart from the command node dist/server.js , I tried following commands also but none of them working
node server.js
node dist/server.js

and if try to run this command node dist/server/main.js
I got following error

C:\Y_ntt\Try-Angular-v4-master>node dist/server/main.js
C:\Y_ntt\Try-Angular-v4-master\node_modules\ngx-bootstrap\carousel\carousel.component.js:14
import { Component, Input, Output, EventEmitter, NgZone } from '@angular/core';
^^^^^^

SyntaxError: Unexpected token import
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.ngx-bootstrap/carousel/carousel.component (C:\Y_ntt\Try-Angular-v4-master\dist\server\main.js:2765:18)

Please help I would highly appreciate!

**Comment by PavelShalahai** [comment]
I have the same problem.

**Comment by gireeshpunathil** [comment]
@gg-gg-v1 - is this still an issue for you? Looking at the error, I guess after `ng build` it did not convert the code into a node.js compatible code, so you may want to report this to angular repo.

**Comment by gg-gg-v1** [comment]
now I am not working on this. 
thanks
