### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by taoqf** [nodejs/help#1452]
* **Node.js Version**:10.9.0
* **OS**: Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64 GNU/Linux
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:[ccap](https://www.npmjs.com/package/ccap)

```sh
npm install ccap 

> ccap@0.6.10 preinstall /home/taoqf/gitee/feidaokj/self_sell/node_modules/ccap
> node make.js

I'm glad you to select ccap, enjoy it!

ccap is a cross plat form and portable nodejs simple captcha module, simple api and lightweight.

starting compile ccap! good luck!

> ccap@0.6.10 install /home/taoqf/gitee/feidaokj/self_sell/node_modules/ccap
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at createHangUpError (_http_client.js:322:15)
gyp ERR! stack     at Socket.socketOnEnd (_http_client.js:425:23)
gyp ERR! stack     at Socket.emit (events.js:187:15)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1085:12)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 4.9.0-7-amd64
gyp ERR! command "/home/taoqf/.nvm/versions/node/v10.9.0/bin/node" "/home/taoqf/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/taoqf/gitee/feidaokj/self_sell/node_modules/ccap
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN daoke@1.0.2018 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ccap@0.6.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ccap@0.6.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/taoqf/.npm/_logs/2018-08-22T02_50_27_159Z-debug.log
```

https://github.com/nodejs/node/issues/22453

**Comment by gireeshpunathil** [comment]
it worked for me, probably it is a transient error due to network issues, can you retry?

**Comment by taoqf** [comment]
It may be the network issues, it's gone now.

**Comment by gireeshpunathil** [comment]
thanks, closing then.

**Comment by taoqf** [comment]
OK, but I can give a clue: it works fine on 10.7.0 under same network.
