### ISSUE TITLE
Error: This socket is closed. (on Windows vs OSX)

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#150]
I get this on Windows

```js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: This socket is closed.
    at Socket._writeGeneric (net.js:640:19)
    at Socket._write (net.js:694:8)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at Socket.Writable.write (_stream_writable.js:207:11)
    at Socket.write (net.js:618:40)
    at process.<anonymous> (c:\Users\denman\WebstormProjects\suman-private\lib\handle-uncaught-exception.js:24:20)
    at emitOne (events.js:77:13)
    at process.emit (events.js:169:7)
    at process._fatalException (node.js:223:26)
```

it is due to this code:

```js
    const strmPath = path.resolve(projRoot + '/suman/stdio-logs/test-stderr.log');
    const strm = global.sumanStderrStream = fs.createWriteStream(strmPath, {flags: 'a'});

    if (!usingRunner) {
        strm.write('Suman start run.');
        process.stderr.pipe(strm);   // this call in particular is what causes it
    }
```

I don't get the error on OSX, just on Windows, same exact code. It is the call to ```process.stderr.pipe(strm); ``` that causes the problem, if I remove that line, then this works on Windows.

Any idea what's going on? How can fix it? thanks

**Comment by ORESoftware** [comment]
if I put an error handler on process.stderr, 

```js
   process.stderr.on('error', function(err){
       console.log(err.stack);
    });
```

then I get 

```
Error: read ENOTCONN
    at exports._errnoException (util.js:874:11)
    at Socket._read (net.js:394:21)
    at Socket.Readable.read (_stream_readable.js:328:10)
    at Socket.read (net.js:283:43)
    at resume_ (_stream_readable.js:718:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
```

**Comment by leesei** [comment]
Not enough context.
What are you trying to connect to?

**Comment by lordKnighton** [comment]
Here is a link for your first err:  http://stackoverflow.com/questions/18591989/nodejs-this-socket-is-closed

--

I'm not sure this is acceptable practice: process.stderr.pipe(strm) and how ever i think the const is throwing it off, try using a var. 

--

So you can't go piping things whimsically, no offense. 
![screen shot 2016-05-24 at 10 14 11 pm](https://cloud.githubusercontent.com/assets/1773260/15528881/2bf0ed62-21fd-11e6-97bc-6f9430a0f3f0.png)

**Comment by lordKnighton** [comment]
@ORESoftware If you wish to continue this convo, reopen issue 

😄

**Comment by ORESoftware** [comment]
It's been awhile since I opened the issue, but I believe it is a possible to stream stdout and stderr to a file, there is just a problem doing it on Windows

**Comment by lordKnighton** [comment]
yea, we're working on the docs for & a guides for streams. 

Anyway happy coding
