### ISSUE TITLE
Request for Nodejs Connector Library to connect to Tibero

### ISSUE THREAD

**Issue by partha6369** [nodejs/help#1508]
* **Node.js v10.10.0**:
* **OS Mac OD High Sierra version 10.13.6 (17G65)**:
* **Scope Other**:
* ****:

**Comment by partha6369** [comment]
Dear Sir,

Thanks for the information.

I followed the instructions and tried to install. I get the below errors. I am getting the same error while installing JDBC. Please help.

```
apples-imac:pConfMan parthamajumdar$ git clone git://github.com/wankdanker/node-odbc.git
fatal: destination path 'node-odbc' already exists and is not an empty directory.
apples-imac:pConfMan parthamajumdar$ cd node-odbc
apples-imac:node-odbc parthamajumdar$ node-gyp configure build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.10.0 | darwin | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /Users/parthamajumdar/anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/parthamajumdar/Documents/Solutions/Paikari/pConfMan/node-odbc
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by NickNaso** [comment]
Hi @partha6369,
I installed on my macOs following these steps:

- Install `inixODBC` through `brew install unixODBC`
- In your Node.js project folder `npm install odbc`
- After the installation you can start use the module in your project.

**Comment by yathamravali** [comment]
@partha6369 
I'm not sure, it looks like the python version is not compatible i.e. old to configure node-gyp. 

Once check `python --version` and ensure it is above 2.7 version

**Comment by yathamravali** [comment]
@partha6369 
I recreated that  the `gyp` tool that `node-gyp` depends on was written for Python 2 and is not compatible with Python 3.

Refer: https://github.com/nodejs/help/issues/1569

**Comment by gireeshpunathil** [comment]
closing as answered
