### ISSUE TITLE
Error: Handshake inactivity timeout with Node.js v8.11.1 and RDS 

### ISSUE THREAD

**Issue by hashimshafiq** [nodejs/help#1519]
Version: v8.11.1
Platform: LINUX

I have RDS running on AWS with NodeJS backed API's. Everything is working perfectly fine. But from today I keep getting an error that "Handshake inactivity timeout"

Error: Handshake inactivity timeout
at Handshake. (/home/ubuntu/server/node_modules/mysql/lib/protocol/Protocol.js:164:17)
at emitNone (events.js:106:13)
at Handshake.emit (events.js:208:7)
at Handshake._onTimeout (/home/ubuntu/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:129:8)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
--------------------
at Protocol._enqueue (/home/ubuntu/server/node_modules/mysql/lib/protocol/Protocol.js:145:48)
at Protocol.handshake (/home/ubuntu/server/node_modules/mysql/lib/protocol/Protocol.js:52:23)
at PoolConnection.connect (/home/ubuntu/server/node_modules/mysql/lib/Connection.js:130:18)
at Pool.getConnection (/home/ubuntu/server/node_modules/mysql/lib/Pool.js:48:16)
at /home/ubuntu/server/new_application/maidpicker.js:61:6
at Layer.handle [as handle_request] (/home/ubuntu/server/node_modules/express/lib/router/layer.js:95:5)
at next (/home/ubuntu/server/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/home/ubuntu/server/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/home/ubuntu/server/node_modules/express/lib/router/layer.js:95:5)
at /home/ubuntu/server/node_modules/express/lib/router/index.js:281:22

**Comment by menme95** [comment]
I have the same error with node 8.9 and Azure server. 
Could you tell me how you solved it?
