### ISSUE TITLE
safe stringify for process.send object

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#1533]
Just wondering, when we use:

```js
   process.send({
        error: err || null,
        result: result || null,
        workId,
        type: (result && result.type) || MessageType.DONE_AND_RETURN_TO_POOL
      });
```

if result or err is a circular / self-referential object, are we going to get a circular reference exception when the object gets serialized, or does Node.js core take care of that?

**Comment by ORESoftware** [comment]
bamp

**Comment by gireeshpunathil** [comment]
#cat 1533.js
```js
const assert = require('assert');
const fork = require('child_process').fork;
if (process.argv[2] === 'child') {
  var obj = {}
  obj.myself = obj
  process.send(obj)
} else {
  const child = fork(process.argv[1], ['child']);
  child.on('message', (message) => {
    console.log(message)
  });
}
```

#node 1533

```trace
internal/child_process.js:751
    const string = JSON.stringify(message) + '\n';
                        ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    --- property 'myself' closes the circle
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:751:25)
    at process.target.send (internal/child_process.js:651:19)
    at Object.<anonymous> (/Users/gireeshpunathil/Desktop/support/1533.js:7:11)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
#
```

Is this what you mean?

**Comment by gireeshpunathil** [comment]
ping @ORESoftware

**Comment by ORESoftware** [comment]
yeah, pretty certain we have to handle circular refs ourselves, np

**Comment by addaleax** [comment]
@ORESoftware If you want to, you can use `v8.serialize()` and `v8.deserialize()` to convert between more complex JS data structures (including circular ones) and Buffers. While you may not be able to send Buffers directly using `process.send()`, converting them to a string using either `latin1` or `base64` should work.
