### ISSUE TITLE
DNS lookup failure when trying to access Amazon RDS endpoint

### ISSUE THREAD

**Issue by gokulk94** [nodejs/help#1546]
* **Node.js Version**: 4.2.1
* **OS**: Amazon Linux AMI
* **Scope (install, code, runtime, meta, other?)**: runtime

I have an API server that fetches data from RDS(MySql) and serves consumers.
Recently I'm seeing some DNS lookup failure when MySql module tries to connect to RDS endpoint.

```
Error: getaddrinfo ENOTFOUND <RDS endpoint> <RDS endpoint>:3306\n    at errnoException (dns.js:26:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```
This happens intermittendly, not on every request.
I tried the following,
- check if this is an issue of file descriptors being low - it's not. `ulimit -a` shows 500k open file limit.
- I was not able to reproduce the issue in my local environment.

```js
const mysql = require('mysql');

const pool = mysql.createPool({
  connectionLimit : 10,
  host     : '<RDS endpoint>',
  user     : 'XXXX',
  password : 'XXXXX',
  database : 'XXXX',
  ssl: 'XXXXX'
});

module.exports = {
  getConnection: function(callback) {
    return pool.getConnection(callback);
  }
};

// Then I import this file whereever I want a connection and use it for querying. I also release the connection once request is complete.
```

- Is this an known issue within Node?
- I saw an old issue(https://github.com/nodejs/node-v0.x-archive/issues/5488) that is similar to mine, however it's seems to be not resolved. Also saw another related issue posted here, #1184 that was closed due to inactivity.
- Is there any workaround for this problem?

Thanks,
Gokul

**Comment by aljaxus** [comment]
Having same issue with mysql package.
Tried connecting to personal VPS, another VPS and `localhost` - all result in same error (same as above)
```

h:\workspaces\REPLACED\server.js:123
  if (err) throw err
           ^

Error: getaddrinfo ENOTFOUND localhost:3306 localhost:3306:3306
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
    --------------------
    at Protocol._enqueue (h:\workspaces\REPLACED\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (h:\workspaces\hub.aljaxus.eu_api\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (h:\workspaces\REPLACED\node_modules\mysql\lib\Connection.js:118:18)
    at Object.<anonymous> (h:\workspaces\REPLACED\server.js:122:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
```

**Comment by aljaxus** [comment]
**Details**
Node: `v10.13.0`
Packages: `mysql`

Having same issue with mysql package.
Tried connecting to personal VPS, another VPS and `localhost` - all result in same error (same as above)
```

h:\workspaces\REPLACED\server.js:123
  if (err) throw err
           ^

Error: getaddrinfo ENOTFOUND localhost:3306 localhost:3306:3306
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
    --------------------
    at Protocol._enqueue (h:\workspaces\REPLACED\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (h:\workspaces\REPLACED\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (h:\workspaces\REPLACED\node_modules\mysql\lib\Connection.js:118:18)
    at Object.<anonymous> (h:\workspaces\REPLACED\server.js:122:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
```

**Comment by gireeshpunathil** [comment]
ping @gokulk94 - is this still outstanding?

**Comment by gokulk94** [comment]
@gireeshpunathil unfortunately, yes.
After some investigation, it seems the DNS lookup failure happens for me when the API server is configured to run at system startup. It feels like the network is not up when application starts.

The application is run with PM2. So the workaround I use now is to restart the pm2 process manually after system startup. That would fix the lookup error for me.

Right now, I'm tinkering with startup scripts to try resolving the issue.

**Comment by gireeshpunathil** [comment]
@gokulk94 - ok, nice to know. I am not seeing any node.js issues that need to be fixed here, so I will close this out. Please let me know if that is not the case.

**Comment by jross-ai** [comment]
Did anyone find a solution to this issue?

**Comment by gokulk94** [comment]
@jross-ai 
I was able to resolve this by moving to a systemd based OS(moved to amazonlinux2) and modify startup script as suggested by [pm2 doc](https://pm2.keymetrics.io/docs/usage/startup/#systemd-installation-checking)
