### ISSUE TITLE
C++ ADDONS Error

### ISSUE THREAD

**Issue by ramprasad2018** [nodejs/help#1604]
* **Node.js Version**: v10.13.0
* **OS**:    Windows 7
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: ADDONS for C++

Issue: - The npm-gyp configure command is getting failed.
Question: - Why the npm-gyp is calling the Python ? Is it mandatory? Even if needed, how to resolve the Python Error ?
Attached : - The screenshot of the error and the project folder.
Error:
C:\Ram\Projects\GraphQL\t\addon>node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.13.0 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Software\Python37-32\python.exe -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack File "", line 1
gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack at ChildProcess.emit (events.js:182:13)
gyp ERR! stack at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack at Socket.emit (events.js:182:13)
gyp ERR! stack at Pipe._handle.close (net.js:606:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\software\nodejs\node.exe" "C:\Users\Admin\AppData\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "configure"
gyp ERR! cwd C:\Ram\Projects\GraphQL\t\addon
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
![capture](https://user-images.githubusercontent.com/43319298/48316409-407ad800-e61e-11e8-8522-1fbde5b48dd2.JPG)

Package.json:

{
  "name": "my_addon",
  "version": "0.0.0",
  "description": "My reusable C++ addon",
  "gypfile": true,
  "main": "./build/Release/my_addon",
  "license": "1.0",
  "dependencies": {
    "nan": "^2.3.3",
    "node-gyp": "^3.8.0"
  }
}

![capture](https://user-images.githubusercontent.com/43319298/48316440-a36c6f00-e61e-11e8-9860-ea7e2eb32f3b.JPG)
[addon.zip](https://github.com/nodejs/help/files/2569647/addon.zip)

**Comment by ramprasad2018** [comment]
Hi Nick,
Thank you very much. I will try the Windows Option 1. 
regards,
Ram

**Comment by ramprasad2018** [comment]
Thank you Nick. The issue is not resolved. I note that Python 2.7.15 should be used instead of 3.6

regards, Ram
