### ISSUE TITLE
Node acts like not seeing more files in directory

### ISSUE THREAD

**Issue by WhiteLeash** [nodejs/help#1620]
* **Node.js Version**: v.11.0.0
* **OS**: Linux Manjaro Illyria 18.0.0
* **Scope (install, code, runtime, meta, other?)**: Problem with `code`
* **Module (and version) (if relevant)**: Nope - raw `Node`

Hi.
I have problem with my method walk() in class FolderTree:

```js
walk(prop = {
        workDir: this.tree.path,
        objDirPath: ""
    }) {
        //Iteration for debug purposes
        this.iteration++;
        console.log(this.iteration);
        
        //Save all files and dirs of current directory to `ls`
        let ls = this.lsDir(prop.workDir);

        //Map list of files and dirs
        ls.map((path) => {
            //If .git-like file/dir - ignore
            if(/^.git*/.test(path)) return;

            //Stat of each file/dir
            let statOfPath = fs.lstatSync(`${prop.workDir}/${path}`);
            
            //If it's file
            if (statOfPath.isFile()) {
                console.log(`${path} is file and it's added`);
                
                //Do in tree directory property new obj with:
                //Name of path to dir
                eval(`this.tree${prop.objDirPath}`)['path'] = prop.workDir;
                //If there is no files property - do one with this file
                if (!eval(`this.tree${prop.objDirPath}`)['files']) eval(`this.tree${prop.objDirPath}`)['files'] = [path];
                //If already is files array in this directory property - add this file to it
                else eval(`this.tree${prop.objDirPath}`)['files'].push(path);

                console.log(this.tree);
            }
            //If it's dir
            if (statOfPath.isDirectory()) {
                this.walk(prop = {
                    workDir: `${prop.workDir}/${path}`,
                    objDirPath: `${prop.objDirPath}.directories`
                });
            }
        })

        return this.tree;
    }
```
(If needed lookup for whole class > [Link to gist](https://gist.github.com/WhiteLeash/2d5f0c242dbf29e10e4cfef02595b76a))
When I test it in folder I have:

```bash
➜  tree-project git:(master) ✗ node object_ls
1
logic.md is file and it's added
{ path: '/home/tymoteusz/Desktop/Coding/tree-project',
  files: [ 'logic.md' ],
  directories: {} }
object_ls.js is file and it's added
{ path: '/home/tymoteusz/Desktop/Coding/tree-project',
  files: [ 'logic.md', 'object_ls.js' ],
  directories: {} }
2
blink is file and it's added
{ path: '/home/tymoteusz/Desktop/Coding/tree-project',
  files: [ 'logic.md', 'object_ls.js' ],
  directories:
   { path:
      '/home/tymoteusz/Desktop/Coding/tree-project/sample_directory',
     files: [ 'blink' ] } }
3
fs.js:122
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '/home/tymoteusz/Desktop/Coding/tree-project/sample_directory/forth_dir/sample_file'
    at Object.lstatSync (fs.js:856:3)
    at ls.map (/home/tymoteusz/Desktop/Coding/tree-project/object_ls.js:36:33)
    at Array.map (<anonymous>)
    at FolderTree.walk (/home/tymoteusz/Desktop/Coding/tree-project/object_ls.js:31:12)
    at ls.map (/home/tymoteusz/Desktop/Coding/tree-project/object_ls.js:54:22)
    at Array.map (<anonymous>)
    at FolderTree.walk (/home/tymoteusz/Desktop/Coding/tree-project/object_ls.js:31:12)
    at Object.<anonymous> (/home/tymoteusz/Desktop/Coding/tree-project/object_ls.js:65:10)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
```
As you see first and second iteration works but with exception, if it's more in second iteration (`sample_directory`) files there find one file but there were 3 (`blink`,`sample`,`second`).

And I have problem in next iteration as you can see - it's going here "deeper" but it shoud scan files in it's parent directory in this case.

Below my actual folder tree:
```
➜  tree-project git:(master) tree
.
├── logic.md
├── object_ls.js
├── sample_directory
│   ├── blink_file
│   ├── forth_dir
│   ├── sample_file
│   ├── second_directory
│   │   ├── one_file
│   │   └── third_directory
│   └── second_file
└── simple_one
    └── test_file

5 directories, 7 files
```

**Comment by WhiteLeash** [comment]
I found my problem - my idea was right, code not so really - map still used item from previous ls but directory changed. Tomorrow I will see how I can change it. If any other ideas feel free to give feedback.
