### ISSUE TITLE
Problem building hello_world addon in V8 tutorial

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/help#1629]
* **Node.js Version**: 11.2.0
* **OS**: Windows 10 Home
* **Scope (install, code, runtime, meta, other?)**: code (need help building "hello world" Addon in V8 tutorial
* **Module (and version) (if relevant)**: V8

My issue is that I tried to build the "hello world" example Addon [here](https://nodejs.org/dist/latest-v11.x/docs/api/addons.html), but couldn't due to errors.  Messages I got when I ran the "node-gyp configure" command were:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.2.0 | win32 | x64
openssl config failed: error:02001003:system library:fopen:No such process
gyp http GET https://nodejs.org/download/release/v11.2.0/node-v11.2.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v11.2.0/node-v11.2.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v11.2.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v11.2.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v11.2.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v11.2.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v11.2.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v11.2.0/win-x86/node.lib
gyp info spawn C:\depot_tools\python.BAT
gyp info spawn args [ 'C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info [0mspawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
The system cannot find the path specified.
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\programming\\Node_Addons\\hello_addon\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Osman\\.node-gyp\\11.2.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Osman\\.node-gyp\\11.2.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Osman\\.node-gyp\\11.2.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\programming\\Node_Addons\\hello_addon',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\programming\\Node_Addons\\hello_addon\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Osman\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd E:\programming\Node_Addons\hello_addon
gyp ERR! node -v v11.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
What I did was create the `hello.cc` file, clone the Node repository and build it (though there were errors with zlib, I was able to build it all -- I probably just shouldn't use zlib), then write gyp file and try to configure the Addon.  The hello.cc file I wrote looks like this:
```cpp
#include <node.h>
#include <v8.h>

namespace demo
{
	using v8::FunctionCallbackInfo;
	using v8::Isolate;
	using v8::Local;
	using v8::NewStringType;
	using v8::Object;
	using v8::String;
	using v8::Value;

	void Method(const FunctionCallbackInfo<Value> &args)
	{
		Isolate *isolate = args.GetIsolate();
		args.GetReturnValue().Set(String::NewFromUtf8(
			isolate, "world", NewStringType::kNormal).ToLocalChecked());
	}

	void Initialize(Local<Object> exports)
	{
		NODE_SET_METHOD(exports, "hello", Method);
	}

	NODE_MODULE(NODE_GYP_MODULE_NAME, Initialize)
}
```
And the binding.gyp file looks like this:
```gyp
{
  "targets": [
    {
      "target_name": "addon",
      "sources": [ "hello.cc" ]
    }
  ]
}
```
Please help.  Thanks in advance.

**Comment by gireeshpunathil** [comment]
not sure, the problem reported here https://github.com/npm/npm/issues/17261#issuecomment-310797098 matches your case, can you please follow the suggested steps and see if it resolves?

**Comment by gireeshpunathil** [comment]
inactive, closing
