### ISSUE TITLE
code ELIFECYCLE Exit status 1 at EventEmitter.<anonymous> in MS Azure

### ISSUE THREAD

**Issue by crdo** [nodejs/help#1640]
So I'am deploying my ASP.NET Core app to MS Azure and getting "code ELIFECYCLE Exit status 1 at EventEmitter.<anonymous> in MS Azure".

It works locally on my macOS Mojave with the same version of nodejs.

Any ideas?

* **Node.js Version 8.9.4**:
* **OS Microsoft Windows NT 10.0.14393.0**:

```js
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files (x86)\\nodejs\\8.9.3\\node.exe',
1 verbose cli   'D:\\Program Files (x86)\\npm\\5.6.0\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v8.9.4
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle gymnastika@0.1.0~prebuild: gymnastika@0.1.0
6 info lifecycle gymnastika@0.1.0~build: gymnastika@0.1.0
7 verbose lifecycle gymnastika@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle gymnastika@0.1.0~build: PATH: D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\home\site\repository\ClientApp\node_modules\.bin;D:\Program Files (x86)\SiteExtensions\Kudu\79.11115.3647\bin\NativeBinaries/x86;D:\home\site\deployments\tools;D:\Program Files (x86)\SiteExtensions\Kudu\79.11115.3647\bin\Scripts;D:\Program Files (x86)\MSBuild\14.0\Bin;D:\Program Files\Git\cmd;D:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;D:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn;D:\Program Files (x86)\Microsoft SDKs\F#\3.1\Framework\v4.0;D:\Program Files\Git\bin;D:\Program Files\Git\usr\bin;D:\Program Files\Git\mingw64\bin;D:\Program Files (x86)\npm\5.6.0;C:\DWASFiles\Sites\#1gymsporty\AppData\npm;D:\Program Files (x86)\bower\1.7.9;D:\Program Files (x86)\grunt\0.1.13;D:\Program Files (x86)\gulp\3.9.0.1;D:\Program Files (x86)\funcpack\1.0.0;D:\Program Files (x86)\nodejs\8.9.3;D:\Windows\system32;D:\Windows;D:\Windows\System32\Wbem;D:\Windows\System32\WindowsPowerShell\v1.0\;D:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;;D:\Program Files (x86)\dotnet;D:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;D:\Program Files (x86)\Git\cmd;D:\Program Files (x86)\PHP\v5.6;D:\Python27;
9 verbose lifecycle gymnastika@0.1.0~build: CWD: D:\home\site\repository\ClientApp
10 silly lifecycle gymnastika@0.1.0~build: Args: [ '/d /s /c', 'react-scripts build' ]
11 silly lifecycle gymnastika@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle gymnastika@0.1.0~build: Failed to exec build script
13 verbose stack Error: gymnastika@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files (x86)\npm\5.6.0\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid gymnastika@0.1.0
15 verbose cwd D:\home\site\repository\ClientApp
16 verbose Windows_NT 10.0.14393
17 verbose argv "D:\\Program Files (x86)\\nodejs\\8.9.3\\node.exe" "D:\\Program Files (x86)\\npm\\5.6.0\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.9.4
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error gymnastika@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the gymnastika@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Tushar-Tilwani** [comment]
Did you found the issue?

**Comment by crdo** [comment]
Yes. Incorrect version of Node. It is incorrectly ordered in Azure config (alfanumerically) so i missed the 10.xx versions between 1.xx

**Comment by gireeshpunathil** [comment]
closing then! thanks.
