### ISSUE TITLE
EADDRINUSE: False Positive with busy port when running npm start

### ISSUE THREAD

**Issue by JamesRLamar** [nodejs/help#1655]
* **Node.js Version**: 10.14.1
* **OS**: Mac OS HIgh Sierra
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:

This issue may be related to installing a python 3 dev environment. I get this on both Mac and Ubuntu when trying run `npm start` which kicks off my local server on port 4000 plus a mock backend server on port 4200. I've verified there are no services running on port 4000. Here is the relevant part of the error message:

[0] Mock Backend listening on: localhost:4000
[0] Using fixture: default with async timeout of: 0
[0] > events.js:167
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: listen EADDRINUSE 127.0.0.1:4000
[0]     at Server.setupListenHandle [as _listen2] (net.js:1286:14)
[0]     at listenInCluster (net.js:1334:12)
[0]     at GetAddrInfoReqWrap.doListen [as callback] (net.js:1460:7)
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:62:10)
[0] Emitted 'error' event at:
[0]     at emitErrorNT (net.js:1313:8)
[0]     at process._tickCallback (internal/process/next_tick.js:63:19)
[0] npm ERR! code ELIFECYCLE
[0] npm ERR! errno 1
[0] npm ERR! management-ui@1.6.23 mock-backend: `node node_modules/@custome/shared/mock-backend`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the management-ui@1.6.23 mock-backend script.
[0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above

**Comment by JamesRLamar** [comment]
Issue solved. There was a service called 'nx' which was bound to port 4000. Running 'lsof' did not reveal any process but running 'netstat -anv | grep 4000' did show the process. The process was kicked off by NoMachine and after it was killed my services ran fine.
