### ISSUE TITLE
Problem building Hello World Addon at https://nodejs.org/dist/latest-v11.x/docs/api/addons.html

### ISSUE THREAD

**Issue by DragonOsman** [nodejs/help#1662]
* **Node.js Version**: v11.3.0
* **OS**: Windows 10 Home
* **Scope (install, code, runtime, meta, other?)**: building addon
* **Module (and version) (if relevant)**: node-gyp version 3.8.0

I just tried to build the Hello World addon shown here: https://nodejs.org/dist/latest-v11.x/docs/api/addons.html with node-gyp but it failed.  This is the output I got from running the `node-gyp configure` command:
```
node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@11.3.0 | win32 | x64
openssl config failed: error:02001003:system library:fopen:No such process
gyp http GET https://nodejs.org/download/release/v11.3.0/node-v11.3.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v11.3.0/node-v11.3.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v11.3.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v11.3.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v11.3.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v11.3.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v11.3.0/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v11.3.0/win-x64/node.lib
gyp info spawn E:\v8_dev\depot_tools\python.BAT
gyp info spawn args [ 'C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info [35mspawn args[0m   '-f',
gyp info spawn args   'msvs',
gyp infoThe system cannot find the path specified.
 spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'E:\\programming\\Node_Addons\\hello_addon\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Osman\\.node-gyp\\11.3.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Osman\\.node-gyp\\11.3.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\Osman\\.node-gyp\\11.3.0\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=E:\\programming\\Node_Addons\\hello_addon',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'E:\\programming\\Node_Addons\\hello_addon\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Osman\AppData\Roaming\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Osman\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure"
gyp ERR! cwd E:\programming\Node_Addons\hello_addon
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```
I'd like to know how to make this work.  And I also want to know how to set `msvs_version` to 2017.  Any help would be appreciated.  [Does it not like that it's Windows NT?  Or that the path to node.exe has a space in it?]

**Comment by DragonOsman** [comment]
I got it to work by doing `node-gyp configure --msvc_version=2017` and IIRC I also set a Python version variable and path.  I don't have the full command anymore.  But either way, I did get it to work, although it was still showing `msvs_version=2015` up there.  I couldn't fix that.  

Anyway, I still need help with turning my currency converter application into an Addon.  I made the code asynchronous, and on the NodeJS website I read that the example Addons there can be used as starting points for an Addon.  I'd like some help in using the Hello World example Addon as a starting point for mine.  The code, again, is [here](https://github.com/DragonOsman/currency_converter).  The C++ code is what I'll turn into an Addon, of course.  The static assets are to be served by the server as part of the application.  

I especially need help on the exports: how do I make sure that all of the functions and variables that I want to expose to Node.js will be added to the `exports` object?  And how do I expose the networking functionality used in my code to Node.js?

**Comment by gireeshpunathil** [comment]
@DragonOsman - is this still outstanding?

You can map your CPP functions to JS function in the `Initialize` function as shown below:
```c++
void Initialize(Local<Object> exports) {
  NODE_SET_METHOD(exports, "jsfoo", CppFoo);
  NODE_SET_METHOD(exports, "jsbar", CppBar);
  NODE_SET_METHOD(exports, "jsbaz", CppBaz);
}
```

and then define those CPP functions with signature as below:

```c++
void CppFoo(const FunctionCallbackInfo<Value>& args) { ... }
void CppBar(const FunctionCallbackInfo<Value>& args) { ... }
void CppBaz(const FunctionCallbackInfo<Value>& args) { ... }
```

and then in the JS land those will be visible as:


```js
{
  jsfoo: [Function: jsfoo],
  jsbar: [Function: jsbar],
  jsbaz: [Function: jsbaz]
}
```

**Comment by gireeshpunathil** [comment]
answered, closing
