### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by JesusSierra** [nodejs/help#1677]
Why does the terminal sends this error? 

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
    at Module.require (internal/modules/cjs/loader.js:653:11)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jesussierra/Documents/curso-mean2/app.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/jesussierra/Documents/curso-mean2/index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

**Comment by gireeshpunathil** [comment]
please provide a test case, of detailed steps to recreate!

**Comment by gireeshpunathil** [comment]
no followup in a month, closing
