### ISSUE TITLE
Error when using require('stream').Readable;

### ISSUE THREAD

**Issue by AshokRamaraja** [nodejs/help#1689]
If you have a question about Node.js that is not a bug report or feature
request, please post it in https://github.com/nodejs/help!

Questions posted to this repository will be closed.

Hello ,
I am receiving the following Error when i try to stream data using Readable stream.

_stream_readable.js:992
      stream.pause();
             ^

TypeError: stream.pause is not a function
    at Stream.stream.on (_stream_readable.js:992:14)
    at Stream.emit (events.js:189:13)
    at Stream.EventEmitter.emit (domain.js:441:20)
    at Socket.<anonymous> (/app/node_modules/webshot/lib/webshot.js:259:9)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
[nodemon] app crashed - waiting for file changes before starting...

I couldnt track why this issue is happenening. 
I am trying to generate images based on the data i am getting from webshot screenshot call back. Can somebody get back to me the reason behind this issue.

**Comment by Qix-** [comment]
Which version of Node are you using? Can you show some example code?

**Comment by gireeshpunathil** [comment]
ping @AshokRamaraja

**Comment by gireeshpunathil** [comment]
inactive, closing
