### ISSUE TITLE
When I run the command "gulp test" the tests are not getting executed and it returns error.

### ISSUE THREAD

**Issue by dmajumder4292** [nodejs/help#1696]
When I run the command 'gulp test', tests are not getting executed, instead I get an error.

```
[11:08:19] Using gulpfile /mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/gulpfile.js
[11:08:21] Starting 'test'...
[11:08:21] Starting 'clean'...
[11:08:22] 'clean' errored after 86 ms
[11:08:22] TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Module.require (internal/modules/cjs/loader.js:652:3)
    at require (internal/modules/cjs/helpers.js:22:18)
    at requireFn (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.get (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/gulp-load-plugins/index.js:59:18)
    at Gulp.<anonymous> (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/gulpfile.js:107:21)
    at module.exports (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/index.js:134:8)
[11:08:22] 'test' errored after 158 ms
[11:08:22] TypeError [ERR_INVALID_ARG_TYPE] in plugin 'run-sequence(clean)'
Message:
    The "id" argument must be of type string. Received type object
Stack:
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at Module.require (internal/modules/cjs/loader.js:652:3)
    at require (internal/modules/cjs/helpers.js:22:18)
    at requireFn (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/gulp-load-plugins/index.js:37:14)
    at Object.get (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/gulp-load-plugins/index.js:59:18)
    at Gulp.<anonymous> (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/gulpfile.js:107:21)
    at module.exports (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/mnt/c/Users/Debchakra/Desktop/Zagg-Stellar-Base/zagg-stellar-base/node_modules/orchestrator/index.js:134:8)
```
The gulpfile.js is written as below:

```
'use strict';

var gulp        = require('gulp');
var isparta     = require('isparta');
var plugins     = require('gulp-load-plugins')();
var runSequence = require('run-sequence');
var webpack     = require("webpack");

gulp.task('default', ['build']);

gulp.task('lint:src', function() {
  return gulp.src(['src/**/*.js'])
    .pipe(plugins.plumber())
    .pipe(plugins.jshint())
    .pipe(plugins.jshint.reporter('jshint-stylish'))
    .pipe(plugins.jshint.reporter('fail'));
});

// Lint our test code
gulp.task('lint:test', function() {
  return gulp.src(['test/unit/**/*.js'])
    .pipe(plugins.plumber())
    .pipe(plugins.jshint())
    .pipe(plugins.jshint.reporter('jshint-stylish'))
    .pipe(plugins.jshint.reporter('fail'));
});

gulp.task('build', function(done) {
  runSequence('clean', 'build:node', 'build:browser', done);
});

gulp.task('test', function(done) {
  runSequence('clean', 'test:node', 'test:browser', done);
});


gulp.task('hooks:precommit', ['build'], function() {
  return gulp.src(['dist/*', 'lib/*'])
    .pipe(plugins.git.add());
});

gulp.task('build:node', ['lint:src'], function() {
    return gulp.src('src/**/*.js')
        .pipe(plugins.babel())
        .pipe(gulp.dest('lib'));
});

gulp.task('build:browser', ['lint:src'], function() {
  return gulp.src('src/browser.js')
    .pipe(plugins.webpack({
      output: { library: 'ZaggStellarBase' },
      module: {
        loaders: [
          { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'}
        ]
      },
      plugins: [
        // Ignore native modules (ed25519)
        new webpack.IgnorePlugin(/ed25519/)
      ]
    }))
    .pipe(plugins.rename('zagg-stellar-base.js'))
    .pipe(gulp.dest('dist'))
    .pipe(plugins.uglify({
      output: {
        ascii_only: true
      }
    }))
    .pipe(plugins.rename('zagg-stellar-base.min.js'))
    .pipe(gulp.dest('dist'));
});

gulp.task('test:init-istanbul', ['clean-coverage'], function () {
  return gulp.src(['src/**/*.js'])
    .pipe(plugins.istanbul({
      instrumenter: isparta.Instrumenter
    }))
    .pipe(plugins.istanbul.hookRequire());
});

gulp.task('test:node', ['build:node', 'test:init-istanbul'], function() {
  return gulp.src(["test/test-helper.js", "test/unit/**/*.js"])
    .pipe(plugins.mocha({
      reporter: ['dot']
    }))
    .pipe(plugins.istanbul.writeReports());
});

gulp.task('test:browser', ["build:browser"], function (done) {
  var Server = require('karma').Server;
  var server = new Server({ configFile: __dirname + '/karma.conf.js' });
  server.start(function() {
    done();
  });
});

gulp.task('test:sauce', ["build:browser"], function (done) {
  var Server = require('karma').Server;
  var server = new Server({ configFile: __dirname + '/karma-sauce.conf.js' });
  server.start(function() {
    done();
  });
});

gulp.task('clean', function () {
  return gulp.src(['dist', 'lib'], { read: false })
      .pipe(plugins.rimraf());
});

gulp.task('watch', ['build'], function() {
  gulp.watch('lib/**/*', ['build']);
});

gulp.task('clean-coverage', function() {
  return gulp.src(['coverage'], { read: false })
    .pipe(plugins.rimraf());
});

gulp.task('submit-coverage', function() {
  return gulp
      .src("./coverage/**/lcov.info")
      .pipe(plugins.coveralls());
});

```

And here is the package.json, which I think might be helpful:

```
{
  "name": "test-stellar-base",
  "version": "0.0.3",
  "description": "Low level stellar support library compatible with zagg-core",
  "main": "lib/index.js",
  "scripts": {
    "test": "babel-node ./node_modules/gulp/bin/gulp.js test:node",
    "docs": "./node_modules/.bin/jsdoc ./src/ -d docs/",
    "preversion": "gulp test",
    "version": "gulp build",
    "postversion": "git push && git push --tags"
  },
  "browser": {
    "ed25519": false
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/stellar/js-stellar-base.git"
  },
  "keywords": [
    "stellar"
  ],
  "engines": {
    "node": ">=4"
  },
  "author": "Scott Fleckenstein <scott@stellar.org>",
  "license": "Apache-2.0",
  "bugs": {
    "url": "https://github.com/stellar/js-stellar-base/issues"
  },
  "homepage": "https://github.com/stellar/js-stellar-base",
  "devDependencies": {
    "babel": "~5.8.23",
    "babel-core": "~5.8.25",
    "babel-loader": "~5.3.2",
    "chai": "^2.2.0",
    "coveralls": "^2.11.4",
    "express": "^4.9.8",
    "ghooks": "^0.3.0",
    "gulp": "^3.8.11",
    "gulp-babel": "^4.0.1",
    "gulp-coveralls": "^0.1.3",
    "gulp-git": "~0.5.3",
    "gulp-istanbul": "^1.1.1",
    "gulp-jshint": "^1.10.0",
    "gulp-load-plugins": "^0.9.0",
    "gulp-mocha": "^2.0.1",
    "gulp-plumber": "^1.0.0",
    "gulp-rename": "~1.2.0",
    "gulp-rimraf": "~0.1.0",
    "gulp-uglify": "~0.3.1",
    "gulp-webpack": "^1.3.1",
    "isparta": "^3.1.0",
    "istanbul": "^0.4.5",
    "jsdoc": "3.5.5",
    "jshint-stylish": "^1.0.1",
    "karma": "^0.13.9",
    "karma-chrome-launcher": "^0.1.7",
    "karma-firefox-launcher": "^0.1.4",
    "karma-mocha": "^0.1.10",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-sauce-launcher": "^1.1.0",
    "karma-sinon-chai": "^0.3.0",
    "karma-webpack": "^1.8.0",
    "minami": "^1.1.1",
    "mocha": "~1.17.1",
    "run-sequence": "^1.0.2",
    "sinon": "^1.14.1",
    "sinon-chai": "^2.7.0",
    "webpack": "^1.15.0"
  },
  "dependencies": {
    "base32.js": "~0.1.0",
    "bignumber.js": "^4.0.0",
    "crc": "3.5.0",
    "gulp-cli": "^2.0.1",
    "js-xdr": "^1.0.5",
    "lodash": "^4.17.10",
    "sha.js": "^2.3.6",
    "tweetnacl": "^1.0.0"
  },
  "optionalDependencies": {
    "ed25519": "0.0.4"
  }
}

```
The project is very similar to this github repo: [https://github.com/stellar/js-stellar-base](https://github.com/stellar/js-stellar-base)

**Comment by gireeshpunathil** [comment]
I guess this should be reported to https://github.com/gulpjs/gulp

**Comment by gireeshpunathil** [comment]
wrog repo, closing
