### ISSUE TITLE
Trying to make a discord bot and getting SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by AntoniTC** [nodejs/help#1705]
* **10.15.0**:
* **windows 10**:

I'm trying to make a discord bot that responds to certain emoji with certain messages, but I get the error below when I try to run node bot.js

C:\Users\USER1\Documents\EmojiBot\bot.js:1
(function (exports, require, module, __filename, __dirname) { ��v
                                                              ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)

Here is my code:

```js
var Discord = require('discord.io');
var logger = require('winston');
var auth = require('./auth.json');
// Configure logger settings
logger.remove(logger.transports.Console);
logger.add(new logger.transports.Console, {
    colorize: true
});
logger.level = 'debug';
// Initialize Discord Bot
var bot = new Discord.Client({
   token: auth.token,
   autorun: true
});
bot.on('ready', function (evt) {
    logger.info('Connected');
    logger.info('Logged in as: ');
    logger.info(bot.username + ' - (' + bot.id + ')');
});
bot.on('message', function (user, userID, channelID, message, evt) {
    // Our bot needs to know if it will execute a command
    // It will listen for messages that will start with `!`
    if (message.substring(0, 1) == '!') {
        var args = message.substring(1).split(' ');
        var cmd = args[0];
       
        args = args.splice(1);
        switch(cmd) {
            case '😄':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: נפשי נמלאת רינה ודיצה'
                });
            break;
            // Just add any case commands if you want to..
            case '👋':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: האח הידד, כה לחי'
                });
            break;
            case '😜':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: לשוני נחרצת לעומתך'
                });
            break;
            case '😳':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: הותרתני במבוכה וכלימה'
                });
            break;
            case '😍':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: האהבה ממלאת כל נים שבי'
                });
            break;
            case '💪':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: ישר חילך, לך בכוחך זה'
                });
            break;
            case '👍':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: ראיתי, הבנתי, רות קיבלתי'
                });
            break;
            case '😂':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: הבאתני לסף דמעות של אושר'
                });
            break;
            case '😡':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: אני שרוי בעידנא דריתחא'
                });
            break;
            case '🤔':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: עודני נמלך בדעתי'
                });
            break;
            case '😱':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: אני בהלם, תדהמה ותבהלה'
                });
            break;
            case '🙏':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: אמן כן יהי רצון או רגשות תודה והוקרה'
                });
            break;
            case '🤑':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: הכסף יענה את הכול'
                });
            break;
            case '🙃':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: נתהפכו היוצרות'
                });
            break;
            case '🤐':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: סייג לחוכמה שתיקה'
                });
            break;
            case '😷':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: שם מחסום לפיו'
                });
            break;
            case '😭':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: פלג מים תרד עיני'
                });
            break;
            case '💔':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: ליבי נשבר בקרבי'
                });
            break;
            case '😴':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: עייף ויגע אנוכי'
                });
            break;
            case '😆':
                bot.sendMessage({
                    to: channelID,
                    message: 'תרגום: צחוק עשה לי אלוהים'
                });
            break;
         }
     }
});
```
-->

**Comment by addaleax** [comment]
Can you run `node -p "fs.readFileSync('bot.js')"` and share the result?

Also, since you’re partially using Hebrew characters – can you make sure that your editor is set to saving files using UTF-8 as its character encoding?

**Comment by AntoniTC** [comment]
Thank you for the response, I changed the encoding and run the command. it says:
<Buffer ef bb bf 76 61 72 20 44 69 73 63 6f 72 64 20 3d 20 72 65 71 75 69 72 65 28 27 64 69 73 63 6f 72 64 2e 69 6f 27 29 3b 0d 0a 76 61 72 20 6c 6f 67 67 65 ... >
