### ISSUE TITLE
need help with this error 

### ISSUE THREAD

**Issue by miaws** [nodejs/help#1727]
i need help i got this error and i dont know how to fix it and new on this help me :P

PS C:\Users\qwerty\Documents\bot> node .
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'C:\Users\qwerty\Documents\bot'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by Hakerh400** [comment]
Create `index.js` file and put some code in it. I suggest you to read the official [getting started](https://nodejs.org/en/docs/guides/getting-started-guide/) guide.

**Comment by gireeshpunathil** [comment]
closing as answered
