### ISSUE TITLE
package.json not found from subfolder

### ISSUE THREAD

**Issue by SpecialEliteSNP** [nodejs/help#1755]
So I have the following directory
--commands
----botinfo.js
--package.json

and in botinfo.js I want to use the version from my package.json so I did the following:
`const package = require("package.json")`
and tried calling the version by doing `package.version` somewhere else in the botinfo.js file.

But then when I try to start it with `node index.js` and try loading that it gives me:

```js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

I have used the relative path of package.json too `require("./package.json")` but that doesn't work either.
So what it is I am trying to do here is trying to access a file within the root folder from within a script in a subfolder.
Any help would be appreciated. ❤️

**Comment by addaleax** [comment]
Can you share source code? Any other information, such as Node.js version?

Did you try using `require("./package.json")`?

**Comment by SpecialEliteSNP** [comment]
The Node.js version is 6.4.1 and yes I tried that. Do I need to include anything else that can help fix this?

**Comment by SpecialEliteSNP** [comment]
```js
ban.js loaded!
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module './package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/app/commands/botinfo.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by addaleax** [comment]
If you’re loading it from `commands/somefile.js`, then you’ll probably want to use `../package.json`, so that it actually looks for the file in the right directory.

**Comment by SpecialEliteSNP** [comment]
I have looked all over the internet. And it was as simple as adding another ```.```
Thanks dude. My issue is hereby resolved.
