### ISSUE TITLE
Errors when updating Node [windows 7]

### ISSUE THREAD

**Issue by RMuskovets** [nodejs/help#1758]
* **Version**: 9.6.1
* **Platform**: Windows 7 Professional 64-bit
* **Subsystem**: node

When I try to update Node.js using npm, it gives me error below:
```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for node-win-x86@11.9.0: wanted {"os":"win3
2","arch":"x86"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  x86
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Roman\AppData\Roaming\npm-cache\_logs\2019-02-09T08_17_12_
176Z-debug.log
module.js:559
    throw err;
    ^

Error: Cannot find module 'node-win-x86/package.json'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.resolve (internal/module.js:18:19)
    at ChildProcess.<anonymous> (C:\Users\Roman\node_modules\node-bin-setup\inde
x.js:18:27)
    at ChildProcess.emit (events.js:127:13)
    at maybeClose (internal/child_process.js:933:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Roman\package.
json'
npm WARN Roman No description
npm WARN Roman No repository field.
npm WARN Roman No README data
npm WARN Roman No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@11.9.0 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node@11.9.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Roman\AppData\Roaming\npm-cache\_logs\2019-02-09T08_17_12_
465Z-debug.log
```

**Comment by alipiry** [comment]
@RMuskovets it seems your system architecture is 32-Bit! Are you sure you got 64-Bit?

**Comment by RMuskovets** [comment]
I've installed Windows x64, previous was 32bit

**Comment by RMuskovets** [comment]
And what is the difference between `ia32` and `x86`?

**Comment by gireeshpunathil** [comment]
@RMuskovets - is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by dziku86** [comment]
> @RMuskovets - is this still an issue?

@gireeshpunathil This is still an issue. x86 equals ie32 so there should be no error. 
I'm trying to install latest node from npm and I'm getting `Unsupported platform` error on my x86 windows.
Should I open new issue for this?
