### ISSUE TITLE
TypeError: xenapi.createClient is not a constructor

### ISSUE THREAD

**Issue by Taurino3** [nodejs/help#1764]
* **Node.js: v10.15.1
* **OS: Xenserver 7.0
* **Scope: Error on startup
* **Module: xen-api 0.24.2 - https://npmjs.org/package/xen-api

I am having an issue with the below can you please help me resolve this? This is for 
https://github.com/mobilenations/newrelic_xenserver/blob/master/README.md

CODE:
        xapi[config.poolMaster] = new xenapi.createClient({
            url: 'config.poolMaster',
            auth: {user: 'config.user', password: 'config.password'},
            readOnly: false
        });

ERROR:
TypeError: xenapi.createClient is not a constructor
    at /home/ituser/pkgs/newrelic_xenserver-master/newrelic_xenserver.js:48:35
    at /home/ituser/pkgs/newrelic_xenserver-master/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/home/ituser/pkgs/newrelic_xenserver-master/node_modules/async/dist/async.js:1069:9)
    at eachOf (/home/ituser/pkgs/newrelic_xenserver-master/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/home/ituser/pkgs/newrelic_xenserver-master/node_modules/async/dist/async.js:3172:5)
    at connectXen (/home/ituser/pkgs/newrelic_xenserver-master/newrelic_xenserver.js:46:11)
    at Object.<anonymous> (/home/ituser/pkgs/newrelic_xenserver-master/newrelic_xenserver.js:731:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)

**Comment by vsemozhetbyt** [comment]
Try `new xenapi().createClient({` (with `()` after constructor name); otherwise operator precedence parsed this as if `xenapi.createClient` is a constructor.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if this is not resolved
