### ISSUE TITLE
'ERR_SOCKET_DGRAM_NOT_RUNNING' on second close

### ISSUE THREAD

**Issue by captain1991cv** [nodejs/help#1780]
I am trying to create a web interface for  udp server, and i should be able to create and close the udp server whenever the user asks for it. for more illustration, assume that i have the fallowing codes for **index.htm** and **server.js**:

```html
<!DOCTYPE html>
<html>
<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.3/socket.io.js"></script> <!-- include socket.io client side script -->

    <button onclick="closeUDPServer()"><span>close </span></button>
    <button onclick="openUDPServer()"><span>open </span></button>

    <script>
        var socket = io();
        function closeUDPServer() {
            socket.emit("closeUDPServer");
        }
        function openUDPServer() {
            socket.emit("CreateUDPServer","192.168.43.74",12345); // put your ip here
        }
    </script>
</body>
</html>
```
and here is my server code:
```js
var http = require('http').createServer(serverFunctionLoadIndex_html); //require http server, and create server with function handler()
var fs = require('fs');                 //require filesystem module
var io = require('socket.io')(http);    //require socket.io module and pass the http object (server)
var dgram = require('dgram');         // udp module
http.listen(8787); //listen to port 8787 ->this port should be entered in browser after ip address

function serverFunctionLoadIndex_html(req, res) { //create server -> loads index.html for the user
    fs.readFile(__dirname + '/index.html', function (err, data) { //read file index.html in  folder
        if (err) {
            res.writeHead(404, { 'Content-Type': 'text/html' }); //display 404 on error
            return res.end("404 Not Found");
        }
        res.writeHead(200, { 'Content-Type': 'text/html' }); //write HTML
        res.write(data); //write data from index.html
        return res.end();
    });
}


io.sockets.on('connection', function (socket) {// WebSocket Connection
    socket.on("CreateUDPServer", function (UDPIp, UDPPort) { // creates a server   
        var UDPServer = dgram.createSocket({ type: 'udp4', reuseAddr: true });
        UDPServer.bind(parseInt(UDPPort), UDPIp);

        UDPServer.on('listening', () => {
            const address = UDPServer.address();
            console.log(`server listening ${address.address}:${address.port}`);
        });

        UDPServer.on('error', (err) => {
            console.log(`server error:\n${err.stack}`);

            UDPServer.close();

        });
        
        UDPServer.on('close', () => {
            console.log("server closed");
        });

        socket.on("closeUDPServer", function () { // closes server 
            UDPServer.close();
        });
    });

});
```
if you click on **open** button, a udp server would be created and if you click on the **close** button, the udp server would be closed, But, when you create the udp server for the second time (click on the **open** button for the second time), it can not be closed properly! and **ERR_SOCKET_DGRAM_NOT_RUNNING** would be thrown.
![error](https://user-images.githubusercontent.com/40887809/52954502-a1454980-339f-11e9-95ea-67b55917eb37.JPG)
How can i create a udp server and  close it for several times?

**Comment by aymen94** [comment]
Hi @captain1991cv  can you try to destroy a socket `socket.destroy` and let me know how it went.

**Comment by captain1991cv** [comment]
Hi @aymen94 
thank you for the response. Actually, this is a simple example to illustrate my problem, my real code includes thousand of lines and i have multiple functions in **io.socket** area, so i can not simply destroy the socket. My real problem is **UDPServer** which can not be closed for the second time. but i tried ```socket.destroy()```, it says destroy is not a function.
```js
var http = require('http').createServer(serverFunctionLoadIndex_html); //require http server, and create server with function handler()
var fs = require('fs');                 //require filesystem module
var io = require('socket.io')(http);    //require socket.io module and pass the http object (server)
var dgram = require('dgram');         // udp module
http.listen(8787); //listen to port 8787 ->this port should be entered in browser after ip address

function serverFunctionLoadIndex_html(req, res) { //create server -> loads index.html for the user
    fs.readFile(__dirname + '/index.html', function (err, data) { //read file index.html in  folder
        if (err) {
            res.writeHead(404, { 'Content-Type': 'text/html' }); //display 404 on error
            return res.end("404 Not Found");
        }
        res.writeHead(200, { 'Content-Type': 'text/html' }); //write HTML
        res.write(data); //write data from index.html
        return res.end();
    });
}


io.sockets.on('connection', function (socket) {// WebSocket Connection
    socket.on("CreateUDPServer", function (UDPIp, UDPPort) { // creates a server   
        var UDPServer = dgram.createSocket({ type: 'udp4', reuseAddr: true });
        UDPServer.bind(parseInt(UDPPort), UDPIp);

        UDPServer.on('listening', () => {
            const address = UDPServer.address();
            console.log(`server listening ${address.address}:${address.port}`);
        });

        UDPServer.on('error', (err) => {
            console.log(`server error:\n${err.stack}`);

            UDPServer.close();
            
        });
        
        UDPServer.on('close', () => {
            console.log("server closed");
        });

        socket.on("closeUDPServer", function () { // closes server 
            UDPServer.close();
            socket.destroy();
        });
    });

});
```
![err2](https://user-images.githubusercontent.com/40887809/52965954-50dbe500-33bb-11e9-9b90-4a99d2ae8d78.JPG)

**Comment by aymen94** [comment]
[socket.destroy](https://nodejs.org/docs/latest/api/net.html#net_socket_destroy_exception) is a function.
Change `socket `with `UDPServer`.

example:
`UDPServer.destroy();`

**Comment by captain1991cv** [comment]
Dear @aymen94,  if i change ```UDPServer.close();``` to ```UDPServer.destroy();```, it says that:
```server listening 192.168.43.74:12345
/home/pi/Desktop/myNodeJSFiles/server.js:42
            UDPServer.destroy();
                      ^

TypeError: UDPServer.destroy is not a function
    at Socket.<anonymous> (/home/pi/Desktop/myNodeJSFiles/server.js:42:23)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at /home/pi/Desktop/node_modules/socket.io/lib/socket.js:528:12
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```
if i change all ```socket```s with UDPServer, like this:
```js
var http = require('http').createServer(serverFunctionLoadIndex_html); //require http server, and create server with function handler()
var fs = require('fs');                 //require filesystem module
var io = require('socket.io')(http);    //require socket.io module and pass the http object (server)
var dgram = require('dgram');         // udp module
http.listen(8787); //listen to port 8787 ->this port should be entered in browser after ip address

function serverFunctionLoadIndex_html(req, res) { //create server -> loads index.html for the user
    fs.readFile(__dirname + '/index.html', function (err, data) { //read file index.html in  folder
        if (err) {
            res.writeHead(404, { 'Content-Type': 'text/html' }); //display 404 on error
            return res.end("404 Not Found");
        }
        res.writeHead(200, { 'Content-Type': 'text/html' }); //write HTML
        res.write(data); //write data from index.html
        return res.end();
    });
}


io.sockets.on('connection', function (UDPServer) {// WebSocket Connection
    UDPServer.on("CreateUDPServer", function (UDPIp, UDPPort) { // creates a server   
        var UDPServer = dgram.createSocket({ type: 'udp4', reuseAddr: true });
        UDPServer.bind(parseInt(UDPPort), UDPIp);

        UDPServer.on('listening', () => {
            const address = UDPServer.address();
            console.log(`server listening ${address.address}:${address.port}`);
        });

        UDPServer.on('error', (err) => {
            console.log(`server error:\n${err.stack}`);

            UDPServer.close();
            
        });
        
        UDPServer.on('destroy', () => {
            console.log("server closed");
        });

        UDPServer.on('message', function (message, remote) {
            console.log(remote.address + ':' + remote.port + ' - ' + message);

        });
        UDPServer.on("closeUDPServer", function () { // closes server 
            UDPServer.destroy();
            
        });
    });

});
```
then, it dose not  close the udp server properly and i can still receive UDP packets and ```'close'``` event is not emitted. if i am doing it in a wrong way, then i was wondering if you could change the code yourself and post it here.

**Comment by captain1991cv** [comment]
for anyone who lands here!
after some debugging, i realized that ```UDPServer``` is closed twice on second close!! first one is successful and the second one fails. so i simply get rid off that by doing this:
```js
        socket.on("closeUDPServer", function () { // closes server 
            if (UDPServer) {
                UDPServer.close();
                UDPServer = null;
            }
        });
```

**Comment by remorses** [comment]
Here is a simple fix:

```ts
udpServer.on('close', () => {
      udpServer.close = () => {}
  })

```

Do you accept a PR to make closing twice not crash the Node process?
