### ISSUE TITLE
JHipster issue generate project

### ISSUE THREAD

**Issue by PaulLAGUES** [nodejs/help#1795]
* **Node.js No idea**:
* **Windows 10**:

Hello,

i got an issue when im trying to generate a Jhipster project, i have installed jHipster with npm like explained on the following link :[https://www.jhipster.tech/installation]

Anyway, i filled all requires questions qhen generate the project (SQL, Maven and stuff) but when its running i got the following error message:

`KeyStore 'src/main/resources/config/tls/keystore.p12' already exists. Leaving unchanged.

fs.js:115
    throw err;
    ^

Error: EPERM: operation not permitted, open 'C:\.yo-rc.json'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at write (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\mem-fs-editor\lib\actions\commit.js:14:6)
    at DestroyableTransform._transform (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\mem-fs-editor\lib\actions\commit.js:43:7)
    at DestroyableTransform.Transform._read (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DestroyableTransform.ondata (C:\Users\paul.lagues\AppData\Roaming\npm-cache\_npx\25128\node_modules\generator-jhipster\node_modules\readable-stream\lib\_stream_readable.js:619:20)
`
I have no idea what i can do to fix this, it's my first time with Jhipster, thank you for help.

I have only one year in the dev, so be tolerant ^^

**Comment by aymen94** [comment]
You don't have permission, try to run as administrator

**Comment by gireeshpunathil** [comment]
@PaulLAGUES - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing
