### ISSUE TITLE
Nodejs crashing with ECONNRESET

### ISSUE THREAD

**Issue by Yoris1** [nodejs/help#1807]
* **Node.js Version**: v11.9.0
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**: 

When building a server with 'net' I noticed that if I write to a tcp socket, and the client closes his connection without reading all of the data, node crashes.
error:
```events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:162:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

The code I am using in the node app for testing this is:
```var net = require('net');
var server = net.createServer(function(socket){
    socket.on('data', function (data) {
        console.log("writing data to socket");
        socket.write("Hello")
  });
});
server.listen(5000, '127.0.0.1');
```
And then I built a little c# utility that sends a message you input and then only reads 4 bytes of the reply, it goes like this :
```
string data = Console.ReadLine();
                byte[] databuf = Encoding.ASCII.GetBytes(data);
                stream.Write(databuf, 0, databuf.Length);
                byte[] dataLength = new byte[4];
                stream.Read(dataLength, 0, 4);
```
so I send a message, node sends a reply and doesn't matter in how much time I disconnect, but if 
I didn't read the ful message, node crashes and the on 'close' or on 'end' don't run before that. I think this is a node issue.

**Comment by Yoris1** [comment]
Figured a way out to fix this is 
```
socket.on('error', (error) => {
        console.log("error - " + error);
        socket.end();
        socket.destroy();
    });

```
