### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Asaelem** [nodejs/help#181]
i try running npm install npm -g and this is the error i get in the console:

C:\Users\Dylan\school\angular>npm install npm -g
module.js:327
    throw err;
    ^

Error: Cannot find module 'npmlog'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at C:\Users\Dylan\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:19:13
    at Object.<anonymous> (C:\Users\Dylan\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:75:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by addaleax** [comment]
Huh – how did you install npm? `C:\Users\Dylan\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js` seems like a weird path for `npm` to reside in…

**Comment by Asaelem** [comment]
just followed the installer and place it in my program files. I try to follow the path that its in ie .. C:\Users\Dylan\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js but there is nothing there i get to my drive and theres no appData in there.

**Comment by addaleax** [comment]
Not a Windows expert but I think `AppData` is kind of a hidden folder.

Does any of https://github.com/npm/npm#windows-install-or-upgrade help you?

**Comment by lordKnighton** [comment]
Here is a link as well https://github.com/nodejs/node/issues/2814

**Comment by lordKnighton** [comment]
@Asaelem did you get any success with this problem?
