### ISSUE TITLE
ERROR Log.gauge.isEnabled is not a function

### ISSUE THREAD

**Issue by ccices** [nodejs/help#1812]
* **Node.js Version**: 10.15.3
* **OS**: Windsows
* **Scope (install, code, runtime, meta, other?)**: Runtime
* **Module (and version) (if relevant)**: npm

After installation of nodejs, any call to npm produces the error. ex: npm -v causes error

```js
C:\Users\Bob>npm -v
C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:22:13
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:153:3)
C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                                     ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npmlog\log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:22:13
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:153:3)
```
-->

**Comment by addaleax** [comment]
@ccices You probably want to update node to the latest v10.x version, and npm with it?

**Comment by ccices** [comment]
> @ccices You probably want to update node to the latest v10.x version, and npm with it?

The package installed was straight from nodejs.org as the latest version...

**Comment by ccices** [comment]
Installing 11.11.0 fixed the issue.

**Comment by CWanjohi** [comment]
Had this same problem with nodejs v10.16.3. Solved by installing nodejs to the default path instead of changing install directory.

**Comment by ferxahi** [comment]
entrando al codigo y borrando la linea 59 se soluciona !!!
