### ISSUE TITLE
Help linking .dll file to native addon with node-gyp

### ISSUE THREAD

**Issue by tonetechnician** [nodejs/help#1834]
* **Node Version**:  v8.11.3 
* **NPM version**: 6.9.0
* **node-gyp version**: 3.8.0
* **Platform**: Windows 10, 64 bit

Hey there! Hoping someone may be able to help me. I'm currently trying to wrap a native framework using N-API. I'm fairly new to gyp with this being the first time I'm actually using it to generate my own .node addon. 

I run the following commands when building the vs project with node-gyp.

```.sh
node-gyp configure

node-gyp rebuild --debug
```

The project builds perfectly, and the .node is created. 

The only problem is when I include the .node in my project, I get the following error

```.sh
module.js:681
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The specified procedure could not be found.
\\?\D:\git-repos\SAF-nodeaddon\build\Debug\SAF_native.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\git-repos\SAF-nodeaddon\index.js:2:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

Now, I have searched through the .node with the dependency walker. I notice that the custom library I have linked doesn't seem to be loading correctly. 

![image](https://user-images.githubusercontent.com/13471797/54739151-c2c46b80-4bbf-11e9-97b1-71033d3a6a7d.png)

I'm not sure if this is to do with the custom .dll, or to do with node.. My feeling is it may be the former, although I do know the .dll works as I got it from someone else who created it and verified it does work. 

Here is my binding.gyp. The only bit I'm unsure about here is if the .lib and .exp must be included. 

```.py
{ 
  "dll_files" : [
    'C:\Windows\System32\saf_mkl_custom.dll'
  ],
  "targets": [{
    "target_name": "SAF_native",
    "include_dirs" : [
      'src/Spatial_Audio_Framework/dependencies/Win64/include',
      'src/Spatial_Audio_Framework/framework/include',
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_calloc.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_complex.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_filters.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_free.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_loudspeaker_presets.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_malloc.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_sensorarray_presets.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_sort.h",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_veclib.h",
      "<!(node -e \"require('napi-macros')\")"
    ],
    "sources": [
      "src/main.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_calloc.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_complex.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_filters.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_free.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_loudspeaker_presets.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_malloc.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_sensorarray_presets.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_sort.c",
      "src/Spatial_Audio_Framework/framework/saf_utilities/saf_veclib.c",
      "src/Spatial_Audio_Framework/framework/saf_hoa/saf_hoa_internal.c",
      "src/Spatial_Audio_Framework/framework/saf_hoa/saf_hoa.c",
      "src/Spatial_Audio_Framework/framework/saf_vbap/saf_vbap_internal.c",
      "src/Spatial_Audio_Framework/framework/saf_vbap/saf_vbap.c",
      "src/Spatial_Audio_Framework/framework/saf_sh/saf_sh_internal.c",
      "src/Spatial_Audio_Framework/framework/saf_sh/saf_sh.c"
    ],
    'link_settings': {
      "libraries" : [
        'D:\git-repos\SAF-nodeaddon\src\Spatial_Audio_Framework\dependencies\Win64\lib\saf_mkl_custom.exp',
        'D:\git-repos\SAF-nodeaddon\src\Spatial_Audio_Framework\dependencies\Win64\lib\saf_mkl_custom.lib',
      ]
    }
  }]
}
```

Any help or ideas for direction would be GREATLY appreciated!

**Comment by tonetechnician** [comment]
I'm going to be closing this :) It turns out the library was missing a dependency in the build. Spoke to the author who's since updated it and now it's linking properly. Check [#1](https://github.com/leomccormack/Spatial_Audio_Framework/issues/1) for more details..
