### ISSUE TITLE
Unable to run npm receiving error 

### ISSUE THREAD

**Issue by Legolasan** [nodejs/help#1885]
Tried removing npm and re-installed, but it's not working. Every time receiving the below error:

```
Error: EEXIST: file already exists, mkdir '/usr/local/bin/npm'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:78:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:228:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:266:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:173:20)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:229:20)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^
`
`
TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:189:13)
    at process._fatalException (internal/bootstrap/node.js:496:27)
```

**Permissions:**

`lrwxr-xr-x  1 root  admin  38 Apr 29 12:08 npm -> ../lib/node_modules/npm/bin/npm-cli.js`

* **Node.js Version**: 
node -v && npm -v
v10.15.3
6.4.1
* **OS**: Mojave

**Comment by wide4head** [comment]
@Legolasan Which command is causing this error? Please also specify your working directory.

**Comment by gireeshpunathil** [comment]
ping @Legolasan

**Comment by priimak** [comment]
I have exactly the same problem with nodejs on ubuntu 16.04. After doing this 
```
curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs
```

I am getting following error when simply running npm command line from anywhere in home directory

```
Error: EEXIST: file already exists, mkdir '/usr/bin/npm'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:78:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:228:22)
    at /usr/lib/node_modules/npm/lib/npm.js:266:24
    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:173:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:229:20)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) 
```

Any ideas?

**Comment by gireeshpunathil** [comment]
can you do : `ls -lrt /usr/bin/npm` and share the output?

**Comment by gireeshpunathil** [comment]
ping @Legolasan

**Comment by PoojaDurgad** [comment]
@Legolasan , is this still an issue?

**Comment by gireeshpunathil** [comment]
inactive, but resolution suggested, closing. feel free to reopen if still an issue
