### ISSUE TITLE
http.get throws error, but can't get full error stack

### ISSUE THREAD

**Issue by chengsu** [nodejs/help#1904]
* **Node.js Version**: v10.15.3
* **OS**: windows 10
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: http

when `http.get` throws error, I can't get full error stack:

this reports full error stack as expected:
```js
async function fn1(option) {
    await new Promise((resolve, reject) => {
        reject(new Error('error'))
    })
}

async function fn2() {
    await fn1();
}

fn2().then(console.log).catch(console.error)
```

```
Error: error
    at Promise (C:\tmp\test.js:5:16)  <--
    at new Promise (<anonymous>)
    at fn1 (C:\tmp\test.js:4:11)      <-- 
    at fn2 (C:\tmp\test.js:17:11)    <--
    at Object.<anonymous> (C:\tmp\test.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```
this doesn't not report full error stack:
```js
const http = require('http')

async function fn1(option) {
    await new Promise((resolve, reject) => {
        let req = http.get('http://www.google.com', { timeout: 1 }, (res) => {
        });
        req.on('timeout', () => {
            reject(new Error('timeout error'))
        })
        req.on('error', () => {
        })
    })
}

async function fn2() {
    await fn1();
}

fn2().then(console.log).catch(console.error)
```
```
Error: timeout error
    at ClientRequest.req.on (C:\tmp\test.js:9:20) <--
    at ClientRequest.emit (events.js:189:13)
    at Socket.emitRequestTimeout (_http_client.js:662:40)
    at Object.onceWrapper (events.js:277:13)
    at Socket.emit (events.js:189:13)
    at Socket._onTimeout (net.js:440:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```

**Comment by Hakerh400** [comment]
That's how JavaScript works. Error stack trace represents the stack trace from where the error is constructed, not from where the function that constructed the error had been defined. JavaScript attempts to resolve promises synchronously as far as no promise requests a timeout or other asynchronous action. All promises in your first example are resolved/rejected synchronously, so you got everything from `Function.Module._load` to the most inner function in the stack trace. The second example you provided contains an internal timeout scheduling, so the promise is called from Node.js asynchronous queue and not from the internal module loader.

You can observe the same behavior in the two following examples:

**Example 1**

```js
throw new Error();
```

Output

```
Error
    at Object.<anonymous> (C:\Projects\JavaScript\test\main.js:24:7)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
    at internal/main/run_main_module.js:17:11
```

**Example 2**

```js
setTimeout(() => { throw new Error(); });
```

Output:

```
Error
    at Timeout._onTimeout (C:\Projects\JavaScript\test\main.js:24:26)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
