### ISSUE TITLE
Cannot install fiber@2.0.2 in Node.js 10

### ISSUE THREAD

**Issue by AhmedHelal90** [nodejs/help#1929]
* **Node.js Version**: 6.11.4
* **OS**:  Red Hat Enterprise Linux 7.4
 
hi all , 
i need to update my node js ver to last stable Ver 10 but when i make update and try to run my application i get this error : 

internal/modules/cjs/loader.js:583
    throw err;
    ^
Error: Cannot find module 'asyncawait/async'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/bet/workspace/BSEnrichment/myapp/routes/devices.js:18:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/bet/workspace/BSEnrichment/myapp/application.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
--------------------------------------------------------------------------------
please i need urgent solution because we are in a production

**Comment by yathamravali** [comment]
@AhmedHelal90 
what's the npm version? Is it pointing to the latest-if not try 
`rm -rf node_modules`
`npm install -g npm@latest`

And please post the package.json

**Comment by AhmedHelal90** [comment]
@yathamravali 
npm ver : npm@6.9.0 
and i did this commands you sent 
and try to run again but the same issue 
and this is the package.json
--------------------------------
{
  "name": "project name",
  "version": "1.0.0",
  "description": "",
  "main": "application.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/--------"
  },
  "author": "",
  "license": "",
  "bugs": {
    "url": "https://github.com/----/-----/-----"
  },
  "homepage": "https://github.com/----/------#readme",
  "dependencies": {
    "async": "^2.5.0",
    "asyncawait": "^1.0.6",
    "body-parser": "^1.17.2",
    "bson-objectid": "^1.2.1",
    "connect-flash": "^0.1.1",
    "cron": "^1.2.1",
    "dateformat": "^3.0.2",
    "deasync": "^0.1.10",
    "dotenv": "^4.0.0",
    "ejs": "^2.5.7",
    "express": "^4.15.4",
    "express-fileupload": "^0.1.4",
    "express-response-handler": "^1.2.0",
    "express-session": "^1.15.5",
    "fs": "0.0.1-security",
    "ip-address": "^5.8.8",
    "method-override": "^2.3.9",
    "mongoose": "^4.11.7",
    "mongoose-csv": "^1.1.0",
    "mongoose-paginate": "^5.0.3",
    "mongoose-to-csv": "^0.1.1",
    "net-snmp": "^1.2.0",
    "node-cmd": "^3.0.0",
    "node-report": "^2.2.1",
    "nodemailer": "^4.0.1",
    "passport": "^0.4.0",
    "passport-local": "^1.0.0",
    "passport-local-mongoose": "^4.1.0",
    "passport-local-mongoose-email": "^0.1.3",
    "string": "^3.3.3",
    "thread-sleep": "^2.0.0",
    "winston": "^2.3.1"
  }
}

********************************
and this is the errors that i get when i try to install package asyncawait and when i try to run project again 

gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 2.6.32-696.13.2.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/proj/node_modules/fibers
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-28T06_50_28_366Z-debug.log
-------------------

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'asyncawait/async'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/bet/workspace/BusinessEnrichment/routes/devices.js:18:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/proj/application.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

i appreciate your support

**Comment by yathamravali** [comment]
@AhmedHelal90 
I am able to install that module despite of warnings and build error. 

I'm not sure what's the reason, 

- Give another try installing globally `npm i -g asyncawait`

- Add engines in package.json as

"engines" : {
 "node" : ">=10.15.3"
},
- Suggestion: `npm cache clean --force` or better reinstall node

**Comment by AhmedHelal90** [comment]
dear @yathamravali 
i tryed all this solutions before 
but i think the error in this lines below 

npm ERR! fibers@2.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

and i take  my solution to another server and i installed  nodejs V10 and when i try to run project i get the same errors in async/await library 

i really confused of this issue , all what i need is that i try to update my node js to last stable version to avoid any errors in package in future ??

**Comment by gireeshpunathil** [comment]
@AhmedHelal90 - is this still an issue for you?

**Comment by bet-proj** [comment]
yes , still have the problem and i can't update to last version because of this error !! 
because our system is production and i don't want to take any dangerous action  impact in our system , 
so if you have a solution for this issue please help me

**Comment by tniessen** [comment]
@AhmedHelal90 The error log indicates that the compilation of the fibers package fails, and it mentions version 2.0.2, which is outdated. Updating your dependencies should solve the issue.

**Comment by bet-proj** [comment]
i tried this solution before but no thing happened

**Comment by tniessen** [comment]
It is most likely not a direct dependency, but a dependency of one of your dependencies. You can use commands such as `npm ls` to find out which package depends on the outdated version.

**Comment by gireeshpunathil** [comment]
ping @AhmedHelal90

**Comment by gireeshpunathil** [comment]
inactive, and / or resolved, closing. pls feel free to reopen if required
