### ISSUE TITLE
Node JS Error: throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Eitan03** [nodejs/help#1930]
10.15.3:
windows 10:
Just installed Node.js' trying to run my first hello world:

```js
var http = require('http');
http.createServer(function( req, res)	
{res.writeHead(200,	{'Content-Type':'text/html'});				
res.end('Hello	World!'); }).listen(8080);
```
-->
After installing Node.js and running an example code to see if the installation was seccesful, I got this error:

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1270:14)
    at listenInCluster (net.js:1318:12)
    at Server.listen (net.js:1405:7)
    at [stdin]:7:4
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:326:38)
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at evalScript (internal/bootstrap/node.js:589:27)
    at Socket.<anonymous> (internal/bootstrap/node.js:323:15)
Emitted 'error' event at:
    at emitErrorNT (net.js:1297:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at evalScript (internal/bootstrap/node.js:592:13)
    at Socket.<anonymous> (internal/bootstrap/node.js:323:15)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Im using Atom IDE, and i tried reinstalling node.js about 5 times, reinstalling or messing with the npm and basiclly every solution i found online, nothing worked so far

**Comment by gireeshpunathil** [comment]
as a first step, could you change the port number (say a higher value such as 12000) and see if it works?
