### ISSUE TITLE
Cannot find module 'readable-stream/transform' on npm install

### ISSUE THREAD

**Issue by martixy** [nodejs/help#1951]
* **Version**:
v12.3.0 and v12.4.0 at least
* **Platform**:
Windows x64
* **Subsystem**:
?

Log of the problem below.
Trying to run any number of commands right now gives me the same error.
Happens on any install attempt, also tried a `firebase deploy`, same error, and probably a ton of other file operation related commands will yield the same error.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Web\\nodejs\\node.exe',
1 verbose cli   'C:\\Web\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'gulp'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose stack Error: Cannot find module 'readable-stream/transform'
4 verbose stack Require stack:
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\mississippi\node_modules\through2\through2.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\mississippi\index.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\cacache\lib\entry-index.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\cacache\ls.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\cacache\locales\en.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\cacache\index.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\pacote\lib\with-tarball-stream.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\pacote\extract.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\node_modules\pacote\index.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\lib\fetch-package-metadata.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\lib\install\deps.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\lib\install.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\lib\npm.js
4 verbose stack - C:\Web\nodejs\node_modules\npm\bin\npm-cli.js
4 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:681:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:16:16)
4 verbose stack     at Object.<anonymous> (C:\Web\nodejs\node_modules\npm\node_modules\mississippi\node_modules\through2\through2.js:1:17)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:774:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:641:32)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
4 verbose stack     at Module.require (internal/modules/cjs/loader.js:681:19)
4 verbose stack     at require (internal/modules/cjs/helpers.js:16:16)
4 verbose stack     at Object.<anonymous> (C:\Web\nodejs\node_modules\npm\node_modules\mississippi\index.js:5:26)
4 verbose stack     at Module._compile (internal/modules/cjs/loader.js:774:30)
4 verbose stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
4 verbose stack     at Module.load (internal/modules/cjs/loader.js:641:32)
4 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
5 verbose cwd C:\Web\cci-test
6 verbose Windows_NT 10.0.17763
7 verbose argv "C:\\Web\\nodejs\\node.exe" "C:\\Web\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp"
8 verbose node v12.4.0
9 verbose npm  v6.9.0
10 error code MODULE_NOT_FOUND
11 error Cannot find module 'readable-stream/transform'
11 error Require stack:
11 error - C:\Web\nodejs\node_modules\npm\node_modules\mississippi\node_modules\through2\through2.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\mississippi\index.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\cacache\lib\entry-index.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\cacache\ls.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\cacache\locales\en.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\cacache\index.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\pacote\lib\with-tarball-stream.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\pacote\extract.js
11 error - C:\Web\nodejs\node_modules\npm\node_modules\pacote\index.js
11 error - C:\Web\nodejs\node_modules\npm\lib\fetch-package-metadata.js
11 error - C:\Web\nodejs\node_modules\npm\lib\install\deps.js
11 error - C:\Web\nodejs\node_modules\npm\lib\install.js
11 error - C:\Web\nodejs\node_modules\npm\lib\npm.js
11 error - C:\Web\nodejs\node_modules\npm\bin\npm-cli.js
12 verbose exit [ 1, true ]
```

**Comment by martixy** [comment]
@cjihrig This looks to me like a bug with node/npm, not a help request.
I don't think it should be in the help repository.

**Comment by bzoz** [comment]
Looks like your npm installation is broken. Can you try reinstalling node and npm?

**Comment by gireeshpunathil** [comment]
ping @martixy

**Comment by gireeshpunathil** [comment]
inactive, closing

**Comment by DanielDziubecki** [comment]
In my case it was that, even after reinstalling node the `PATH` environment variable contains wrong path to npm. After changing this to the node installation folder everything works fine.

**Comment by Ondelette** [comment]
When you upgrade the nodejs without delete the old directory, this issue will appear.
Please delete the old directory 'C:\Program Files\nodejs\node_modules\npm' and reinstall nodejs.
