### ISSUE TITLE
Cannot Find Module './config.json'

### ISSUE THREAD

**Issue by Tf2Trader** [nodejs/help#1959]
Now, This is a werid one. I made it a js file using notepad++ and also tried with sublime text 3.
It said

Error: Cannot find module './config.json'
Require stack:

C:\Users \ ******\Desktop\Bot\bot.js
�[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)�[39m
�[90m at Function.Module._load (internal/modules/cjs/loader.js:527:27)�[39m
�[90m at Module.require (internal/modules/cjs/loader.js:681:19)�[39m
�[90m at require (internal/modules/cjs/helpers.js:16:16)�[39m
at Object. (C:\Users\danie\Desktop\Bot\bot.js:2:16)
�[90m at Module._compile (internal/modules/cjs/loader.js:774:30)�[39m
�[90m at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)�[39m
�[90m at Module.load (internal/modules/cjs/loader.js:641:32)�[39m
�[90m at Function.Module._load (internal/modules/cjs/loader.js:556:12)�[39m
�[90m at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)�[39m {
code: �[32m'MODULE_NOT_FOUND'�[39m,
requireStack: [ �[32m'C:\Users\danie\Desktop\Bot\bot.js'�[39m ]
}
And the JSON file is inside my folder Skärmbild (53)

I tried using different kind of ones instead ( Js and one more ) And it didnt work.

**Comment by Hakerh400** [comment]
From the screenshot that you posted in https://github.com/nodejs/node/issues/28105 I can see that your `config.json` is missing extension `.json` (you named it just `config`).

**Comment by gireeshpunathil** [comment]
ping @Tf2Trader

**Comment by gireeshpunathil** [comment]
inactive; closing. pls reopen if still outstanding

**Comment by aldousbengco** [comment]
Can you help me in solving this error code.

Error: Cannot find module './config.json/db'
Require stack:
C:\Users \ ******\Desktop\pi\scale\fyn\fyn\***********\server.js
   at Funcction.Module._resolveFilename(internal/modules/cjs/loader.js:880:15) 
   at Funcction.Module._load(internal/modules/cjs/loader.js:728:27)
   at Module.require (internal/modules/cjs/loader.js:952:19)
   at require (internal/modules/cjs/helpers.js:88:18)
   at Object.<anonymous> (C:\Users \ ******\Desktop\pi\scale\fyn\fyn\***********\server.js:5:10)
   at Module._compile (internal/modules/cjs/loader.js:1063:30)
   at Object.Module._extention..js(internal/modules/cjs/loader.js:1092:10)
   at Module.load (internal/modules/cjs/loader.js:928:32)
   at Funcction.Module._load(internal/modules/cjs/loader.js:769:14)
   at Funcction.executeUserEntryPoint [as runMain] (internal/modules/cjs/run_main.js:72:12)
