### ISSUE TITLE
Can not find module 'joi' after @hapi/joi installation

### ISSUE THREAD

**Issue by emclab** [nodejs/help#1960]
* **Node.js Version**: 10.16.0. express 4.16.4
* **OS**: Win10
* **Scope (install, code, runtime, meta, other?)**: module joi can not find after adding to the project
* **Module (and version) (if relevant)**: @hapi/joi 15.0.3

I just upgraded to @hapi/joi 15.0.3 from deprecated Joi on Nodejs 10.16.0/express 4.16.4 platform. What I did was yarn add @hapi/joi and yarn remove joi. However after upgrade, the node project can not find the module joi:

PS C:\d\code\js\emps_bbone> nodemon index.js
[nodemon] 1.18.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\d\code\js\emps_bbone\models\user.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[nodemon] app crashed - waiting for file changes before starting...

Here is the line of code requesting the module Joi
const Joi = require('@hapi/joi');

I just upgraded to @hapi/joi 15.0.3 from deprecated Joi on Nodejs 10.16.0/express 4.16.4 platform. What I did was yarn add @hapi/joi and yarn remove joi. However after upgrade, the node project can not find the module joi:

PS C:\d\code\js\emps_bbone> nodemon index.js
[nodemon] 1.18.5
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\d\code\js\emps_bbone\models\user.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[nodemon] app crashed - waiting for file changes before starting...

I  deleted whole node_module a couple of times and yarn install, also clean the cache with yarn cache clean, but the error is the same.

**Comment by addaleax** [comment]
Can you share your `models\user.js` file, or at least the first few lines?

**Comment by emclab** [comment]
addaleax, I found the problem. It is a out of date request to the old Joi module in one model. Thank you.

**Comment by Aakarshak1** [comment]
@emclab `const Joi = require('@hapi/joi');` try using this.

**Comment by Taxellool** [comment]
I had to install both 'joi' and '@hapi/joi' to fix this.
