### ISSUE TITLE
Nightmare JS is not working on Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-145-generic x86_64) Server, same script is working in my local system Window 10

### ISSUE THREAD

**Issue by Shailesh172** [nodejs/help#2011]
When i try to run node js script it will return below error, please help me. Thank you all.
I have used this : https://github.com/segmentio/nightmare

```
root@ns:/load-market-data# DEBUG=* node index.js
  nightmare queuing process start +0ms
Bot starting...
  nightmare queueing action "cookies" +279ms
  nightmare queueing action "viewport" +1ms
  nightmare queueing action "useragent" +0ms
  nightmare running +0ms
  nightmare electron child process not started yet, skipping kill. +7ms
/load-market-data/node_modules/nightmare/lib/nightmare.js:128
    this.proc.stdout.pipe(split2()).on('data', (data) => {
                     ^

TypeError: Cannot read property 'pipe' of undefined
    at Nightmare.queue (/load-market-data/node_modules/nightmare/lib/nightmare.js:128:22)
    at next (/load-market-data/node_modules/nightmare/lib/nightmare.js:341:12)
    at Nightmare.run (/load-market-data/node_modules/nightmare/lib/nightmare.js:331:3)
    at startApplication (/load-market-data/index.js:103:4)
    at Object.<anonymous> (/load-market-data/index.js:169:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
root@ns:/load-market-data# this.proc.stdout.pipe(split2())TypeError: Cannot read property 'pipe' of undefined
-bash: syntax error near unexpected token `split2'
```

**Comment by addaleax** [comment]
This seems like a bug in the library, and I don’t think there’s much to do besides reporting it to them, using the link you posted.

When you do, make sure to provide information about your operating system and node version (`node -v`) as well as the version of `nightmare` that you’re using.

**Comment by gireeshpunathil** [comment]
ping @Shailesh172

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if this is still outstanding.
