### ISSUE TITLE
(node:8889) UnhandledPromiseRejectionWarning: Error: invalid_grant: Robot is disabled.

### ISSUE THREAD

**Issue by trithesh** [nodejs/help#2015]
* **Node.js Version**: v8.10.0
* **OS**: Ubuntu 18.04.2 LTS
* **Scope **: runtime

All by Sudden, I got this error. One day back code is executing and working well, I haven't changed any code also.
**This is the complete log** : 
(node:8889) UnhandledPromiseRejectionWarning: Error: invalid_grant: Robot is disabled.
    at Request._callback (/home/rithesh/codes/chatbot/node_modules/gtoken/lib/index.js:215:34)
    at Request.self.callback (/home/rithesh/codes/chatbot/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/rithesh/codes/chatbot/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/rithesh/codes/chatbot/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:8889) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8889) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wide4head** [comment]
@trithesh Looks like a google authentication related. 
Can you try the root cause analysis as detailed in https://groups.google.com/forum/#!topic/google-doubleclick-for-advertisers-api/FZo-6ZZGeyQ

**Comment by trithesh** [comment]
Thank's Nodejs/Help

**Comment by gireeshpunathil** [comment]
@trithesh - is this resolved?

**Comment by PoojaDurgad** [comment]
@trithesh , were you able to follow the @wide4head' s suggestion? is it resolved?
