### ISSUE TITLE
crypto.privateDecrypt 

### ISSUE THREAD

**Issue by martinamuscariello** [nodejs/help#2017]
Node.js Version: 11.13.0
OS: Ubuntu 18.04.2 LTS (Codename:       bionic)

I try to use crypto to encrypt data with a public key from file system, using padding RSA_PKCS1_PADDING. 
It works well, but I can't decrypt the result with a private key from filesytem, using the same padding.

Below my code:
-- Encrypt --
```js
var keyProfile = crypto.createPublicKey(fs.readFileSync(curPath + '/openssl/something.pub'));
var buffer = Buffer.from(to_encrypt);
var msg = crypto.publicEncrypt({ key: keyUse, padding: crypto.constants.RSA_PKCS1_PADDING }, buffer)toString('base64');
```

this produces a string like 
```
fw36ZnifVRx/DDeVVa2w4uMe0TPIqhW07YM+P7eCbkPXCD13IoGwjihdFxRJ8Ewe81HwBMntFM06o2NexFXeJ2Tj0oWU2F1uN9qr7zhKsiR4Dusbyt1xb5IF6wsjY/5A854P26Ov/c+tLxsePW3MBMEouk7D59G16qcIggjMrDprX14F/4zvQON/1G9THJwwXxbVeCJqXl4ZWLMlbU2YVMGIcsjO0/3ThLvmi40cUAGQuTSqkC4No/Lp+ruyeWGp7hdXAov5nH8KPKB4yBUV07iknXdJknYWg32MCu+68GtLtU4YYd7bVOkUsZ5+JnuCxIU7kgk5qHPxADyZHPTo7w==
```

-- Decrypt --
```js
var crt = crypto.createPrivateKey(fs.readFileSync(curPath + '/openssl/something.key.pem'));
var buffer = Buffer.from(to_decrypt);
var msg = crypto.privateDecrypt({ key: crtUse, padding: crypto.constants.RSA_PKCS1_PADDING }, buffer).toString('utf8');
```

where to_decrypt = string produced by encryption

During the decrypt I encountered the following error 
error:0406506C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len

Could somebody helps me, please?

**Comment by addaleax** [comment]
Can you share more of your code?

One possibility is that the `var buffer = Buffer.from(to_decrypt);` line points to a bug… is `to_decrypt` a string? Should that be `Buffer.from(to_decrypt, 'base64')` in order to undo the base64 encoding you applied during encryption?

And by the way, you can wrap pieces of source code that you post on github in  ```` ``` ```` so that it becomes more readable, for example:

    ```js
    console.log('Hello world!');
    ```

becomes

```js
console.log('Hello world!');
```

:slightly_smiling_face:

**Comment by martinamuscariello** [comment]
Thanks for the support.
Below my test function:

```js
var crypto = require('crypto');
var crt = crypto.createPrivateKey(fs.readFileSync(curPath + '/openssl/clinaccess.key.pem'));
 var keyProfile = crypto.createPublicKey(fs.readFileSync(curPath + '/openssl/merqurio_clinaccess_new.pub'));

exports.Crypt = function (req, res, next) {
    var data = req.param('data', '');
  
    if(data.length > 0){        
        
        var bufferEn = Buffer.from(data);
        var msg = crypto.publicEncrypt({ key: keyProfile, padding: crypto.constants.RSA_PKCS1_PADDING }, bufferEn).toString('base64');
        
        var bufferDe = Buffer.from(msg, 'base64');
        var dec = crypto.privateDecrypt({ key: crt, padding: crypto.constants.RSA_PKCS1_PADDING }, bufferDe).toString('utf8');
        
        res.end(dec);
      }
      else{
  		res.status(401).end('Not authorized...');
  	}
}
```
I made the change you suggested and now I have this error:

_error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error_

**Comment by MalavitaC** [comment]
me too
node nersion: 13.14.0
``` js
fs.readFile('./rsa_private_key.pem', (err, privateKey)=>{

  let Ciphertext = 'lr9wWO5NaB3cUqmDgeU6WvnyfMBqspcrory6vlyKDkQOW1fH411KXqRp0jhRbdnQoqNJa3mGBNiLHLL1+WNb+2Qs7cp29WzRaoMcjdBsE4bD2yzIu2OLF1PfeZMNcwbn0QJ1Y0E+pQk5UQX2w/Yhk5xrZzywm5apuhQf/CKE1kQ='
  Ciphertext = Buffer.from(Ciphertext)
  
  const decryptedData = crypto.privateDecrypt({
    key: privateKey,
    padding: crypto.constants.RSA_PKCS1_PADDING,
  }, Ciphertext)
  
  console.log(decryptedData.toString())
})
```
``` shell
internal/crypto/cipher.js:63
    return method(data, format, type, passphrase, buffer, padding, oaepHash,
           ^

Error: error:0406506C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len
    at Object.privateDecrypt (internal/crypto/cipher.js:63:12)
    at /Users/caiminhao/Documents/my/test/rsa.js:25:32
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  library: 'rsa routines',
  function: 'rsa_ossl_private_decrypt',
  reason: 'data greater than mod len',
  code: 'ERR_OSSL_RSA_DATA_GREATER_THAN_MOD_LEN'
```

**Comment by 2Marks** [comment]
Apparently you need to always specify the encoding type when decrypting. say you encrypted and did a toString('base64') on the value, you'll need to do : Buffer.from (encryptedData, 'base64') when decoding it

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.

**Comment by AyemunHossain** [comment]
Having this same issue, with Buffer.from(Ciphertext, "base64") or Buffer.from(Ciphertext, "utf8")
