### ISSUE TITLE
Failed to lookup view in views directory handlebars

### ISSUE THREAD

**Issue by raghavkandpal** [nodejs/help#2024]
* **Node.js Version**: 10.15.1
* **OS**: Windows 10
* **Module (and version) (if relevant)**: Express v4.17.1, Handlebars v3.1.0

I am working on a node project using express and handlebars.
I've been trying to create a view, but it always fails to look up even though the file exists in the folder specified. 
Also, it renders index.handlebars just fine. 

-app.js
-views
  --- index.handlebars
  --- about.handlebars

Here is the request:
```js
app.get('/about', (req,res)=>{
  res.render('/about');
});
```
And this is the error I recieve:
```js
Error: Failed to lookup view "/about" in views directory "G:\Project\views"
    at Function.render (G:\Project\node_modules\express\lib\application.js:580:17)
    at ServerResponse.render (G:\Project\node_modules\express\lib\response.js:1012:7)
    at app.get (G:\Project\app.js:65:7)
    at Layer.handle [as handle_request] (G:\Project\node_modules\express\lib\router\layer.js:95:5)
    at next (G:\Project\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (G:\Project\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (G:\Project\node_modules\express\lib\router\layer.js:95:5)
    at G:\Project\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (G:\Project\node_modules\express\lib\router\index.js:335:12)
    at next (G:\Project\node_modules\express\lib\router\index.js:275:10)
    at G:\Project\app.js:53:3
    at Layer.handle [as handle_request] (G:\Project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (G:\Project\node_modules\express\lib\router\index.js:317:13)
    at G:\Project\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (G:\Project\node_modules\express\lib\router\index.js:335:12)
    at next (G:\Project\node_modules\express\lib\router\index.js:275:10)
```

**Comment by wide4head** [comment]
@raghavkandpal Can you try `res.render('about');`

**Comment by gireeshpunathil** [comment]
ping @raghavkandpal -

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
