### ISSUE TITLE
Nodejs on NixOS

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2035]
So even though NixOS is all about haskell I am sure there's room and desire for scripting languages as well.

I got these errors when running a working node program on NixOS

```console
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
path.js:1165
        path = process.cwd();
                       ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1165:24)
    at Function.Module._resolveLookupPaths (module.js:424:17)
    at Function.Module._resolveFilename (module.js:542:20)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/interos/repos/ntrs-cli/cli/deploy-platform-with-sanity.js:3:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

the script I have is:

```
    const k = cp.spawn('bash');
      
      k.stdin.end(`
      
        set -e;
        cd "${v.dir}";
        backend_hosts="$(cat backend_hosts)"
        if [[ "$backend_hosts" != "${v.dns}" ]]; then
           echo "Backend host has mis-matched values, ${v.dns} and $backend_hosts" >&2
           exit 1;
        fi
        ob thunk unpack src
        (cd src && ( git checkout -b deploy-${hashFlagValue} ${hashFlagValue} || git checkout deploy-${hashFlagValue} ))
        ob thunk pack src
        ob deploy push -v
        sleep 5
 
        
      `);
      
      k.stderr.pipe(pt(chalk.cyan(`deploy to ${v.dns} stdout: `))).pipe(process.stderr);
      k.stdout.pipe(pt(chalk.magentaBright(`deploy to ${v.dns} stderr: `))).pipe(process.stdout);
      
      
      k.once('exit', code => {
        cb(null, {code});
      });
```

it might just be a matter of re-configuring NixOS not sure.  Maybe I can try `sh` instead of `bash` for the child process.

**Comment by bnoordhuis** [comment]
I've moved this to nodejs/help because it's not an issue with Node.js itself, just the environment it runs in.

**Comment by ORESoftware** [comment]
Yeah np, NixOS is weird
