### ISSUE TITLE
unlink an opened file succeed but get ENOENT

### ISSUE THREAD

**Issue by hanzhangyu** [nodejs/help#2046]
* **Node.js Version**: 12.6
* **OS**: Linux version 4.4.0-17763-Microsoft
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

unlink an opened file succeed but get an error.

```js
const FILE_PATH = ...;
if (!process.env.isChild) {
  fork('./link.js', {
    env: { isChild: true }
  });

  const fd = fs.openSync(FILE_PATH);
  // then keep alive
}

setTimeout(()=>{
  fs.unlinkSync(FILE_PATH);
// out:
// Error: ENOENT: no such file or directory, unlink '/mnt/f/code/js/learn-node/files/temp.txt'
// at Object.unlinkSync (fs.js:976:3)
// at Timeout._onTimeout (/mnt/f/code/js/learn-node/playground/fs/link.js:18:6)
// at listOnTimeout (internal/timers.js:531:17)
// at processTimers (internal/timers.js:475:7) {
//   errno: -2,
//     syscall: 'unlink',
//     code: 'ENOENT',
//     path: '/mnt/f/code/js/learn-node/files/temp.txt'
// }
},1000); // make later then fork
```

**Comment by tniessen** [comment]
Based on your code, it seems like you are calling `unlinkSync` both from the parent process and from the child process.

**Comment by hanzhangyu** [comment]
oh, my fault, thank your time
