### ISSUE TITLE
Exception not caught!

### ISSUE THREAD

**Issue by calidion** [nodejs/help#2064]
* **Version**:  v10.16.0
* **Platform**: Linux 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* **Subsystem**:

exception not caught but aborted with error ENETUNREACH

```
Error: connect ENETUNREACH 226.19.52.123:19800 - Local (0.0.0.0:0)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at defaultTriggerAsyncIdScope (net.js:971:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by cjihrig** [comment]
Can you try attaching an [`'error'`](https://nodejs.org/api/net.html#net_event_error_1) event handler instead?
