### ISSUE TITLE
mon bot discord que j'ai crée avec node me sort sa 

### ISSUE THREAD

**Issue by alphaleadership** [nodejs/help#2075]
internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module './src'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\SMA\Dropbox\alphaleadership-bot\node_modules\snekfetch\index.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)

**Comment by tniessen** [comment]
There is absolutely no way we can help you without more information. The error says very clearly that Node.js cannot find the module `./src`, and it seems to originate from the [snekfetch package](https://www.npmjs.com/package/snekfetch), which is deprecated.

If you need further assistance, please provide more information.
