### ISSUE TITLE
Cannot find module './defaults'

### ISSUE THREAD

**Issue by K0tka** [nodejs/help#2083]
* **Node.js Version**: 10.16.0
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**: Install
* **Module (and version) (if relevant)**: './defaults'

I'm not able to run my code (a Discord bot) like I could do before I moved to a different computer. I pulled my project from GitHub and did 'npm install' to get 'node_modules', but I'm getting this error all the time:

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './defaults'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Kotka\Programas propios\CatBotJS\index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

I have no idea how to fix it.

Thanks a lot in advance!

**Comment by LayMuiToh** [comment]
I faced the same issue
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './session-Manager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/test/src/K8s/api/index.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module './session-Manager'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/test/src/K8s/api/index.js:2:24)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

but this sessionManager.js exist at
~/K8s/api/session-manager.js

it has no issue running in my local macOS machine but I upload the dev machine (other machine, centos), it got this issue.
some difference in OS?
