### ISSUE TITLE
Error: Socket Hang Up

### ISSUE THREAD

**Issue by ghost** [nodejs/help#2119]
Whenever i open the project i have this error on console spamming...
I can't fixed :/ 

(node:30949) UnhandledPromiseRejectionWarning: Error: socket hang up

    at TLSSocket.onConnectEnd (_tls_wrap.js:1083:19)

    at Object.onceWrapper (events.js:272:13)

    at TLSSocket.emit (events.js:185:15)

    at endReadableNT (_stream_readable.js:1106:12)

    at process._tickCallback (internal/process/next_tick.js:178:19)

**Comment by OzgurTR** [comment]
I cant fixed please help guys..

**Comment by gireeshpunathil** [comment]
closing the user does not exist for follow up
