### ISSUE TITLE
Failed to appium installation from command ‘npm install -g appium’

### ISSUE THREAD

**Issue by GaneshGunaki** [nodejs/help#2127]
**npm version - 6.4.1**

npm install -g appium
C:\Users\g315315\AppData\Roaming\npm\authorize-ios -> C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\node_modules\.bin\authorize-ios
C:\Users\g315315\AppData\Roaming\npm\appium -> C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\build\lib\main.js

> appium-chromedriver@4.11.0 install C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\node_modules\appium-chromedriver
> node install-npm.js

[20:29:14] [Chromedriver Install] Installing Chromedriver version '2.46' for platform 'win' and architecture '32'
[20:29:14] [Chromedriver Install] Opening temp file to write 'chromedriver_win32' to...
[20:29:15] [Chromedriver Install] Opened temp file 'C:\Users\g315315\AppData\Local\Temp\2019719-4684-19slehu.2ljd\chromedriver_win32.zip'
[20:29:15] [Chromedriver Install] Downloading https://chromedriver.storage.googleapis.com/2.46/chromedriver_win32.zip...
RequestError: Error: getaddrinfo ENOTFOUND chromedriver.storage.googleapis.com chromedriver.storage.googleapis.com:443
    at new RequestError (C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.onRequestError (C:\Users\g315315\AppData\Roaming\npm\node_modules\appium\node_modules\request\request.js:881:8)
    at ClientRequest.emit (events.js:189:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:189:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[            ......] \ install: info lifecycle appium-chromedriver@4.11.0~install: Failed to exec install script

**Comment by gireeshpunathil** [comment]
@GaneshGunaki - is this still outstanding? looks like a temporary network issue to me.

**Comment by gireeshpunathil** [comment]
closing, inactive
