### ISSUE TITLE
listen EADDRINUSE error while Starting  Appium 

### ISSUE THREAD

**Issue by mani246** [nodejs/help#2128]
* **Node.js Version**:v10.16.3
* **OS**: Mojave (10.14.5 ) 
appium version : 1.14.1
* **Scope (install, code, runtime, meta, other?)**: Starting appium server 
* **Module (and version) (if relevant)**:

Every time I start the appium server I get this error 

[35m[HTTP][39m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.
Fatal Error: listen EADDRINUSE: address already in use 153.83.46.215:9000
    at Server.setupListenHandle [as _listen2] (net.js:1279:14)
    at listenInCluster (net.js:1327:12)
    at doListen (net.js:1460:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)

I tried changing this with couple of ports but same error. There is no other instant is running . 

It started happening after updating with mojave.

**Comment by gireeshpunathil** [comment]
@aditi246 - is this still outstanding?

you could find out who is listening at that port
`lsof -nP -i4TCP:9000 | grep LISTEN`

sometimes it may be in `TIMED_WAIT` for a long time depending on many factors. If it persists, rebooting may help.

**Comment by PoojaDurgad** [comment]
@mani246 , were you able to follow @gireeshpunathil 's suggestion? or it is still an issue ?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
