### ISSUE TITLE
"Cannot find Module Zames" when running "cloudcmnd"

### ISSUE THREAD

**Issue by grayerbeard** [nodejs/help#2131]
typeing "sudo cloudcmd"

* **Version**:   cloudcmd vesrion 13.2.0
* **Platform**:
* **Subsystem**:

The responce yo trying to run cloudcmd is
pi@RPi400sd2:/ $ sudo cloudcmd
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'zames'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/cloudcmd/node_modules/copymitter/lib/copymitter.js:16:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3

**Comment by grayerbeard** [comment]
Transferred to where?

**Comment by gireeshpunathil** [comment]
@grayerbeard -  is this still outstanding?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
