### ISSUE TITLE
i face this problem when i tried to run npm -v through windows command?

### ISSUE THREAD

**Issue by loverphp487** [nodejs/help#2161]
i face this problem when i tried to run npm -v through windows command?

i uninstall the nodejs version 10.15.0 and install the new version 12.10.1 but the problem still exists after i have deleted all node_module and node folder from my pc the operating system is window 8.1 

```
$ npm --versions
<!-- paste output here -->
Error: EINVAL: invalid argument, mkdir 'C:\Users\AmgadMohamadAdel\=c:\Users\AmgadMohamadAdel\AppData\Roaming'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97:27)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:215:3)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\←[4mnpm←[24m\lib\utils\error-handler.js:97:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\←[4mnpm←[24m\lib\utils\error-handler.js:215:3)
←[90m    at process.emit (events.js:209:13)←[39m
←[90m    at process._fatalException (internal/process/execution.js:150:25)←[39m
Error: EINVAL: invalid argument, mkdir 'C:\Users\AmgadMohamadAdel\=c:\Users\AmgadMohamadAdel\AppData\Roaming'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97:27)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:215:3)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:77:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\←[4mnpm←[24m\lib\utils\error-handler.js:97:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\←[4mnpm←[24m\lib\utils\error-handler.js:215:3)
←[90m    at process.emit (events.js:209:13)←[39m
←[90m    at process._fatalException (internal/process/execution.js:150:25)←[39m

$ node -p process.platform
<!-- paste output here -->
```

**Comment by tniessen** [comment]
What shell are you running this from? Is it cmd, PowerShell, or a different shell?

**Comment by gireeshpunathil** [comment]
ping @loverphp487 - is this still unresolved?

**Comment by sidrakshe28** [comment]
Same,even I'm getting the same error.
can someone help with this?

**Comment by PoojaDurgad** [comment]
@loverphp487 and @sidrakshe28 - is this issue resolved? for me this issue looks similar to  https://github.com/zkat/npx/issues/100 
hopefully it will help to resolve the issue.

**Comment by Rayangit** [comment]
Try reseting the cache config argument by using the follwing command (it worked for me).
`npm config set cache `

**Comment by sidrakshe28** [comment]
yes its resolved. thank you:)

**Comment by PoojaDurgad** [comment]
closing as resolved.
