### ISSUE TITLE
 BadRequestError: request aborted 

### ISSUE THREAD

**Issue by shashankdev12** [nodejs/help#2166]
Unhandled error for request POST /api/users/imageUpdate?access_token=0mN8Z7CAmNGvdGXlLpjlHZRVBMHBbIrMleALlVAHhcBzotoGfy5AtP9EeRc2IeBD: BadRequestError: request aborted
    at IncomingMessage.onAborted (/home/ubuntu/KnowIt/test-loopback/node_modules/raw-body/index.js:231:10)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at abortIncoming (_http_server.js:445:9)
    at socketOnClose (_http_server.js:438:3)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)

**Comment by gireeshpunathil** [comment]
@shashankdev12 - is this still outstanding? looks like the error is thrown from a module called `raw-body`

**Comment by deeeed** [comment]
I have a similar error on production that I cannot reproduce locally. Any update on this?

**Comment by dmahely** [comment]
Same here as well. As far as I can tell there's no pattern to this error occurring. It's really clogging up my logs. 

```
BadRequestError: request aborted
     at IncomingMessage.onAborted (/home/bitnami/htdocs/node_modules/raw-body/index.js:231:10)
     at IncomingMessage.emit (events.js:210:5)
     at IncomingMessage.EventEmitter.emit (domain.js:476:20)
     at abortIncoming (_http_server.js:492:9)
     at socketOnClose (_http_server.js:485:3)
     at Socket.emit (events.js:215:7)
     at Socket.EventEmitter.emit (domain.js:476:20)
     at TCP.<anonymous> (net.js:658:12)
```

I traced it to this snippet in `node_modules/raw-body/index.js`. Any idea when the `aborted` event is emitted?

```
  stream.on('aborted', onAborted)

   ....

  function onAborted () {
    if (complete) return

    done(createError(400, 'request aborted', {
      code: 'ECONNABORTED',
      expected: length,
      length: length,
      received: received,
      type: 'request.aborted'
    }))
  }

```

**Comment by ntedgi** [comment]
any updates on this error? 
or anyone can share an insight on how to capture these errors thrown from` raw-body`?

**Comment by txqsyg** [comment]
any updates on this error?

**Comment by gireeshpunathil** [comment]
pls report this to the `raw-body` module, this code does not belong to node.js
