### ISSUE TITLE
error in node js

### ISSUE THREAD

**Issue by Bharani415** [nodejs/help#2175]
```
PS C:\Users\BB\Desktop\bootcamp-master\complete-node-bootcamp-master\1-node-farm> node index.js
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'C:\Users\BB\Desktop\bootcamp-master\complete-node-bootcamp-master\1-node-farm\index.js'
?[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:677:27)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)?[39m
?[90m    at internal/main/run_main_module.js:17:11?[39m {
  code: ?[32m'MODULE_NOT_FOUND'?[39m,
  requireStack: []
}
```

**Comment by ORESoftware** [comment]
there's no file named index.js in the current directory

**Comment by ORESoftware** [comment]
try this:

```
echo 'console.log("hello its moi")' > main.js
node main.js
```

**Comment by Bharani415** [comment]
Thanks for your reply...

**Comment by ORESoftware** [comment]
sure...

**Comment by tniessen** [comment]
I am assuming your issue was resolved, if it wasn't, please let us know by commenting here or opening a new issue.
