### ISSUE TITLE
ERR_INVALID_URL with valid URL?

### ISSUE THREAD

**Issue by mastergberry** [nodejs/help#2179]
**Version**: v12.6.0
**Platform**: Windows 64-bit
**Subsystem**: url.js

I am using this library which in turn calls nodejs internals as shown by the stack trace below: https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater

```
2019/09/13 12:35:19:055 Error: TypeError [ERR_INVALID_URL]: Invalid URL: https://client-updates.badlion.net
    at onParseError (internal/url.js:243:9)
    at new URL (internal/url.js:319:5)
    at newBaseUrl (C:\Program Files\Badlion Client\resources\app.asar\node_modules\electron-updater\out\main.js:152:18)
    at new GenericProvider (C:\Program Files\Badlion Client\resources\app.asar\node_modules\electron-updater\out\providers\GenericProvider.js:43:43)
    at createClient (C:\Program Files\Badlion Client\resources\app.asar\node_modules\electron-updater\out\providerFactory.js:95:14)
    at C:\Program Files\Badlion Client\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:479:99
    at async NsisUpdater.getUpdateInfoAndProvider (C:\Program Files\Badlion Client\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:482:20)
    at async NsisUpdater.doCheckForUpdates (C:\Program Files\Badlion Client\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:503:20)
```

A user reported the above error in our logs from trying to parse that URL...there are no issues with this URL though. This was only an issue for some users...I myself cannot reproduce the above problem.

Was this fixed in a later version of NodeJS v12? Is this is a nodejs problem? I'm not really sure but I thought this was the right place to start.

**Comment by marsonya** [comment]
Hi @mastergberry - I tried to parse the url `https://client-updates.badlion.net` on Node v14.15.4.
It worked smoothly.

**Comment by mastergberry** [comment]
Yeah, I don't know if this is still an issue on NodeJS 14.X...it was random on 12.X for only a few users. It's just a weird problem overall tbh that it was only happening for a few users and not all of them.

**Comment by killpowa** [comment]
Still an issue on node 14.x

**Comment by benjamingr** [comment]
The URL parser has been changed since this issue so I assume it's no longer relevant - cheers.
