### ISSUE TITLE
Get EPERM error on ubuntu, but not on MacOS

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#2206]
On Node.js 11/12 on Ubuntu. I am getting this error:

```console
Uncaught exception: Error: kill EPERM
    at process.kill (internal/process/per_thread.js:189:13)
    at /home/ubuntu/.nvm/versions/node/v12.8.0/lib/node_modules/bunion/dist/consumer/cli.js:452:17
    at ReadStream.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.8.0/lib/node_modules/bunion/dist/consumer/cli.js:493:13)
    at ReadStream.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at ReadStream.Readable.push (_stream_readable.js:210:10)
    at TTY.onStreamRead (internal/stream_base_commons.js:166:17) {
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'kill'
}
```

I can't figure out what causes this error exactly, it happens when I send the process a SIGINT using Ctrl-C...but it doesn't happen on MacOS just Ubuntu.

I think it happens when `process.exit()` gets called, not when SIGINT gets received, if that's a clue.

**Comment by bnoordhuis** [comment]
bunion is trying to send a signal to a process it doesn't have the right to signal. That's about all I can tell you from looking at the stack trace.

@ORESoftware can probably provide more insight but I expect it's related to this line:

https://github.com/ORESoftware/bunion/blob/3cbfa4325ffd31ed8151e8063c177dd27c94d40c/lib/consumer/cli.ts#L641

**Comment by gireeshpunathil** [comment]
@ORESoftware - is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
