### ISSUE TITLE
child_process error while using gulp

### ISSUE THREAD

**Issue by irenkaaa** [nodejs/help#2247]
* **Node.js Version**: v10.15.3
* **OS**: Windows 64
* **Scope (install, code, runtime, meta, other?)**: Visual Studio Code

On to using gulp, after makin some edits in VSC getting this message and waiting ~2 min for Browsersync to work with the edits

```js
Error: exited with error code: 1
    at ChildProcess.onexit (d:\Users\User\Desktop\mishland\node_modules\end-of-stream\index.js:40:36)
    at ChildProcess.emit (events.js:198:13)
    at ChildProcess.EventEmitter.emit (domain.js:466:23)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
[Browsersync] Reloading Browsers... (buffered 24 events)
```

**Comment by PoojaDurgad** [comment]
@irenkaaa - can you elaborate the issue please? so that it will be helpful to debug your error. Like which command leading to this error.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
