### ISSUE TITLE
Getting “request aborted” error when trying to serve file using res.download()

### ISSUE THREAD

**Issue by jesscorda** [nodejs/help#2264]
* **Node.js Version**:10.6.0
* **OS**:Windows

I am trying to serve csv file to the client when he clicks on a button. I have managed to generate the csv file with the data. But when I try to download I get an error "Request Aborted".

```
exists(join('./public/file.csv'), (exists) => {
        console.log(exists)
        if (exists) {
            response.download(join('./public/file.csv'), "file.csv", (err: Error) => {
                if (err) {
                    logger.error(err);
                }
            });
        }
        else {
            logger.error("file cant be downloaded")
        }
    })
```
the error I get is 
```
 Error: Request aborted
    at onaborted (\node_modules\express\lib\response.js:1025:15)
    at Immediate._onImmediate (node_modules\express\lib\response.js:1067:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5) code: 'ECONNABORTED'
```
-->

**Comment by gireeshpunathil** [comment]
@jesscorda - is this still an issue? which package / module you are using that contain the `response` object?
