### ISSUE TITLE
"invalid argument" when running npm --version

### ISSUE THREAD

**Issue by satyarajj** [nodejs/help#2278]
C:\Users\satya>npm --version
Error: EINVAL: invalid argument, mkdir 'C:\Program Files\nodejs\node_modules\npm\bin"'
TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97:27)
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:225:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:263:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:81:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:80:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:171:20)
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:97:27)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:210:5)
    at process._fatalException (internal/process/execution.js:150:25)
6.12.0

**Comment by IMHOJEONG** [comment]
It`s maybe helpful to you
https://github.com/zkat/npx/issues/146

**Comment by sidrakshe28** [comment]
I'm getting this error 
can  anyone help ?


C:\Users\Admin pc>npx create-react-app hello
npm ERR! code EINVAL
npm ERR! syscall mkdir
npm ERR! path C:\Users\Admin pc\.conda:\Users\Admin~1pc\AppData\Roaming\npm-cache --global\_cacache\tmp
npm ERR! errno -4071
npm ERR! EINVAL: invalid argument, mkdir 'C:\Users\Admin pc\.conda:\Users\Admin~1pc\AppData\Roaming\npm-cache --global\_cacache\tmp'
npm ERR! code ENOLOCAL
npm ERR! Could not install from "pc\.conda:\Users\Admin~1pc\AppData\Roaming\npm-cache" as it does not contain a package.json file.
Install for [ 'create-react-app@latest' ] failed with code 4294963225

**Comment by PoojaDurgad** [comment]
@satyarajj - did @IMHOJEONG 's suggestion help you to resolve the issue? and @sidrakshe28 - is this still an issue?

**Comment by PoojaDurgad** [comment]
inactive. closing!!
