### ISSUE TITLE
readdirSync get incorrect result

### ISSUE THREAD

**Issue by yegao** [nodejs/help#2285]
Version: 11.15.0
Platform: Darwin

```JavaScript
const rmdirSync = (path, options) => {
    if (options && options.recursive) {
        let files = [];
        if (fs.existsSync(path)) {
            if(fs.statSync(path).isDirectory()){
                files = fs.readdirSync(path);
                for (const file of files) {
                    const currentPath = $path.resolve(path, file);
                    if (fs.statSync(currentPath).isDirectory()) {
                        rmdirSync(currentPath, options);
                    } else {
                        fs.unlinkSync(currentPath);
                    }
                }
            }
            else{
                fs.unlinkSync(path);
            }
        }
    }
    return fs.rmdirSync(path);
};
```
when i use 
```JavaScript
fs.readdirSync('/project/node_modules/.bin')
```
I get files with in /project/node_modules/.bin as following
```
[
  'acorn',                'atob',
  'babylon',              'browserslist',
  'detect-libc',          'errno',
  'import-local-fixture', 'jsesc',
  'json5',                'loose-envify',
  'mg-service',           'miller-rabin',
  'mkdirp',               'needle',
  'node-pre-gyp',         'nopt',
  'parser',               'qrcode-terminal',
  'rc',                   'regjsparser',
  'rimraf',               'semver',
  'sha.js',               'terser',
  'uuid',                 'webpack',
  'webpack-cli',          'which'
]
```

When I open the directory  .bin, there is no acorn in it 
```
[
  'atob',
  'babylon',              'browserslist',
  'detect-libc',          'errno',
  'import-local-fixture', 'jsesc',
  'json5',                'loose-envify',
  'mg-service',           'miller-rabin',
  'mkdirp',               'needle',
  'node-pre-gyp',         'nopt',
  'parser',               'qrcode-terminal',
  'rc',                   'regjsparser',
  'rimraf',               'semver',
  'sha.js',               'terser',
  'uuid',                 'webpack',
  'webpack-cli',          'which'
]
```
as I do this:
```JavaScript
rmdirSync($path.resolve(__dirname,"..","projects","test-empty","node_modules"),{recursive:true})
```
there is a Error: ENOTEMPTY: directory not empty, rmdir '/project/test-empty/node_modules/.bin'

**Comment by bnoordhuis** [comment]
I'm moving this to nodejs/help because I see no indication that it's a bug with Node.js itself. Note that your example has a TOCTOU bug (`fs.existsSync()` followed by `fs.statSync()`.)

**Comment by yegao** [comment]
> what is `ls -lh` of `/project/node_modules/.bin`?
```
ls -lh ./node_modules/@babel/template/node_modules/.bin
```
```
// result is
total 0
lrwxr-xr-x  1 vvadmin  staff    35B 11 21 11:05 parser -> ../../../parser/bin/babel-parser.js
```

**Comment by yegao** [comment]
> I'm moving this to nodejs/help because I see no indication that it's a bug with Node.js itself. Note that your example has a TOCTOU bug (`fs.existsSync()` followed by `fs.statSync()`.)
I do't understand.Can't `fs.existsSync()` be followed by `fs.statSync()`?Could you explain why in a little more detail :)thank you very much.
Now I have resolved my problem with rimraf.But I don't understand why my implementation is problematic
When I use my implementation ,I get Error:
```
Error: ENOTEMPTY: directory not empty, rmdir '/Users/vvadmin/work/minigame-server/temp/e880a539-0ad2-403b-a347-7c959a0bfa65/node_modules/@babel/template/node_modules/.bin'
    at Object.rmdirSync (fs.js:763:3)
    at rmdirSync (/Users/vvadmin/work/minigame-server/utils/fs.js:157:15)
    at rmdirSync (/Users/vvadmin/work/minigame-server/utils/fs.js:143:29)
    at rmdirSync (/Users/vvadmin/work/minigame-server/utils/fs.js:143:29)
    at rmdirSync (/Users/vvadmin/work/minigame-server/utils/fs.js:143:29)
    at Object.rmdirSync (/Users/vvadmin/work/minigame-server/utils/fs.js:143:29)
    at bundle (/Users/vvadmin/work/minigame-server/build/index.js:174:24) {
  errno: -66,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: '/Users/vvadmin/work/minigame-server/temp/e880a539-0ad2-403b-a347-7c959a0bfa65/node_modules/@babel/template/node_modules/.bin'
}
```

**Comment by PoojaDurgad** [comment]
@yegao - looks like this issue can be closed now .please let me know if that is not the case.

**Comment by PoojaDurgad** [comment]
inactive. closing!!
