### ISSUE TITLE
UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by Chalverscheid79** [nodejs/help#2307]
* **Version**: 6.13.1
* **Platform**: Window 10 x64
* **Subsystem**:

After installing the @Vaadin/cli
I tried to create a project and got the following exception:

```
> Y:\>vaadin init test-project
> Creating application 'test-project' using spring
> (node:12528) UnhandledPromiseRejectionWarning: RequestError: Error: connect ETIMEDOUT 104.20.36.243:443
>     at new RequestError (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vaadin\cli\node_modules\request-promise-core\lib\errors.js:14:15)
>     at Request.plumbing.callback (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vaadin\cli\node_modules\request-promise-core\lib\plumbing.js:87:29)
>     at Request.RP$callback [as _callback] (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vaadin\cli\node_modules\request-promise-core\lib\plumbing.js:46:31)
>     at self.callback (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vaadin\cli\node_modules\request\request.js:185:22)
>     at Request.emit (events.js:210:5)
>     at Request.onRequestError (C:\Users\xxx\AppData\Roaming\npm\node_modules\@vaadin\cli\node_modules\request\request.js:881:8)
>     at ClientRequest.emit (events.js:210:5)
>     at TLSSocket.socketErrorListener (_http_client.js:406:9)
>     at TLSSocket.emit (events.js:210:5)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)
> (node:12528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:12528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Unfortunately, I'm sitting behind a proxy, the settings have done so:

```
Y:\>npm config list
; cli configs
metrics-registry = "http://registry.npmjs.org/"
scope = ""
user-agent = "npm/6.13.1 node/v12.13.0 win32 x64"

; userconfig C:\Users\xxx\.npmrc
https-proxy = "https://user:password@xxx.xxx.xxx.xxx:80/"
proxy = "http://user:password@xxx.xxx.xxx.xxx:80/"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; builtin config undefined
prefix = "C:\\Users\\xxx\\AppData\\Roaming\\npm"
```

**Comment by vitjok27** [comment]
have you found a resolution to this?

**Comment by gireeshpunathil** [comment]
@Chalverscheid79 - is this resolved?

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
