### ISSUE TITLE
Crash Node process

### ISSUE THREAD

**Issue by walter-heestermans-toyota** [nodejs/help#2341]
Can this exception kills a nodejs process

undefined:1
undefined
^

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at Request._callback (/opt/node-apps/locs-ui/app/controllers/pages.js:998:29)
    at self.callback (/opt/node-apps/locs-ui/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/opt/node-apps/locs-ui/node_modules/request/request.js:878:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:314:9)
    at emitOne (events.js:96:13)
undefined:1
undefined
^

We are suing NodejS VERSION nodejs-v6.14.4-x64

**Comment by Zabrah** [comment]
It's not valid to have undefined in a stringified JSON. Instead you have to find an alternative way, such as 0, an empty string "" or omit the attribute.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
