### ISSUE TITLE
STDIN as socket problem

### ISSUE THREAD

**Issue by zdm** [nodejs/help#2342]
* **Node.js Version**:
13.3.0 x64
* **OS**:
Windows 10 x64

I am starting node as child process with STDIN redirected to the socket.
When I am trying to work with STDIN from the node process (for example, set events listeners) I am getting errors:
```
process.stdin.on( "readable", () => { } );

net.js:322
      err = this._handle.open(fd);
                         ^

Error: EINVAL: invalid argument, uv_pipe_open
    at new Socket (net.js:322:26)
    at process.getStdin [as stdin] (internal/process/stdio.js:85:19)
    at Object.<anonymous> (d:\downloads\eslint-server\index.js:39:9)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'uv_pipe_open'
}
```

This issue is present only on Widows.

Is it fixable or I am doing something wrong?

**Comment by gireeshpunathil** [comment]
@nodejs/platform-windows
