### ISSUE TITLE
Module did not self-register error using bcrypt in worker_thread

### ISSUE THREAD

**Issue by amrendra007** [nodejs/help#2352]
* **Node.js Version**: 12.13.0
* **OS**: macos version10.13.6

Requiring "bcrypt": "^3.0.7" in workers_thread throwing  Error: Module did not self-register.
 
```
error Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/developer/Syook/syook-tnt-server/node_modules/bcrypt/bcrypt.js:6:16)```


```js
//code to create worker_thread
const createThread = async topic => {
  try {
    const worker = new Worker(__dirname + '/thread.js', { workerData: topic });
    console.log('worker created ', worker.threadId);
    worker.on('message', message => {
        console.log("TCL: message", message)
    });
    worker.on('error', err => {
      console.log('error', err);
    });
    worker.on('exit', code => {
      if (code !== 0) console.log(new Error(`Worker stopped with exit code ${code}`));
    });
  } catch (error) {
    throw error;
  }
};

> thread.js
 const { parentPort, workerData } = require('worker_threads');

console.log('workerData', workerData);

const bcrypt = require('bcrypt');


```
-->

**Comment by bnoordhuis** [comment]
https://github.com/kelektiv/node.bcrypt.js/issues/709 - bcrypt doesn't support worker_threads at the time of writing.
