### ISSUE TITLE
nodejs cannot start

### ISSUE THREAD

**Issue by RedGuys** [nodejs/help#2359]
* **Node.js Version**: v13.3.0
* **OS**: Ubuntu 16.04.6 LTS

buffer.js:586
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

RangeError: Index out of range
    at Object.slice (buffer.js:586:37)
    at Buffer.toString (buffer.js:783:14)
    at Object.readFileSync (fs.js:392:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:22)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_OUT_OF_RANGE'
}

This problem with any code

**Comment by Hakerh400** [comment]
Does it happen with any script?
Can you try with an empty js file?
Can you start repl (run `node` without arguments)?
Does it crash when you run `node -v` ?

**Comment by RedGuys** [comment]
1) yes
2) still crash
3) yes
4) no
PS. the problem was solved, I can not specify how.

**Comment by Dantali0n** [comment]
I am having this exact same issue.

**Comment by algj** [comment]
Exact same issue on Arch Linux (qemu, virtual machine)
