### ISSUE TITLE
Facing an issue while running an docker image getting an error : internal/modules/cjs/loader.js:800

### ISSUE THREAD

**Issue by ymkarthik** [nodejs/help#2380]
* **Node.js Version**: 12.4.0
* **OS**: Linux
docker run my_hub_user_name/select
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'mysql'
Require stack:
- /usr/src/app/select.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/src/app/select.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/select.js' ]
}

**Comment by gireeshpunathil** [comment]
@ymkarthik - is this still an issue?

you will need to review the documentation on the usage of the said docker image. Looks like the app requires some dependent libraries (`mysql`) which are not installed. Ideally, the `Dockerfile` would have verbs for installing dependencies, and if that is not present, then that has to be performed while running the container.

**Comment by gireeshpunathil** [comment]
inactive, closing. feel free to re-open if it is outstanding
