### ISSUE TITLE
npm problems, build and linux binaries

### ISSUE THREAD

**Issue by jomarocas** [nodejs/help#2415]
* **Node.js Version**: v13.6.0 and 12.14.1
* **OS**:Centos 7 3.10.0-862.14.4.el7.x86_64
* **Scope (install, code, runtime, meta, other?)**:binaries
* **Module (and version) (if relevant)**:none

Hi, i try the use the binaries download in a custom location nodejs LTS 12.14.1

```
wget https://nodejs.org/dist/v12.14.1/node-v12.14.1-linux-x64.tar.xz
~/nodejs_env/12.14.1/bin
./node -v
response v12.14.1
./npm -v
internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /home/user/nodejs_env/12.14.1/bin/npm
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/user/nodejs_env/12.14.1/bin/npm:19:21
    at Object.<anonymous> (/home/user/nodejs_env/12.14.1/bin/npm:153:3)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/user/nodejs_env/12.14.1/bin/npm' ]
}

```
ok error with binaries in custom location

i downloaded the latest version

```
wget https://nodejs.org/dist/v13.6.0/node-v13.6.0-linux-x64.tar.xz
cd ~/nodejs_env/node-v13.6.0-linux-x64/bin
./node -v
v13.6.0
./npm -v
6.13.4
```
working good
later go to my project in loopback 4 and execute npm i woking good with
`export PATH=~/nodejs_env/node-v13.6.0-linux-x64/bin:$PATH`
`npm install `
all good
but i make `npm run build`
```
> reactions@1.0.0 build /var/www/html/reacciones-ET
> lb-tsc

internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module './utils'
Require stack:
- /var/www/html/reacciones-ET/node_modules/.bin/lb-tsc
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/var/www/html/reacciones-ET/node_modules/.bin/lb-tsc:21:15)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/www/html/reacciones-ET/node_modules/.bin/lb-tsc' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reactions@1.0.0 build: `lb-tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reactions@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2020-01-14T16_02_59_665Z-debug.log
```
Then i dont know if is a issue with the compiled binaries or what, any help for this

**Comment by PoojaDurgad** [comment]
@jomarocas - There are some names which npm will automatically install but 'build' is not one of them as build is an internal command as described in  https://docs.npmjs.com/cli/build  . 
when you are running 'npm install' , it will install package.json dependencies .So there is missing build script in your package.json so try to modify your package.json along with that Try using other npm scripts like classic 'npm start'

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
