### ISSUE TITLE
Failure when i was trying to update Node using npm install

### ISSUE THREAD

**Issue by Zorono** [nodejs/help#2431]
[2020-01-22T02_30_35_268Z-debug.log](https://github.com/nodejs/node/files/4095033/2020-01-22T02_30_35_268Z-debug.log)
[2020-01-22T02_30_35_527Z-debug.log](https://github.com/nodejs/node/files/4095034/2020-01-22T02_30_35_527Z-debug.log)

Version: v12.13.0
Platform: Windows 8.1 Pro x86-bit(ia32)
Subsystem: `npm install`

i was trying to upgrade Node(v12.13.0 -> v13.6.0) using the command `npm install -g node` but it failed with the following error logs...
```
C:\Users\Zoro>npm install -g node

> node@13.6.0 preinstall C:\Users\Zoro\AppData\Roaming\npm\node_modules\node
> node installArchSpecificPackage

npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for node-win-x86@13.6.0: wanted {"os":"win3
2","arch":"x86"} (current: {"os":"win32","arch":"ia32"})
npm ERR! notsup Valid OS:    win32
npm ERR! notsup Valid Arch:  x86
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: ia32

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zoro\AppData\Roaming\npm-cache\_logs\2020-01-22T02_30_35_2
68Z-debug.log
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module 'node-win-x86/package.json'
Require stack:
- C:\Users\Zoro\AppData\Roaming\npm\node_modules\node\installArchSpecificPackage
.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794
:15)←[39m
←[90m    at Function.resolve (internal/modules/cjs/helpers.js:80:19)←[39m
    at ChildProcess.<anonymous> (C:\Users\Zoro\AppData\Roaming\npm\node_modules\
←[4mnode←[24m\node_modules\←[4mnode-bin-setup←[24m\index.js:18:27)
←[90m    at ChildProcess.emit (events.js:210:5)←[39m
←[90m    at maybeClose (internal/child_process.js:1021:16)←[39m
←[90m    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5
)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\Zoro\\AppData\\Roaming\\npm\\node_modules\\node\\installArc
hSpecificPackage.js'←[39m
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@13.6.0 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node@13.6.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zoro\AppData\Roaming\npm-cache\_logs\2020-01-22T02_30_35_5
27Z-debug.log
```

**Comment by Dalinaa** [comment]
i have the same issue and idk how to fix it

**Comment by gireeshpunathil** [comment]
@Zorono - is this still an issue? does the standard `msi` installer work?
