### ISSUE TITLE
Discord Bot

### ISSUE THREAD

**Issue by AudiophilePL** [nodejs/help#2463]
Hello, I want to make a bot for Discord, but I have a little issue when I want to start it! Please help.

* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

Issue:

ReferenceError: Client is not defined
    at Object.<anonymous> (C:\Users\user\Desktop\bot\index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```js

const Discord = require('discord.js');
const client = new Discord.Client();

Client.login("Njc0NzAxMzkyNzM2MTU3NzAw.Xj3lMQ.lm8A1iAjH6DtcRGr4d4bdpn-rvQ");

const PREFIX = 'r/';

client.on('ready', () =>{
    console.log('This bot is online!');
})

client.on('message', message =>{

    let args = message.content.substring(PREFIX.length).split(" ");

    switch(args[0]){
        case 'info':
            message.channel.sendMessage('Main Author: Mikael Main Programmer: :<')
            break;
    }
})

```
-->

**Comment by Hakerh400** [comment]
It should be `client.login` (lowercased).

**Comment by AudiophilePL** [comment]
Thank You! Now It's working

> It should be `client.login` (lowercased).

**Comment by PoojaDurgad** [comment]
@AudiophilePL - looks like this issue can be closed now .please let me know if that is not the case.

**Comment by PoojaDurgad** [comment]
closing as resolved. feel free to reopen if it is required.
