### ISSUE TITLE
I am unable to start my discord bot.

### ISSUE THREAD

**Issue by Deducts** [nodejs/help#2485]
Title - I can't seem to find the error either. If you require code then please let me know.

```
`internal/modules/cjs/loader.js:744
    throw err;
    ^

SyntaxError: C:\Users\Billy Lovett\Documents\Discord Bots\RiftMC\storage\config.json: Unexpected token } in JSON at position 353
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:741:27)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Billy Lovett\Documents\Discord Bots\RiftMC\index.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
PS C:\Users\Billy Lovett\Documents\Discord Bots\RiftMC> git remote add origin https://github.com/Deducts/RiftMC.git `
```

**Comment by gireeshpunathil** [comment]
@Deducts - is this still an issue? if so, can you provide full steps to recreate?

**Comment by CharlieFarrar** [comment]
Bit late now mate, havent been coding the bot for a good while now.

Thanks anyways.

**Comment by gireeshpunathil** [comment]
closing then, cheers. feel free to re-open if it becomes relevant again!
