### ISSUE TITLE
Error: Cannot find module '../lib/utils/unsupported.js'

### ISSUE THREAD

**Issue by flying1020** [nodejs/help#2498]
run cmd: `npm`
show:
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /usr/local/src/node-v12.16.1-linux-arm64/bin/npm
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at /usr/local/src/node-v12.16.1-linux-arm64/bin/npm:19:21
    at Object.<anonymous> (/usr/local/src/node-v12.16.1-linux-arm64/bin/npm:153:3)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/src/node-v12.16.1-linux-arm64/bin/npm' ]
}
,
some error also when run `npx`.

arch: arm64, version: V12.6.1

**Comment by flying1020** [comment]
Seems like the ‘Relative path’ is not wrok correctly in `require` cmd.

**Comment by Hakerh400** [comment]
Possibly related: https://github.com/nodejs/help/issues/1983 and https://github.com/nodejs/node/issues/29916

**Comment by flying1020** [comment]
> 
> 
> Possibly related: #1983 and [nodejs/node#29916](https://github.com/nodejs/node/issues/29916)

Yeah，I run ubuntu env in a chroot which in android system. now I konw this is a bug caused by android instead of nodejs, think you!

**Comment by omkashyap7** [comment]
plz help me how solve this error
