### ISSUE TITLE
Getting issue internal/modules/cjs/loader.js:638

### ISSUE THREAD

**Issue by rituchoudhary680** [nodejs/help#2500]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'dotenv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\WRENT\report.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by KelseyMetter** [comment]
I'm getting the same issue.

**Comment by zelenins** [comment]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'loadash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/b.zelenovic/Documents/graphql-project/server/schema/schema.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

node v10.19.0

**Comment by PoojaDurgad** [comment]
@rituchoudhary680 and @KelseyMetter - can you elaborate the issue please? like which command you are trying to run ?

for me this issue looks similar to https://github.com/JedWatson/sydjssite/issues/36, https://github.com/nodejs/help/issues/1846 
hopefully this may help you to get rid of this issue. probably  by looking at your error , make sure you do npm install  (latest stable version) before running any commands.

**Comment by gireeshpunathil** [comment]
answered, closing. feel free to re-open if it is outstanding
