### ISSUE TITLE
MongoDB Inserting Datas Problems

### ISSUE THREAD

**Issue by PaulTsai20160627** [nodejs/help#251]
Hi Node JS : 
Here is one problems that I encoutered during using NodeJS to insert informations to MongoDB.
Under the connections to the MongoDB connections, It shows the following messages:
Why there will show pool destroyed  ? It seems that Data has not been inserted correctly !

Connection established to mongodb://localhost:27017/paultsai
{ MongoError: pool destroyed
    at Pool.write (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/connection/pool.js:825:15)
    at executeOp (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:457:12)
    at Object.getLastErrorCallback [as cb](/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:453:9)
    at /home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/connection/pool.js:446:18
    at authenticateStragglers (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/connection/pool.js:402:16)
    at .messageHandler (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/connection/pool.js:424:5)
    at Socket.<anonymous> (/home/esp8266/node-v6.3.1-linux-x86/node-prac/node_modules/mongodb-core/lib/connection/connection.js:294:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18) name: 'MongoError', message: 'pool destroyed' }
esp8266@esp8266-VirtualBox:~/node-v6.3.1-linux-x86/node-prac/mongodb$ 

Here are my original source code:

``` javascript
var mongodb = require('mongodb');
var MongoClient = mongodb.MongoClient;
var url = 'mongodb://localhost:27017/paultsai';
// build a connection through MongoClient Object which creates by calling the mongodb modules MongoClient Methods.
MongoClient.connect(url,function(err,db){
// when connects, check if its ok, if not, return err message,
//else show the connect succeed messages.
//create or read a collection from mongodb database named "users"
// insert user informations to this users collection
// there are insert/update/delete/query method for management of any
// user informations.
    if(err)
    {
        console.log("Unable to connect to the mongoDB server. Error:",err);
    }else{
        console.log("Connection established to",url);
    // get the documents collection
    var collection = db.collection('users');
    // create some users    
    var user1 = {name: 'modules admin',age: 42, roles:['admin', 'moderator','user']};
    var user2 = {name: 'modules user' ,age: 22, roles:['user']};
    var user3 = {name: 'modules super admin',age: 92, roles:['Super-admin','admin' ,'moderator','user']};
    collection.insert([user1,user2,user3],function(err,result){
        if(err){
            console.log(err);
               }
        else {
            console.log('Inserted %d documents into the "users" collection. The documents inserted with "_id" are:',result.length,result);
             }
        });
/*
    collection.update({name: 'modulus user'},{$set: {enable: false}},function(err,numUpdated){
    if(err){
        console.log(err);
    }else if(numUpdated) {
        console.log('Updated Successfully %d documents.',numUpdated);
    }else {
        console.log("No document founde with defined "find" criteria!");
    }
    });
    collection.find({name: 'modulus user'}).toArray(function(err,result){
    if(err){
        console.log(err);
    }else if(result.length) {
        console.log('Found',result);
    }else {
        console.log('No documents found with defined "find" criteria!');
    }
});
*/
    db.close();
    }
});
```

**Comment by lordKnighton** [comment]
Try to model your DB setup after this 💯 

![screen shot 2016-08-13 at 10 38 00 am](https://cloud.githubusercontent.com/assets/1773260/17644688/24ffabd6-6142-11e6-9fdb-1fa280ec9515.png)

**Comment by lordKnighton** [comment]
try 🎱 

 ||>  `mongoclient.open`  then remove `mongoclient.connect`  <||

**Comment by ranjeetkaur** [comment]
I think only dropping the db.close() will fix the error. Mongodb takes care of closing the connection based on it's scope. In your code, scope of db is only within the callback function, so it is safe not to explicitly close the connection.

Here is working copy of your code:
```
var mongodb = require('mongodb');
var MongoClient = mongodb.MongoClient;
var url = 'mongodb://localhost:27017/paultsai';
// build a connection through MongoClient Object which creates by calling the mongodb modules MongoClient Methods.
MongoClient.connect(url,function(err,db){
// when connects, check if its ok, if not, return err message,
//else show the connect succeed messages.
//create or read a collection from mongodb database named "users"
// insert user informations to this users collection
// there are insert/update/delete/query method for management of any
// user informations.
  if(err) {
    console.log("Unable to connect to the mongoDB server. Error:", err);
    return;
  }
  console.log("Connection established to",url);
  // get the documents collection
  var collection = db.collection('users');
  // create some users
  var user1 = {name: 'modules admin',age: 42, roles:['admin', 'moderator','user']};
  var user2 = {name: 'modules user' ,age: 22, roles:['user']};
  var user3 = {name: 'modules super admin',age: 92, roles:['Super-admin','admin' ,'moderator','user']};
  collection.insert([user1,user2,user3],function(err,result){
    if(err){
      console.log(err);
    }
    else {
      console.log('Inserted %d documents into the "users" collection. The documents inserted with "_id" are:',result.length,result);
    }
  });

  collection.update({name: 'modulus user'},{$set: {enable: false}},function(err,numUpdated){
   if(err){
      console.log(err);
   }else if(numUpdated) {
      console.log('Updated Successfully %d documents.',numUpdated);
   }else {
      console.log("No document founde with defined 'find' criteria!");
   }
   });
   collection.find({name: 'modulus user'}).toArray(function(err,result){
   if(err){
      console.log(err);
   }else if(result.length) {
      console.log('Found',result);
   }else {
     console.log('No documents found with defined "find" criteria!');
   }
  });

});
```
