### ISSUE TITLE
Client/Server app - problem with certificate

### ISSUE THREAD

**Issue by Heziode-dev** [nodejs/help#253]
Hi all,

I would like create client/server app with Node.js (in TCP). I use TLS. I've followed instruction on the [official doc](https://nodejs.org/api/tls.html) but I can't create a self-signed certificat for client and server who work…

Here it's code :

Server.js :
```javascript
const tls = require('tls');
const fs = require('fs');
 
const options = {
  key: fs.readFileSync('server-key.pem'),
  cert: fs.readFileSync('server-cert.pem'),
 
  // This is necessary only if using the client certificate authentication.
  requestCert: true,
 
  // This is necessary only if the client uses the self-signed certificate.
  ca: [ fs.readFileSync('client-cert.pem') ]
};
 
const server = tls.createServer(options, (socket) => {
  console.log('server connected',
              socket.authorized ? 'authorized' : 'unauthorized');
  socket.write('welcome!\n');
  socket.setEncoding('utf8');
  socket.pipe(socket);
});
server.listen(8000, () => {
  console.log('server bound');
});
```

client.js :

```javascript
const tls = require('tls');
const fs = require('fs');
 
const options = {
  // Necessary only if using the client certificate authentication
  key: fs.readFileSync('client-key.pem'),
  cert: fs.readFileSync('client-cert.pem'),
 
  // Necessary only if the server uses the self-signed certificate
  ca: [ fs.readFileSync('server-cert.pem') ]
};
 
const socket = tls.connect(8000, options, () => {
  console.log('client connected',
              socket.authorized ? 'authorized' : 'unauthorized');
  process.stdin.pipe(socket);
  process.stdin.resume();
});
socket.setEncoding('utf8');
socket.on('data', (data) => {
  console.log(data);
});
socket.on('end', () => {
  server.close();
});
```

The error who has returned is :

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
 
Error: Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not cert's CN: CA"
    at Object.checkServerIdentity (tls.js:186:15)
    at TLSSocket.<anonymous> (_tls_wrap.js:1023:29)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:582:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:424:38)
```

Server traceback

```
server bound
server connected authorized
```

Would anyone have a solution?

Respectfully,

Heziode

**Comment by kkc** [comment]
it's clearly that your public key is wrong. Because your public key doesn't include hostname `localhost`. How do you generate your public key?

**Comment by Heziode-dev** [comment]
I followed instruction here for generate key : [Node.js - TLS doc](https://nodejs.org/api/tls.html#tls_tls_ssl_concepts)

**Comment by Heziode-dev** [comment]
Hi,
<br />
I solve my problem with this topic : [Using client certs in node.js](http://ceejbot.tumblr.com/post/39969163196/using-client-certs-in-nodejs)
<br />
Here's a script that I created based on what is said in the blog post cited above :
<br />
```bash
#!/bin/bash
if test $# -ne 3
then
    echo "Wrong number of arguments"
    exit 1
fi

ROOTPATH="$1"
FQDN=$2
PASSWORD=$3
RSABITS=4096

# make directories to work from
mkdir -p $ROOTPATH/certs/{server,client,ca,tmp}

PATH_CA=$ROOTPATH/certs/ca
PATH_SERVER=$ROOTPATH/certs/server
PATH_CLIENT=$ROOTPATH/certs/client
PATH_TMP=$ROOTPATH/certs/tmp

######
# CA #
######

openssl genrsa -des3 -passout pass:$PASSWORD -out $PATH_TMP/ca.key $RSABITS

# Create Authority Certificate
openssl req -new -x509 -days 365 -key $PATH_TMP/ca.key -out $PATH_CA/ca.crt -passin pass:$PASSWORD -subj "/C=FR/ST=./L=./O=ACME Signing Authority Inc/CN=."

##########
# SERVER #
##########

# Generate server key
openssl genrsa -out $PATH_SERVER/server.key $RSABITS

# Generate server cert
openssl req -new -key $PATH_SERVER/server.key -out $PATH_TMP/server.csr -passout pass:$PASSWORD -subj "/C=FR/ST=./L=./O=ACME Signing Authority Inc/CN=$FQDN"

# Sign server cert with self-signed cert
openssl x509 -req -days 365 -passin pass:$PASSWORD -in $PATH_TMP/server.csr -CA $PATH_CA/ca.crt -CAkey $PATH_TMP/ca.key -set_serial 01 -out $PATH_SERVER/server.crt

##########
# CLIENT #
##########

openssl genrsa -out $PATH_CLIENT/client.key $RSABITS

openssl req -new -key $PATH_CLIENT/client.key -out $PATH_TMP/client.csr -passout pass:$PASSWORD -subj "/C=FR/ST=./L=./O=ACME Signing Authority Inc/CN=CLIENT"

openssl x509 -req -days 365 -passin pass:$PASSWORD -in $PATH_TMP/client.csr -CA $PATH_CA/ca.crt -CAkey $PATH_TMP/ca.key -set_serial 01 -out $PATH_CLIENT/client.crt

exit 0
```
<br />
Server :
<br />
```javascript
#!/usr/bin/env node
'use strict';

const tls = require('tls');
const fs = require('fs');
const port = 8000;

const options = {
    key: fs.readFileSync('certs/server/server.key'),
    cert: fs.readFileSync('certs/server/server.crt'),
    ca: fs.readFileSync('certs/ca/ca.crt'), // authority chain for the clients
    requestCert: true, // ask for a client cert
    //rejectUnauthorized: false, // act on unauthorized clients at the app level
};

var server = tls.createServer(options, (socket) => {
  socket.write('welcome!\n');
  socket.setEncoding('utf8');
  socket.pipe(socket);
})

.on('connection', function(c)
{
	console.log('insecure connection');
})

.on('secureConnection', function (c)
{
	// c.authorized will be true if the client cert presented validates with our CA
	console.log('secure connection; client authorized: ', c.authorized);
})

.listen(port, function() {
	console.log('server listening on port ' + port + '\n');
});
```
<br />
Client :
<br />
```javascript
#!/usr/bin/env node
'use strict';

const port = 8000;
const hostname = 'localhost';

const tls = require('tls');
var fs = require('fs');

const options = {
  host: hostname,
  port: port,

  // Necessary only if using the client certificate authentication
  key: fs.readFileSync('certs/client/client.key'),
  cert: fs.readFileSync('certs/client/client.crt'),

  // Necessary only if the server uses the self-signed certificate
  ca: fs.readFileSync('certs/ca/ca.crt')
};

var socket = tls.connect(options, () => {
  console.log('client connected',
              socket.authorized ? 'authorized' : 'unauthorized');
  process.stdin.pipe(socket);
  process.stdin.resume();

  socket.end();
})

.setEncoding('utf8')

.on('data', (data) => {
  console.log(data);
})

.on('end', () => {
  console.log("End connection");
});
```
<br />
When server and one client is running, the traceback in server side is :
<br />
```
server listening on port 8000

insecure connection
secure connection; client authorized:  true
```
<br />
And client side :
<br />
```
client connected authorized
End connection
```
<br />
Everything works perfectly, I manage to have a secure connection between a client and a server with a self-signed certificate.
<br />
I created a GitHub project for illustrate this exemple : [Simble TLS Client/Server with Node.js](https://github.com/Heziode-dev/Simble-TLS-Client-Server-with-Node.js)

**Comment by Heziode** [comment]
Hi @Ridley-nelson17, 

`.crt` and `.key` are generate with scripts given above.

This script:
```bash
#!/bin/bash
if test $# -ne 3
then
    echo "Wrong number of arguments"
    exit 1
fi

ROOTPATH="$1"
FQDN=$2
PASSWORD=$3
RSABITS=4096

# make directories to work from
mkdir -p $ROOTPATH/certs/{server,client,ca,tmp}

PATH_CA=$ROOTPATH/certs/ca
PATH_SERVER=$ROOTPATH/certs/server
PATH_CLIENT=$ROOTPATH/certs/client
PATH_TMP=$ROOTPATH/certs/tmp

######
# CA #
######

openssl genrsa -des3 -passout pass:$PASSWORD -out $PATH_TMP/ca.key $RSABITS

# Create Authority Certificate
openssl req -new -x509 -days 365 -key $PATH_TMP/ca.key -out $PATH_CA/ca.crt -passin pass:$PASSWORD -subj "/C=FR/ST=./L=./O=ACME Signing Authority Inc/CN=."

##########
# SERVER #
##########

# Generate server key
openssl genrsa -out $PATH_SERVER/server.key $RSABITS

# Generate server cert
openssl req -new -key $PATH_SERVER/server.key -out $PATH_TMP/server.csr -passout pass:$PASSWORD -subj "/C=FR/ST=./L=./O=ACME Signing Authority Inc/CN=$FQDN"

# Sign server cert with self-signed cert
openssl x509 -req -days 365 -passin pass:$PASSWORD -in $PATH_TMP/server.csr -CA $PATH_CA/ca.crt -CAkey $PATH_TMP/ca.key -set_serial 01 -out $PATH_SERVER/server.crt

##########
# CLIENT #
##########

openssl genrsa -out $PATH_CLIENT/client.key $RSABITS

openssl req -new -key $PATH_CLIENT/client.key -out $PATH_TMP/client.csr -passout pass:$PASSWORD -subj "/C=FR/ST=./L=./O=ACME Signing Authority Inc/CN=CLIENT"

openssl x509 -req -days 365 -passin pass:$PASSWORD -in $PATH_TMP/client.csr -CA $PATH_CA/ca.crt -CAkey $PATH_TMP/ca.key -set_serial 01 -out $PATH_CLIENT/client.crt

exit 0
```

**Comment by Ridley-nelson17** [comment]
@Heziode thank you, now I understand.

**Comment by miqmago** [comment]
Why `ca.key` is generated inside `tmp` folder?
I'm not really sure, but in my understanding `ca.key` seems that should be kept in `ca` folder, isn't it?
If new client certificates needs to be generated, `ca.key` is needed...

**Comment by Heziode** [comment]
`openssl genrsa -des3 -passout pass:$PASSWORD -out $PATH_TMP/ca.key $RSABITS` is just to generate a simple CA file without authority. We add authority with `openssl req -new -x509 -days 365 -key $PATH_TMP/ca.key -out $PATH_CA/ca.crt -passin pass:$PASSWORD -subj "/C=FR/ST=./L=./O=ACME Signing Authority Inc/CN=."` so that is the key that should be used after for all other keys.

I've been doing this for a long time and I'm not a openssl expert.

**Comment by miqmago** [comment]
This is the command used to sign the client certificate signing request in the script:

```sh
openssl x509 -req -days 365 -passin pass:$PASSWORD -in $PATH_TMP/client.csr -CA $PATH_CA/ca.crt -CAkey $PATH_TMP/ca.key -set_serial 01 -out $PATH_CLIENT/client.crt
```
It gets ca key from **`$PATH_TMP/ca.key`** as it is the place previously stored.

So every time a new client certificate is needed, the ca key must be used to sign it.
I'm neither an expert in certificates, but from what I've understood, a CA authority issues one or more server certificates and should be able to issue multiple client certificates, one per each client that wants to communicate with the server. So that means that the `ca.key` must be used multiple times during the live-cycle of CA cert.

It's just a question of where the keys are placed: when `ca.key` is placed in `PATH_TMP` it seems something that you can delete without problems, but in fact, if you delete the `ca.key`, you couldn't be able to issue more certificates from this CA authority. A new key should be generated, so new `ca.crt` should be generated and all existing certificates would be automatically invalidated (server and client ones), or multiple `ca.crt` certificates should be indicated in server `ca` option.

**Comment by Heziode** [comment]
Indeed, you are right. I have updated the script and [the repo](https://github.com/Heziode/Simple-TLS-Client-Server-with-Node.js).
