### ISSUE TITLE
 spawn EPERM Issue - exec() method

### ISSUE THREAD

**Issue by rdaddinsc** [nodejs/help#2530]
* **Node.js Version**: 10.15.2
* **OS**: Windows 2012 R2
* **Scope (install, code, runtime, meta, other?)**: runtime
* **Module (and version) (if relevant)**:child_process

Note: This method execution fails 5 out of 10 times.

2020-03-16 09:45:07.382 - error: [pid: 10708] app top level domain caught uncaughtException: Error: spawn EPERM
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at spawn (child_process.js:538:9)
    at Object.execFile (child_process.js:221:15)
    at exec (child_process.js:152:18)
    at getData (app_modules\app.js:114:23)

var readerProc = exec(command, function(error, stdout, stderr)
{
	if (error)
	{
		return onResult(error, screenInfo);
	}
	else
	{
		data = JSON.parse(stdout);
	}

	return onResult(false, data);
});

**Comment by gireeshpunathil** [comment]
@rdaddinsc - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
