### ISSUE TITLE
websocket nodejs errors !!

### ISSUE THREAD

**Issue by PaulTsai20160627** [nodejs/help#257]
Hi:
Here is one problem that happens during the testing of nodejs employing websocket protocols(hope can connect with devices that used "mqtt" protocol with websocket(mosquitto) ). I have tried to search through google , but does not find the match "solution"
The errors are shown below:
esp8266@esp8266-VirtualBox:~/node-v6.3.1-linux-x86/node-prac/udp_test$ node index.js
Server has Started
request for /start response
Request url: /start
Route this request /start
Request handler 'start' was called
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:426:15)
    at Server.onRequest (/home/esp8266/node-v6.3.1-linux-x86/node-prac/udp_test/server.js:10:11)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)

index.js source code

``` javascript
var router = require("./router");
var server = require("./server");

var handlers = require("./requestHandlers");
var req = { "/": handlers.start,
        "/start": handlers.start,
        "/send": handlers.send};
//var socket_client =require("./udp_socket_client");
server.start(router.route,req);
```

sever.js source code

``` javascript
var http = require("http");
var url = require("url");
var WebSocketServer = require('websocket').server;
// Connected WebSocket clients
var clients = [];

function start(route,handlers){
function onRequest(request,response){
    var pathname = url.parse(request.url).pathname;
    console.log("request for "+ pathname +" response");
    console.log("Request url: " + request.url);
    route(pathname,handlers,response,request);
    response.writeHead(200,{"Content-Type": "text/plain"});
    response.write("Hello World!!!");
    response.end();
/*
    var pathname = url.parse(request.url).pathname;
    route(route,pathname);
*/  
}
    var server = http.createServer(onRequest).listen(8082,function(){
    console.log("Server has started and is listening on port 8082.");

});
    wsServer = new WebSocketServer({
      httpServer: server,
      autoAcceptConnections: false
    });

    function onWsConnMessage(message){
      if(message.type == 'utf8')
        {
            console.log('Received message:' + message.utf8Data);
        }else if (message.type == 'binary'){
            console.log('Received binary data.');
        }
    }
    function onWsConnClose(reasonCode, description){
      cosole.log('Peer disconnected with reason: ' + reasonCode);
    }
    function onWsRequest(request){
      var connection = request.accept('echo-protocol',request.origin);
      console.log("WebSocket connection accepted.");
      // Save clients (unlimited clients)
       clients.push(connection);

      connection.on('message',onWsConnMessage);
      connection.on('close',onWsConnClose);
    }
    wsServer.on('request',onWsRequest);
}
exports.start = start;

```

router.js source code

``` javascript
/*
function route(handle,pathname){
    if(typeof handle[pathname] === 'function'){
    handle[pathname];
    }
    else {
    console.log("failed to connect !!\n");

    response.writeHead(404,{"Content-Type": "text-plain"});
    response.write("404 Not found");
    response.end();

    }
}
*/
function route(pathname,handlers,response,request){
    console.log("Route this request "+ pathname);
    if(typeof handlers[pathname] == "function"){
    handlers[pathname](response,request);
    }
    else {
    console.log("failed to connect !!\n");
    console.log("No request handler for this pathname: '" + pathname + "'");
    }
}   
exports.route = route;
```

requesthandlers.js source code

``` javascript
//var exec = require("child_process").exec;
function start(response,request){
    console.log("Request handler 'start' was called");
    //const dgram = require('dgram');
/*
    const dgram = require('dgram');
    const server = dgram.createSocket('udp4');
    server.on('message',(msg,rinfo)=>{
    console.log(`server got: ${msg} from ${rinfo.address}:${rinfo.port}`);
});
*/

    const message = Buffer.from('Hello Server ! I am Client ','utf8');
    response.writeHead(200,{"Content-Type": "text/plain"});
    //response.write(message);
    response.end(message);

/*
    const client = dgram.createSocket('udp4');
    client.send(message,8080,'localhost',(err)=>{
    client.close();
*/
//});

/*
    exec("ls -lah",function(error,stdout,stderr){
    response.writeHead(200,{"Content-Type": "text/plain"});
    response.write(stdout);
    response.end();
*/
//});
/*
    response.writeHead(200,{"Content-Type": "text-plain"});
    response.write("Hi How are you ?");
    resposne.end();
*/
}
function send(response){
    console.log("Request handler 'send' was called");
/*
    const dgram = require('dgram');
    const message = Buffer.from('Hello Server ! I am Client ','utf8');
    const client = dgram.createSocket('udp4');
    client.send(message,8080,'localhost',(err)=>{
    client.close();
});
*/
}

exports.start = start;
exports.send = send;
```

**Comment by lordKnighton** [comment]
Closing for now, If you still need help with this, reopen & we can take it from there. I apologize we didn't respond in time.
