### ISSUE TITLE
Getting error while trying to work with API using Node.js in Visual Studio. 

### ISSUE THREAD

**Issue by sumit409** [nodejs/help#2571]
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- C:\Users\HP\Desktop\Nodejs_course\playground\4-callback.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\Nodejs_course\playground\4-callback.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\HP\\Desktop\\Nodejs_course\\playground\\4-callback.js'
  ]
}

**Comment by Hakerh400** [comment]
> Cannot find module 'request'

It means that you have not installed module `request`.
Type `npm i request` to install it.

**Comment by PoojaDurgad** [comment]
@sumit409 - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive . closing!! please feel free to reopen the issue if it is outstanding!!
