### ISSUE TITLE
i keep getting an error while deploying my Discord Bot to Heroku

### ISSUE THREAD

**Issue by ChaostruxCZ** [nodejs/help#2591]
2020-04-09T10:59:54.320392+00:00 app[Worker.1]: internal/modules/cjs/loader.js:985
2020-04-09T10:59:54.320417+00:00 app[Worker.1]:   throw err;
2020-04-09T10:59:54.320418+00:00 app[Worker.1]:   ^
2020-04-09T10:59:54.320418+00:00 app[Worker.1]: 
2020-04-09T10:59:54.320418+00:00 app[Worker.1]: Error: Cannot find module 'dotenv'
2020-04-09T10:59:54.320419+00:00 app[Worker.1]: Require stack:
2020-04-09T10:59:54.320419+00:00 app[Worker.1]: - /app/index.js
2020-04-09T10:59:54.320420+00:00 app[Worker.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
2020-04-09T10:59:54.320420+00:00 app[Worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
2020-04-09T10:59:54.320420+00:00 app[Worker.1]:     at Module.require (internal/modules/cjs/loader.js:1044:19)
2020-04-09T10:59:54.320421+00:00 app[Worker.1]:     at require (internal/modules/cjs/helpers.js:77:18)
2020-04-09T10:59:54.320421+00:00 app[Worker.1]:     at Object.<anonymous> (/app/index.js:2:20)
2020-04-09T10:59:54.320421+00:00 app[Worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
2020-04-09T10:59:54.320422+00:00 app[Worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
2020-04-09T10:59:54.320422+00:00 app[Worker.1]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
2020-04-09T10:59:54.320422+00:00 app[Worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
2020-04-09T10:59:54.320423+00:00 app[Worker.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
2020-04-09T10:59:54.320423+00:00 app[Worker.1]:   code: 'MODULE_NOT_FOUND',
2020-04-09T10:59:54.320424+00:00 app[Worker.1]:   requireStack: [ '/app/index.js' ]
2020-04-09T10:59:54.320424+00:00 app[Worker.1]: }

I tried doing "npm install --dotenv-extended" but i still get the error

**Comment by ChaostruxCZ** [comment]
nvm, got that one fixed, now im getting a different error
