### ISSUE TITLE
After fixing an error i'm now getting a different one while deploying my Discord Bot to Heroku

### ISSUE THREAD

**Issue by ChaostruxCZ** [nodejs/help#2592]
2020-04-09T11:10:06.311755+00:00 app[Worker.1]: /app/index.js:15
2020-04-09T11:10:06.311771+00:00 app[Worker.1]: ["command"].forEach(handler => {
2020-04-09T11:10:06.311772+00:00 app[Worker.1]:            ^
2020-04-09T11:10:06.311773+00:00 app[Worker.1]: 
2020-04-09T11:10:06.311777+00:00 app[Worker.1]: TypeError: Cannot read property 'forEach' of undefined
2020-04-09T11:10:06.311777+00:00 app[Worker.1]:     at Object.<anonymous> (/app/index.js:15:12)
2020-04-09T11:10:06.311777+00:00 app[Worker.1]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
2020-04-09T11:10:06.311778+00:00 app[Worker.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
2020-04-09T11:10:06.311778+00:00 app[Worker.1]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
2020-04-09T11:10:06.311779+00:00 app[Worker.1]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
2020-04-09T11:10:06.311779+00:00 app[Worker.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
2020-04-09T11:10:06.311780+00:00 app[Worker.1]:     at internal/main/run_main_module.js:18:47

i followed a video on how to do this and i did it the same way as he did, but i got this error and he didnt

(link to video: https://www.youtube.com/watch?v=WwiNxva5RkM)

**Comment by ChaostruxCZ** [comment]
nvm fixed the error again
