### ISSUE TITLE
Protractor webdriver-manager update error

### ISSUE THREAD

**Issue by Yashvi-Mehta** [nodejs/help#2611]
* **Node.js Version**: 12.13.0
* **OS**: Windows 10 64bit
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

Cannot run webdriver-manager update.

Already did the following:-
1. To solve tunnel issue
 set no_proxy, npm cache clean,npm config set proxy http://userid:password/url/port,npm config set http:// , npm config set registry=:http://path, npm config set strict-ssl false.

After this,I am getting chromdriver error

C:\Users\UX149128\Peregrine automation>webdriver-manager update
webdriver-manager: using local installed version 12.1.5
[14:48:02] I/config_source - curl -oC:\Users\UX149128\Peregrine automation\node_modules\webdriver-manager\selenium\standalone-response.xml https://selenium-release.storage.googleapis.com/
[14:48:02] I/config_source - curl -oC:\Users\UX149128\Peregrine automation\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND selenium-release.storage.googleapis.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on Request instance at:
    at Request.onRequestError (C:\Users\UX149128\Peregrine automation\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:215:7)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'selenium-release.storage.googleapis.com'
}

C:\Users\UX149128\Peregrine automation>ping selenium-release.storage.googleapis.com
Ping request could not find host selenium-release.storage.googleapis.com. Please check the name and try again.

**Comment by gireeshpunathil** [comment]
@Yashvi-Mehta - is this still an issue?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
