### ISSUE TITLE
Generate library command throws error

### ISSUE THREAD

**Issue by seaBubble** [nodejs/help#2623]
* **Node.js Version**: 12.10.0
* **OS**: darwin x64
* **Scope (install, code, runtime, meta, other?)**: Generate library
* **nrwl schematics version: 7.6.2
* **angular cli version: 8.3.14

When I run the command to generate a library in my empty workspace I get an error.

Command run:
nx g @nrwl/angular:lib searchField

Error:
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'typescript'
Require stack:
- /usr/local/lib/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js
- /usr/local/lib/node_modules/@nrwl/schematics/src/command-line/shared.js
- /usr/local/lib/node_modules/@nrwl/schematics/src/command-line/affected.js
- /usr/local/lib/node_modules/@nrwl/schematics/src/command-line/nx-commands.js
- /usr/local/lib/node_modules/@nrwl/schematics/src/command-line/nx.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@nrwl/schematics/src/command-line/deps-calculator.js:15:10)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',

Folder structure:
org/
    /apps
    /libs
    /node_modules
    /tools
jest.config.js
nx.json
package.json
tsconfig.json
tslint.json
workspace.json
yarn.lock

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
