### ISSUE TITLE
Unexpected behavior on Linux. Error: Cannot find module.

### ISSUE THREAD

**Issue by IhorRybakTR** [nodejs/help#2637]
**Steps to reproduce:**
1. Create file `src/application-test.js`
```javascript
const chai = require('Chai');
const assert = chai.assert;

describe('test', function () {
    it('1 + 2', function () {
        assert.equal(3, 1 + 2);
    });
});
```
2.  `package.json`
```json
{
  "name": "nodejs-bug",
  "scripts": {
    "test": "node node_modules/mocha/bin/mocha ./src"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "mocha": "^6.2.3"
  },
  "engines": {
    "node": "^13.13.0"
  }
}
```
3.  Dockerfile
```Dockerfile
FROM node:14.0.0-stretch
WORKDIR /app
ADD src /app/src
ADD package.json /app
RUN npm install
CMD npm test
```
4. Run  
```shell 
docker build -t nodejs-bug . && docker run --name nodejs-bug nodejs-bug
```
**Actual result:**
```
> node node_modules/mocha/bin/mocha ./src

/app/node_modules/yargs/yargs.js:1172
      else throw err
           ^

Error: Cannot find module 'Chai'
Require stack:
- /app/src/application-test.js
- /app/node_modules/mocha/lib/mocha.js
- /app/node_modules/mocha/lib/cli/one-and-dones.js
- /app/node_modules/mocha/lib/cli/options.js
- /app/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/src/application-test.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /app/node_modules/mocha/lib/mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/app/node_modules/mocha/lib/mocha.js:331:14)
    at Mocha.run (/app/node_modules/mocha/lib/mocha.js:809:10)
    at Object.exports.singleRun (/app/node_modules/mocha/lib/cli/run-helpers.js:108:16)
    at exports.runMocha (/app/node_modules/mocha/lib/cli/run-helpers.js:142:13)
    at Object.exports.handler (/app/node_modules/mocha/lib/cli/run.js:292:3)
    at Object.runCommand (/app/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/app/node_modules/yargs/yargs.js:1096:28)
    at Object.parse (/app/node_modules/yargs/yargs.js:575:25)
    at Object.exports.main (/app/node_modules/mocha/lib/cli/cli.js:68:6)
    at Object.<anonymous> (/app/node_modules/mocha/bin/mocha:162:29)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/app/src/application-test.js',
    '/app/node_modules/mocha/lib/mocha.js',
    '/app/node_modules/mocha/lib/cli/one-and-dones.js',
    '/app/node_modules/mocha/lib/cli/options.js',
    '/app/node_modules/mocha/bin/mocha'
  ]
}
npm ERR! Test failed.  See above for more details.
```
But  ```npm install && npm test``` works as expected on Windows.

**Comment by PoojaDurgad** [comment]
@IhorRybakTR  - is this issue resolved?

**Comment by PoojaDurgad** [comment]
answered. closing!! feel free to reopen if that is not the case.
