### ISSUE TITLE
ERR_INVALID_ARG_TYPE(name, 'number', value);

### ISSUE THREAD

**Issue by yixi7994498** [nodejs/help#2646]
internal/validators.js:85
        throw new ERR_INVALID_ARG_TYPE(name, 'number', value);
        ^

TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number. Received undefined
    at Object.close (fs.js:409:3)
    at Object.<anonymous> (C:\Users\Usuario\Desktop\botminec\index.js:218:4)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by addaleax** [comment]
@yixi7994498 This is hard to diagnose without knowing your code. Chances are, at `C:\Users\Usuario\Desktop\botminec\index.js:218` there’s a call to `fs.close()` that doesn’t pass an as an argument.

**Comment by dinglittle** [comment]
The same

**Comment by Botprogrammer190** [comment]
same cant fix issue

**Comment by RaisinTen** [comment]
As the docs say already: https://nodejs.org/api/fs.html#fs_fs_close_fd_callback
The `fd` (the file descriptor of the file you want to close) must be passed to the function. This works:
```js
const fs = require('fs');

fs.open(__filename, (err, fd) => {
  if (err) throw err;
  fs.close(fd, (err) => {
    if (err) throw err;
    console.log('No errors');
  });
});
```
Closing since this is already answered.
