### ISSUE TITLE
I am getting error while inserting elements in database using Postman (and seeing it in RoboT )working with Visual studio for code.

### ISSUE THREAD

**Issue by sumit409** [nodejs/help#2668]
This is seen in console of Visual studio-------------------------------

Server is up on port3000
mongod
(node:15348) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at new MongooseServerSelectionError (C:\Users\HP\Desktop\2nd_course\task-manager\node_modules\mongoose\lib\error\serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (C:\Users\HP\Desktop\2nd_course\task-manager\node_modules\mongoose\lib\connection.js:823:32)
    at Mongoose.connect (C:\Users\HP\Desktop\2nd_course\task-manager\node_modules\mongoose\lib\index.js:333:15)
    at Object.<anonymous> (C:\Users\HP\Desktop\2nd_course\task-manager\src\db\mongoose.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\2nd_course\task-manager\src\index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
(node:15348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a 
catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag 
`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] starting `node src/index.js`
Server is up on port3000
(node:12036) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at new MongooseServerSelectionError (C:\Users\HP\Desktop\2nd_course\task-manager\node_modules\mongoose\lib\error\serverSelection.js:22:11)
    at NativeConnection.Connection.openUri (C:\Users\HP\Desktop\2nd_course\task-manager\node_modules\mongoose\lib\connection.js:823:32)
    at Mongoose.connect (C:\Users\HP\Desktop\2nd_course\task-manager\node_modules\mongoose\lib\index.js:333:15)
    at Object.<anonymous> (C:\Users\HP\Desktop\2nd_course\task-manager\src\db\mongoose.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\HP\Desktop\2nd_course\task-manager\src\index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
(node:12036) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a 
catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag 
`--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12036) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

This is seen in Postman----------------------------------

Could not get any response
There was an error connecting to http://localhost:3000/users.
Why this might have happened:
The server couldn't send a response:
Ensure that the backend is working properly
Self-signed SSL certificates are being blocked:
Fix this by turning off 'SSL certificate verification' in Settings > General
Proxy configured incorrectly
Ensure that proxy is configured correctly in Settings > Proxy
Request timeout:
Change request timeout in Settings > General

This is seen in Postman--------------------------------------------------------------
Cannot connect to the MongoDB at localhost:27017.

Error:
Network is unreachable. Reason: couldn't connect to server localhost:27017, connection attempt failed: SocketException: Error connecting to localhost:27017 (127.0.0.1:27017) :: caused by :: No connection could be made because the target machine actively refused it.

**Comment by PoojaDurgad** [comment]
> Cannot connect to the MongoDB at localhost:27017.


@sumit409 - is this issue resolved? I don't have much deeper insight about this but for me with your issue  by looking at the error this could be because the host or ip address is wrong I mean not able to connect to the server make sure your mongodb is running before giving the mongo command.

**Comment by PoojaDurgad** [comment]
inactive issue . please feel free to reopen the issue if its still outstanding.
