### ISSUE TITLE
call back is not a function

### ISSUE THREAD

**Issue by karthiknl0** [nodejs/help#2697]
Typeerror: callback is not a function
    at RGBTWLightAccessory.<anonymous> (/usr/lib/node_modules/homebridge-tuya-lan/lib/BaseAccessory.js:12:13)
    at PlatformAccessory.emit (events.js:198:13)
    at Accessory.PlatformAccessory._associatedHAPAccessory.on (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:85:12)
    at Accessory.emit (events.js:198:13)
    at Accessory.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Accessory._this._identificationRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:259:12)
    at Identify.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:248:16)
    at Identify.emit (events.js:198:13)
    at Identify.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at Identify.Characteristic._this.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:614:12)

**Comment by lundibundi** [comment]
Looks like you have passed something that is not callable (`not a function`) to the code that expects a function-callback or trying to use an argument as a callback when it is not a function and is therefore not callable (specifically at `lib/BaseAccessory.js:12`).

**Comment by PoojaDurgad** [comment]
@karthiknl0 - is this issue resolved?

**Comment by PoojaDurgad** [comment]
inactive. closing!! feel free to re-open the issue if its still outstanding
