### ISSUE TITLE
Windows 10 pro 64bit - Error: Cannot find module 'wrappy'

### ISSUE THREAD

**Issue by benoit1980** [nodejs/help#271]
Hello,

I have tried everything tonight.
Uninstall Node.js, redownloaded the msi version V 6.4.0, installed it using administrator rights + antivirus turned off. It seems to install correctly but each time I run a command I get this error:

```
$ npm install -g angular-cli
module.js:457
    throw err;
    ^

Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Ben\AppData\Roaming\npm\node_modules\npm\node_modules\once\once.js:1:76)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```
I tried to do a reset as suggested by some but this did not help.

**Comment by bnoordhuis** [comment]
The stack trace suggests it's an issue with npm itself (wrappy is a dependency of npm) so I would suggest closing this issue and reporting it over at https://github.com/npm/npm/issues.

**Comment by benoit1980** [comment]
Thank you I will report it to npm.
