### ISSUE TITLE
Microsoft.AspNetCore.SpaServices[0] An unhandled exception occurred: Invalid or unexpected token

### ISSUE THREAD

**Issue by Teomazivila** [nodejs/help#2724]
Hi Everyone, I have an issue that is related to this topic. I am creating a an ASPNETCORE Angular app, and getting the bellow error when executing DOTNET WATCH RUN
[error] D:\TeoProjects.Net\AspNet\Teomaz_C\ClientApp\node_modules\bluebird\js\release\reduce.js:1
(function (exports, require, module, __filename, __dirname) {

SyntaxError: Invalid or unexpected token
at new Script (vm.js:80:7)
at createScript (vm.js:274:10)
at Object.runInThisContext (vm.js:326:10)
at Module._compile (internal/modules/cjs/loader.js:664:28)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
at Function.Module._load (internal/modules/cjs/loader.js:531:3)
at Module.require (internal/modules/cjs/loader.js:637:17)
at require (internal/modules/cjs/helpers.js:22:18)
at module.exports (D:\TeoProjects.Net\AspNet\Teomaz_C\ClientApp\node_modules\bluebird\js\release\promise.js:788:1)
at Object. (D:\TeoProjects.Net\AspNet\Teomaz_C\ClientApp\node_modules\bluebird\js\release\bluebird.js:9:36)
at Module._compile (internal/modules/cjs/loader.js:701:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
at Module.load (internal/modules/cjs/loader.js:600:32)
at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

I have tried:

npm install
Deleting the node_modules and and reinstalling them again
I tried a couple more options that I can't remember that were suggested on Stackoverflow.
I am quite new on this topic, so please take it easy on me. Thanks in advanced

**Comment by addaleax** [comment]
Can you share your Node.js/npm version, your package.json (in particular the version of `bluebird` in your `node_modules` folder, etc.)?

**Comment by Teomazivila** [comment]
Node.js Version v10.15.3 and NPM Version is 6.4.1, Package.jason : {
  "name": "teomaz_c",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build:ssr": "ng run Teomaz_C:server:dev",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.2.12",
    "@angular/common": "8.2.12",
    "@angular/compiler": "8.2.12",
    "@angular/core": "8.2.12",
    "@angular/forms": "8.2.12",
    "@angular/platform-browser": "8.2.12",
    "@angular/platform-browser-dynamic": "8.2.12",
    "@angular/platform-server": "8.2.12",
    "@angular/router": "8.2.12",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.3.1",
    "core-js": "^3.3.3",
    "jquery": "3.4.1",
    "oidc-client": "^1.9.1",
    "popper.js": "^1.16.0",
    "rxjs": "^6.5.3",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.24",
    "@angular/cli": "8.3.14",
    "@angular/compiler-cli": "8.2.12",
    "@angular/language-service": "8.2.12",
    "@types/jasmine": "~3.4.4",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "~12.11.6",
    "codelyzer": "^5.2.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "typescript": "3.5.3"
  },
  "optionalDependencies": {
    "node-sass": "^4.12.0",
    "protractor": "~5.4.2",
    "ts-node": "~8.4.1",
    "tslint": "~5.20.0"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/Myuser/myproject.git"
  }
}

Sorry for the delay.
