### ISSUE TITLE
/var/www/html/bot/driver.js:299 load();

### ISSUE THREAD

**Issue by dudu123x** [nodejs/help#2737]
Hello, i have this problem /var/www/html/bot/driver.js:299
load();
^

ReferenceError: load is not defined
    at Object.<anonymous> (/var/www/html/bot/driver.js:299:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

My pastebin is here https://pastebin.com/j4mPnvq0 

I've tried to define but i didn't solved that, if anyone have a suggest.

Greetings

**Comment by Hakerh400** [comment]
You defined function `load` inside the `io.on('connection')` event handler, but you are calling it outside of the callback, so it is not in the scope. Either define `load` outside, or move `load()` call inside the callback.

**Comment by dudu123x** [comment]
thank you so much
