### ISSUE TITLE
This socket has been ended by the other party at Socket.writeAfterFIN [as write] 

### ISSUE THREAD

**Issue by xFl0vVx** [nodejs/help#2745]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:453:14)
    at Timeout._onTimeout (C:\Users\Chris Cepeda\Downloads\stress-test\stress-test\example.js:46:11)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at listOnTimeout (internal/timers.js:518:9)
    at processTimers (internal/timers.js:492:7) {
  code: 'EPIPE'
}

**Comment by lundibundi** [comment]
Could you provide a bit more info (OS, Node.js version, code)?

Based on the error: you tried to write to the socket that was closed by the other party (i.e. server called `socket.end()` / `socker.destroy()`).

**Comment by PoojaDurgad** [comment]
@xFl0vVx - is this still an issue?
