### ISSUE TITLE
when type in the terminal npm -v or any update I get this error

### ISSUE THREAD

**Issue by Israel2000** [nodejs/help#2813]
~ $npm -v
internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module '../lib/utils/unsupported.js'
Require stack:
- /usr/local/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/npm/bin/npm-cli.js' ]
}

**Comment by zacanger** [comment]
That looks like your npm installation got messed up. That could happen if you did something like `npm i -g` and then `ctrl+c` in the middle of it, I suppose. You can reinstall it with something like

```shell
curl -SsL https://registry.npmjs.org/npm/-/npm-6.0.0.tgz | tar -xzf - && \
  cd package && \
  make install
```

**Comment by Israel2000** [comment]
thanks, @zacanger, I decided to uninstall node and npm and reinstall. 
https://www.youtube.com/watch?v=Ic_dpGAqeBQ&t=43s
