### ISSUE TITLE
Redis error in node.js

### ISSUE THREAD

**Issue by sriramgroot** [nodejs/help#2820]
* **Node.js Version**: 12.13.1
* **OS**: macOS Mojave 10.14.6
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: Redis database connection

I am using Redis in Node.js and when deployed on live server it started to crash with below error message:
The no of requests are more per second.

```
at Object.replyToObject [as reply_to_object] (/home/ubuntu/webservices/node_modules/redis/lib/utils.js:7:15)
at RedisClient.handle_reply (/home/ubuntu/webservices/node_modules/redis/index.js:319:23)
at multi_callback (/home/ubuntu/webservices/node_modules/redis/lib/multi.js:79:43)
at Command.callback (/home/ubuntu/webservices/node_modules/redis/lib/multi.js:116:9)
at normal_reply (/home/ubuntu/webservices/node_modules/redis/index.js:726:21)
at RedisClient.return_reply (/home/ubuntu/webservices/node_modules/redis/index.js:824:9)
at JavascriptRedisParser.returnReply (/home/ubuntu/webservices/node_modules/redis/index.js:192:18)
at JavascriptRedisParser.execute (/home/ubuntu/webservices/node_modules/redis/node_modules/redis-parser/lib/parser.js:553:10)
Socket.<anonymous> (/home/ubuntu/webservices/node_modules/redis/index.js:274:27)
emitOne (events.js:116:13)
Socket.emit (events.js:211:7)
addChunk (_stream_readable.js:263:12)
readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:594:20)
```

**Comment by addaleax** [comment]
Could you maybe share the error message itself? I assume the stack trace is preceded by it.

**Comment by IshaanOhri** [comment]
This is just mentioning the location of the error. Could you please share the error message?

**Comment by PoojaDurgad** [comment]
ping @sriramgroot - is this issue resolved?

**Comment by gireeshpunathil** [comment]
closing, inactive. feel free to re-open if it is outstanding
