### ISSUE TITLE
npm install: permission denied for mkdir as root

### ISSUE THREAD

**Issue by antond1990** [nodejs/help#2851]
I try to install my packages defined in `package.json` with `npm install`. I get allways a permission denied error for a folder that is writeable for the current user (root).

```
root@staging2:/var/www/html# npm install

> node-sass@4.13.1 install /var/www/html/node_modules/node-sass
> node scripts/install.js

Unable to save binary /var/www/html/node_modules/node-sass/vendor/linux-x64-83 : Error: EACCES: permission denied, mkdir '/var/www/html/node_modules/node-sass/vendor'
    at Object.mkdirSync (fs.js:947:3)
    at sync (/var/www/html/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/var/www/html/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/var/www/html/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/var/www/html/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: '/var/www/html/node_modules/node-sass/vendor'
}

> core-js@2.6.9 postinstall /var/www/html/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.13.1 postinstall /var/www/html/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /var/www/html/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/usr/bin/node',
gyp verb cli   '/var/www/html/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@14.5.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.17
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 14.5.0
gyp verb command install [ '14.5.0' ]
gyp verb install input version string "14.5.0"
gyp verb install installing version: 14.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/14.5.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/html/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '14.5.0' ]
gyp verb install input version string "14.5.0"
gyp verb install installing version: 14.5.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 14.5.0
gyp verb ensuring nodedir is created /var/www/html/node_modules/node-sass/.node-gyp/14.5.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.5.0' ]
gyp verb remove using node-gyp dir: /var/www/html/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 14.5.0
gyp verb remove removing development files for version: 14.5.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '14.5.0' ]
gyp verb remove using node-gyp dir: /var/www/html/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 14.5.0
gyp verb remove removing development files for version: 14.5.0
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/html/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 4.15.0-111-generic
gyp ERR! command "/usr/bin/node" "/var/www/html/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/node_modules/node-sass
gyp ERR! node -v v14.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN html No repository field.
npm WARN html No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-16T14_33_09_206Z-debug.log
```

* **Version**: 6.14.5
* **Platform**: Ubuntu 18.04

**Comment by richardlau** [comment]
Since you're using node-sass. see https://github.com/sass/node-sass/blob/master/TROUBLESHOOTING.md#running-with-sudo-or-as-root

**Comment by antond1990** [comment]
... as sudo or as root. I ran the command as root.

**Comment by richardlau** [comment]
> 
> 
> ... as sudo or as root. I ran the command as root.

Yes, and the node-sass page I linked to suggests that if you really want to do that to use the `--unsafe-perm` flag for npm.

**Comment by PoojaDurgad** [comment]
@antond1990 - is this issue resolved?

**Comment by antond1990** [comment]
it works with `sudo`, yes

**Comment by PoojaDurgad** [comment]
resolved. closing!!
