### ISSUE TITLE
NPM install returning Segmentation fault on PPC64 architecture

### ISSUE THREAD

**Issue by narkhedek3** [nodejs/help#2900]
* **Node.js Version**:12.18.3 
* **OS**:CentOS 7 
* **Arch**:PPC64
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:npm [6.14.7]

Not able to create the new angular project because npm install returning segmentation fault(core dumped).

```properties
$ ng new my-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE my-app/README.md (1023 bytes)
CREATE my-app/.editorconfig (274 bytes)
CREATE my-app/.gitignore (631 bytes)
CREATE my-app/angular.json (3566 bytes)
CREATE my-app/package.json (1249 bytes)
CREATE my-app/tsconfig.base.json (458 bytes)
CREATE my-app/tsconfig.json (426 bytes)
CREATE my-app/tslint.json (3184 bytes)
CREATE my-app/.browserslistrc (853 bytes)
CREATE my-app/karma.conf.js (1018 bytes)
CREATE my-app/tsconfig.app.json (292 bytes)
CREATE my-app/tsconfig.spec.json (338 bytes)
CREATE my-app/src/favicon.ico (948 bytes)
CREATE my-app/src/index.html (291 bytes)
CREATE my-app/src/main.ts (372 bytes)
CREATE my-app/src/polyfills.ts (2835 bytes)
CREATE my-app/src/styles.css (80 bytes)
CREATE my-app/src/test.ts (753 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (662 bytes)
CREATE my-app/src/app/app-routing.module.ts (245 bytes)
CREATE my-app/src/app/app.module.ts (393 bytes)
CREATE my-app/src/app/app.component.css (0 bytes)
CREATE my-app/src/app/app.component.html (25757 bytes)
CREATE my-app/src/app/app.component.spec.ts (1059 bytes)
CREATE my-app/src/app/app.component.ts (210 bytes)
CREATE my-app/e2e/protractor.conf.js (869 bytes)
CREATE my-app/e2e/tsconfig.json (299 bytes)
CREATE my-app/e2e/src/app.e2e-spec.ts (639 bytes)
CREATE my-app/e2e/src/app.po.ts (301 bytes)
⠧ Installing packages...Segmentation fault (core dumped)
```

**Comment by bnoordhuis** [comment]
cc @nodejs/platform-aix (I know, it's not AIX but we don't have a PPC team.)

@narkhedek3 Would it be possible for you turn on core dumps (`ulimit -c unlimited`) and inspect the core dump with gdb afterwards?

`gdb $(which node) <corefile>` , then `bt` to get a stack trace and `disassemble` and `info registers` to get a disassembly of the segfaulting code.

**Comment by shellberg** [comment]
Based on the output of a [fairly recent Angular 'ng' issue](https://github.com/angular/angular-cli/issues/16876) (illustrative of the steps the _ng_ tool is trying to take), it looks like your problem might be experienced with the '_npm_' binary?

Can you see if your SIGSEGV is reproducible with something as simple as 'npm -v'?

**Comment by miladfarca** [comment]
Cannot reproduce the issue.

Compiled from source:
```
git clone https://github.com/nodejs/node.git
git checkout v12.18.3
```
Used binaries from the community:
```
wget https://nodejs.org/dist/v12.18.3/node-v12.18.3-linux-ppc64le.tar.gz
```
npm version is `6.14.6` in both methods.

Environment on docker:
```
# cat /etc/*release
CentOS Linux release 7.8.2003 (AltArch)
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"

# lscpu
Architecture:          ppc64le
```
Output:
```
# ng new my-app
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? CSS
CREATE my-app/README.md (1023 bytes)
CREATE my-app/.editorconfig (274 bytes)
CREATE my-app/.gitignore (631 bytes)
CREATE my-app/angular.json (3566 bytes)
CREATE my-app/package.json (1249 bytes)
CREATE my-app/tsconfig.base.json (458 bytes)
CREATE my-app/tsconfig.json (426 bytes)
CREATE my-app/tslint.json (3184 bytes)
CREATE my-app/.browserslistrc (853 bytes)
CREATE my-app/karma.conf.js (1018 bytes)
CREATE my-app/tsconfig.app.json (292 bytes)
CREATE my-app/tsconfig.spec.json (338 bytes)
CREATE my-app/src/favicon.ico (948 bytes)
CREATE my-app/src/index.html (291 bytes)
CREATE my-app/src/main.ts (372 bytes)
CREATE my-app/src/polyfills.ts (2835 bytes)
CREATE my-app/src/styles.css (80 bytes)
CREATE my-app/src/test.ts (753 bytes)
CREATE my-app/src/assets/.gitkeep (0 bytes)
CREATE my-app/src/environments/environment.prod.ts (51 bytes)
CREATE my-app/src/environments/environment.ts (662 bytes)
CREATE my-app/src/app/app-routing.module.ts (245 bytes)
CREATE my-app/src/app/app.module.ts (393 bytes)
CREATE my-app/src/app/app.component.css (0 bytes)
CREATE my-app/src/app/app.component.html (25757 bytes)
CREATE my-app/src/app/app.component.spec.ts (1059 bytes)
CREATE my-app/src/app/app.component.ts (210 bytes)
CREATE my-app/e2e/protractor.conf.js (869 bytes)
CREATE my-app/e2e/tsconfig.json (299 bytes)
CREATE my-app/e2e/src/app.e2e-spec.ts (639 bytes)
CREATE my-app/e2e/src/app.po.ts (301 bytes)
✔ Packages installed successfully.
```

This isn't a Big endian machine correct?

**Comment by narkhedek3** [comment]
Thank you for your responses,
When I am using following tar file it is giving error
https://nodejs.org/dist/latest-v12.x/node-v12.18.3-linux-ppc64le.tar.gz
But after installing using following tar file issue is resolved
https://nodejs.org/dist/latest-v12.x/node-v12.18.3.tar.gz

**Comment by miladfarca** [comment]
I also tried your first link within my Centos docker env and it's working fine.

Your second link is the src code, did you compile from src?

**Comment by narkhedek3** [comment]
@miladfarca 
> Your second link is the src code, did you compile from src?
Yes I have compiled src code

**Comment by miladfarca** [comment]
Could you please share your exact Centos version with `cat /etc/*release`.
Having the core dump data will also help a lot: https://github.com/nodejs/help/issues/2900#issuecomment-671268522

**Comment by narkhedek3** [comment]
@miladfarca

```
$ cat /etc/*release
CentOS Linux release 7.7.1908 (AltArch)
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7:server"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.7.1908 (AltArch)
CentOS Linux release 7.7.1908 (AltArch)
```

**Comment by miladfarca** [comment]
There are no PPC docker images for `Centos 7.7.1908` so I tried `7.6.1810` (as well as 7.8.2003) and they both work just fine.
We will need your stack trace to find the issue, using these instructions: https://github.com/nodejs/help/issues/2900#issuecomment-671268522

You might have a specific `libc` (or another dependent library) installed locally which is causing our binaries to crash.

**Comment by narkhedek3** [comment]
```
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000001064bbe4 in uv__hrtime (type=UV_CLOCK_FAST) at ../deps/uv/src/unix/linux-core.c:431
#2  uv__update_time (loop=0x11e49020 <default_loop_struct>) at ../deps/uv/src/unix/internal.h:311
#3  uv__io_poll (loop=0x11e49020 <default_loop_struct>, timeout=<optimized out>)
    at ../deps/uv/src/unix/linux-core.c:285
#4  0x00000000106347b4 in uv_run (loop=0x11e49020 <default_loop_struct>, mode=<optimized out>)
    at ../deps/uv/src/unix/core.c:370
#5  0x00000000105040c0 in node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) ()
#6  0x0000000010502d6c in node::Start(int, char**) ()
#7  0x0000000011273f7c in reorder(int, char**) ()
#8  0x00007ffff7a45280 in generic_start_main.isra.0 () from /lib64/libc.so.6
#9  0x00007ffff7a45474 in __libc_start_main () from /lib64/libc.so.6
#10 0x0000000000000000 in ?? ()
(gdb) info register
r0             0x1064bb18       275036952
r1             0x7fffffff9ae0   140737488329440
r2             0x11e34f00       300109568
r3             0x6      6
r4             0x7fffffffdb80   140737488345984
r5             0x0      0
r6             0xffffffffffffffff       18446744073709551615
r7             0x0      0
r8             0x2      2
r9             0x0      0
r10            0x0      0
r11            0x0      0
r12            0x0      0
r13            0x7ffff7ffd1d0   140737354125776
r14            0x11e49020       300191776
r15            0x0      0
r16            0x0      0
r17            0x0      0
r18            0x3dff6384e      16642357326
r19            0x3b9aca00       1000000000
r20            0x0      0
r21            0x11e315e0       300094944
r22            0xffffffffffffffff       18446744073709551615
r23            0x431bde82d7b634db       4835703278458516699
r24            0x7fffffff9b00   140737488329472
---Type <return> to continue, or q <return> to quit---
r25            0x7ffff7ff6210   140737354097168
r26            0x0      0
r27            0x1      1
r28            0xffffffffffffffff       18446744073709551615
r29            0x11e49250       300192336
r30            0x11dff970       299891056
r31            0x7fffffff9ae0   140737488329440
pc             0x0      0x0
msr            0x900000004000d033       10376293542535417907
cr             0x24002882       603990146
lr             0x1064bbe4       0x1064bbe4 <uv__io_poll+692>
ctr            0x0      0
xer            0x0      0
orig_r3        0x1042fa2c       272824876
trap           0x400    1024
```

**Comment by narkhedek3** [comment]
@miladfarca,
```
(gdb) bt
#0  0x000578e000020000 in ?? ()
#1  0x0000000010649154 in uv__hrtime (type=UV_CLOCK_FAST) at ../deps/uv/src/unix/linux-core.c:431
#2  uv__update_time (loop=0x11e4c310 <default_loop_struct>) at ../deps/uv/src/unix/internal.h:311
#3  uv__io_poll (loop=0x11e4c310 <default_loop_struct>, timeout=<optimized out>)
    at ../deps/uv/src/unix/linux-core.c:285
#4  0x0000000010631c74 in uv_run (loop=0x11e4c310 <default_loop_struct>, mode=<optimized out>)
    at ../deps/uv/src/unix/core.c:370
#5  0x00000000104ff8b0 in node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) ()
#6  0x00000000104fe50c in node::Start(int, char**) ()
#7  0x00000000104bb798 in main ()
(gdb) disassemble uv__hrtime
Dump of assembler code for function uv__hrtime:
   0x00000000106495b0 <+0>:     lis     r2,4581
   0x00000000106495b4 <+4>:     addi    r2,r2,-6248
   0x00000000106495b8 <+8>:     mflr    r0
   0x00000000106495bc <+12>:    std     r30,-16(r1)
   0x00000000106495c0 <+16>:    std     r31,-8(r1)
   0x00000000106495c4 <+20>:    cmpwi   cr7,r3,1
   0x00000000106495c8 <+24>:    std     r29,-24(r1)
   0x00000000106495cc <+28>:    ld      r30,-31960(r2)
   0x00000000106495d0 <+32>:    li      r3,1
   0x00000000106495d4 <+36>:    std     r0,16(r1)
   0x00000000106495d8 <+40>:    stdu    r1,-80(r1)
   0x00000000106495dc <+44>:    mr      r31,r1
   0x00000000106495e0 <+48>:    beq     cr7,0x10649640 <uv__hrtime+144>
   0x00000000106495e4 <+52>:    addi    r4,r31,32
   0x00000000106495e8 <+56>:    bl      0x10429e90 <0000022e.plt_call.clock_gettime@@GLIBC_2.17>
   0x00000000106495ec <+60>:    ld      r2,24(r1)
   0x00000000106495f0 <+64>:    li      r9,0
   0x00000000106495f4 <+68>:    cmpdi   cr7,r3,0
   0x00000000106495f8 <+72>:    bne     cr7,0x10649614 <uv__hrtime+100>
   0x00000000106495fc <+76>:    ld      r10,32(r31)
   0x0000000010649600 <+80>:    lis     r9,15258
   0x0000000010649604 <+84>:    ori     r9,r9,51712
   0x0000000010649608 <+88>:    mulld   r9,r9,r10
   0x000000001064960c <+92>:    ld      r10,40(r31)
---Type <return> to continue, or q <return> to quit---
   0x0000000010649610 <+96>:    add     r9,r9,r10
   0x0000000010649614 <+100>:   addi    r1,r31,80
   0x0000000010649618 <+104>:   mr      r3,r9
   0x000000001064961c <+108>:   ld      r0,16(r1)
   0x0000000010649620 <+112>:   ld      r29,-24(r1)
   0x0000000010649624 <+116>:   ld      r30,-16(r1)
   0x0000000010649628 <+120>:   ld      r31,-8(r1)
   0x000000001064962c <+124>:   mtlr    r0
   0x0000000010649630 <+128>:   blr
   0x0000000010649634 <+132>:   nop
   0x0000000010649638 <+136>:   nop
   0x000000001064963c <+140>:   ori     r2,r2,0
   0x0000000010649640 <+144>:   ld      r29,-32624(r30)
   0x0000000010649644 <+148>:   ld      r3,0(r29)
   0x0000000010649648 <+152>:   cmpdi   cr7,r3,-1
   0x000000001064964c <+156>:   extsw   r3,r3
   0x0000000010649650 <+160>:   bne     cr7,0x106495e4 <uv__hrtime+52>
   0x0000000010649654 <+164>:   li      r3,6
   0x0000000010649658 <+168>:   addi    r4,r31,32
   0x000000001064965c <+172>:   bl      0x10429200 <0000022e.plt_call.clock_getres@@GLIBC_2.17>
   0x0000000010649660 <+176>:   ld      r2,24(r1)
   0x0000000010649664 <+180>:   cmpdi   cr7,r3,0
   0x0000000010649668 <+184>:   bne     cr7,0x10649690 <uv__hrtime+224>
   0x000000001064966c <+188>:   ld      r10,40(r31)
   0x0000000010649670 <+192>:   lis     r9,15
---Type <return> to continue, or q <return> to quit---
   0x0000000010649674 <+196>:   ori     r9,r9,16960
   0x0000000010649678 <+200>:   cmpd    cr7,r10,r9
   0x000000001064967c <+204>:   bgt     cr7,0x10649690 <uv__hrtime+224>
   0x0000000010649680 <+208>:   li      r9,6
   0x0000000010649684 <+212>:   li      r3,6
   0x0000000010649688 <+216>:   std     r9,0(r29)
   0x000000001064968c <+220>:   b       0x106495e4 <uv__hrtime+52>
   0x0000000010649690 <+224>:   li      r9,1
   0x0000000010649694 <+228>:   li      r3,1
   0x0000000010649698 <+232>:   std     r9,0(r29)
   0x000000001064969c <+236>:   b       0x106495e4 <uv__hrtime+52>
   0x00000000106496a0 <+240>:   .long 0x0
   0x00000000106496a4 <+244>:   .long 0x1000000
   0x00000000106496a8 <+248>:   .long 0x380
End of assembler dump.
(gdb) info register
r0             0x10649088       275026056
r1             0x7fffffff9ab0   140737488329392
r2             0x11e4e798       300214168
r3             0x6      6
r4             0x7fffffff9af0   140737488329456
r5             0x0      0
r6             0xffffffffffffffff       18446744073709551615
r7             0x0      0
r8             0x2      2
r9             0x0      0
r10            0x0      0
r11            0x0      0
r12            0x578e000020000  1540278351691776
r13            0x7ffff7ffcc50   140737354124368
r14            0x11e4c310       300204816
r15            0x0      0
r16            0x0      0
r17            0x0      0
r18            0x3e4fac2a1      16726540961
r19            0x3b9aca00       1000000000
r20            0x0      0
r21            0x11df08b0       299829424
r22            0xffffffffffffffff       18446744073709551615
r23            0x431bde82d7b634db       4835703278458516699
r24            0x7fffffff9b80   140737488329600
---Type <return> to continue, or q <return> to quit---
r25            0x7ffff7ff5c90   140737354095760
r26            0x0      0
r27            0x1      1
r28            0xffffffffffffffff       18446744073709551615
r29            0x11e4c540       300205376
r30            0x11e192b0       299995824
r31            0x7fffffff9ab0   140737488329392
pc             0x578e000020000  0x578e000020000
msr            0x900000004000d033       10376293542535417907
cr             0x24002882       603990146
lr             0x10649154       0x10649154 <uv__io_poll+692>
ctr            0x578e000020000  1540278351691776
xer            0x0      0
orig_r3        0x1042920c       272798220
trap           0x400    1024
```

**Comment by narkhedek3** [comment]
@miladfarca, Sorry for the inconvenience caused. I have provided node-v8.17.0 backtrace by mistake.
Backtrace with node-v12.18.3 while creating the new angular app is as follows:

```
Reading symbols from /home/parade/node-v12.18.3-linux-ppc64le/bin/node...done.
[New LWP 137446]
[New LWP 137450]
[New LWP 137448]
[New LWP 137451]
[New LWP 137447]
[New LWP 137452]
[New LWP 137449]
Core was generated by `ng new my-app                                   '.
Program terminated with signal 11, Segmentation fault.
#0  0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000011275ad8 in uv__signal_handler (signum=17) at ../deps/uv/src/unix/signal.c:186
#2  <signal handler called>
#3  0x00007fffb29b8a28 in ?? ()
#4  0x00007fffb29b89f0 in ?? ()
#5  0x00000000112821b8 in uv__io_poll (loop=0x128b72b0 <default_loop_struct>, timeout=<optimized out>)
    at ../deps/uv/src/unix/linux-core.c:309
#6  0x00000000112685c0 in uv_run (loop=0x128b72b0 <default_loop_struct>, mode=<optimized out>)
    at ../deps/uv/src/unix/core.c:381
#7  0x000000001069e330 in node::NodeMainInstance::Run() ()
#8  0x000000001060f784 in node::Start(int, char**) ()
#9  0x000000001058a858 in main ()
(gdb) info register
r0             0x7fffb2dd04d8   140736194217176
r1             0x7fffed49f0d0   140737174434000
r2             0x128a4c00       311053312
r3             0x11     17
r4             0x7fffed49f318   140737174434584
r5             0x400    1024
r6             0xffffffffffffffff       18446744073709551615
r7             0x2      2
r8             0x0      0
r9             0x0      0
r10            0x0      0
r11            0x0      0
r12            0x0      0
r13            0x7fffb2e3ca40   140736194660928
r14            0x0      0
r15            0x0      0
r16            0x1      1
r17            0x30     48
r18            0x3b9aca00       1000000000
r19            0x3eedb5ef8      16892255992
r20            0xffffffffffffffff       18446744073709551615
r21            0x431bde82d7b634db       4835703278458516699
r22            0x7fffed4a02f0   140737174438640
r23            0x128b76e4       311129828
r24            0x128b7308       311128840
---Type <return> to continue, or q <return> to quit---
r25            0x11     17
r26            0xffffffffffffffff       18446744073709551615
r27            0x128b72b0       311128752
r28            0x128b72b0       311128752
r29            0x128b7308       311128840
r30            0x12887728       310933288
r31            0x7fffed49f0d0   140737174434000
pc             0x0      0x0
msr            0x900000004280f033       10376293542577369139
cr             0x54002888       1409296520
lr             0x11275ad8       0x11275ad8 <uv__signal_handler+72>
ctr            0x0      0
xer            0x0      0
orig_r3        0x10564144       274088260
trap           0x400    1024
(gdb)
```
>

**Comment by PoojaDurgad** [comment]
@narkhedek3 - is this still outstanding??

**Comment by PoojaDurgad** [comment]
inactive. closing. feel free to reopen the issue if its  still outstanding
