### ISSUE TITLE
Node not installing on fresh debian buster install in kvm

### ISSUE THREAD

**Issue by memetb** [nodejs/help#2903]
* **Version**: v14.7.0
* **Platform**: Linux debian 4.19.0-10-amd64 nodejs/node#1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
* **Subsystem**:

### What steps will reproduce the bug?

Installed a fresh new debian buster into virsh kvm using debian-10.5.0-amd64-netinst.iso. Host system is debian buster as well.

Ran:

     wget https://nodejs.org/dist/v14.7.0/node-v14.7.0-linux-x64.tar.xz
     mkdir /usr/local/lib/nodejs
     tar -xJvf node-v14.7.0-linux-x64.tar.xz -C /usr/local/lib/nodejs

as per installation instructions [here](https://github.com/nodejs/help/wiki/Installation)

Running:

      $node -v
      v14.7.0

      $nodejs -v
      v14.7.0

      $npm -v
      buffer.js:604
          slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

      RangeError: Index out of range
          at Object.slice (buffer.js:604:37)
          at Buffer.toString (buffer.js:801:14)
          at Object.readFileSync (fs.js:412:41)
          at Object.Module._extensions..js (internal/modules/cjs/loader.js:1276:22)
          at Module.load (internal/modules/cjs/loader.js:1105:32)
          at Function.Module._load (internal/modules/cjs/loader.js:967:14)
          at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
          at internal/main/run_main_module.js:17:47 {
        code: 'ERR_OUT_OF_RANGE'
      }

I can provide kvm creation script if necessary.

I've seen this bug referenced in [this](https://www.reddit.com/r/node/comments/evycez/npm_debian_buster_hell/) reddit thread with the implication that it might be relating to the kvm.

**Comment by memetb** [comment]
Quite honestly, I fail to see how this is a help related issue. The installation procedure is fairly straightforward and I am able to install  on a non-virtualized host without a problem.

There is a legitimate bug in the code base here.
