### ISSUE TITLE
TypeError: Cannot read property 'channel' of undefined

### ISSUE THREAD

**Issue by Krystian1218** [nodejs/help#2921]
Hi,
When I type the command "grafika" it shows me an error in console: 

**(node:11860) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'channel' of undefined
    at Object.run (C:\Users\Admin\Documents\GitHub\dzbanbot\src\commands\grafik.command.js:7:41)
    at Client.<anonymous> (C:\Users\Admin\Documents\GitHub\dzbanbot\src\handlers\command.handler.js:134:11)
    at Client.emit (events.js:315:20)
    at MessageCreateAction.handle (C:\Users\Admin\Documents\GitHub\dzbanbot\node_modules\discord.js\src\client\actions\MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\Admin\Documents\GitHub\dzbanbot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\Admin\Documents\GitHub\dzbanbot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)    at WebSocketShard.onPacket (C:\Users\Admin\Documents\GitHub\dzbanbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)        
    at WebSocketShard.onMessage (C:\Users\Admin\Documents\GitHub\dzbanbot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)       
    at WebSocket.onMessage (C:\Users\Admin\Documents\GitHub\dzbanbot\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
(node:11860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

`How can I fix it?`

**Comment by PoojaDurgad** [comment]
@Krystian1218 - I guess you can refer this , https://github.com/galnir/Master-Bot/issues/10 , https://github.com/google/grafika and make sure git configured properly.

**Comment by PoojaDurgad** [comment]
closing as answered. please let me know if that is not the case.
