### ISSUE TITLE
Error: Cannot find module './lib/js-yaml.js'

### ISSUE THREAD

**Issue by morange** [nodejs/help#2971]
Hey folks,

i tried to start foundation on my mac and became that error.

the error:
Error: Cannot find module './lib/js-yaml.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object. (/usr/local/lib/node_modules/foundation-cli/node_modules/js-yaml/index.js:4:12)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)

I'm using:
OS: macOS 10.15.6
node v10.18.0
npm 6.13.4

I tried this command: `npm uninstall -g foundation-cli && npm install -g foundation-cli` and became that error:
npm ERR! code EEXIST
npm ERR! path /usr/local/lib/node_modules/foundation-cli/node_modules/.bin/which
npm ERR! Refusing to delete /usr/local/lib/node_modules/foundation-cli/node_modules/.bin/which: ../which/bin/which symlink target is not controlled by npm /usr/local/lib/node_modules/foundation-cli/node_modules/which
npm ERR! File exists: /usr/local/lib/node_modules/foundation-cli/node_modules/.bin/which
npm ERR! Remove the existing file and try again, or run npm
npm ERR! with --force to overwrite files recklessly.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2020-09-09T13_49_50_952Z-debug.log

Who can give me a tip on how to eliminate the error?

Many thanks for your help
m.orange

**Comment by addaleax** [comment]
Would it be okay for you to run `sudo rm -rf /usr/local/lib/node_modules/foundation-cli && npm install -g foundation-cli`? It’s a bit more brutal, but it should get rid of any npm packages that you have installed that have become broken in some way (as far as `foundation-cli` is concerned, at least)

**Comment by morange** [comment]
Hi @addaleax,

many thanks for your fast help! That fixed the error nearly. I tried 'npm install' and 'npm rebuild node-sass --force'.

So it works now. Yeah
