### ISSUE TITLE
Unable to install npm packages that require node-gyp compile

### ISSUE THREAD

**Issue by wmmihaa** [nodejs/help#3005]
* **Node.js Version**: 14:13.0
* **OS**: Linux (Yocto, ARM7)
* **Scope (install, code, runtime, meta, other?)**: Installed via binary archive on Linux
```bash
$> node -v
v14.13.0
$> npm version
{
  npm: '6.14.8',
  ares: '1.16.1',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.2',
  modules: '83',
  napi: '7',
  nghttp2: '1.41.0',
  node: '14.13.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.40.0',
  v8: '8.4.371.19-node.16',
  zlib: '1.2.11'
}
$> npx -v
6.14.8

```

I have installed Node.js 14 using binary install as described [here](https://github.com/nodejs/help/wiki/Installation). Almost everything works as normal, except for when I want to install a package that require node-gyp such as `serialport`. I would greatly appreciate any hints of what is causing this... 

```bash
$: sudo npm i serialport
wlcore: down.......] \ extract:serialport: verb lock using /home/root/.npm/_locks/staging-7b48b93fac14577c.lock for /home/root/node_modules/.staging
wlcore: PHY firmware version: Rev 8.2.0.0.243rb lock using /home/root/.npm/_locks/staging-7b48b93fac14577c.lock for /home/root/node_modules/.staging
wlcore: firmware booted (Rev 8.9.0.0.83)n-comments: sill extract npmlog@4.1.2
IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready

> @serialport/bindings@9.0.1 install /home/root/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=14.13.0 runtime=node arch=arm libc= platform=linux)
Traceback (most recent call last):
  File "/usr/local/lib/nodejs/node-v14.13.0-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
    import gyp
  File "/usr/local/lib/nodejs/node-v14.13.0-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
    import gyp.input
  File "/usr/local/lib/nodejs/node-v14.13.0-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 9, in <module>
    import gyp.common
  File "/usr/local/lib/nodejs/node-v14.13.0-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/common.py", line 6, in <module>
    import filecmp
ImportError: No module named filecmp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/nodejs/node-v14.13.0-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.19.35+g0f9917c56d59
gyp ERR! command "/usr/local/lib/nodejs/node-v14.13.0-linux-armv7l/bin/node" "/usr/local/lib/nodejs/node-v14.13.0-linux-armv7l/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/root/node_modules/@serialport/bindings
gyp ERR! node -v v14.13.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @serialport/bindings@9.0.1 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @serialport/bindings@9.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/root/.npm/_logs/2020-10-05T13_57_12_334Z-debug.log

```

**Comment by celesteking** [comment]
you've got a broken python install

**Comment by gireeshpunathil** [comment]
@wmmihaa - is this outstanding?
