### ISSUE TITLE
Error: Cannot find module 'C:\Users\username\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js'

### ISSUE THREAD

**Issue by imshines** [nodejs/help#3006]
* **Version**: v12.18.4
* **Platform**: Windows 10 64-bit
* **Subsystem**: N/A

### What steps will reproduce the bug?

I have installed Nodejs 12.18.4 using NVM.
While running the npx command eg. npx create-react-app or npx.

### How often does it reproduce? Is there a required condition?

I have tried unistalled and tried reinstalling the Nodejs. But still it didn't work and repeats the same error

### What is the expected behavior?

It is supposed to create a new react app setup while using the command create-react-app.

### What do you see instead?

The command doesn't work and shows an error as mentioned in the title.

``` internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'C:\Users\shine\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

this is the output from the terminal.

### Additional information

As mentioned above I have installed Nodejs 12.18.4 via NVM for windows 64 bit. Kindly igonre this issue is this is wrong to raise here.
Here are some screenshots while running the command.

![image](https://user-images.githubusercontent.com/46491614/95190007-4bc7e580-07ec-11eb-8ac4-24db8bd59ba8.png)
![image](https://user-images.githubusercontent.com/46491614/95190054-5b472e80-07ec-11eb-8b0f-42d14c2e67ed.png)

**Comment by imshines** [comment]
Hey there,
Sorry for raising this issue.
If you encounter a similar issue like this just delete nvm, npm-cache, and related files in the following **directory**,
> **C:\Users\username\AppData\Roaming\ - nvm, npm, npm-cache**
And try installing Nodejs from nodejs.org or even try installing nvm then check again.

Hope this helps 🙂
