### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by StefanROM** [nodejs/help#3008]
SyntaxError: Unexpected token }
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:617:28)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Function.Module.runMain (module.js:694:10)
at startup (bootstrap_node.js:204:16)
at bootstrap_node.js:625:3

i get this when i try "nodejs driver.js" its a steam bot using ubuntu 14.04

**Comment by 0wx** [comment]
It just syntax error, that's mean something isn't properly writen, try install eslint in vs code for better debugging.

**Comment by PoojaDurgad** [comment]
closing as answered. please feel free to re-open the issue if its still outstanding.
