### ISSUE TITLE
ES6+ imports not working

### ISSUE THREAD

**Issue by VelrinBlack** [nodejs/help#3030]
* **Node.js Version**: 10.19.0
* **OS**: Ubuntu 20.04 (Linux)

Hello,
I want to use ES6+ module imports. I added `"type": "module"` to my `package.json`, but imports are still not working. I know, there's a way to do it with babel, but I'm following the Whatsapp clone build tutorial and the instructor is doing it like so.
One thing to mention is, when I import a package with `require()`, it works correctly. 

Here is my `package.json`:
```
{
  "name": "whatsapp-mern-backend",
  "version": "1.0.0",
  "description": "",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js"
  },
  "author": "Bartek Wleciał (Velrin Black)",
  "license": "ISC",
  "dependencies": {
    "express": "^4.17.1",
    "mongoose": "^5.10.7"
  }
}
```

And here is my `server.js`:
```
import express from 'express';

const app = express();
const port = process.env.PORT || 9000;

app.get('/', (req, res) => res.status(200).send('Hello World!'));

app.listen(port, () => console.log(`Listening on localhost:${port}`));
```

When I run `npm start` or `npm run start` I get this logs:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle whatsapp-mern-backend@1.0.0~prestart: whatsapp-mern-backend@1.0.0
6 info lifecycle whatsapp-mern-backend@1.0.0~start: whatsapp-mern-backend@1.0.0
7 verbose lifecycle whatsapp-mern-backend@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle whatsapp-mern-backend@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/velrinblack/Desktop/WebDev/Projects/whatsapp-mern/whatsapp-mern-backend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle whatsapp-mern-backend@1.0.0~start: CWD: /home/velrinblack/Desktop/WebDev/Projects/whatsapp-mern/whatsapp-mern-backend
10 silly lifecycle whatsapp-mern-backend@1.0.0~start: Args: [ '-c', 'node --experimental-modules server.js' ]
11 silly lifecycle whatsapp-mern-backend@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle whatsapp-mern-backend@1.0.0~start: Failed to exec start script
13 verbose stack Error: whatsapp-mern-backend@1.0.0 start: `node --experimental-modules server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid whatsapp-mern-backend@1.0.0
15 verbose cwd /home/velrinblack/Desktop/WebDev/Projects/whatsapp-mern/whatsapp-mern-backend
16 verbose Linux 5.4.0-51-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error whatsapp-mern-backend@1.0.0 start: `node --experimental-modules server.js`
22 error Exit status 1
23 error Failed at the whatsapp-mern-backend@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

_Thanks in advance_

**Comment by addaleax** [comment]
Your Node.js version is 10.19.0, but the “History” entry for https://nodejs.org/api/packages.html#packages_type says that this is only available on Node v12.x and upwards :)

**Comment by VelrinBlack** [comment]
@addaleax Thank you so much! Now it is working fine!
