### ISSUE TITLE
nodejs cannot work

### ISSUE THREAD

**Issue by alex-xf** [nodejs/help#3052]
Node.js Version: v12.19.0.  (>=11)
OS: centos 7.8 (CentOS-7-x86_64-GenericCloud-2003.qcow2)

[root@test3 ~]# node
Welcome to Node.js v12.19.0.
Type ".help" for more information.
> internal/main/repl.js:43
        throw err;
        ^

RangeError: Index out of range
    at Object.slice (buffer.js:604:37)
    at Buffer.toString (buffer.js:801:14)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:58:23)
    at FSReqCallback.callbackTrampoline (internal/async_hooks.js:126:14) {
  code: 'ERR_OUT_OF_RANGE'
}

[root@test3 ~]# npm
buffer.js:604
    slice: (buf, start, end) => buf.utf8Slice(start, end),
                                    ^

RangeError: Index out of range
    at Object.slice (buffer.js:604:37)
    at Buffer.toString (buffer.js:801:14)
    at Object.readFileSync (fs.js:408:41)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1034:22)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_OUT_OF_RANGE'
}

**Comment by PoojaDurgad** [comment]
@alex-xf -  you're not running the binary from https://nodejs.org/, unless you copied it over. for me this issue looks similar to https://github.com/nodejs/node/issues/34709 so you can refer this . and also refer https://linuxize.com/post/how-to-install-node-js-on-centos-7/ to install the node on you machine.

**Comment by alex-xf** [comment]
I modified the nova configuration to virt-type = kvm and recreated the virtual machine, which can be used normally.
@PoojaDurgad thanks for help.
