### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by longhung534-discord** [nodejs/help#3054]
internal/modules/cjs/loader.js:584
6:07 AM
    throw err;
6:07 AM
    ^
6:07 AM
6:07 AM
Error: Cannot find module 'm3u8stream/lib/parse-time'
6:07 AM
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
6:07 AM
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
6:07 AM
    at Module.require (internal/modules/cjs/loader.js:637:17)
6:07 AM
    at require (internal/modules/cjs/helpers.js:22:18)
6:07 AM
    at Object.<anonymous> (/rbd/pnpm-volume/f6cead61-ad20-4c21-a8d4-40dfa362d1f5/node_modules/.registry.npmjs.org/ytdl-core/0.29.7/node_modules/ytdl-core/lib/info-extras.js:5:21)
6:07 AM
    at Module._compile (internal/modules/cjs/loader.js:701:30)
6:07 AM
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
6:07 AM
    at Module.load (internal/modules/cjs/loader.js:600:32)
6:07 AM
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
6:07 AM
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by PoojaDurgad** [comment]
@longhung534-discord - can you elaborate your issue more please? which version of node.js you are using ?which  os you are using? what you are trying to run? by looking at the error I think packages needed installing: m3u8stream and parse-time .

**Comment by PoojaDurgad** [comment]
inactive. closing!! please feel free to reopen the issue if its still outstanding
