### ISSUE TITLE
Need to know how to fix this! It says TypeError: Cannot read property 'rmdir' of undefined

### ISSUE THREAD

**Issue by Epic99992** [nodejs/help#3065]
TypeError: Cannot read property 'writeFile' of undefined
    at Object.createProjectDetailsFile (C:\Users\gohid\AppData\Roaming\npm\node_modules\slappey\lib\filesystem.js:38:26)
    at Object.<anonymous> (C:\Users\gohid\AppData\Roaming\npm\node_modules\slappey\lib\scaffold.js:38:36)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\gohid\AppData\Roaming\npm\node_modules\slappey\lib\scaffold.js:5:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
TypeError: Cannot read property 'rmdir' of undefined

**Comment by RaisinTen** [comment]
What steps will reproduce the bug?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
