### ISSUE TITLE
Error: Cannot find module './project/menu'

### ISSUE THREAD

**Issue by petekal1323** [nodejs/help#3105]
* **Node.js Version**: v14.15.1
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

node server.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './project/menu'
Require stack:
- C:\Users\pkalinowski\Desktop\Decypher\AAA_EAT_njs\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\pkalinowski\Desktop\Decypher\AAA_EAT_njs\server.js:79:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\pkalinowski\\Desktop\\Decypher\\AAA_EAT_njs\\server.js'
  ]
}

i don't know what i'm missing here

**Comment by Lxxyx** [comment]
The error is usually caused by a non-existent file, so check the '. /project/menu.js' file exists.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
