### ISSUE TITLE
ERR_MODULE_NOT_FOUND for project-level module

### ISSUE THREAD

**Issue by thany** [nodejs/help#3163]
* **Node.js Version**: 14.15
* **OS**: Windows 10 20H2
* **Scope (install, code, runtime, meta, other?)**: code/runtime?
* **Module (and version) (if relevant)**: N/A

This is my project structure:
```
* project
    * modules
        * place-details.js
        * map-codes.js
    * index.js
    * package.json
    * package-lock.json
```

Then, in `index.js` is this:

```js
import placeDetails from './modules/place-details';
import mapCodes from './modules/map-codes';
```

The rest of the code is not relevant. Importing modules from node_modules like (using `import ... from`) this works a charm. VS Code can navigate through these modules perfectly fine. Infact, this is how VS Code automatically added the imports.

When I run the code:
```
D:\Projecten\maps-importer>node index.js
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Projecten\maps-importer\modules\place-details' imported from D:\Projecten\maps-importer\index.js
Did you mean to import ../modules/place-details.js?
←[90m    at finalizeResolution (internal/modules/esm/resolve.js:276:11)←[39m
←[90m    at moduleResolve (internal/modules/esm/resolve.js:699:10)←[39m
←[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)←[39m
←[90m    at Loader.resolve (internal/modules/esm/loader.js:86:40)←[39m
←[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)←[39m
←[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)←[39m
←[90m    at link (internal/modules/esm/module_job.js:55:36)←[39m {
  code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m
}
```

The suggestion obviously doesn't work, as it suggests the file is one level up. It is not.
I've also tried `./modules/place-details.js` (adding extension) and `modules/place-details` (removing the dot-slash) and a combination. None of those work (or I wouldn't have opened this issue 😀).

I'm also confused why Node.js doesn't say *where* it couldn't find said module, in other words, where it's been looking for it. Because it's right there. So I *really* don't know how else to tell Node.js where to go and grab this module. I've never had an error so confusing.

What am I missing here? I'm sure this is not a bug, seeing how mature Node.js already is.

**Comment by RaisinTen** [comment]
I think file extensions are needed here: https://nodejs.org/api/esm.html#esm_mandatory_file_extensions
and you need to export something named `'default'` if you want to `import` like that.

Here is the log of something that works for me:
```console
❯ tree .
.
├── index.js
├── modules
│   ├── map-codes.js
│   └── place-details.js
├── package.json
└── package-lock.json

1 directory, 5 files
❯ cat package.json
{
  "name": "project",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "type": "module",
  "keywords": [],
  "author": "",
  "license": "ISC"
}
❯ cat package-lock.json
{
  "name": "project",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "version": "1.0.0",
      "license": "ISC"
    }
  }
}
❯ cat index.js
import placeDetails from './modules/place-details.js';
import mapCodes from './modules/map-codes.js';

console.log(placeDetails);
console.log(mapCodes);
❯ cat modules/map-codes.js
export default 'map-codes';
❯ cat modules/place-details.js
export default 'place-details';
❯ node index.js
place-details
map-codes

```

Does this work for you?

**Comment by thany** [comment]
Interesting. I'll look into it tonight. I don't quite understand why I'm also getting errors when adding file existensions. Must be another problem then maybe.

Also, and this is not a Node.js question I realize, but do you happen to know why VS Code would automatically not add file extensions when letting it automatically add `import` directives, even if they are required?

**Comment by RaisinTen** [comment]
I'm sorry, I don't know that about VS Code. :/

**Comment by k3nnet** [comment]
add js extentions on the imports line resolved the isseu for me . thanks !

**Comment by OmgImAlexis** [comment]
I think I'm also hitting this same issue though it's a little weirder in the error.

```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/local/bin/unraid-api/dist/cli.js' imported from /root/
Did you mean to import /usr/local/bin/unraid-api/dist/cli.js?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:321:11)
    at moduleResolve (node:internal/modules/esm/resolve:756:10)
    at Loader.defaultResolve [as _resolve] (node:internal/modules/esm/resolve:867:11)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
    at Loader.getModuleJob (node:internal/modules/esm/loader:242:28)
    at Loader.import (node:internal/modules/esm/loader:177:28)
    at node:internal/modules/run_main:49:28
    at Object.loadESM (node:internal/process/esm_loader:68:11)
    at async handleMainPromise (node:internal/modules/run_main:63:12) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by naseemahmd** [comment]
install nodemon and in you package.json under script add this nodemon  --experimental-modules --es-module-specifier-resolution=node <your index.js file>.

**Comment by J-NAVEEN-KUMAR** [comment]
Adding the .js extension on the import lines resolves the issue. It is a weird error but I think we have to provide an extension so that nodejs can understand. 
Thanks

**Comment by OmgImAlexis** [comment]
@J-NAVEEN-KUMAR it shouldn't be needed as node checks a bunch of paths for the import including with the `.js` added.

**Comment by zurdozarazaga** [comment]
> Agregar la extensión .js en las líneas de importación resuelve el problema. Es un error extraño, pero creo que tenemos que proporcionar una extensión para que nodejs pueda entenderlo. Gracias

I don't understand why it will be but it worked for me

**Comment by Saumya15082001** [comment]
HEY! I'VE BEEN GETTING THIS ERROR FOR ABOUT A WEEK NOW AND I DON'T UNDERSTAND HOW TO SOLVE THIS. 
IF ANYONE HAS ANY IDEAS PLEASE LET ME KNOW!!


node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/D:/SemProject/prepbv/Backend/model/Schemas/Application' imported from D:\SemProject\prepbv\Backend\model\\ApplicationCrudModel.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:407:11)
    at moduleResolve (node:internal/modules/esm/resolve:981:10)
    at defaultResolve (node:internal/modules/esm/resolve:1078:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_MODULE_NOT_FOUND'

**Comment by bepro9** [comment]
add the .js after every import , you will get your errror resolved

**Comment by RaisinTen** [comment]
Judging by the feedback, https://github.com/nodejs/help/issues/3163#issuecomment-755261877 seems to be the right solution. I'm closing this as resolved for now but feel free to let me know if this still needs to stay open.

**Comment by musakazim989** [comment]
If you used "type": "module", on package.json and then you should use import. while you are using import it required default so in router or related required file you must use "export default serverRouter" 
Or can follow the below syntax:

import express from "express"
const serverRouter = express.Router()

serverRouter.get("/", (req, res) => {
  res.send("hello I'm runnig 4000")
})

export default serverRouter

**Comment by pavlovvv** [comment]
Add this to `tsconfig.json`

```
{
  "compilerOptions": {
  //...
  },
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node",
}
}
```

**Comment by almar7oom** [comment]
Hello, I have a problem with the package.json file, two days ago, and I have been suffering from the problem, and I did not find a solution to it. Can someone help and support you?

==> Build uploaded in 17s
Apr 21 03:05:46 AM  ==> Build successful 🎉
Apr 21 03:05:46 AM  ==> Deploying...
Apr 21 03:06:08 AM  ==> Starting service with 'yarn start'
Apr 21 03:06:11 AM  yarn run v1.22.5
Apr 21 03:06:12 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:06:12 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Apr 21 03:06:20 AM  ==> Starting service with 'yarn start'
Apr 21 03:06:24 AM  yarn run v1.22.5
Apr 21 03:06:25 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:06:25 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by almar7oom** [comment]
Hello, I have a problem with the package.json file, two days ago, and I have been suffering from the problem, and I did not find a solution to it. Can someone help and support you?

pr 21 03:02:16 AM  ==> Cloning from https://github.com/almar7oom/WhatsApp-bot-UAE...
Apr 21 03:02:16 AM  ==> Checking out commit 3de11b7e59d3e056da4d44ae90211a5c9b0f8fcc in branch main
Apr 21 03:02:19 AM  ==> Running build command 'yarn'...
Apr 21 03:02:20 AM  yarn install v1.22.5
Apr 21 03:02:20 AM  info No lockfile found.
Apr 21 03:02:20 AM  [1/4] Resolving packages...
Apr 21 03:02:20 AM  [2/4] Fetching packages...
Apr 21 03:02:20 AM  [3/4] Linking dependencies...
Apr 21 03:02:20 AM  [4/4] Building fresh packages...
Apr 21 03:02:20 AM  success Saved lockfile.
Apr 21 03:02:20 AM  Done in 0.03s.
Apr 21 03:02:20 AM  ==> Generating container image from build. This may take a few minutes...
Apr 21 03:05:17 AM  ==> Uploading build...
Apr 21 03:05:46 AM  ==> Build uploaded in 17s
Apr 21 03:05:46 AM  ==> Build successful 🎉
Apr 21 03:05:46 AM  ==> Deploying...
Apr 21 03:06:08 AM  ==> Starting service with 'yarn start'
Apr 21 03:06:11 AM  yarn run v1.22.5
Apr 21 03:06:12 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:06:12 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Apr 21 03:06:20 AM  ==> Starting service with 'yarn start'
Apr 21 03:06:24 AM  yarn run v1.22.5
Apr 21 03:06:25 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:06:25 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Apr 21 03:06:51 AM  ==> Starting service with 'yarn start'
Apr 21 03:06:54 AM  yarn run v1.22.5
Apr 21 03:06:54 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:06:54 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Apr 21 03:07:32 AM  ==> Starting service with 'yarn start'
Apr 21 03:07:35 AM  yarn run v1.22.5
Apr 21 03:07:36 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:07:36 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Apr 21 03:08:33 AM  ==> Starting service with 'yarn start'
Apr 21 03:08:37 AM  yarn run v1.22.5
Apr 21 03:08:37 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:08:37 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Apr 21 03:10:14 AM  ==> Starting service with 'yarn start'
Apr 21 03:10:17 AM  yarn run v1.22.5
Apr 21 03:10:18 AM  error Couldn't find a package.json file in "/opt/render/project/src"
Apr 21 03:10:18 AM  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by udaybagda** [comment]
Before :
import placeDetails from './modules/place-details';
import mapCodes from './modules/map-codes';

After :
import placeDetails from '../modules/place-details.js';
import mapCodes from '../modules/map-codes'.js;

Try this.
This is works 100%. 👍

**Comment by minhajzein** [comment]
Error: Cannot find module '/home/ubuntu/legnutz/node_modules/razorpay/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:438:19)
    at Module._findPath (node:internal/modules/cjs/loader:680:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/home/ubuntu/legnutz/controllers/cart-cnt.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/ubuntu/legnutz/node_modules/razorpay/package.json',
  requestPath: 'razorpay'
}

**Comment by nirbhay2001** [comment]
HEY! I'VE BEEN GETTING THIS ERROR FOR ABOUT A WEEK NOW AND I DON'T UNDERSTAND HOW TO SOLVE THIS.
IF ANYONE HAS ANY IDEAS PLEASE LET ME KNOW!!





node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\Nirbhay Gupta\Desktop\Web\web_Development_Project\16_Social_Media_App\server\controllers\authController' imported from C:\Users\Nirbhay Gupta\Desktop\Web\web_Development_Project\16_Social_Media_App\server\routes\auth.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.18.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by minhajzein** [comment]
Send me the code

**Comment by nirbhay2001** [comment]
This error has been resolved,recently

To give thanks response

**Comment by Shradhas123** [comment]
node:internal/modules/esm/resolve:265
[1]     throw new ERR_MODULE_NOT_FOUND(
[1]           ^
[1]
[1] Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Workplace\repository\research-portal\code\middleware\dist\app' imported from D:\Workplace\repository\research-portal\code\middleware\dist\index.js
[1]     at finalizeResolution (node:internal/modules/esm/resolve:265:11)
[1]     at moduleResolve (node:internal/modules/esm/resolve:933:10)
[1]     at defaultResolve (node:internal/modules/esm/resolve:1157:11)
[1]     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
[1]     at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
[1]     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
[1]     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
[1]     at link (node:internal/modules/esm/module_job:86:36) {
[1]   code: 'ERR_MODULE_NOT_FOUND',
[1]   url: 'file:///D:/Workplace/repository/research-portal/code/middleware/dist/app'
[1] }
[1]
[1] Node.js v20.12.2
[1] [nodemon] app crashed - waiting for file changes before starting...
[1] [nodemon] restarting due to changes...
[1] [nodemon] starting `node --experimental-modules --es-module-specifier-resolution=node dist/index.js`
[1] node:internal/modules/esm/resolve:265
[1]     throw new ERR_MODULE_NOT_FOUND(
[1]           ^
[1]
[1] Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Workplace\repository\research-portal\code\middleware\dist\app' imported from D:\Workplace\repository\research-portal\code\middleware\dist\index.js
[1]     at finalizeResolution (node:internal/modules/esm/resolve:265:11)
[1]     at moduleResolve (node:internal/modules/esm/resolve:933:10)
[1]     at defaultResolve (node:internal/modules/esm/resolve:1157:11)
[1]     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
[1]     at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
[1]     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
[1]     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
[1]     at link (node:internal/modules/esm/module_job:86:36) {
[1]   code: 'ERR_MODULE_NOT_FOUND',
[1]   url: 'file:///D:/Workplace/repository/research-portal/code/middleware/dist/app'
[1] }
[1]
[1] Node.js v20.12.2
[1] [nodemon] app crashed - waiting for file changes before starting...
[1] [nodemon] restarting due to changes...
[1] [nodemon] starting `node --experimental-modules --es-module-specifier-resolution=node dist/index.js`
[1] node:internal/modules/esm/resolve:265
[1]     throw new ERR_MODULE_NOT_FOUND(
[1]           ^
[1]
[1] Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Workplace\repository\research-portal\code\middleware\dist\app' imported from D:\Workplace\repository\research-portal\code\middleware\dist\index.js
[1]     at finalizeResolution (node:internal/modules/esm/resolve:265:11)
[1]     at moduleResolve (node:internal/modules/esm/resolve:933:10)
[1]     at defaultResolve (node:internal/modules/esm/resolve:1157:11)
[1]     at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:390:12)
[1]     at ModuleLoader.resolve (node:internal/modules/esm/loader:359:25)
[1]     at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:234:38)
[1]     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:87:39)
[1]     at link (node:internal/modules/esm/module_job:86:36) {
[1]   code: 'ERR_MODULE_NOT_FOUND',
[1]   url: 'file:///D:/Workplace/repository/research-portal/code/middleware/dist/app'
[1] }


I am using node V 20.12.1 but i am getting this error. Give me solutions.

**Comment by rebase-master** [comment]
> add the .js after every import , you will get your errror resolved

This worked for me. Thanks.

**Comment by Nimesh30** [comment]
> * **Node.js Version**: 14.15
> * **OS**: Windows 10 20H2
> * **Scope (install, code, runtime, meta, other?)**: code/runtime?
> * **Module (and version) (if relevant)**: N/A
> 
> This is my project structure:
> 
> ```
> * project
>     * modules
>         * place-details.js
>         * map-codes.js
>     * index.js
>     * package.json
>     * package-lock.json
> ```
> 
> Then, in `index.js` is this:
> 
> import placeDetails from './modules/place-details';
> import mapCodes from './modules/map-codes';
> The rest of the code is not relevant. Importing modules from node_modules like (using `import ... from`) this works a charm. VS Code can navigate through these modules perfectly fine. Infact, this is how VS Code automatically added the imports.
> 
> When I run the code:
> 
> ```
> D:\Projecten\maps-importer>node index.js
> internal/process/esm_loader.js:74
>     internalBinding('errors').triggerUncaughtException(
>                               ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Projecten\maps-importer\modules\place-details' imported from D:\Projecten\maps-importer\index.js
> Did you mean to import ../modules/place-details.js?
> ←[90m    at finalizeResolution (internal/modules/esm/resolve.js:276:11)←[39m
> ←[90m    at moduleResolve (internal/modules/esm/resolve.js:699:10)←[39m
> ←[90m    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:810:11)←[39m
> ←[90m    at Loader.resolve (internal/modules/esm/loader.js:86:40)←[39m
> ←[90m    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)←[39m
> ←[90m    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:56:40)←[39m
> ←[90m    at link (internal/modules/esm/module_job.js:55:36)←[39m {
>   code: ←[32m'ERR_MODULE_NOT_FOUND'←[39m
> }
> ```
> 
> The suggestion obviously doesn't work, as it suggests the file is one level up. It is not. I've also tried `./modules/place-details.js` (adding extension) and `modules/place-details` (removing the dot-slash) and a combination. None of those work (or I wouldn't have opened this issue 😀).
> 
> I'm also confused why Node.js doesn't say _where_ it couldn't find said module, in other words, where it's been looking for it. Because it's right there. So I _really_ don't know how else to tell Node.js where to go and grab this module. I've never had an error so confusing.
> 
> What am I missing here? I'm sure this is not a bug, seeing how mature Node.js already is.

Go to index.js file and comment unnecessary import statement
