### ISSUE TITLE
trouble when trying to run p5serial in command prompt.

### ISSUE THREAD

**Issue by adamace7** [nodejs/help#3231]
* **Node.js Version**: 14.5.5
* **OS**: Windows 10
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

//I am trying to run the command p5serial, but I am running into a issue where it cannot find the bindings in my directory. Please help me, this is for a school assignment for an arduino project. Below is the copy and pasted attempts from the beginning of my command prompt and when I try to run p5serial. Please, any help is appreciated. I am a beginner.

```js
// Microsoft Windows [Version 10.0.19041.804]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\Gears>npm install -g p5.serialserver
C:\Users\Gears\AppData\Roaming\npm\p5serial -> C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\startserver.js
+ p5.serialserver@0.0.29
updated 1 package in 13.934s

C:\Users\Gears>p5serial
C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\bindings\bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\build\bindings.node → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\build\Debug\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\build\Release\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\out\Debug\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\Debug\bindings.node → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\out\Release\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\Release\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\build\default\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\compiled\14.15.5\win32\x64\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\addon-build\release\install-root\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\addon-build\debug\install-root\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\addon-build\default\install-root\bindings.node
 → C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\lib\binding\node-v83-win32-x64\bindings.node
    at bindings (C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\bindings\bindings.js:126:9)
    at Object.<anonymous> (C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\lib\win32.js:1:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Gears\AppData\Roaming\npm\node_modules\p5.serialserver\node_modules\@serialport\bindings\lib\index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\build\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\build\\Debug\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\build\\Release\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\out\\Debug\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\Debug\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\out\\Release\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\Release\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\build\\default\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\compiled\\14.15.5\\win32\\x64\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\addon-build\\release\\install-root\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\addon-build\\debug\\install-root\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\addon-build\\default\\install-root\\bindings.node',
'C:\\Users\\Gears\\AppData\\Roaming\\npm\\node_modules\\p5.serialserver\\node_modules\\@serialport\\bindings\\lib\\binding\\node-v83-win32-x64\\bindings.node'
  ]
}
```
-->

**Comment by marsonya** [comment]
This seems like an issue with the `p5.serialserver` npm package. I would recommend posting the issue on it's [github repo](https://github.com/p5-serial/p5.serialport).
The repo does seem inactive since the last changes were over a year ago. 

Incase you don't get any response there, I would suggest looking for an alternative to `p5.serialserver`.

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
