### ISSUE TITLE
Node Wizard doesn't install dependencies

### ISSUE THREAD

**Issue by fourglobe302500** [nodejs/help#3245]
* **Node.js Version**: < 14.16.0
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**:

I was trying to update node version from 14.15.1 to 15.10.0 and the automatic installer did not install python (apparently since keeped trhowng this error when trying to use npm)

```
npm ERR! code 1
npm ERR! path C:\Francisco\programas\F#\Fable-Learn\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Francisco\programas\F#\Fable-Learn\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Francisco\\programas\\F#\\Fable-Learn\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@14.16.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at E (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21)
npm ERR! gyp verb `which` failed  python Error: not found: python
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Francisco\programas\F#\Fable-Learn\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:183:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb could not find "python". checking python launcher
npm ERR! gyp verb could not find "python". guessing location
npm ERR! gyp verb ensuring that file exists: C:\Python27\python.exe
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
npm ERR! gyp ERR! stack     at PythonFinder.failNoPython (C:\Francisco\programas\F#\Fable-Learn\node_modules\node-gyp\lib\configure.js:484:19)
npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (C:\Francisco\programas\F#\Fable-Learn\node_modules\node-gyp\lib\configure.js:509:16)
npm ERR! gyp ERR! stack     at callback (C:\Francisco\programas\F#\Fable-Learn\node_modules\graceful-fs\polyfills.js:295:20)
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:183:21)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Francisco\\programas\\F#\\Fable-Learn\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Francisco\programas\F#\Fable-Learn\node_modules\node-sass
npm ERR! gyp ERR! node -v v14.16.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1
```

so I tried using the LTS version but keeped trhowing the same error. if anyone can help me I would be grateful

-->

**Comment by mollthecoder** [comment]
Uninstall any traces of python and try installing Python2 from the official website. Does this help?

**Comment by marsonya** [comment]
Hey @fourglobe302500, is this issue resolved?

**Comment by fourglobe302500** [comment]
Yes, it's.

**Comment by marsonya** [comment]
> Yes, it's.

Awesome. I am going ahead and closing this issue.
