### ISSUE TITLE
How to open exist tty using net.Socket ?

### ISSUE THREAD

**Issue by oppai** [nodejs/help#3264]
Hi, there

I want to open *exist* tty using net.Socket. But I got an error like a below.

I have two questions.
First, how can I open tty using [net.Socket module](https://nodejs.org/api/net.html#net_class_net_socket) ?
Second, I success to open tty using [tty.ReadStream](https://nodejs.org/api/tty.html#tty_class_tty_readstream) like a [them](https://github.com/nodejs/node/issues/28590). But I didn't find it in document. It is trial function? (It is not safe to use in production?)

thank you

* **Node.js Version**: v14.16.0
* **OS**: MacOS / Linux
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: net.Socket

```js
var fs = require('fs')
var net = require('net')

const fd = fs.openSync('/dev/ttys003', 'r+');
const tty = new net.Socket({fd, readable: true})
tty.on('data', (data) => {
  console.log(data)
})
```

```log
TypeError [ERR_INVALID_FD_TYPE]: Unsupported fd type: TTY
    at createHandle (net.js:147:9)
    at new Socket (net.js:328:22)
    at Object.<anonymous> (/Users/hiroaki.murayama/progate/progate_ide/v2/src/runtime/sample.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_FD_TYPE'
```

**Comment by RaisinTen** [comment]
I don't think opening a socket to a TTY fd is supported yet.
At the bottom of https://nodejs.org/api/net.html#net_class_net_socket:
> The newly created socket can be either a TCP socket or a streaming IPC endpoint, depending on what it connect() to.

**Comment by addaleax** [comment]
@RaisinTen No, it is supported. I think this might also qualify as a bug in the net module.

In any case, one can use `tty.ReadStream(fd)` and `tty.WriteStream(fd)` to create TTY streams (which should be one class but for some reason isn’t), and both of these inherit from `net.Socket`.

**Comment by RaisinTen** [comment]
@addaleax The passed fd type gets rejected here: https://github.com/nodejs/node/blob/3bba40abc636ff50b03930cb510f7d1082272563/lib/net.js#L140-L156. So, this can be fixed by adding an option to accept TTY fds. Should we move this issue to the main repo?

**Comment by addaleax** [comment]
Yeah, although I think there might also be another issue somewhere for merging the two TTY classes? I think that would be the best solution here.

**Comment by oppai** [comment]
Thank you, @addaleax and @RaisinTen !
I understand that net.Socket is not supported for tty fd, and I should use tty module instead of net.Socket.

So, there is no document about accepting fd in tty modules. 
https://nodejs.org/api/tty.html#tty_class_tty_readstream

it is missing? or experimental function?

**Comment by addaleax** [comment]
I don’t know why the constructors are not documented, but they should be, yes.
