### ISSUE TITLE
I'm getting this error when I type node . to make my Discord Bot online.

### ISSUE THREAD

**Issue by ItzGalactic** [nodejs/help#3309]
Hi, 

I am getting this error when I type node . to make my Discord Bot online plz help

C:\Users\Tanma\Desktop\LegendBot>node .
C:\Users\Tanma\Desktop\LegendBot\main.js:1
const Discord require('discord.js');
      ^^^^^^^

SyntaxError: Missing initializer in const declaration
←[90m    at wrapSafe (internal/modules/cjs/loader.js:979:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1027:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m

What should I do to fix this error?

Getting this error from the past 2 days

I have tried 
- Restarting my computer
- Restarting Command Prompt
- Tried in Powershell
- Uninstalling node,js and re-installing
- Installing Additional Tools for Node.JS

Nothing helps

**Comment by marsonya** [comment]
> (node:10216) UnhandledPromiseRejectionWarning: TypeError: console.login is not a function

replace `console.login` with `console.log`.
`log` method is used to print data into the console/terminal.

**Comment by youtubetanmayyt** [comment]
ok let me see

**Comment by marsonya** [comment]
> ok let me see

did it work?

**Comment by marsonya** [comment]
I hope the answer was helpful. This issue has been open for a long time now so I am going ahead and closing it. Feel free to reopen if necessary.

**Comment by FastCglass2** [comment]
@marsonya could you please help me with this error I've been getting with my bot?

        throw new Error(WSCodes[error.code]);
              ^

Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (C:\Users\fastc\Desktop\FastBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:250:15)
    at async Client.login (C:\Users\fastc\Desktop\FastBot\node_modules\discord.js\src\client\Client.js:254:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}

**Comment by FastCglass2** [comment]
nvm i fixed it, sorry to bother you.

**Comment by FastCglass2** [comment]
wtf now im getting this error

PS C:\Users\fastc\Desktop\FastBot> node .
FastBot is online!
(node:7400) DeprecationWarning: The message event is deprecated. Use messageCreate instead
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\fastc\Desktop\FastBot\commands\reactionrole.js:12
        let embed = new Discord.MessageEmbed()
                    ^

ReferenceError: Discord is not defined
    at Object.execute (C:\Users\fastc\Desktop\FastBot\commands\reactionrole.js:12:21)
    at Client.<anonymous> (C:\Users\fastc\Desktop\FastBot\main.js:39:45)
    at Client.emit (node:events:526:28)
    at MessageCreateAction.handle (C:\Users\fastc\Desktop\FastBot\node_modules\discord.js\src\client\actions\MessageCreate.js:34:18)
    at Object.module.exports [as MESSAGE_CREATE] (C:\Users\fastc\Desktop\FastBot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\fastc\Desktop\FastBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:351:31)
    at WebSocketShard.onPacket (C:\Users\fastc\Desktop\FastBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:444:22)
    at WebSocketShard.onMessage (C:\Users\fastc\Desktop\FastBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:301:10)
    at WebSocket.onMessage (C:\Users\fastc\Desktop\FastBot\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:526:28)
