### ISSUE TITLE
unable to lint codebase

### ISSUE THREAD

**Issue by Ayase-252** [nodejs/help#3327]
* **Node.js Version**: v16.0.0-pre
* **OS**:  MacOS
* **Scope (install, code, runtime, meta, other?)**: lint

I'm working with Node.js project. **Sometimes**, when I run `make lint`, it pops some internal errors about linter.

```
➜  make lint     
Running JS linter...

Oops! Something went wrong! :(

ESLint: 7.24.0

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys (/Users/qingyudeng/projects/node/tools/node_modules/eslint/node_modules/flat-cache/src/cache.js:52:19)
    at removeNotFoundFiles (/Users/qingyudeng/projects/node/tools/node_modules/eslint/node_modules/file-entry-cache/cache.js:18:35)
    at Object.create (/Users/qingyudeng/projects/node/tools/node_modules/eslint/node_modules/file-entry-cache/cache.js:31:5)
    at new LintResultCache (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/cli-engine/lint-result-cache.js:88:46)
    at new CLIEngine (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/cli-engine/cli-engine.js:592:29)
    at new ESLint (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/eslint/eslint.js:432:27)
    at Object.execute (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/cli.js:290:24)
    at main (/Users/qingyudeng/projects/node/tools/node_modules/eslint/bin/eslint.js:142:52)
    at Object.<anonymous> (/Users/qingyudeng/projects/node/tools/node_modules/eslint/bin/eslint.js:146:2)
make[1]: *** [lint-js] Error 2
make[1]: Nothing to be done for `lint-cpp'.
make[1]: Nothing to be done for `lint-addon-docs'.
Running JS linter...

Oops! Something went wrong! :(

ESLint: 7.24.0

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.keys (/Users/qingyudeng/projects/node/tools/node_modules/eslint/node_modules/flat-cache/src/cache.js:52:19)
    at removeNotFoundFiles (/Users/qingyudeng/projects/node/tools/node_modules/eslint/node_modules/file-entry-cache/cache.js:18:35)
    at Object.create (/Users/qingyudeng/projects/node/tools/node_modules/eslint/node_modules/file-entry-cache/cache.js:31:5)
    at new LintResultCache (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/cli-engine/lint-result-cache.js:88:46)
    at new CLIEngine (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/cli-engine/cli-engine.js:592:29)
    at new ESLint (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/eslint/eslint.js:432:27)
    at Object.execute (/Users/qingyudeng/projects/node/tools/node_modules/eslint/lib/cli.js:290:24)
    at main (/Users/qingyudeng/projects/node/tools/node_modules/eslint/bin/eslint.js:142:52)
    at Object.<anonymous> (/Users/qingyudeng/projects/node/tools/node_modules/eslint/bin/eslint.js:146:2)
make[1]: *** [lint-js-doc] Error 2
make: *** [lint] Error 2
```

I have tried run `make -j4` and `make test-only` before running `make lint` per [test guide](https://github.com/nodejs/node/blob/master/BUILDING.md#running-tests). 

I'm not sure how to reproduce it. May it is related to branch switching between `master` and `feature` of mine? What should I do to fix linter error?

**Comment by richardlau** [comment]
Trying deleting your `.eslintcache` file.

**Comment by Ayase-252** [comment]
Thanks for quick answer. It works well.
