### ISSUE TITLE
TypeError: localModule.interact is not a function

### ISSUE THREAD

**Issue by LightnerDev** [nodejs/help#3338]
* **Node.js Version**: v14.16.1
* **OS**: ChromeOS
* **Scope (install, code, runtime, meta, other?)**: idk ig code and runtime?
* **Module (and version) (if relevant)**:

I am receiving error.

```js
//test.js
const localModule = require('./src/index.js')

localModule.interact()
```

```js
//src/index.js
function interact() {
    console.timeLog()
    console.log(':)')
}
```

Here is full eror:
```txt
localModule.interact()
            ^

TypeError: localModule.interact is not a function
    at Object.<anonymous> (/home/lightnerdev/NPM_Packages/devs-hub-api/test.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by addaleax** [comment]
What happens if you use `exports.interact = function() {` instead of `function interact() {`?

**Comment by LightnerDev** [comment]
Tysm
