### ISSUE TITLE
OverwriteModelError: Cannot overwrite `posts` model once compiled.

### ISSUE THREAD

**Issue by vishnu-mevada** [nodejs/help#3346]
E:\Angular\nodejs course>nodemon
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node src/index.ts`

E:\Angular\nodejs course\node_modules\mongoose\lib\index.js:548
      throw new _mongoose.Error.OverwriteModelError(name);
            ^
![mongoose overwrite](https://user-images.githubusercontent.com/71388551/116773193-a4edb400-aa71-11eb-9b5c-1d0ebb07d374.jpg)
    at Mongoose.model (E:\Angular\nodejs course\node_modules\mongoose\lib\index.js:548:13)
    at Object.<anonymous> (E:\Angular\nodejs course\src\models\Post.ts:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (C:\Users\Dell\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Dell\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (E:\Angular\nodejs course\src\validators\CommentValidators.ts:2:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Module.m._compile (C:\Users\Dell\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\Dell\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:988:32)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by Ayase-252** [comment]
https://stackoverflow.com/questions/19051041/cannot-overwrite-model-once-compiled-mongoose.

This post could help. Problematic code seems in `E:\Angular\nodejs course\src\models\Post.ts:12:16`

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
