### ISSUE TITLE
CMD prompt Error message for running node Tello.js 

### ISSUE THREAD

**Issue by kvan64** [nodejs/help#3347]
* **Node.js 14.16.1 LTS**:
* **OS: Windows**:
CMD prompt Error message for running node Tello.js 

C:\>node Tello.js
---------------------------------------
Tello Scratch Ext running at http://127.0.0.1:8001/
---------------------------------------
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:668:15)
    at ServerResponse.end (_http_outgoing.js:789:7)
    at Server.<anonymous> (C:\Tello.js:151:11)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:727:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

C:\>
Please help.

**Comment by Ayase-252** [comment]
Could you share what code you are going to run if possible?

**Comment by kvan64** [comment]
Just basic Scratch blockcodes for flying Tello drone.

Thanks for helping.

DK

 
 

Sent: Saturday, May 01, 2021 at 8:22 PM

**Comment by shoio** [comment]
I've got the same problem. How did you resolve @kvan64 ?

**Comment by RedYetiDev** [comment]
Hi! Without the code sample, we can't reproduce the issue, so it's hard to find a solution.
