### ISSUE TITLE
(node:9494) UnhandledPromiseRejectionWarning: 操作系统识别失败

### ISSUE THREAD

**Issue by developer-zsg** [nodejs/help#3418]
* **Version**: v14.17.0
* **Platform**: Darwin xxx.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
* **Subsystem**: npm start

### What steps will reproduce the bug?

when I upgrade my MBP 11.4 （MacOS Big Sur）after, happened the problem.
### What do you see instead?
```console
$ npm start
(node:9494) UnhandledPromiseRejectionWarning: 操作系统识别失败
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9494) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9494) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Additional information
```console
$ node --trace-warnings ... 
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '/Users/xxx/Documents/workspace/git/web/demo/demo/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by Ayase-252** [comment]
Could you please provide the code you are running?

**Comment by developer-zsg** [comment]
Thx! I had resolved.
