### ISSUE TITLE
internal/modules/cjs/loader.js:905 -> throw err;

### ISSUE THREAD

**Issue by Searge** [nodejs/help#3458]
* **Node.js Version**: v14.17.3
* **OS**:  Fedora 34 (Workstation Edition) x86_64 
* **Scope (install, code, runtime, meta, other?)**:  `node init`

Just tried to initialize node at local directory

```sh
❯ node init
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '/home/searge/Dev/Learn/GoIT/Webpack/init'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

❯ nvm list
->     v14.17.3
default -> lts/* (-> v14.17.3)

❯ npm -v
7.19.1
```

First, I have installed `n` version manager with same problem, so I've installed `nvm`, but error the same.

**Comment by Searge** [comment]
Please, close it, or delete. There was supposed to be `npm init` //_-
