### ISSUE TITLE
When I use Nodemon, and after change something in js file it give me an error and rs also not working

### ISSUE THREAD

**Issue by HARSH419** [nodejs/help#3470]
### Version

node v14.17.2
nodemon v2.0.12 ---global install

### Platform

[nodemon] restarting due to changes... (node:15260) UnhandledPromiseRejectionWarning: Error: Command failed: wmic process where (ParentProcessId=11920) get ProcessId 2> nul     at checkExecSyncError (child_process.js:643:11)     at execSync (child_process.js:679:15)     at kill (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:345:26)     at Function.run.kill (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:437:7)     at Bus.<anonymous> (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:507:7)     at Bus.emit (events.js:387:35)     at restartBus (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:228:7)     at FSWatcher.filterAndRestart (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:212:16)     at FSWatcher.emit (events.js:375:28)     at FSWatcher.emitWithAll (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\node_modules\chokidar\index.js:540:8) (Use `node --trace-warnings ...` to show where the warning was created) (node:15260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

### What steps will reproduce the bug?

PS C:\Users\Harsh .LAPTOP-QCSDR81D\Downloads\web dev\CSS WORK\My work\tut67Creating a Custom Backend> nodemon -v 
2.0.12
PS C:\Users\Harsh .LAPTOP-QCSDR81D\Downloads\web dev\CSS WORK\My work\tut67Creating a Custom Backend> nodemon index
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
Server running at http://127.0.0.1:3000/home
[nodemon] restarting due to changes...
(node:15260) UnhandledPromiseRejectionWarning: Error: Command failed: wmic process where (ParentProcessId=11920) get ProcessId 2> nul
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at kill (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:345:26)
    at Function.run.kill (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:437:7)
    at Bus.<anonymous> (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:507:7)
    at Bus.emit (events.js:387:35)
    at restartBus (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:228:7)
    at FSWatcher.filterAndRestart (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (events.js:375:28)
    at FSWatcher.emitWithAll (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\node_modules\chokidar\index.js:540:8)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15260) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[nodemon] restarting due to changes...
(node:15260) UnhandledPromiseRejectionWarning: Error: Command failed: wmic process where (ParentProcessId=11920) get ProcessId 2> nul
    at checkExecSyncError (child_process.js:643:11)
    at execSync (child_process.js:679:15)
    at kill (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:345:26)
    at Function.run.kill (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:437:7)
    at Bus.<anonymous> (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\run.js:507:7)
    at Bus.emit (events.js:387:35)
    at FSWatcher.filterAndRestart (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\lib\monitor\watch.js:212:16)
    at FSWatcher.emit (events.js:375:28)
    at FSWatcher.emitWithAll (C:\Users\Harsh .LAPTOP-QCSDR81D\AppData\Roaming\npm\node_modules\nodemon\node_modules\chokidar\index.js:540:8)
(node:15260) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise whise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#clidled_r_unhandled_rejections_mode). (rejection id: 2)

**Comment by HARSH419** [comment]
which work in nodemon@2.0.7 but after I update toward nodemon@2.0.8 it gives me that error

**Comment by VoltrexMaster** [comment]
Even if this is a bug, I recommend either looking at the issues tab or opening your issue at [nodemon's github repository](https://github.com/remy/nodemon) as this is not directly caused by Node.js, hopefully you'll find a solution there.

**Comment by HARSH419** [comment]
> Even if this is a bug, I recommend either looking at the issues tab or opening your issue at [nodemon's github repository](https://github.com/remy/nodemon) as this is not directly caused by Node.js, hopefully you'll find a solution there.

Nodemon works well not give an error when I use version 2.0.7, but when I update it gives me the above error.
