### ISSUE TITLE
I get the following error when trying to lift on heroku

### ISSUE THREAD

**Issue by kevinjuanjacque** [nodejs/help#3491]
* **v14.17.3**:
* **BigSur**:
* **npm start**:
* **heroku**:

I get the following error when trying to lift on heroku

```js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module '../database/connect'
Require stack:
- /app/dist/models/server.js
- /app/dist/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/app/dist/models/server.js:16:35)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
```
package.json

```js

{
  "name": "backend",
  "version": "1.0.0",
  "description": "",
  "main": "dist/app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node dist/app.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/bcrypt": "^5.0.0",
    "@types/cors": "^2.8.10",
    "@types/express": "^4.17.11",
    "@types/jsonwebtoken": "^8.5.1",
    "@types/morgan": "^1.9.2",
    "nodemon": "^2.0.7",
    "tslint": "^6.1.3"
  },
  "dependencies": {
    "bcrypt": "^5.0.1",
    "cors": "^2.8.5",
    "dotenv": "^10.0.0",
    "express": "^4.17.1",
    "express-validator": "^6.11.1",
    "fs": "0.0.1-security",
    "jsonwebtoken": "^8.5.1",
    "morgan": "^1.10.0",
    "path": "^0.12.7",
    "pg": "^8.6.0",
    "pg-hstore": "^2.3.3",
    "sequelize": "^6.6.2",
    "typescript": "^4.2.4",
    "nodemon": "^2.0.7"
  }
}


```
 in database/connect.js

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const sequelize_1 = require("sequelize");
const db = new sequelize_1.Sequelize("x", "x", "x", {
    host: "x",
    port: 5432,
    dialect: "postgres",
    logging: false,
    ssl: true,
    dialectOptions: {
        ssl: {
            require: true,
            rejectUnauthorized: false
        }
    }
});
exports.default = db;
```

**Comment by Ayase-252** [comment]
Could you show the file structure of `dist` folder?

**Comment by gireeshpunathil** [comment]
closing as inactive, pls reopen if this is outstanding, and when you can provide details.
