### ISSUE TITLE
failing to deploy - TypeError cannot read property of '_events' of undefined

### ISSUE THREAD

**Issue by twigs67** [nodejs/help#3520]
### Version

14.4.0

### Platform

linux

### What steps will reproduce the bug?

Hello,

Apologies if this isn't the correct place for this, but I'm completely lost as to why I'm getting this error. events=target._events does not exist anywhere in my codebase, so i'm guessing it is due to a node_module, but I can't find the culprit.

```
What's worse is I can't reproduce this locally, it just fails when deploying to our dev environment.

2021-08-29T14:26:05.489-04:00	Running Node Cluster

2021-08-29T14:26:05.489-04:00	Master server started on 1

2021-08-29T14:26:05.529-04:00	events.js:350

2021-08-29T14:26:05.530-04:00	events = target._events;

2021-08-29T14:26:05.530-04:00	^

2021-08-29T14:26:05.530-04:00	TypeError: Cannot read property '_events' of undefined

2021-08-29T14:26:05.530-04:00	at _addListener (events.js:350:19)

2021-08-29T14:26:05.530-04:00	at addListener (events.js:406:10)

2021-08-29T14:26:05.530-04:00	at Function.clusterize (/usr/src/app/dist/src/core/node-cluster.js:40:30)

2021-08-29T14:26:05.530-04:00	at Object.<anonymous> (/usr/src/app/dist/src/main.js:121:38)

2021-08-29T14:26:05.530-04:00	at Module._compile (internal/modules/cjs/loader.js:1200:30)

2021-08-29T14:26:05.530-04:00	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)

2021-08-29T14:26:05.530-04:00	at Module.load (internal/modules/cjs/loader.js:1049:32)

2021-08-29T14:26:05.530-04:00	at Function.Module._load (internal/modules/cjs/loader.js:937:14)

2021-08-29T14:26:05.530-04:00	at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

2021-08-29T14:26:05.530-04:00	at internal/main/run_main_module.js:17:47
package.json

Cluster server started on 56
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/child.js:193:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:46:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:337:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:839:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:835:20)
    at process.target.send (internal/child_process.js:706:19)
    at sendHelper (internal/cluster/utils.js:26:15)
    at send (internal/cluster/child.js:193:10)
    at EventEmitter.cluster._setupWorker (internal/cluster/child.js:46:3)
    at initializeClusterIPC (internal/bootstrap/pre_execution.js:337:13)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:62:3)
    at internal/main/run_main_module.js:7:1
Emitted 'error' event on Worker instance at:
    at process.<anonymous> (internal/cluster/worker.js:29:12)
    at process.emit (events.js:315:20)
    at internal/child_process.js:839:39
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

Any help would be greatly appreciated.

**Comment by twigs67** [comment]
Wait @Mesteery @aduh95 can we reopen this? I mistakenly opened that duplicat.

**Comment by Mesteery** [comment]
It's already open. By the way, could you share this line `/usr/src/app/dist/src/core/node-cluster.js:40` so we can more easily help you?

**Comment by twigs67** [comment]
@Mesteery 
```
let AppClusterService = class AppClusterService {                                                                                                                                                                                       
    static clusterize(callback) {                                                                                                                                                                                                       
        if (cluster_1.isMaster) {                                                                                                                                                                                                       
            console.log(`Master server started on ${process.pid}`);                                                                                                                                                                     
            for (let i = 0; i < numCPUs; i++) {                                                                                                                                                                                         
                (0, cluster_1.fork)();                                                                                                                                                                                                  
            }                                                                                                                                                                                                                           
            (0, cluster_1.on)('exit', (worker, code, signal) => {                                                                                                                                                                       
                console.log(`Worker ${worker.process.pid} died. Restarting`);                                                                                                                                                           
                (0, cluster_1.fork)();                                                                                                                                                                                                  
            });                                                                                                                                                                                                                         
        }                                                                                                                                                                                                                               
        else {                                                                                                                                                                                                                          
            console.log(`Cluster server started on ${process.pid}`);                                                                                                                                                                    
            callback();                                                                                                                                                                                                                 
        }                                                                                                                                                                                                                               
    }                                                                                                                                                                                                                                   
};  
```

**Comment by aduh95** [comment]
What's the reason for using `(0, cluster_1.on)(` instead of `cluster_1.on(`? That's the cause of your error as this syntax doesn't set the `this` of the method to the expected instance:

```js
class Foo{ bar(){ return this } }

let foo = new Foo;

console.log(foo.bar() === foo); // true
console.log((0, foo.bar)() === undefined); // true
```

**Comment by twigs67** [comment]
@aduh95 you were correct. It was the node-cluster that was causing the issue. We have just removed it for now, but we would like to get this working. This is the original code (code snippet above is the compiled version). 

```
// node-cluster.ts
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@services';

 import * as cluster from 'cluster';
 import * as os from 'os'

const numCPUs = os.cpus().length;

@Injectable()
export class ClusterService {
  static clusterize(callback: Function): void {
    if (cluster.isMaster && !ConfigService.isDevEnvironment()) {
      console.log(`MASTER SERVER (${process.pid}) IS RUNNING `);

      for (let i = 0; i < numCPUs; i++) {
        cluster.fork();
      }

      cluster.on('exit', (worker, code, signal) => {
        console.log(`worker ${worker.process.pid} died`);
      });
    } else {
      callback();
    }
  }
}
```

**Comment by aduh95** [comment]
Maybe something related to `@Injectable()`? Maybe there's an option you can add to disable this behavior?

**Comment by Den-dp** [comment]
Looks like when transpiler (babel in my case) tries to output commonjs modules, we end up with the code that loses `this`.

So the following code...
```js
import { on } from 'process';

on('beforeExit', () => console.log('exit'));
```
...are getting transpiled to this:
```js
"use strict";

var _process = require("process");
(0, _process.on)('beforeExit', () => console.log('exit'));
```

Here is [the example in babel playground](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzhAdnAvnAZlCI4DkYuAxgKYDOFBA3AFB2oAUBARmVtGQKIAewMAgBo4TAJRwAvAD44JVBQgAbMgDolEAOYsy_QWLH0gA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cstage-2&prettier=false&targets=Node-18&version=7.23.10&externalPlugins=&assumptions=%7B%7D)

**Comment by RedYetiDev** [comment]
Is this issue still occuring? If not, feel free to self-close.

**Comment by chriskuech** [comment]
@RedYetiDev I am facing this issue

**Comment by RedYetiDev** [comment]
Can you provide more information?

**Comment by chriskuech** [comment]
I have the same repro as @Den-dp . When I changed `import { on } from "process"` to `import on from "process"`, then the issue was resolved. Now I'm trying to figure out if I can reconfigure my tsconfig.json to no have this issue, but the issue occurs regardless of what module system I use.
