### ISSUE TITLE
Why bcrypt is not working

### ISSUE THREAD

**Issue by WarunaWMPL** [nodejs/help#3522]
> backend_@1.0.0 start M:\BACKEND NEW\SPM_explores_CAFE_backend
> node server.js

internal/modules/cjs/loader.js:1131
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\M:\BACKEND NEW\SPM_explores_CAFE_backend\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node is not a valid Win32 application.
\\?\M:\BACKEND NEW\SPM_explores_CAFE_backend\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (M:\BACKEND NEW\SPM_explores_CAFE_backend\node_modules\bcrypt\bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (M:\BACKEND NEW\SPM_explores_CAFE_backend\controllers\userC.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! backend_@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the backend_@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lahiru\AppData\Roaming\npm-cache\_logs\2021-08-30T11_24_17_396Z-debug.log

**Comment by Ayase-252** [comment]
Could you try to run `npm rebuild bcrypt --build-from-source`?

Refs: https://stackoverflow.com/a/60977960

**Comment by gireeshpunathil** [comment]
closing as answered, pls reopen if there is anything outstanding.
