### ISSUE TITLE
require() doesn't work

### ISSUE THREAD

**Issue by ImperatorOfIntellectualism** [nodejs/help#3527]
### Version

14.17.3

### Platform

Microsoft Windows NT 10.0.19041.0 x64

### What steps will reproduce the bug?

app.post("/getAvatar", (req, res) => {
  res.send(require('./data/pictureName.jpg'))
})

### How often does it reproduce? Is there a required condition?

Always

### What is the expected behavior?

I expect it to return a picture from the server to the client

### What do you see instead?

SyntaxError: Invalid or unexpected token

### Additional information

Please fix.

**Comment by Ayase-252** [comment]
Could you provide complete code snippet and complete error stack trace?

**Comment by ImperatorOfIntellectualism** [comment]
> Could you provide complete code snippet and complete error stack trace?

```
app.post("/getAvatar", (req, res) => {
  res.send(require('./data/pictureName.jpg'))
})
```
Obviously this picture does exist.
Here is the full error:
`SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\index.js:52:12
    at Layer.handle [as handle_request] (C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\Meh\Desktop\Код\nodejs\CHRISTchat\ChristApp\backend\index.js:25:3`

Hope you guys fix this bug soon.

**Comment by Ayase-252** [comment]
Okay....I think I got it.

Requiring a *picture* is not supported in Node.js. Instead, depending on what you are intended to do, you should use [`fs.read`](https://nodejs.org/dist/latest-v16.x/docs/api/fs.html#fs_fs_open_path_flags_mode_callback) to get a buffer then use `res.send` to send it, or [`res.sendFile()`](http://expressjs.com/zh-cn/api.html#res.sendFile).
