### ISSUE TITLE
Error running npm install or yarn install in project -> Zlib Error

### ISSUE THREAD

**Issue by Niltonsf** [nodejs/help#3565]
* **Node.js Version**: 14.18.0
* **OS**: macOS Big Sur
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: 14.18.0

I have just made some pulls from my library's from GitHub, I was using my windows computer to do the coding in VSCode. The code has no problem, although when I attempt to run npm install or yarn install to get the node_modules and the yarn.lock I get a weird error and the packages don't work. I'm using ZSH as the terminal for my Mac.

node: v14.18.0
npm: 6.14.15
yarn: 1.22.15

I have attempted:
- Deleting the yarn.lock
- Running npm cache verify and then npm cache clean --force

This is a piece of the log result:
```
1165 verbose stack     at PassThrough.Writable.write (internal/streams/writable.js:303:10)
1165 verbose stack     at PassThrough.ondata (internal/streams/readable.js:731:22)
1165 verbose stack     at PassThrough.emit (events.js:400:28)
1166 verbose cwd /Users/niltonsf/Desktop/github.nosync/ignews
1167 verbose Darwin 20.6.0
1168 verbose argv "/usr/local/Cellar/node@14/14.18.0/bin/node" "/usr/local/opt/node@14/bin/npm" "install"
1169 verbose node v14.18.0
1170 verbose npm  v6.14.15
1171 error code Z_DATA_ERROR
1172 error errno -3
1173 error zlib: incorrect data check
1174 verbose exit [ -3, true ]
```

<img width="836" alt="img1" src="https://user-images.githubusercontent.com/49406326/135947352-5b38d902-3c00-4c06-bd46-8e1e76aa3cdf.png">

**Comment by Niltonsf** [comment]
The problem was installing node and npm from brew. For some reason it made the crash. When I installed from the website directly, there was success.
