### ISSUE TITLE
brotliDecompress errno: -2, code: ERR_RESERVED"

### ISSUE THREAD

**Issue by MrMagicPenguin** [nodejs/help#3613]
### Details

I am trying to write and read a decompressed string from a file using the synchronous versions of `zlib`'s brotli functions. The writing seems to correctly function, but when I go to read it throws a mysterious error:

```
node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error: Decompression failed
    at BrotliDecoder.zlibOnError [as onerror] (node:zlib:190:17)
    at processChunkSync (node:zlib:456:12)
    at zlibBufferSync (node:zlib:178:12)
    at Object.syncBufferWrapper [as brotliDecompressSync] (node:zlib:791:14)
    at readObject (file:///home/voodoo/WebstormProjects/Pholcidae/management_funcs/PholObjectManager.js:14:22)
    at file:///home/voodoo/WebstormProjects/Pholcidae/index.js:8:1
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12) {
  errno: -2,
  code: 'ERR_RESERVED'
}
```

I saw a thread on [StackExchange](https://stackoverflow.com/questions/59152541/compress-and-decompress-utf8-string-with-brotli) mentioning that there is an issue with UTF-8 encoding where the Buffer is not always correctly reversed. When I try to use base64 instead however, I loose my punctuation and the last few letters of my string.

### Node.js version

v16.11.1

### Example code

```js
// Read
export function readObject(fp){
    const raw = fs.readFileSync( fp, {encoding:'utf8'})
    const data = Buffer.from(raw, 'utf8')
    console.log(zlib.brotliDecompressSync(data).toString('utf8'))
```

```js 
// Write
export function writeObject(fp, write=true){
    const content = "what is up, doc?"
    const header = "blob" + " " + Buffer.byteLength(content, "utf8") + Buffer.from(['0'])
    const store = header + content

    const compstore = zlib.brotliCompressSync(Buffer.from(store, 'utf8'))
    console.log(compstore)

    fs.writeFileSync(fp, compstore)
}
```

### Operating system

Arch Linux

### Scope

Runtime

### Module and version

zlib

**Comment by MrMagicPenguin** [comment]
I never really figured out this issue, but for any future visitors - I needed to use streams instead and that made it work
