### ISSUE TITLE
Cannot install better-sqlite3 in a path with spaces

### ISSUE THREAD

**Issue by TheDcoder** [nodejs/help#3634]
### Details

Hi, I am trying to install the `better-sqlite3` module but the building of the native code fails due to incorrect handling of the path string, if there are any spaces in the current path the installation fails.

How do I fix this issue? Should I report this to the module developer?

### Node.js version

Not applicable.

### Example code

Steps to reproduce the issue:
```
TheDcoder@arch /tmp> mkdir 'node test'
TheDcoder@arch /tmp> cd node\ test/
TheDcoder@arch /t/node test> ls
TheDcoder@arch /t/node test> npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (node-test) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /tmp/node test/package.json:

{
  "name": "node-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) 
TheDcoder@arch /t/node test> npm i better-sqlite3
npm ERR! code 1
npm ERR! path /tmp/node test/node_modules/better-sqlite3
npm ERR! command failed
npm ERR! command sh -c prebuild-install || npm run build-release
npm ERR! > better-sqlite3@7.4.5 build-release
npm ERR! > node-gyp rebuild --release
npm ERR! 
npm ERR! make: Entering directory '/tmp/node test/node_modules/better-sqlite3/build'
npm ERR!   TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR!   ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate
npm ERR! make: Leaving directory '/tmp/node test/node_modules/better-sqlite3/build'
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=17.1.0 runtime=node arch=x64 libc= platform=linux)
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.2.0
npm ERR! gyp info using node@17.1.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.9.9 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/tmp/node test/node_modules/better-sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/TheDcoder/.cache/node-gyp/17.1.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/TheDcoder/.cache/node-gyp/17.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/TheDcoder/.cache/node-gyp/17.1.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/tmp/node test/node_modules/better-sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: line 1: test/node_modules/better-sqlite3/build/Release/lib.host:/tmp/node: No such file or directory
npm ERR! /tmp/node test/node_modules/better-sqlite3/deps/extract.js:8
npm ERR! process.on('unhandledRejection', (err) => { throw err; });
npm ERR!                                             ^
npm ERR! 
npm ERR! CwdError: ENOENT: Cannot cd into '/tmp/node test/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3'
npm ERR!     at /tmp/node test/node_modules/tar/lib/mkdir.js:43:12
npm ERR!     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR!   path: '/tmp/node test/node_modules/better-sqlite3/build/Release/obj/gen/sqlite3',
npm ERR!   code: 'ENOENT'
npm ERR! }
npm ERR! 
npm ERR! Node.js v17.1.0
npm ERR! make: *** [deps/locate_sqlite3.target.mk:17: b857c92884e9598d609f6be182a2595df7a8e00f.intermediate] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Linux 5.15.5-zen1-1-zen
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
npm ERR! gyp ERR! cwd /tmp/node test/node_modules/better-sqlite3
npm ERR! gyp ERR! node -v v17.1.0
npm ERR! gyp ERR! node-gyp -v v8.2.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/TheDcoder/.npm/_logs/2021-12-02T02_40_17_386Z-debug.log
```

It works fine if I rename the directory to `node-test`:

```
TheDcoder@arch /t/node-test> npm i better-sqlite3

added 68 packages, and audited 69 packages in 1m

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
TheDcoder@arch /t/node-test> ls
```

### Operating system

Arch Linux

### Scope

Installation

### Module and version

`better-sqlite3` - `v7.4.5`

**Comment by VoltrexMaster** [comment]
> How do I fix this issue? Should I report this to the module developer?

Yes, it is a better idea to report this to the developer of this NPM package.

And it seems like you've already done it, should this be closed?
