### ISSUE TITLE
Can't find source of event emitter leak

### ISSUE THREAD

**Issue by ORESoftware** [nodejs/help#366]
Patching a foreign library and I get:

` MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added. Use emitter.setMaxListeners() to increase limit`

It would be nice if there was a stack showing where the ee.on('event') call was that leading to this warning...the warning is kind of useless to me otherwise because I can't fix it. Any ideas on how to find the source of the leak?

**Comment by addaleax** [comment]
> It would be nice if there was a stack showing where the ee.on('event') call was that leading to this warning

`node --trace-warnings`? :)

**Comment by ORESoftware** [comment]
let me give that a shot, if that works, that's the kinda help I am talkin' about! ;)

**Comment by addaleax** [comment]
@ORESoftware Fwiw, if you want something more programmatical for Node v6/v7, you can use `process.on('warning', (warning) => …)`. The `warning` object will be an instance of `Error`, so you can use `.stack` on it, and it contains a reference to the emitter itself, too.

**Comment by ORESoftware** [comment]
nice, that might do it, I will try that now

**Comment by ORESoftware** [comment]
```js
process.on('warning', function(w){
  console.log(' => Suman interactive warning => ', w.stack || w);
});
```

**Comment by ORESoftware** [comment]
Yep this worked! thanks. I wasn't getting the full stack before.

```
 => Suman interactive warning =>  MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 keypress listeners added. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:259:19)
    at ReadStream.Readable.on (_stream_readable.js:687:35)
    at EventPatternObservable._add (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.async.js:447:32)
    at EventPatternObservable.subscribeCore (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.async.js:488:30)
    at EventPatternObservable.tryCatcher (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:63:31)
    at setDisposable (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:2082:46)
    at EventPatternObservable.Rx.ObservableBase.ObservableBase._subscribe (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:2097:9)
    at EventPatternObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:2034:19)
    at AnonymousObservable.subscribe [as __subscribe] (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:4371:50)
    at AnonymousObservable.tryCatcher (/Users/Olegzandr/WebstormProjects/oresoftware/Inquirer.js/node_modules/rx/dist/rx.js:63:31)

```
