### ISSUE TITLE
 Error: Cannot find module 'typescript' from 'P:\FORGE\JPMC-tech-task-3-PY3\node_modules'

### ISSUE THREAD

**Issue by nishad132** [nodejs/help#3700]
### Details

> bank-merge-co-task-3@0.1.0 start
> react-scripts start

C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\node_modules\resolve\lib\sync.js:113
    throw err;
    ^

Error: Cannot find module 'typescript' from 'P:\FORGE\JPMC-tech-task-3-PY3\node_modules'
    at Function.resolveSync [as sync] (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\node_modules\resolve\lib\sync.js:111:15)
    at getModules (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\config\modules.js:119:32)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\config\modules.js:142:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\config\webpack.config.js:28:17) {
  code: 'MODULE_NOT_FOUND'
}

### Node.js version

Not applicable.

### Example code

> bank-merge-co-task-3@0.1.0 start
> react-scripts start

C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\node_modules\resolve\lib\sync.js:113
    throw err;
    ^

Error: Cannot find module 'typescript' from 'P:\FORGE\JPMC-tech-task-3-PY3\node_modules'
    at Function.resolveSync [as sync] (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\node_modules\resolve\lib\sync.js:111:15)
    at getModules (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\config\modules.js:119:32)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\config\modules.js:142:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (C:\Users\PC\AppData\Roaming\npm\node_modules\react-scripts\config\webpack.config.js:28:17) {
  code: 'MODULE_NOT_FOUND'
}

### Operating system

windows

### Scope

runtime

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
It seems it's not able to find the `typescript` module from `node_modules`, meaning that you don't have [typescript](https://npmjs.com/package/typescript) installed.

To install it, run the following in your terminal shell:
```console
npm i typescript
```
or supply the `--save-dev` CLI flag to install it as a dev dependency:
```console
npm i --save-dev typescript
```

And finally rerun your project.

If the solutions above doesn't work, I recommend trying to install `typescript` globally and see if it's trying to use it that way by running the following in your terminal shell:
```console
npm i -g typescript
```
and rerunning your project.

**Comment by gireeshpunathil** [comment]
@nishad132 - is this resolved?
