### ISSUE TITLE
npm install does not work

### ISSUE THREAD

**Issue by tohoyn** [nodejs/help#3726]
### Details

Command `npm install` does not work. For command `npm install tree-sitter` I get the following output:

```text
TypeError: Class extends value undefined is not a constructor or null
     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
     at Module._compile (node:internal/modules/cjs/loader:1101:14)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     at Module.require (node:internal/modules/cjs/loader:1005:19)
     at require (node:internal/modules/cjs/helpers:102:18)
     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
     at Module._compile (node:internal/modules/cjs/loader:1101:14)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
     at Module.load (node:internal/modules/cjs/loader:981:32)
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     at Module.require (node:internal/modules/cjs/loader:1005:19)
     at require (node:internal/modules/cjs/helpers:102:18)
     at Object.<anonymous> (/usr/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
     at Module._compile (node:internal/modules/cjs/loader:1101:14)
 ```

### Node.js version

16.13.2

### Operating system

Debian bookworm

### Scope

installation

### Module and version

Not applicable.

**Comment by Khylex** [comment]
having same issues here

**Comment by tohoyn** [comment]
The problem is solved when you install node.js with nvm. See [this page](https://github.com/nvm-sh/nvm).

**Comment by Khylex** [comment]
so I should re-install a new node.js application

**Comment by tohoyn** [comment]
Remove the old node.js and install the new one with nvm.

**Comment by Khylex** [comment]
Thanks, i will let you know when i am done

**Comment by Khylex** [comment]
I am finding it hard installing THE SCRIPT, I HAVE NOT DOWNLOADED IT YET.
please,i need help
I am a newbie to this

**Comment by tohoyn** [comment]
If you have questions just ask. Do you have access to Libera.Chat?

**Comment by RedYetiDev** [comment]
*(user solved own problem)*
