### ISSUE TITLE
vite https.Agent is not a constructor

### ISSUE THREAD

**Issue by goodtimec** [nodejs/help#3738]
### Details

the problems with web3 development using vite。

```text
TypeError: https.Agent is not a constructor
    at new HttpProvider2 (index.js:43:31)
    at RequestManager2.RequestManager.setProvider (index.js:64:24)
    at new RequestManager2 (index.js:39:10)
    at Object.packageInit (index.js:45:31)
    at new Web32 (index.js:39:10)
    at getERC_Allowance (index.vue:191:13)
    at index.vue:155:118
```

### Node.js version

v12.18.4

### Operating system

windows 10  x86_64

### Scope

```js
/*
    This file is part of web3.js.

    web3.js is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    web3.js is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with web3.js.  If not, see <http://www.gnu.org/licenses/>.
*/
/** @file httpprovider.js
 * @authors:
 *   Marek Kotewicz <marek@parity.io>
 *   Marian Oancea
 *   Fabian Vogelsteller <fabian@ethereum.org>
 * @date 2015
 */
var errors = require('web3-core-helpers').errors;
var XHR2 = require('xhr2-cookies').XMLHttpRequest; // jshint ignore: line
var http = require('http');
var https = require('https');
/**
 * HttpProvider should be used to send rpc calls over http
 */
var HttpProvider = function HttpProvider(host, options) {
    options = options || {};
    this.withCredentials = options.withCredentials || false;
    this.timeout = options.timeout || 0;
    this.headers = options.headers;
    this.agent = options.agent;
    this.connected = false;
    // keepAlive is true unless explicitly set to false
    const keepAlive = options.keepAlive !== false;
    this.host = host || 'http://localhost:8545';
    if (!this.agent) {
        if (this.host.substring(0, 5) === "https") {
            this.httpsAgent = new https.Agent({ keepAlive });
        }
        else {
            this.httpAgent = new http.Agent({ keepAlive });
        }
    }
};
```

report a mistake on `this.httpsAgent = new https.Agent({ keepAlive }); `

### Module and version

Not applicable.

**Comment by T-Damer** [comment]
Getting same error when using libs with `web3`, they're using `node-https-agent`
![image](https://user-images.githubusercontent.com/49658988/154808259-65d1b1e5-280a-493f-956f-fac7973bba92.png)

**Comment by T-Damer** [comment]
Found [a solution](https://github.com/Web3Modal/web3modal/issues/412#issuecomment-1054178118).
 I've added this into vite.config.ts (after running yarn add agent-base):
```TS
...
resolve: {
    alias: {
      process: 'process/browser',
      stream: 'stream-browserify',
      util: 'util',
      https: 'agent-base',
      zlib: 'browserify-zlib',
    },
  },
...
```
Works fine for me
