### ISSUE TITLE
Angular Devkit install error

### ISSUE THREAD

**Issue by AhmadAlHalabi** [nodejs/help#3757]
### Version

16.14.0

### Platform

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?

```shell
npm install --save-dev @angular-devkit/build-angular
```

### How often does it reproduce? Is there a required condition?

When i want to run
```bash
npm install --save-dev @angular-devkit/build-angular
```

### What is the expected behavior?

serve the project (ng serve)

### What do you see instead?

```text
cannot read property of null (reading 'pickalgorithm')
```

### Additional information

```text
553 verbose stack TypeError: Cannot read properties of null (reading 'pickAlgorithm')
553 verbose stack     at Integrity.match (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\npm\node_modules\ssri\index.js:234:24)
553 verbose stack     at CachePolicy.satisfies (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\policy.js:113:49)
553 verbose stack     at Function.find (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\entry.js:172:25)
553 verbose stack     at async cacheFetch (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\cache\index.js:8:17)
553 verbose stack     at async fetch (C:\Users\Ahmad\AppData\Roaming\npm\node_modules\npm\node_modules\make-fetch-happen\lib\fetch.js:82:7)
554 verbose cwd C:\xampp\htdocs\full-stack-angular-projects-main\Test
555 verbose Windows_NT 10.0.19044
556 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ahmad\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "@angular-devkit/build-angular"
557 verbose node v16.14.0
558 verbose npm  v7.24.2
559 error Cannot read properties of null (reading 'pickAlgorithm')
560 verbose exit 1
```

**Comment by takipsizad** [comment]
it looks like npm issue try to update npm

**Comment by AhmadAlHalabi** [comment]
> it looks like npm issue try to update npm

I tried this solution, i solved the error by deleting the npm folder from app data folder (hidden folder)
