### ISSUE TITLE
Visual Studio Code Errorr

### ISSUE THREAD

**Issue by ArdaKaygusuz** [nodejs/help#3777]
### Details

I creating nft colletion but visual gave to me erorr like that so i need help. How can i fix that 

### Node.js version

node-v16.14.0

### Example code

```console
npm ERR! code 1
npm ERR! path C:\Users\Casper\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\node_modules\ganache\node_modules\secp256k1
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Users\Casper\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/node-v16.14.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/SHASUMS256.txt
npm ERR! gyp http 404 https://nodejs.org/download/release/v16.14.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.0/win-x86/node.lib
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details     
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:406:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Casper\Desktop\Masterclass\hashlips_art_engine-1.1.2_patch_v6\node_modules\ganache\node_modules\secp256k1
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Casper\AppData\Local\npm-cache\_logs\2022-03-08T21_03_48_969Z-debug-0.log
```

### Operating system

Win 11

### Scope

Code

### Module and version

node-v16.14.0

**Comment by VoltrexMaster** [comment]
The error is self-explanatory here.

```console
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
```

You need to install latest version (or the version specified by the NPM package/library you're trying to install) of Visual Studio from [here](https://visualstudio.microsoft.com/downloads/) and choose the "with C++" download option, if that doesn't work, you may need to install the "Desktop development with C++" workload through the installer.

After installing the target Visual Studio version, try installing the NPM package/library you were trying to install again.

**Comment by gireeshpunathil** [comment]
@ArdaKaygusuz -  is this resolved?

**Comment by gireeshpunathil** [comment]
closing as inactive
