### ISSUE TITLE
Node version 18.0.0 crashes, when <audio src="..."></audio> is provided

### ISSUE THREAD

**Issue by neverlose-lv** [nodejs/help#3859]
### Version

18.0.0

### Platform

Darwin Apples-MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### What steps will reproduce the bug?

Fresh install of the latest Angular project.

Then replace the generated demo page with the source

`
<audio controls src="assets/sounds/click.ogg"></audio>
`
(the file was added at this path)

### How often does it reproduce? Is there a required condition?

all the time

### What is the expected behavior?

not to crash.

### What do you see instead?

```console
node:events:505
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot set property closed of #<Readable> which has only a getter
    at FsReadStream.close (/Users/apower/Desktop/VR_Tours/node_modules/memfs/lib/volume.js:2047:17)
    at FsReadStream._destroy (/Users/apower/Desktop/VR_Tours/node_modules/memfs/lib/volume.js:2032:10)
    at _destroy (node:internal/streams/destroy:109:10)
    at class_1.destroy (node:internal/streams/destroy:71:5)
    at class_1.<anonymous> (/Users/apower/Desktop/VR_Tours/node_modules/memfs/lib/volume.js:1962:22)
    at class_1.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on class_1 instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Node.js v18.0.0
```

### Additional information

The 18.0.0 version is installed by the brew.
Now downgraded to the 16th node version.
The 16th node version works well.

**Comment by KevinHodder** [comment]
Also seeing this on 18.1.0. Any audio tag causes it to crash.

**Comment by racocvr** [comment]
Still getting the same crash on v18.7.0

**Comment by tomdmason** [comment]
I don't suppose anyone has resolved this?

**Comment by littletuna4** [comment]
Still seeing this on 
node:18.15.0
react:18.2.0

Anyone in here find a workaround?

**Comment by preveen-stack** [comment]
@neverlose-lv did the suggestion from @littletuna4 solved your issue?
