### ISSUE TITLE
[bug?] Why can't capture the error in events

### ISSUE THREAD

**Issue by fanybook** [nodejs/help#3882]
### Version

14.x

### Platform

windows 10

### What steps will reproduce the bug?
```js
const net = require('net')
 
const portUsed = (port) => {
  return new Promise((resolve, reject) => {
    let server = net.createServer().listen(port)
    server.on('listening', function () {
      server.close()
      resolve(port)
    })
    server.on('error', function (err) {
      if (err.code == 'EADDRINUSE') {
        resolve(err)
      }
    })
  })
}
 
const start = async () => {
    try {
        // TODO: 80 must been used
        const port = await portUsed(80)
    } catch (err) {
        console.log('--------->debug', err)
    }
}
start()
```

### What do you see instead?

try catch don't work，the process crashed

**Comment by fanybook** [comment]
@F3n67u thanks, 'reject(err)' can be capture in js

but, in ts
```typescript
import os from "os"
import net from "net"

// const self: {[propName: string]: any} = {}
const getIntranetIp = function(): string[] {
    let ipAddrs: string[] = []

    let interfaces = os.networkInterfaces()
    for (let devName in interfaces) {
        let iface = interfaces[devName]
        if (typeof(iface) == "undefined") {
            continue
        }

        for (let i = 0; i < iface.length; i++) {
            let alias = iface[i]
            if (alias.family === 'IPv4' && alias.address !== '127.0.0.1' && !alias.internal) {
                ipAddrs.push(alias.address)
            }
        }
    }

    return ipAddrs
}

const checkPort = function(port: number): Promise<number> {
    return new Promise((resolve, reject) => {
        let server = net.createServer().listen(port)
        server.on('listening', function () {
            server.close()
            resolve(port)
        })
        server.on('error', function (err) {
            // @ts-ignore
            if (err.code == 'EADDRINUSE') {
                reject(err)
            }
        })
    })
}

const getAvailablePort = async function(port: number): Promise<number> {
    try {
        const availablePort = await checkPort(3000)
        return <number>availablePort
    } catch(err) {
        console.log(2222, err)
    }
    return 0
}

export default {
    getIntranetIp,
    getAvailablePort,
}
```


to 

```js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const os_1 = __importDefault(require("os"));
const net_1 = __importDefault(require("net"));
const getIntranetIp = function () {
    let ipAddrs = [];
    let interfaces = os_1.default.networkInterfaces();
    for (let devName in interfaces) {
        let iface = interfaces[devName];
        if (typeof (iface) == "undefined") {
            continue;
        }
        for (let i = 0; i < iface.length; i++) {
            let alias = iface[i];
            if (alias.family === 'IPv4' && alias.address !== '127.0.0.1' && !alias.internal) {
                ipAddrs.push(alias.address);
            }
        }
    }
    return ipAddrs;
};
const checkPort = function (port) {
    return new Promise((resolve, reject) => {
        let server = net_1.default.createServer().listen(port);
        server.on('listening', function () {
            server.close();
            resolve(port);
        });
        server.on('error', function (err) {
            if (err.code == 'EADDRINUSE') {
                reject(err);
            }
        });
    });
};
const getAvailablePort = function (port) {
    return __awaiter(this, void 0, void 0, function* () {
        try {
            const availablePort = yield checkPort(3000);
            return availablePort;
        }
        catch (err) {
            console.log(2222, err);
        }
        return 0;
    });
};
exports.default = {
    getIntranetIp,
    getAvailablePort,
};
```


output
```bash
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (net.js:1320:16)
    at listenInCluster (net.js:1368:12)
    at Server.listen (net.js:1454:7)
    at Application.listen (D:\workspace-gitee\fanybook\letsno-next\node_modules\koa\lib\application.js:82:19)
    at Object.<anonymous> (D:\workspace-gitee\fanybook\letsno-next\.build\main.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1347:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3000
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! letsno@1.0.0 start: `tsc && node .build-helper && node .build/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the letsno@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2022-06-07T15_34_11_444Z-debug.log

```

**Comment by F3n67u** [comment]
If problem is solved, please help to close this issue.
