### ISSUE TITLE
not fully unpacked asar

### ISSUE THREAD

**Issue by asmrs22** [nodejs/help#3886]
### Details

unpacks asar incompletely

### Node.js version

v.16.15.1

### Example code

```console
TypeError: Cannot read properties of undefined (reading 'files')
    at Filesystem.getNode (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\lib\filesystem.js:132:19)
    at Filesystem.getFile (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\lib\filesystem.js:140:23)
    at Filesystem.getFile (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\lib\filesystem.js:144:19)
    at Object.module.exports.extractAll (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\lib\asar.js:187:29)
    at Command.<anonymous> (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\bin\asar.js:72:10)
    at Command.listener [as _actionHandler] (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mcommander←[24m\index.js:413:31)
    at Command._parseCommand (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mcommander←[24m\index.js:914:14)
    at Command._dispatchSubcommand (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mcommander←[24m\index.js:865:18)
    at Command._parseCommand (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mcommander←[24m\index.js:882:12)
    at Command.parse (C:\Users\Vitaliy\AppData\Roaming\npm\node_modules\←[4masar←[24m\node_modules\←[4mcommander←[24m\index.js:717:10)
```

### Operating system

win10 64x

### Scope

electron extract app.asar

### Module and version

`AppData\Roaming\npm\node_modules\asar\lib\filesystem.js:132`

**Comment by F3n67u** [comment]
Thanks for creating this issue. Could you provide reproduce step so we could help you better？The reproduction would include:
1. Which command do you run when the error happen?
2. Which version of asar do you install? How do you install it.

You also need to provide a asar file which could used to reproduce this problem.

**Comment by asmrs22** [comment]
> 



> Спасибо за создание этой проблемы. Не могли бы вы предоставить этап воспроизведения, чтобы мы могли помочь вам лучше? Воспроизведение будет включать в себя:
> 
> 1. Какую команду вы запускаете, когда возникает ошибка?
> 2. Какую версию asar вы устанавливаете? Как вы его устанавливаете.
> 
> Вам также необходимо предоставить файл asar, который можно использовать для воспроизведения этой проблемы.




> Thanks for creating this issue. Could you provide reproduce step so we could help you better？The reproduction would include:
> 
> 1. Which command do you run when the error happen?
> 2. Which version of asar do you install? How do you install it.
> 
> You also need to provide a asar file which could used to reproduce this problem.

1.  command "asar extract app.asar app_unpacked"
2.  version v3.1.0 , install " npm install -g asar "
3.  file [https://drive.google.com/file/d/11B_PDVagkxw6MzjKoUK5oDtG72L4i_Ag/view?usp=sharing](url)

**Comment by asmrs22** [comment]
> Thanks for creating this issue. Could you provide reproduce step so we could help you better？The reproduction would include:
> 
> 1. Which command do you run when the error happen?
> 2. Which version of asar do you install? How do you install it.
> 
> You also need to provide a asar file which could used to reproduce this problem.

1. command "asar extract app.asar app_unpacked"
2. version v3.1.0 , install " npm install -g asar "
3. file https://drive.google.com/file/d/11B_PDVagkxw6MzjKoUK5oDtG72L4i_Ag/view?usp=sharing

**Comment by F3n67u** [comment]
I could reproduce this problem on Windows now.  

This is a Windows-specific problem, It will not happen in other OS. It only happened when asar pack file contains symbol link file.

The problem is when getting node info of `node_modules\.bin\detect-libc`, the symbol link info(`info.link`) is a Linux path(`node_modules/detect-libc/bin/detect-libc.js`). It is not correct, it should be a windows path: `node_modules\detect-libc\bin\detect-libc.js`. Because the symbol link info is not correct, so when we call `this.getFile(info.link)` to get a file we get nothing, and then an error happened. See the below screenshot for details.

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/12343178/174437382-3600549d-6b52-41f8-a3d6-a89f5c2dfaca.png">

Why does this error not happen in other OS?
Because in other OS, `followLink` is `false`. It will not use `info.link` in other OS. see https://github.com/electron/asar/blob/main/lib/asar.js#L177-L178 

I will suggest reporting this bug to https://github.com/electron/asar repo.

## Possible workaround
Excluding symbol link from being packed

**Comment by Kh4f** [comment]
Still relevant
