### ISSUE TITLE
node throws errors with assert module and self invoking function

### ISSUE THREAD

**Issue by ivitivan** [nodejs/help#391]
Why do errors happen when I execute these pieces of code?

```
const assert = require('assert')

(function() {}())
```

and

```
const assert = require('assert')

(function() {})()
```

Errors, correspondingly:

```
assert.js:85
  throw new assert.AssertionError({
  ^
AssertionError: undefined == true
    at Object.<anonymous> (/home/vit/Projects/add/add.test.js:3:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

and

```
/home/vit/Projects/add/add.test.js:3
(function() {})()
               ^

TypeError: require(...)(...) is not a function
    at Object.<anonymous> (/home/vit/Projects/add/add.test.js:3:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

node -v: v7.2.0
os: Ubuntu 16.04

**Comment by bnoordhuis** [comment]
You're a victim of automatic semicolon insertion a.k.a. ASI.  Put a semicolon after the require statement and the problem goes away.  It's a good example of why you should always use semicolons.
