### ISSUE TITLE
Help!!!

### ISSUE THREAD

**Issue by Eluxidatr** [nodejs/help#3970]
### Details

```console
> nodemon --exec babel-node src/servers.js
[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `babel-node src/servers.js`
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/quang/Documents/RIAN Chatbot/src/servers.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at Object.<anonymous> (/home/quang/Documents/RIAN Chatbot/node_modules/@babel/node/lib/_babel-node.js:176:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

### Node.js version

Lastest

### Example code

Check my git

### Operating system

Linux

### Scope

cannot do npm start

### Module and version

Not applicable.

**Comment by VoltrexMaster** [comment]
The error is self-explanatory here, the `src/servers.js` file wasn't found as it's non-existent.

Looking at your GitHub repository it seems to be named `server.js`, not `servers.js`.
