### ISSUE TITLE
Getting an errno: -100, code: 'EPROTO', syscall: 'write', when visiting localhost in my Next.js project

### ISSUE THREAD

**Issue by ajsaule** [nodejs/help#4014]
### Details

I haven't touched this repo in a while, and as far as I remember it was running fine before It was sitting dormant for almost a year. I wonder if it something to do with SSL going out of date or needing an update or something, I tried deleting node_modules and re-installing but nothing.  

[![Error](https://i.stack.imgur.com/wsT8X.png)](https://i.stack.imgur.com/wsT8X.png)

That's the error I am getting, here it is in the console in VS Code: 
```
Error: write EPROTO 140704571122880:error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1544:SSL alert number 80

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16) {
  errno: -100,
  code: 'EPROTO',
  syscall: 'write',
  response: undefined
}
```

Here is the error in the console of chrome browser: 
```
Uncaught     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
```

I am not sure what information to give, but I can provide more info if anyone has questions. 

Tried to `npm run dev` and the frontend repo, compiles successfully, but when I visit localhost it throws an SSL error. 

### Node.js version

v14.19.1

### Operating system

macOS 13.0

### Scope

runtime? not exactly sure 

### Module and version

Not applicable.

**Comment by ajsaule** [comment]
I found out that it was actually one of the API_HOST environment variable that was in my .env file, when I started running the backend locally and pointed the API_HOST to localhost I got past the above error. Hopefully this helps you in some way.
