### ISSUE TITLE
[Bug]: error accessing os.networkInterfaces() in REPL (Android - Termux)

### ISSUE THREAD

**Issue by pandas-id** [nodejs/help#4058]
### Details

I installed nodejs on Android (Termux app) and then install vue-cli using npm.but when I want to check the version of vue-cli, the error that is returned is instead.

i think it happened because of the android 13 version i am using. In previous versions of android 12 i found no error when doing the same think.

### Node.js version

v18.12.1

### Example code

On REPL with `on.networkInterfaces()` command
```
> os.networkInterfaces()
Uncaught:                                                  SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)
    at new SystemError (node:internal/errors:244:5)            at new NodeError (node:internal/errors:355:7)
    at __node_internal_checkError (node:os:69:13)              at Object.networkInterfaces (node:os:272:16) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 13,
    code: 'Unknown system error 13',
    message: 'Unknown system error 13',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter: 13],
  syscall: [Getter/Setter: 'uv_interface_addresses']
}
```

on command line `vue --version`
```
❯ vue --version
node:os:69
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
    at Object.networkInterfaces (node:os:272:16)
    at getIPType (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/entities/Defaults.js:70:34)
    at new Defaults (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/entities/Defaults.js:45:21)
    at new Parser (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/entities/EventParser.js:8:14)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/dao/client.js:11:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 13,
    code: 'Unknown system error 13',
    message: 'Unknown system error 13',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v18.12.1
```

### Operating system

Android 13, Termux App

Termux Info:
```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9663
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.34.1
Android version:
13
Kernel build information:
Linux localhost 4.14.186-25356148 #1 SMP PREEMPT Tue Nov 8 11:01:54 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A225F
```

### Scope

code and runtime

### Module and version

Vue-Cli.The error also appears when I want to check `vue --version`.

**Comment by krrishdholakia** [comment]
Are there any workarounds to access os.networkInterfaces() in Android - Termux? - [Clerkie](https://bit.ly/clerkie_ai_github)

**Comment by tumimo-cloud** [comment]
To get a clear understanding as to why this is happening, kindly visit:
https://github.com/termux/termux-packages/issues/10868#issuecomment-1144635504

**Comment by tumimo-cloud** [comment]
Personally what I did in order to run on localhost, I went offline to stop the query from running, thus avoiding the error.
