### ISSUE TITLE
unable to use NPM

### ISSUE THREAD

**Issue by galaxine-senpai** [nodejs/help#4060]
### Details

As of a few days ago I can no longer use NPM, I tried running it on my other machines and it works fine

### Node.js version

Not applicable.

### Example code

```js
ERROR:
/usr/local/lib/node_modules/npm/lib/utils/exit-handler.js:22
  const hasLoadedNpm = npm?.config.loaded
                           ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:76:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:2:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

### Operating system

Zorin OS

### Scope

Unsure how to classify it

### Module and version

N/A

**Comment by VoltrexKeyva** [comment]
npm uses Node.js to run, your current Node.js installation is pretty old (you can check it's version by running `node -v`) so it doesn't support the [optional chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) (`?.`) used by npm, uninstall your current Node.js installation and use something like [nvm](https://nvm.sh/) or [NodeSource distributions](https://github.com/nodesource/distributions) to install/update Node.js.

**Comment by galaxine-senpai** [comment]
Will do thank you
