### ISSUE TITLE
Error: Cannot find module 'write-file-atomic'

### ISSUE THREAD

**Issue by aliaburas80** [nodejs/help#412]
Hi, I tried to unintall and reinstall nodejs and same issue for NPM

Error: Cannot find module 'write-file-atomic'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object. (\npm\node_modules\npm\lib\cache\caching-client.js:17:17)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)

**Comment by TheAlphaNerd** [comment]
@aliaburas80 what operating system are you on?

How did you install node? What are you trying to do when you get this error?

**Comment by lordKnighton** [comment]
Do you see it in your npm packages? Can you verify it it's there?

**Comment by aliaburas80** [comment]
@TheAlphaNerd  I installed the "msi" file, and I did simple thing like "install, start,.."

**Comment by aliaburas80** [comment]
The problem solved by removing everything related to NPM and unstall node after that install node again.

**Comment by aliaburas80** [comment]
Thanks everyone
