### ISSUE TITLE
Segmentation fault with fs

### ISSUE THREAD

**Issue by adityapareek18** [nodejs/help#4125]
### Details

Our application gives the user the ability to download a bundle (ZIP) of logs from the UI.
These logs are generated on the server and kept in the file system.
When user request for logs we read the logs folder and pull individual files present in it to create a zip and download it.
Problem:
We have spent many days on this problem but are still unable to understand how we can fix it. Whenever a user requests for the logs our app crashes with a segmentation fault. There's no error related to heap memory or anything.
I understand that segfault is raised by OS when the application tries to access a memory location that it's not supposed to...
But in this case, our log files are simply lying in the most accessible of places with little to know permission required. Following is the output from the gdb of the code dump:

```gdb
(gdb) bt
#0  0x00007f3a561b1be6 in elf_machine_rela (reloc=0x7f3a229b9fd8, reloc=0x7f3a229b9fd8, skip_ifunc=0, 
    reloc_addr_arg=0x7f3a22bcdfb0, version=0xa8, sym=0x7f3a229b7850, map=0x6e4eb80)
    at ../sysdeps/x86_64/dl-machine.h:299
#1  elf_dynamic_do_Rela (skip_ifunc=0, lazy=<optimized out>, nrelative=<optimized out>, 
    relsize=<optimized out>, reladdr=<optimized out>, map=0x6e4eb80) at do-rel.h:137
#2  _dl_relocate_object (scope=<optimized out>, reloc_mode=reloc_mode@entry=1, 
    consider_profiling=<optimized out>, consider_profiling@entry=0) at dl-reloc.c:259
#3  0x00007f3a561ba66c in dl_open_worker (a=a@entry=0x7ffecd303ff8) at dl-open.c:423
#4  0x00007f3a561b57d4 in _dl_catch_error (objname=objname@entry=0x7ffecd303fe8, 
    errstring=errstring@entry=0x7ffecd303ff0, mallocedp=mallocedp@entry=0x7ffecd303fe0, 
    operate=operate@entry=0x7f3a561ba160 <dl_open_worker>, args=args@entry=0x7ffecd303ff8) at dl-error.c:177
#5  0x00007f3a561b9b8b in _dl_open (file=0x7f3a5531fc06 "libgcc_s.so.1", mode=-2147483647, 
    caller_dlopen=<optimized out>, nsid=-2, argc=4, argv=0x7ffecd306928, env=0x7ffecd306950) at dl-open.c:649
#6  0x00007f3a552d5952 in do_dlopen (ptr=ptr@entry=0x7ffecd304200) at dl-libc.c:87
#7  0x00007f3a561b57d4 in _dl_catch_error (objname=0x7ffecd3041e0, errstring=0x7ffecd3041f0, 
    mallocedp=0x7ffecd3041d0, operate=0x7f3a552d5910 <do_dlopen>, args=0x7ffecd304200) at dl-error.c:177
#8  0x00007f3a552d5a12 in dlerror_run (args=0x7ffecd304200, operate=0x7f3a552d5910 <do_dlopen>)
    at dl-libc.c:46
#9  __GI___libc_dlopen_mode (name=name@entry=0x7f3a5531fc06 "libgcc_s.so.1", mode=mode@entry=-2147483647)
    at dl-libc.c:163
#10 0x00007f3a552acc05 in init () at ../sysdeps/x86_64/backtrace.c:52
#11 0x00007f3a5556c20b in __pthread_once_slow (once_control=0x7f3a55563cc0 <once.7829>, 
    init_routine=0x7f3a552acbf0 <init>) at pthread_once.c:117
#12 0x00007f3a552acd1c in __GI___backtrace (array=<optimized out>, size=256)
    at ../sysdeps/x86_64/backtrace.c:101
#13 0x0000000000b8db16 in report::WriteNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, std::string const&, std::ostream&, v8::Local<v8::Value>, bool) ()
#14 0x0000000000b8f596 in report::GetNodeReport(v8::Isolate*, node::Environment*, char const*, char const*, v8::Local<v8::Value>, std::ostream&) ()
#15 0x0000000000b9286f in report::GetReport(v8::FunctionCallbackInfo<v8::Value> const&) ()
#16 0x0000000000d53cfe in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Han---Type <return> to continue, or q <return> to quit---
dle<v8::internal::Object>, v8::internal::BuiltinArguments) ()
#17 0x0000000000d5511f in v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) ()
#18 0x00000000015f0b79 in Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit ()
#19 0x000000000158354a in Builtins_InterpreterEntryTrampoline ()
```
info shared:

```gdb
(gdb) info shared
From                To                  Syms Read   Shared Object Library
0x00007f3a55fa2e50  0x00007f3a55fa394e  Yes         /lib64/libdl.so.2
0x00007f3a55cf54e0  0x00007f3a55d5c59a  Yes         /lib64/libstdc++.so.6
0x00007f3a5599d350  0x00007f3a55a08336  Yes         /lib64/libm.so.6
0x00007f3a55784ad0  0x00007f3a55794285  Yes         /lib64/libgcc_s.so.1
0x00007f3a5556b8f0  0x00007f3a55576db1  Yes         /lib64/libpthread.so.0
0x00007f3a551b79f0  0x00007f3a55307b6f  Yes         /lib64/libc.so.6
0x00007f3a561a6af0  0x00007f3a561c2060  Yes         /lib64/ld-linux-x86-64.so.2
0x00007f3a44568d90  0x00007f3a445dbb1a  Yes         /node_modules/re2-applic/node_modules/re2/build/Release/re2.node
0x00007f3a3fc2ac80  0x00007f3a3fdcd7d0  Yes (*)     /webapp/node_modules/sqlite3/lib/binding/napi-v3-linux-x64/node_sqlite3.node
0x00007f3a44137b30  0x00007f3a4414163a  Yes (*)     /webapp/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node
0x00007f3a3ebcf330  0x00007f3a3ebe0e32  Yes (*)     /node_modules/pdf-generator/node_modules/canvas/build/Release/libz.so.1
0x00007f3a3e515a10  0x00007f3a3e54a3c6  Yes         /node_modules/pdf-generator/node_modules/canvas/build/Release/libgobject-2.0.so.0
0x00007f3a3e1edb30  0x00007f3a3e270e69  Yes         /node_modules/pdf-generator/node_modules/canvas/build/Release/libglib-2.0.so.0
0x00007f3a3cc74cc0  0x00007f3a3cd70615  Yes         /node_modules/pdf-generator/node_modules/canvas/build/Release/libgio-2.0.so.0
0x00007f3a3c124230  0x00007f3a3c1271bc  Yes         /lib64/librt.so.1
0x00007f3a239bea00  0x00007f3a239c640e  Yes (*)     /node_modules/pdf-generator/node_modules/canvas/build/Release/libffi.so.7
0x00007f3a237792b0  0x00007f3a237a2131  Yes         /node_modules/pdf-generator/node_modules/canvas/build/Release/libpcre.so.1
0x00007f3a22bd20b0  0x00007f3a22bd2f85  Yes         /node_modules/pdf-generator/node_modules/canvas/build/Release/libgmodule-2.0.so.0
0x00007f3a229ba980  0x00007f3a229c9162  Yes         /lib64/libresolv.so.2
(*): Shared library is missing debugging information.
(gdb) 
```

I have spent too much time on this and don't see an end coming. So need some pros to look at it.

### Node.js version

v16.14.0

### Example code

```js
collect: async function () {
      let inputDirectory = path.dirname(inputFile);
      let inputFileName = path.basename(inputFile);

      const logRotatedFileNames = (await fs.readdir(inputDirectory)).filter(file => {
        const fileName = path.basename(file);
        const suffix = fileName.substring(inputFileName.length);

        return fileName.startsWith(inputFileName) && /(?:\.\d+|)/.test(suffix);
      });

      // sort files descendingly by suffix
      logRotatedFileNames.sort((a, b) => getFileSuffix(b) - getFileSuffix(a));

      if (logRotatedFileNames.length === 0) {
        throw Error(`The service log file ${inputFile} could not be found.`);
      }

      const filesWithModificationTime = await Promise.all(
        logRotatedFileNames.map(async fileName => {
          const file = path.join(inputDirectory, fileName);
          return {
            file,
            modificationTime: (await fs.stat(file)).mtime,
          };
        })
      );

      const writeStream = fs.createWriteStream(
        path.join(outputDirectory, path.basename(inputFile))
      );

      let remainingFileSize = maxFileSizeInBytes;
      let totalBytesOmitted = 0;

      for (const { file, modificationTime } of filesWithModificationTime) {
        if (startTime > modificationTime) {
          continue;
        }

        const { bytesWritten, bytesOmitted } = await processFile(
          file,
          writeStream,
          remainingFileSize
        );

        remainingFileSize -= bytesWritten;
        totalBytesOmitted += bytesOmitted;
      }

      if (totalBytesOmitted > 0) {
        writeStream.write(`[ ... omitted ${totalBytesOmitted} bytes ... ]\n`);
      }

      await promisify(writeStream.end.bind(writeStream))();

      return totalBytesOmitted > 0
        ? [`Omitted ${totalBytesOmitted} bytes from ${path.basename(inputFile)}`]
        : [];
    },
  };
```

### Operating system

Centos7

### Scope

runtime

### Module and version

fs

**Comment by VoltrexKeyva** [comment]
Does the segmentation fault still occur when you try on the latest LTS release of Node.js (v18 as of writing this)?

**Comment by adityapareek18** [comment]
Hi @VoltrexKeyva, Unable to attempt recreation with LTS release as this is on a production instance.
