### ISSUE TITLE
 number is not defined     at Object.<anonymous> (D:\javascriptcode\practiceconditional.js:4:1)     at Module._compile (node:internal/modules/cjs/loader:1241:14)     at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)     at Module.load (node:internal/modules/cjs/loader:1091:32)     at Module._load (node:internal/modules/cjs/loader:938:12)     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)     at node:internal/main/run_main_module:23:47

### ISSUE THREAD

**Issue by avantisutar** [nodejs/help#4261]
### Details

 number is not defined
    at Object.<anonymous> (D:\javascriptcode\practiceconditional.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47

### Node.js version

Version: 20.8.0 (includes npm 10.1.0)

### Example code

const propmt = require("prompt-sync")()
const a = propmt("hey tell your age")
a = number.parseInt(a)
console.log(typeof a)

### Operating system

windows 11

### Scope

variable is not defined error

### Module and version

.Version: 20.8.0 (includes npm 10.1.0)

**Comment by avantisutar** [comment]
plz give me solution for this quetion

**Comment by ljharb** [comment]
It’s meant to be Number, not number.
