### ISSUE TITLE
SIMD issue

### ISSUE THREAD

**Issue by nurulnabi** [nodejs/help#439]
i tried this code...
----------------------------------------------
var a = SIMD.Float32x5(1,2,3,4,5);
var b = SIMD.Float32x5(0,9,8,7,6);
var c = SIMD.Float32x5.add(a,b);
-----------------------------------------------

when i run this code i got the following error....
**ReferenceError: SIMD is not defined**
    at Object.<anonymous> (/home/csdevu/learning/app.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by lordKnighton** [comment]
Let's see your import code, `nodejs` require `SIMD` code

**Comment by nurulnabi** [comment]
var SIMD = require('./simd');
var SIMD = require('simd');

i tried both

**Comment by bnoordhuis** [comment]
Start node with `node --harmony_simd`.  Keep in mind that `--harmony_*` features are unstable.

**Comment by nurulnabi** [comment]
**this is my code**
var SIMD = require('simd');

var a = SIMD.Float32x5(1,2,3,4,5);
var b = SIMD.Float32x5(0,9,8,7,6);

var c = SIMD.Float32x5.add(a,b);
console.log(c);

**this is the error**
Error: Cannot find module 'simd'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/csdevu/learning/app.js:2:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by targos** [comment]
You should remove the `require()` statement. `SIMD` is a global object.
BTW `SIMD.Float32x5` does not exist. The currently available types are: 

SIMD.Bool16x8, SIMD.Bool32x4,              SIMD.Bool8x16,              SIMD.Float32x4,        SIMD.Int16x8,               SIMD.Int32x4,               SIMD.Int8x16, SIMD.Uint16x8,              SIMD.Uint32x4,              SIMD.Uint8x16,

**Comment by nurulnabi** [comment]
Thanx @targos ,
Kindly resolve my another query. If I need to create a vector of size n using the SIMD types then how can I do that?

**Comment by bnoordhuis** [comment]
You cannot create SIMD vectors of arbitrary size, only the sizes @targos listed.

**Comment by nurulnabi** [comment]
Thanx @bnoordhuis,
Could you tell the logic behind fixed size.

**Comment by Fishrock123** [comment]
@nurulnabi At the very least, those are the sizes that TC39 (The JavaScript Technical Committee) chose. That isn't our decision.

**Comment by bnoordhuis** [comment]
SIMD vectors in JS map to the SIMD CPU registers and instructions and those are logically of fixed size.
