### ISSUE TITLE
TLS socket keeps being reset with Chrome

### ISSUE THREAD

**Issue by daveconger** [nodejs/help#444]
* **Node.js Version**: 6.9.2
* **OS**: Windows 10 1607
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**: HTTPS, TLS

The issue I'm having seems to be related to [https://github.com/nodejs/node-v0.x-archive/issues/1516](url).

I'd like to use the requestCert option for an HTTPS server and use a client certificate that requires a PIN input.  This works well enough in Edge and FF, but Chrome constantly prompts for PIN input on nearly every page load, which makes it unbearable to use.

Looking at the above referenced issue, I thought this was due to the cert request.  Obviously, if I remove the requestCert option, there is no perceived problem because there is no need for the client to enter any information.  However, looking at the socket events you can still see there is an issue.  With Chrome the socket is closed after almost every request it seems and a new session is created.  With Edge the socket remains open for the duration of the timeout.

I simplified my code to get at the issue:

```js
var port = 8080;
const opts = {
  // Server key and cert (can be self-signed or signed by trusted CA)
  key: fs.readFileSync(__dirname + '/../serverkey.pem'),
  cert: fs.readFileSync(__dirname + '/../servercert.pem'),
  passphrase: process.env.KEY_SERVER_PASS,
  
  // Request client cert and match against CA certificate
  //requestCert: true,
  //rejectUnauthorized: true, //blocks certs which don't match CA
  //ca: [ ... ]
}

var server = https.createServer(opts,function(req,res) {
  res.setHeader('Content-Type', 'text/html');
  res.writeHead(200, {'Content-Type': 'text/plain'});
  res.end('ok');
});

server.on('secureConnection',function(socket) {
  console.log(socket.getSession());

  socket.on('_socketEnd',function(e) { console.log('socketEnd'); });
  socket.on('secure',function(e) { console.log('secure'); });
  socket.on('data',function(e) { console.log('data'); });
  socket.on('resume',function(e) { console.log('resume'); });
  socket.on('pause',function(e) { console.log('pause'); });
  socket.on('close',function(had_err) { console.log('close ' + had_err); });
  socket.on('end',function() { console.log('end'); });
  socket.on('finish',function(e) { console.log('finish'); });
  socket.on('error',function(e) {
    console.log('error');
    console.log(e);
  });
});

server.on('tlsClientError',function(e,socket) {
  console.log('tlsError');
  console.log(e);
});

server.on('clientError',function(e) {
  console.log('clientError');
  console.log(e);
});

server.on('resumeSession',function(id,cb) {
  console.log('resumeSess ' + id.toString('hex'));
});

server.listen(port, function() {
  console.log('Express server listening on port %d',port);
});
```

**With Chrome:**
**[initial page request]**
<Buffer 30 7e 02 01 01 02 02 03 03 04 02 c0 2f 04 00 04 30 cc a7 3e 31 e9 94 00 45 63 c7 06 53 92 a8 e3 4f 38 ed b5 86 21 16 ee 5b ef 74 0c ca ec 83 9f 47 c4 ... >
resume
clientError
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
close true
<Buffer 30 7e 02 01 01 02 02 03 03 04 02 c0 2f 04 00 04 30 6a 81 e8 d7 e9 f2 6a 16 1e 7a 94 77 b1 c3 6a fc c8 56 97 7b 68 87 fd df 67 06 4e 6d 9d 41 d8 39 5c ... >
resume
clientError
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
close true
<Buffer 30 7e 02 01 01 02 02 03 03 04 02 c0 2f 04 00 04 30 71 1d 49 b2 45 70 8d 2d 0c c6 6f 7f 80 f5 c3 96 52 9c c0 6c f3 68 94 8e d4 dc bc 08 86 85 e5 d2 44 ... >
resume
data
data
finish
socketEnd
end
close false
**[page refresh]**
<Buffer 30 7e 02 01 01 02 02 03 03 04 02 c0 2f 04 00 04 30 0b aa 64 e7 a0 f0 59 1e 01 d3 eb dc 12 ae b8 0c d2 56 8c bf 31 d8 4b 63 27 8e 51 57 5d c0 24 90 57 ... >
resume
clientError
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
error
{ Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
close true
<Buffer 30 7e 02 01 01 02 02 03 03 04 02 c0 2f 04 00 04 30 3f 89 50 a0 7c 94 b9 a8 52 cb 58 fe 2f f9 71 98 09 ac 0f 75 dd 20 af d1 68 ed fc 8a 28 ba 23 c9 d6 ... >
resume
data
data
finish
socketEnd
end
close false

**With Edge:**
**[initial page request]**
clientError
{ Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:839:25)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at Socket._destroy.cb._handle.close (net.js:498:12)
    at Socket.done (_tls_wrap.js:325:7)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP.Socket._destroy.cb._handle.close [as _onclose] (net.js:498:12) code: 'ECONNRESET' }
tlsError
{ Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:839:25)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at Socket._destroy.cb._handle.close (net.js:498:12)
    at Socket.done (_tls_wrap.js:325:7)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP.Socket._destroy.cb._handle.close [as _onclose] (net.js:498:12) code: 'ECONNRESET' }
clientError
{ Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:839:25)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at Socket._destroy.cb._handle.close (net.js:498:12)
    at Socket.done (_tls_wrap.js:325:7)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP.Socket._destroy.cb._handle.close [as _onclose] (net.js:498:12) code: 'ECONNRESET' }
tlsError
{ Error: socket hang up
    at TLSSocket.<anonymous> (_tls_wrap.js:839:25)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)
    at Socket._destroy.cb._handle.close (net.js:498:12)
    at Socket.done (_tls_wrap.js:325:7)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP.Socket._destroy.cb._handle.close [as _onclose] (net.js:498:12) code: 'ECONNRESET' }
<Buffer 30 7e 02 01 01 02 02 03 03 04 02 c0 2f 04 00 04 30 21 f3 fc 3a 12 01 a4 11 de 68 3a 6d 20 a9 ca e8 fb 60 08 0d 28 3c 20 3c 15 a1 04 63 87 00 ad 74 1f ... >
resume
data
**[page refresh]**
data

Please help; I've been working at this for days now.  Thank you!

**Comment by lordKnighton** [comment]
closing for now.  But if still need help, hit me up & we will take it from there.
