### ISSUE TITLE
Dependency cannot be found (internally) even after installation

### ISSUE THREAD

**Issue by modaralgayal** [nodejs/help#4503]
### Node.js Version

Node.js v22.9.0

### NPM Version

10.9.0

### Operating System

22.04.1-Ubuntu

### Subsystem

Other

### Description

I am having trouble understanding why my body-parser in my nodeJs express project is throwing error: 
```
[nodemon] 3.1.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node src/index.js`
node:internal/modules/cjs/loader:1248
  const err = new Error(message);
              ^

Error: Cannot find module 'qs'
Require stack:
- /home/algayalm/Työpöytä/TP/node_modules/body-parser/lib/types/urlencoded.js
- /home/algayalm/Työpöytä/TP/node_modules/body-parser/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1248:15)
    at Module._load (node:internal/modules/cjs/loader:1074:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:217:24)
    at Module.require (node:internal/modules/cjs/loader:1339:12)
    at require (node:internal/modules/helpers:135:16)
    at parser (/home/algayalm/Työpöytä/TP/node_modules/body-parser/lib/types/urlencoded.js:248:13)
    at extendedparser (/home/algayalm/Työpöytä/TP/node_modules/body-parser/lib/types/urlencoded.js:144:15)
    at Function.urlencoded (/home/algayalm/Työpöytä/TP/node_modules/body-parser/lib/types/urlencoded.js:68:7)
    at file:///home/algayalm/Ty%C3%B6p%C3%B6yt%C3%A4/TP/src/index.js:35:20 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/algayalm/Työpöytä/TP/node_modules/body-parser/lib/types/urlencoded.js',
    '/home/algayalm/Työpöytä/TP/node_modules/body-parser/index.js'
  ]
}

Node.js v22.9.0
```
Even though I have installed qs, deleted and reinstalled nodeJs multiple times with no prevail. This issue suddenly started appearing when I implemented functions from aws-sdk in my project. Additionally, this is the package.json file that I have: 
```
{
  "devDependencies": {
    "@aws-sdk/util-dynamodb": "^3.656.0",
    "@types/express": "^4.17.21",
    "@types/node": "^22.5.5",
    "nodemon": "^3.1.7",
    "typescript": "^5.6.2"
  },
  "scripts": {
    "dev": "nodemon src/index.js"
  },
  "dependencies": {
    "@aws-sdk/client-cognito-identity-provider": "^3.658.1",
    "@aws-sdk/client-dynamodb": "^3.656.0",
    "@aws-sdk/client-s3": "^3.654.0",
    "@aws-sdk/client-secrets-manager": "^3.693.0",
    "aws-sdk": "^2.1691.0",
    "axios": "^1.7.7",
    "body-parser": "^1.20.3",
    "cookie-parser": "^1.4.7",
    "cors": "^2.8.5",
    "dotenv": "^16.4.5",
    "eslint": "^9.11.0",
    "express": "^4.21.1",
    "jsonwebtoken": "^9.0.2",
    "qs": "^6.13.0",
    "uuid": "^10.0.0"
  },
  "type": "module"
}

```

### Before You Submit

- [X] I have looked for issues that already exist before submitting this
- [X] My issue follows the guidelines in the README file, and follows the 'How to ask a good question' guide at https://stackoverflow.com/help/how-to-ask

**Comment by modaralgayal** [comment]
Well im having a really hard time replicating the error in a separate project, but in this this current project when i delete the line 
```
app.use(bodyParser.urlencoded({ extended: true }));
```
the error disappears.
