### ISSUE TITLE
Missing module graceful-fs

### ISSUE THREAD

**Issue by Umb3333** [nodejs/help#4519]
### Version

Node.js v20.18.0

### Platform

```text
Microsoft Windows NT 10.0.19045.0 x64
```

### Subsystem

graceful fs

### What steps will reproduce the bug?

I truely haven't a clue why this is happening. 

### How often does it reproduce? Is there a required condition?

It happens every time i run a command

### What is the expected behavior? Why is that the expected behavior?

Expected behavior is a successful installation of what ever library i'm installing.

### What do you see instead?

`node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'graceful-fs'
Require stack:
- C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\npm.js
- C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\npm.js:21:10
    at Object.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\npm.js:467:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\lib\\npm.js',
    'C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js'
  ]
}

Node.js v20.18.0`

**Comment by CodeGoura** [comment]
I want to work with this issue

**Comment by CodeGoura** [comment]
Check if graceful-fs is Installed:
 ls node_modules | grep graceful-fs // this is check  graceful-fs installed or not  
@preveen-stack  if not installed run 
npm install graceful-fs // it install the module
check required module correctly in code:
const gracefulFs = require('graceful-fs');

Clear cache and reinstall node module 
npm cache clean --force
rm -rf node_modules
npm install

**Comment by avivkeller** [comment]
@Umb3333 DId @CodeGoura's suggestion resolve the issue for you?
