### ISSUE TITLE
EADDRINUSE Error please help me 

### ISSUE THREAD

**Issue by hasanoff** [nodejs/help#513]
Hello guys I have a problem I need help
when I start the app I`ll see this problem
{ [Error: listen EADDRINUSE] code: 'EADDRINUSE', errno: 'EADDRINUSE', syscall: 'listen' }
Error: listen EADDRINUSE
at exports._errnoException (util.js:746:11)
at Server._listen2 (net.js:1158:14)
at listen (net.js:1184:10)
at Server.listen (net.js:1269:5)
at Server.listen.Server.attach (/home/root/node_modules/socket.io/lib/index.js:228:9)
at null._onTimeout (/home/root/site.js:1004:29)
at Timer.listOnTimeout (timers.js:1
https://cloud.githubusercontent.com/assets/26087493/23405368/53d79aee-fdd3-11e6-9918-608c319da93b.jpg

**Comment by thefourtheye** [comment]
This error means that there is some other process is already and listening on that port.

PS: I see that you are running your application as root. It is generally not advisable.
