### ISSUE TITLE
Error log when I try npm install...please help

### ISSUE THREAD

**Issue by sandynicot** [nodejs/help#539]
```
39308 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\yargs-parser\node_modules\camelcase
39309 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\yargs-parser
39310 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\yargs\node_modules\camelcase
39311 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\yargs\node_modules\window-size
39312 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\yargs
39313 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\yeast
39314 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\engine.io-client
39315 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\socket.io-client
39316 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\socket.io
39317 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\browser-sync
39318 silly finalize C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\angular2
39319 verbose unlock done using C:\Users\yvazquez\AppData\Roaming\npm-cache\_locks\staging-c70dbc0d50902d05.lock for C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging
39320 silly rollbackFailedOptional Starting
39321 silly rollbackFailedOptional Finishing
39322 silly runTopLevelLifecycles Finishing
39323 silly install printInstalled
39324 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
39325 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
39326 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
39326 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
39326 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
39326 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
39327 warn angular2-quickstart@1.0.0 No description
39328 verbose If you need help, you may report this error at:
39328 verbose     <https://github.com/npm/npm/issues>
39329 warn angular2-quickstart@1.0.0 No repository field.
39330 verbose If you need help, you may report this error at:
39330 verbose     <https://github.com/npm/npm/issues>
39331 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging\angular2-e87fbb08' -> 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\angular2'
39331 verbose stack     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
39331 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
39331 verbose stack     at FSReqWrap.oncomplete (fs.js:123:15)
39331 verbose stack
39331 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging\angular2-e87fbb08' -> 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\angular2'
39331 verbose stack     at Error (native)
39332 verbose cwd C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed
39333 error Windows_NT 10.0.14393
39334 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
39335 error node v6.10.0
39336 error npm  v3.10.10
39337 error path C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging\angular2-e87fbb08
39338 error code EPERM
39339 error errno -4048
39340 error syscall rename
39341 error Error: EPERM: operation not permitted, rename 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging\angular2-e87fbb08' -> 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\angular2'
39341 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
39341 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
39341 error     at FSReqWrap.oncomplete (fs.js:123:15)
39341 error
39341 error Error: EPERM: operation not permitted, rename 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging\angular2-e87fbb08' -> 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\angular2'
39341 error     at Error (native)
39341 error  { Error: EPERM: operation not permitted, rename 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging\angular2-e87fbb08' -> 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\angular2'
39341 error     at destStatted (C:\Program Files\nodejs\node_modules\npm\lib\install\action\finalize.js:25:7)
39341 error     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:264:29
39341 error     at FSReqWrap.oncomplete (fs.js:123:15)
39341 error
39341 error Error: EPERM: operation not permitted, rename 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\.staging\angular2-e87fbb08' -> 'C:\Users\yvazquez\Documents\SANDY\Proyectos\angular2-seed\node_modules\angular2'
39341 error     at Error (native) parent: 'angular2-quickstart' }
39342 error Please try running this command again as root/Administrator.
39343 verbose exit [ -4048, true ]
```

**Comment by sandynicot** [comment]
I ran command as Administrator

**Comment by lordKnighton** [comment]
Hey @sandynicot you still need help? If no response i'm gonna close this issue. 

😺  happy coding

**Comment by sandynicot** [comment]
You can close...thanks...
