### ISSUE TITLE
Scope install

### ISSUE THREAD

**Issue by youyongnian** [nodejs/help#549]
* **Node.js Version**:
* **OS**:
* **Scope (install, code, runtime, meta, other?)**:
* **Module (and version) (if relevant)**:

**Comment by bnoordhuis** [comment]
Closing.  If you actually have a question, please post it.

**Comment by aarie33** [comment]
I have the same error too. Anyone can help me ?

C:\Users\Arie Ahmad>node hello.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'C:\Users\Arie Ahmad\hello.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
