### ISSUE TITLE
getting 

### ISSUE THREAD

**Issue by itumasov** [nodejs/help#553]
* **Node.js Version**: v7.7.4
* **OS**: OSX
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: nmp v4.1.2.

Getting the following error : 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.1.2
3 info using node@v7.7.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle conversation-simple@0.1.1~prestart: conversation-simple@0.1.1
6 silly lifecycle conversation-simple@0.1.1~prestart: no script for prestart, continuing
7 info lifecycle conversation-simple@0.1.1~start: conversation-simple@0.1.1
8 verbose lifecycle conversation-simple@0.1.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle conversation-simple@0.1.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Tumasov/Documents/Builder/Car ChatBot/conversation-simple-master/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle conversation-simple@0.1.1~start: CWD: /Users/Tumasov/Documents/Builder/Car ChatBot/conversation-simple-master
11 silly lifecycle conversation-simple@0.1.1~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle conversation-simple@0.1.1~start: Returned: code: 1  signal: null
13 info lifecycle conversation-simple@0.1.1~start: Failed to exec start script
14 verbose stack Error: conversation-simple@0.1.1 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid conversation-simple@0.1.1
16 verbose cwd /Users/Tumasov/Documents/Builder/Car ChatBot/conversation-simple-master
17 error Darwin 16.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v7.7.4
20 error npm  v4.1.2
21 error code ELIFECYCLE
22 error conversation-simple@0.1.1 start: `node server.js`
22 error Exit status 1
23 error Failed at the conversation-simple@0.1.1 start script 'node server.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the conversation-simple package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node server.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs conversation-simple
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls conversation-simple
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

From this code: https://github.com/watson-developer-cloud/conversation-simple

Any idea of this is a nodejs issue or code issue?

**Comment by sam-github** [comment]
Not a node issue, and its good to cross linke when you report an issue multiple places: https://github.com/watson-developer-cloud/conversation-simple/issues/106

**Comment by gibfahn** [comment]
I'll reopen this if you don't get resolution in the module issue.
