### ISSUE TITLE
how to add  data to html page after its loaded from mysql database?

### ISSUE THREAD

**Issue by gkumarOB** [nodejs/help#570]
```js

<var http = require('http');
var mysql = require('mysql');
var ejs = require('ejs');
var fs=require('fs');
var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password:'root',
    database: 'node_form'
});

console.log('MySQL Connection details  '+connection);

http.createServer(function (request, response) 
{       

    fs.readFile('index1.html', 'utf-8', function(err, content) {
    if (err) {
      res.end('error occurred');
      return;
    }

        console.log('Creating the http server');
        connection.query('SELECT * FROM manaegr ', function(err, rows, fields)
        {   

                response.writeHead(200, { 'Content-Type': 'text/html '});
                
                        var rows = JSON.stringify(rows); 

                         var renderedHtml = ejs.render(content, {rows:rows});
                            response.end(renderedHtml);

                }
        
                 
        }); 
});

}).listen(8083);
```

```html
<html>
   <head><script type="text/javascript" src="ejs_production.js"></script>
   </head>
<body>

<table>
    <tr>
    <th>id</th>
    <th>user</th> 
    <th>PASS</th>
  </tr>
<% for(var i=0; i < rows.length; i++) { %>
   <tr>
     <td><%= rows[i].id %></td>
     <td><%= rows[i].user %></td>
     <td><%= rows[i].PASS %></td>
   </tr>
<% } %>
</table>


</body>
</html>
```
```error
MySQL Connection details  [object Object]
Creating the http server
/home/software/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: ejs:12
    10|     <th>PASS</th>
    11|   </tr>
 >> 12| <% for(var i=0; i < rows.length; i++) { %>
    13|    <tr>
    14|      <td><%= rows[i].id %></td>
    15|      <td><%= rows[i].user %></td>

Cannot read property 'length' of undefined
    at eval (eval at compile (/home/software/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:11:29)
    at returnedFn (/home/software/node_modules/ejs/lib/ejs.js:555:17)
    at Object.exports.render (/home/software/node_modules/ejs/lib/ejs.js:364:37)
    at Query._callback (/home/software/Desktop/my_ren.js:44:49)
    at Query.Sequence.end (/home/software/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/home/software/node_modules/mysql/lib/protocol/sequences/Query.js:90:8)
    at Protocol._parsePacket (/home/software/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/software/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/home/software/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/software/node_modules/mysql/lib/Connection.js:103:28)
```

**Comment by gkumarOB** [comment]
```html
<html>
   <head><script type="text/javascript" src="ejs_production.js"></script>
   </head>
<body>

<table>
	 <tr>
    <th>id</th>
    <th>user</th> 
    <th>PASS</th>
  </tr>
<% for(var i=0; i < rows.length; i++) { %>
   <tr>
     <td><%= rows[i].id %></td>
     <td><%= rows[i].user %></td>
     <td><%= rows[i].PASS %></td>
   </tr>
<% } %>
</table>


</body>
</html>

**Comment by ORESoftware** [comment]
@gkumarOB this question is much better for stackoverflow.com.

**Comment by ORESoftware** [comment]
By the way, I'd recommend using React for serverside rendering like this instead of EJS

**Comment by ORESoftware** [comment]
You also have a typo:

`<var http = require('http');`

**Comment by ORESoftware** [comment]
Your problem is probably that your query is returning an error, that is why rows is undefined
```js

  connection.query('SELECT * FROM manaegr ', function(err, rows, fields){   

               // do some error handling here  <<<<

                response.writeHead(200, { 'Content-Type': 'text/html '});
                
                        var rows = JSON.stringify(rows); 

                         var renderedHtml = ejs.render(content, {rows:rows});
                            response.end(renderedHtml);

                }
        
                 
        }); 
```

**Comment by ORESoftware** [comment]
Probably because you misspelled "manaegr"

jeez, take some pride in your work :)

**Comment by gkumarOB** [comment]
@ORESoftware thanks for pointing out the mess up.
But, still problem persist.
Now, page is loading but data is not coming through.
![screenshot from 2017-04-10 13 47 29](https://cloud.githubusercontent.com/assets/26710557/24852220/5992f906-1df4-11e7-89d1-f8392f2a7ec1.png)
![screenshot from 2017-04-10 13 47 37](https://cloud.githubusercontent.com/assets/26710557/24852221/5995fa52-1df4-11e7-89fa-f5bf7013524a.png)
