### ISSUE TITLE
I have an error - Cannot find module '../keys.json'

### ISSUE THREAD

**Issue by periyasamy25** [nodejs/help#62]
Please tell me how to solve this error?
module.js:338
throw err;
^

Error: Cannot find module '../keys.json'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:286:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object. (/var/www/ArbitrageBot/lib/apiOverlay.js:2:9)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)

**Comment by kelthenoble** [comment]
Help me help you :smile:, can you show me your folder structure? And be sure to show me the folder, if keys.json is in a folder.  Then let's see what we can do for you, after that.

**Comment by kelthenoble** [comment]
hope you solved your issue, closing for now; feel free to open another issue.
