### ISSUE TITLE
A stange error

### ISSUE THREAD

**Issue by gil0mendes** [nodejs/help#65]
Hey... I have a strange error on my code.... The original code is written in es6 and this is transpileted using babel to es5 without errors. But when I try to run the code I get the following exception:

```text
/Users/gil0mendes/Documents/Projects/stellar/core/dist/servers/websocket.js.map:1
(function (exports, require, module, __filename, __dirname) { {"version":3,"sources":["servers/websocket.js"],"names":[],"mappings":";;;;;;;;;;IAAqB,eAAe;WAAf,eAAe;0BAAf,eAAe;;;eAAf,eAAe;;yBAEtB,GAAG,EAAE,OAAO,EAAE,IAAI,EAAE;AAC9B,aAAO,CAAC,GAAG,CAAC,WAAW,CAAC,CAAC;KAC1B;;;SAJkB,eAAe;;;kBAAf,eAAe","file":"servers/websocket.js","sourcesContent":["export default class WebSocketServer {\n\n  static load(api, options, next) {\n    console.log(\"WebSocket\");\n  }\n\n}\n"],"sourceRoot":"/source/"}
                                                                        ^

SyntaxError: Unexpected token :
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /Users/gil0mendes/Documents/Projects/stellar/core/dist/initializers/servers.js:75:27
    at arrayEach (/Users/gil0mendes/Documents/Projects/stellar/core/node_modules/lodash/index.js:1289:13)
    at Function.<anonymous> (/Users/gil0mendes/Documents/Projects/stellar/core/node_modules/lodash/index.js:3345:13)
```

Code on line 75 of servers.js file:

```javascript
// (...)
// check if the server is enabled on app config
if (self.api.config.servers[server] && self.api.config.servers[server].enable == true) {
    inits[server] = require(file).default.load;
}
// (...)
```

Code on the websocket.js file:

```javascript
"use strict";

var _createClass = (function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; })();

Object.defineProperty(exports, "__esModule", {
  value: true
});

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var WebSocketServer = (function () {
  function WebSocketServer() {
    _classCallCheck(this, WebSocketServer);
  }

  _createClass(WebSocketServer, null, [{
    key: "load",
    value: function load(api, options, next) {
      console.log("WebSocket");
    }
  }]);

  return WebSocketServer;
})();

exports.default = WebSocketServer;
//# sourceMappingURL=websocket.js.map
```

**Comment by blakeembrey** [comment]
Are you loading files in a loop by reading from the directory or something similar? The error is occurring because you're requiring the `.js.map` file instead of the `.js` file.

**Comment by gil0mendes** [comment]
God ... When I'm in debug mode the babel generates the `.map` files to debug be easier. I forgot all about it :(
thank you
