### ISSUE TITLE
steamtrade bot 

### ISSUE THREAD

**Issue by userlep** [nodejs/help#655]
Hello can enyone help me?

nodevs v8.0.0

Error:
```
/home/BOT/app.js:267
            newInventory[key] = {ids:[EconItem.id],count:1,value:prices.value[key],price,color:colortest,image:EconItem.getImageURL(),preview:previewLink,type:itemType,wear:type,unstable:prices.value[key].unstable};
                                                                                   ^

ReferenceError: price is not defined
    at /home/BOT/app.js:267:84
    at Array.forEach (native)
    at /home/BOT/app.js:180:19
    at SteamCommunity.<anonymous> (/home/BOT/node_modules/steamcommunity/components/users.js:331:5)
    at Request._callback (/home/BOT/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/home/BOT/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/BOT/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)

```

Code:
``` 
newInventory[key] = {ids:[EconItem.id],count:1,value:prices.value[key].price,color:colortest,image:EconItem.getImageURL(),preview:previewLink,type:itemType,wear:type,unstable:prices.value[key].unstable};

```

**Comment by addaleax** [comment]
> Code:

That’s the line where the error comes from, but there is obviously other code around it, and in this case that code would be really helpful

**Comment by userlep** [comment]
```

	community.setCookies(cookies);
    //Starting Mobile Confirmations Loop
	community.startConfirmationChecker(10000, twofactorAuth["identity_secret"]);
    //Filling Inventory
    Bots["main"] = {};
    manager.loadInventory(730, 2, true, function (err,inventory,currencies) {
        if(err) {
            return;
        }
        var newInventory = {};
        inventory.forEach(function(EconItem) {
            EconItem.market_hash_name = EconItem.market_hash_name.replace("'", "");
            if(newInventory.hasOwnProperty(EconItem.market_hash_name)) {
                //If it already exists add a new assetid and increase count
                if(true) {//Feature that was removed
                    newInventory[EconItem.market_hash_name].count += 1;
                    newInventory[EconItem.market_hash_name].ids = JSON.parse(newInventory[EconItem.market_hash_name].ids);
                    newInventory[EconItem.market_hash_name].ids.push(EconItem.id);
                    newInventory[EconItem.market_hash_name].ids = JSON.stringify(newInventory[EconItem.market_hash_name].ids);
                    return;
                }
            }
            //Fetching item type and state
            var type = "";
            var itemType = "misc";
            var key = EconItem.market_hash_name;

            if(key.indexOf("Factory New") > -1) {
               type = "FN";
            }
            if(key.indexOf("Minimal Wear") > -1) {
                type = "MW";
            }
            if(key.indexOf("Field-Tested") > -1) {
                type = "FT";
            }
            if(key.indexOf("Well-Worn") > -1) {
                type = "WW";
            }
            if(key.indexOf("Battle-Scarred") > -1) {
                type = "BS";
            }
			if(key.indexOf("StatTrak") > -1) {
               itemType = "stattrak";
            }
            else if(key.indexOf("★") > -1) {
               itemType = "knife";
            }
            else if(key.indexOf("Factory New") > -1) {
               itemType = "weapon";
            }
            else if(key.indexOf("Minimal Wear") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Field-Tested") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Well-Worn") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Battle-Scarred") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Key") > -1) {
                itemType = "key";
            }
             //else if(key.indexOf("Knife") > -1) {
             //    itemType = "knife";
            // }
            var previewLink = "";
            //Updating preview link to be fully functional
            if(EconItem.actions != undefined) {
                previewLink = EconItem.actions[0].link;
                previewLink = previewLink.replace("%owner_steamid%", client.steamID.getSteamID64());
                previewLink = previewLink.replace("%assetid%", EconItem.assetid);
            }
            var itm = prices.value[EconItem.market_hash_name];
            //console.log(itm.price);//
            //Creating item in inventory and adding basic information

			var colortest;
			try {

                  colortest = EconItem['tags'][4]['color'];

                } catch (err) {
                  colortest = 'd8d8d8';
                }
     if(itemType == "key") {
             colortest = '4a9c4f';
            }
     if(itemType == "knife") {
             colortest = 'FDCC00';
            }

            newInventory[key] = {ids:[EconItem.id],count:1,value:prices.value[key].price,color:colortest,image:EconItem.getImageURL(),preview:previewLink,type:itemType,wear:type,unstable:prices.value[key].unstable};
			//console.log(EconItem.tags[4]);
            newInventory[key].ids = JSON.stringify(newInventory[key].ids);
        }, this);
        Bots["main"].inventory = newInventory;
    });
    //Retrieve Offer Token
    manager.getOfferToken(function(err,token) {
        myToken = token;
    });
});

```

**Comment by gireeshpunathil** [comment]
error line:
`value:prices.value[key],price`

your code:
`value:prices.value[key].price`

Looks like you showed a different code than what was run - look at the comma instead of dot before `price`. It has to be a dot. A comma separated independent `price` value cannot live there, without a key-value pair.

**Comment by userlep** [comment]
oh yes my mistake here the right code and error from the app.js
Error:
```
root@vserver-kd###:/home/BOT# node app.js
Trading BOT
Logged into Steam
Running
Body empty retrying in 10 min...
Got API key: ###
/home/BOT/app.js:267
            newInventory[key] = {ids:[EconItem.id],count:1,value:prices.value[key].price,color:colortest,image:EconItem.getImageURL(),preview:previewLink,type:itemType,wear:type,unstable:prices.value[key].unstable};
                                                                                  ^

TypeError: Cannot read property 'price' of undefined
    at /home/BOT/app.js:267:83
    at Array.forEach (native)
    at /home/BOT/app.js:180:19
    at SteamCommunity.<anonymous> (/home/BOT/node_modules/steamcommunity/components/users.js:331:5)
    at Request._callback (/home/BOT/node_modules/steamcommunity/components/http.js:67:15)
    at Request.self.callback (/home/BOT/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/BOT/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)

```
Code:
```

	community.setCookies(cookies);
    //Starting Mobile Confirmations Loop
	community.startConfirmationChecker(10000, twofactorAuth["identity_secret"]);
    //Filling Inventory
    Bots["main"] = {};
    manager.loadInventory(730, 2, true, function (err,inventory,currencies) {
        if(err) {
            return;
        }
        var newInventory = {};
        inventory.forEach(function(EconItem) {
            EconItem.market_hash_name = EconItem.market_hash_name.replace("'", "");
            if(newInventory.hasOwnProperty(EconItem.market_hash_name)) {
                //If it already exists add a new assetid and increase count
                if(true) {//Feature that was removed
                    newInventory[EconItem.market_hash_name].count += 1;
                    newInventory[EconItem.market_hash_name].ids = JSON.parse(newInventory[EconItem.market_hash_name].ids);
                    newInventory[EconItem.market_hash_name].ids.push(EconItem.id);
                    newInventory[EconItem.market_hash_name].ids = JSON.stringify(newInventory[EconItem.market_hash_name].ids);
                    return;
                }
            }
            //Fetching item type and state
            var type = "";
            var itemType = "misc";
            var key = EconItem.market_hash_name;

            if(key.indexOf("Factory New") > -1) {
               type = "FN";
            }
            if(key.indexOf("Minimal Wear") > -1) {
                type = "MW";
            }
            if(key.indexOf("Field-Tested") > -1) {
                type = "FT";
            }
            if(key.indexOf("Well-Worn") > -1) {
                type = "WW";
            }
            if(key.indexOf("Battle-Scarred") > -1) {
                type = "BS";
            }
			if(key.indexOf("StatTrak") > -1) {
               itemType = "stattrak";
            }
            else if(key.indexOf("★") > -1) {
               itemType = "knife";
            }
            else if(key.indexOf("Factory New") > -1) {
               itemType = "weapon";
            }
            else if(key.indexOf("Minimal Wear") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Field-Tested") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Well-Worn") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Battle-Scarred") > -1) {
                itemType = "weapon";
            }
            else if(key.indexOf("Key") > -1) {
                itemType = "key";
            }
             //else if(key.indexOf("Knife") > -1) {
             //    itemType = "knife";
            // }
            var previewLink = "";
            //Updating preview link to be fully functional
            if(EconItem.actions != undefined) {
                previewLink = EconItem.actions[0].link;
                previewLink = previewLink.replace("%owner_steamid%", client.steamID.getSteamID64());
                previewLink = previewLink.replace("%assetid%", EconItem.assetid);
            }
            var itm = prices.value[EconItem.market_hash_name];
            //console.log(itm.price);//
            //Creating item in inventory and adding basic information

			var colortest;
			try {

                  colortest = EconItem['tags'][4]['color'];

                } catch (err) {
                  colortest = 'd8d8d8';
                }
     if(itemType == "key") {
             colortest = '4a9c4f';
            }
     if(itemType == "knife") {
             colortest = 'FDCC00';
            }



            newInventory[key] = {ids:[EconItem.id],count:1,value:prices.value[key].price,color:colortest,image:EconItem.getImageURL(),preview:previewLink,type:itemType,wear:type,unstable:prices.value[key].unstable};
			//console.log(EconItem.tags[4]);
            newInventory[key].ids = JSON.stringify(newInventory[key].ids);
        }, this);
        Bots["main"].inventory = newInventory;
    });
    //Retrieve Offer Token
    manager.getOfferToken(function(err,token) {
        myToken = token;
    });
});

```

**Comment by gireeshpunathil** [comment]
The error message indicates that `prices.value[key]` is undefined. 
So the normal course of debugging would be to:

- print the whole list of `prices.value` as well as `key`
- validate that `prices.value[key]` does not exist, based on the printed data
- Identify which one `prices.value` or `key` which is holding unexpected data
- debug backwards to trace the bad data, using prints / live debugging
