### ISSUE TITLE
Make test error in  --napi-modules, linux

### ISSUE THREAD

**Issue by brianp007** [nodejs/help#670]
* **Node.js Version**:  v8.1.1
* **OS**: openSUSE Tumbleweed 20170609, vmlinuz-4.11.3-1-default, 64bit
* **Scope (install, code, runtime, meta, other?)**: make test 
* **Module (and version) (if relevant)**: addons-napi

All prereqs satisfied:
GNU Make 4.2.1
gcc version 7.1.1 20170530 [gcc-7-branch revision 248621] (SUSE Linux)
clang 4.9.9-1.1 (from yast)
/usr/bin/python -> python2.7*

./configure  <<  OK
make           << OK
make test  ...  
[  PASSED  ] 46 tests.
~99% OK, then ...
/usr/bin/python tools/test.py --mode=release -J \
        async-hooks doctool inspector known_issues message parallel pseudo-tty sequential \
        addons addons-napi
=== release testInstanceOf ===
Path: addons-napi/test_general/testInstanceOf
fs.js:651
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/brianp/download/websockets/node-v8.1.1/deps/v8/test/mjsunit/instanceof.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at testFile (/home/brianp/download/websockets/node-v8.1.1/test/addons-napi/test_general/testInstanceOf.js:37:23)
    at Object.<anonymous> (/home/brianp/download/websockets/node-v8.1.1/test/addons-napi/test_general/testInstanceOf.js:42:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
Command: out/Release/node --napi-modules /home/brianp/download/websockets/node-v8.1.1/test/addons-napi/test_general/testInstanceOf.js
[01:08|% 100|+ 1598|-   1]: Done
make: *** [Makefile:200: test] Error 1

```js
// I am an example of JS code
// please remove me too
```
-->

**Comment by richardlau** [comment]
See https://github.com/nodejs/node/issues/13344.
