### ISSUE TITLE
npm install fails | for folder, contents in bucket.iteritems(): AttributeError: 'MSVSProject' object has no attribute 'iteritems' gyp ERR! configure error

### ISSUE THREAD

**Issue by Fakerinc** [nodejs/help#715]
* **Node.js Version**:
```$ node -v
v8.1.3
```
* **OS**:
Windows 7 Enterprise 64 bit

* **Scope (install, code, runtime, meta, other?)**:
```
npm -v
5.0.3

grunt --version
grunt-cli v1.2.0
grunt v0.4.5

bower --version
1.8.0

tsd --version
>> tsd 0.6.5

```

* **Module (and version) (if relevant)**:

Hey guys, I am working on a project at work that requires cordova, Node and npm, bower, git, grunt, grunt-cli, and tsd. As I am a beginner in that field I dont know a lot. 
In this case, where my problem begins and I get the error, I am trying to install all dependencies via ```npm install```. I have done it before on different occasions with no errors, and clean result, but in this case I get a ton of output: 

```npm install
npm WARN deprecated bower@1.7.2: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deprecated tsd@0.6.5: TSD is deprecated in favor of Typings (https://github.com/typings/typings) - see https://github.com/DefinitelyTyped/tsd/issues/269 for more information
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN registry Unexpected warning for http://registry.npmjs.org/: Miscellaneous Warning ECONNRESET: request to http://registry.npmjs.org/gzip-size failed, reason: read ECONNRESET
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g

> phantomjs-prebuilt@2.1.14 install D:\dev\briefingWebUI-master\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at D:\Users\u585778\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing D:\dev\briefingWebUI-master\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder D:\Users\u585778\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1499435280160\phantomjs-2.1.1-windows -> D:\dev\briefingWebUI-master\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at D:\dev\briefingWebUI-master\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe

> fsevents@1.1.2 install D:\dev\briefingWebUI-master\node_modules\karma\node_modules\fsevents
> node install


> fsevents@0.3.8 install D:\dev\briefingWebUI-master\node_modules\fsevents
> node-gyp rebuild


D:\dev\briefingWebUI-master\node_modules\fsevents>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 2019, in GenerateOutput
    sln_projects, project_objects, flat=msvs_version.FlatSolution())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1778, in _GatherSolutionFolders
    return _DictsToFolders('', root, flat)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1731, in _DictsToFolders
    for folder, contents in bucket.iteritems():
AttributeError: 'MSVSProject' object has no attribute 'iteritems'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\dev\briefingWebUI-master\node_modules\fsevents
gyp ERR! node -v v8.1.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN briefingWebUI@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 (node_modules\fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@0.3.8 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1044 packages in 597.08s
```
-->

I found similar threads, but none fit perfectly to my issue and there was no solution available to me that worked. Sorry in advance if I overlooked something. I don't know how to proceed. 

Thank you for your help

**Comment by bnoordhuis** [comment]
fsevents should be in your project's package.json's optionalDependencies; it's a MacOS-only module.

**Comment by bnoordhuis** [comment]
In case you missed my edit: I suspect you do have fsevents in your optionalDependencies.  If you can't get past that error (instead of it just being a warning) you might be hitting an npm@5 bug that is still unfixed.  Try downgrading to npm@4.

**Comment by Fakerinc** [comment]
Thanks for your quick answers! 
I will try your suggestion on Monday and will come back to you.

**Comment by Fakerinc** [comment]
a lower npm version worked. 

```
$ npm --version
3.10.10
```

had a problem downgrading though. I had to uninstall node.js completly, delete the npm folder manually and the reinstall node.js again. NPM installed itself on version 3.10.10 which I am still working with and it works so far. Thank you for your help
