### ISSUE TITLE
How to retrieve TLD name servers for "com" domain?

### ISSUE THREAD

**Issue by ipeychev** [nodejs/help#752]
* **Node.js Version**: 8.2.1
* **OS**: Mac
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: dns

I'm trying to find the TLD servers of "com" domain from Node, but it fails. Here is how I would do that with "dig" command:
1. "dig NS ." - to retrieve the root servers
2. Picking some of them, for example "g.root-servers.net", then executing:
3. "dig NS @g.root-servers.net com" to get the TLD name servers for "com" domain.

This returns them successfully. However, I cannot achieve that with Node. Here is the code:

```js
const dns = require('dns');
const util = require('util');

const resolveNsAsync = util.promisify(dns.resolveNs);
const resolve4Async = util.promisify(dns.resolve4);

async function test() {
  const rootServers = await resolveNsAsync('.');
  console.log(rootServers);

  const ipRoot = await resolve4Async(rootServers[3]);
  console.log('IP ROOT', ipRoot);

  dns.setServers(ipRoot);

  try {
    const comTldServers = await resolveNsAsync('com'); // This fails, see catch clause
    console.log('COM TLD SERVERS', comTldServers);
  } catch (error) {
    // Here it comes with the following error:
    // "Error: queryNs ENODATA com"
    console.error(error);
  }
}

test();
```

Retrieving the root servers completes successfully, but retrieving the "com" fails with the following error:
"Error: queryNs ENODATA com"

How it should be done? How can I replicate the same what "dig" does?
And the second question - how can I retrieve the AUTHORITY section, as in "dig" response?

Thanks,

**Comment by styfle** [comment]
@ipeychev You might try asking this question on StackOverflow.

@Trott Should this have the `question` label?

**Comment by devsnek** [comment]
on my linux and macos devices checking both `com.` and `com` work as expected, with SOA (authority) records:

```js
> dns.resolveAny('com', console.log)
null [ { value: 'm.gtld-servers.net', type: 'NS' },
  { value: 'd.gtld-servers.net', type: 'NS' },
  { value: 'k.gtld-servers.net', type: 'NS' },
  { value: 'e.gtld-servers.net', type: 'NS' },
  { value: 'i.gtld-servers.net', type: 'NS' },
  { value: 'l.gtld-servers.net', type: 'NS' },
  { value: 'j.gtld-servers.net', type: 'NS' },
  { value: 'a.gtld-servers.net', type: 'NS' },
  { value: 'h.gtld-servers.net', type: 'NS' },
  { value: 'g.gtld-servers.net', type: 'NS' },
  { value: 'c.gtld-servers.net', type: 'NS' },
  { value: 'b.gtld-servers.net', type: 'NS' },
  { value: 'f.gtld-servers.net', type: 'NS' },
  { nsname: 'a.gtld-servers.net',
    hostmaster: 'nstld.verisign-grs.com',
    serial: 1521470215,
    refresh: 1800,
    retry: 900,
    expire: 604800,
    minttl: 86400,
    type: 'SOA' } ]
```

**Comment by gireeshpunathil** [comment]
@ipeychev - is this still outstanding?

**Comment by ipeychev** [comment]
On my machine (Mac) `resolveAny` doesn't return anything:
```
const dns = require('dns');

dns.resolveAny('com', (error, ret) => {
  if (error) {
    console.error('ERROR', error);
  } else {
    console.log('DATA', ret);
  }
});
```

```
node test.js
DATA []
```

**Comment by gireeshpunathil** [comment]
@ipeychev - this has been fixed upstream (specifically commit https://github.com/c-ares/c-ares/commit/18ea99693d63f957ecb670045adbd2c1da8a4641 ). So you could use v8.3.0 or later. I have checked your code and verified it.

$cat 752.js 
```js
require('dns').resolveAny('com', (e, o) => console.log({e: e, o: o}))
```
$821/bin/node 752.js 
```
{ e: 
   { Error: queryAny EBADRESP com
       at errnoException (dns.js:50:10)
       at QueryReqWrap.onresolve [as oncomplete] (dns.js:236:19)
     code: 'EBADRESP',
     errno: 'EBADRESP',
     syscall: 'queryAny',
     hostname: 'com' },
  o: undefined }
```
$830/bin/node 752.js
```
{ e: null,
  o: 
   [ { value: 'm.gtld-servers.net', type: 'NS' },
     { value: 'e.gtld-servers.net', type: 'NS' },
     { value: 'j.gtld-servers.net', type: 'NS' },
     { value: 'b.gtld-servers.net', type: 'NS' },
     { value: 'a.gtld-servers.net', type: 'NS' },
     { value: 'l.gtld-servers.net', type: 'NS' },
     { value: 'g.gtld-servers.net', type: 'NS' },
     { value: 'c.gtld-servers.net', type: 'NS' },
     { value: 'k.gtld-servers.net', type: 'NS' },
     { value: 'd.gtld-servers.net', type: 'NS' },
     { value: 'h.gtld-servers.net', type: 'NS' },
     { value: 'i.gtld-servers.net', type: 'NS' },
     { value: 'f.gtld-servers.net', type: 'NS' } ] }
$
```

Hope this helps!

**Comment by ipeychev** [comment]
Great!
