### ISSUE TITLE
Nodemailer not working :(

### ISSUE THREAD

**Issue by WAINGOR** [nodejs/help#755]
* **Node.js Version**: v6.5.9
* **OS**: Sierra 10.12.2
* **Module (and version) (if relevant)**: nodemailer

Hi all, I have been trying for a few days to do something very simple with Node: send an email. I tried doing so by following instructions on these 2 vids:
https://www.youtube.com/watch?v=JJ44WA_eV8E&t=29s
https://www.youtube.com/watch?v=WK1qOO9E7qk&t=201s

The last one seems so simple, but I still cant get it to work. I read somewhere that this might be because of updates on the module nodemailer which would make some of the code outdated. I ended up using this block of code (following the last of the two vids) but I just can't get it to work... I get : 
TypeError: Cannot create property 'mailer' on string 'SMTP'
    at Mail (/Users/o.vanvelsen/Desktop/Nodesaves/nodetest/node-crawler-master/node_modules/nodemailer/lib/mailer/index.js:45:33)
    at Object.module.exports.createTransport (/Users/o.vanvelsen/Desktop/Nodesaves/nodetest/node-crawler-master/node_modules/nodemailer/lib/nodemailer.js:46:14)
    at Object.<anonymous> (/Users/o.vanvelsen/Desktop/Nodesaves/nodetest/node-crawler-master/mailerTest2.js:4:32)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)

My code: 
```var nodemailer = require("nodemailer");

// create reusable transport method (opens pool of SMTP connections)
var smtpTransport = nodemailer.createTransport("SMTP",{
    service: "Gmail",
    auth: {
        user: "oscar.vanvelsen@gmail.com",
        pass: "myPassword"
    }
});

// setup e-mail data with unicode symbols
var mailOptions = {
    from: "'Oscar van Velsen ✔' <oscar.vanvelsen@gmail.com>", // sender address
    to: "oscar.vanvelsen@gmail.com", // list of receivers
    subject: "Hello ✔", // Subject line
    text: "Hello world ✔", // plaintext body
    html: "<b>Hello world ✔</b>" // html body
}

// send mail with defined transport object
smtpTransport.sendMail(mailOptions, function(error, response){
    if(error){
        console.log(error);
    }else{
        console.log("Message sent: " + response.message);
    }

    // if you don't want to use this transport object anymore, uncomment following line
    //smtpTransport.close(); // shut down the connection pool, no more messages
});
```

Does anybody know where I am going wrong here?  Or might anybody know another module that works well? I want to get an program running that sends a max of 20 mails a day.

**Comment by tniessen** [comment]
You will need to be a little more specific than "I still cant get it to work". What does not work? How do you know it does not work? Are there errors during execution? Don't you receive emails?

Sending emails has become slightly more difficult in the last years, e.g. some SMTP servers require senders to have a valid PTR DNS record etc.

**Comment by WAINGOR** [comment]
Sorry if I wasnt clear. I updated my post, I put in the error log

**Comment by bnoordhuis** [comment]
@WAINGOR Take a look at https://github.com/nodemailer/nodemailer/blob/master/examples/full.js - the first arg should be an object, not a string.

**Comment by WAINGOR** [comment]
Thanks both of you. I managed to get it to work after updating Node and adjusting my code according to the example provided by bnoordhuis. Cheers!

**Comment by BernardMarieOnzo** [comment]
I have trouble too, I'm using firebase cloud functions

TypeError: Cannot create property 'mailer' on string 'SMTP'
    at new Mail (/tmp/fbfn_9891MDU0tHTxpkqR/node_modules/nodemailer/lib/mailer/index.js:45:33)
    at Object.module.exports.createTransport (/tmp/fbfn_9891MDU0tHTxpkqR/node_modules/nodemailer/lib/nodemailer.js:52:14)
    at Object.<anonymous> (/tmp/fbfn_9891MDU0tHTxpkqR/index.js:21:30)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)

and my code is 

``

please help

**Comment by damiantoczek** [comment]
> 
> 
> Thanks both of you. I managed to get it to work after updating Node and adjusting my code according to the example provided by bnoordhuis. Cheers!

People giving such comments should get banned from github.

**Comment by bnoordhuis** [comment]
Comments like yours aren't really helpful either. What's up with the downvotes?
