### ISSUE TITLE
Issue Node.js Tradebot steam.

### ISSUE THREAD

**Issue by MarvinGdt** [nodejs/help#787]
Hello everyone. I am new in coding and I have a problem that I can not solve. I create my tradebot steam. Everything was fine then by the time I start coding the offer messages, accept, decline etc my bot does not start anymore. A message "module.js: 471" is displayed.

"module.js:471
    throw err;
    ^

Error: Cannot find module 'steam-tradeoffer-manager'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\marvin\Desktop\tradebot\bot.js:4:27)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)"

After some search, it says that the files have been installed incorrectly or that the bot.js is not in the same folder but nothing of it concerns me. The codes are good (I'm looking at a tutorial). If you have an idea, I am a taker.

**Comment by gibfahn** [comment]
Did you resolve this? It sound like an `npm install --save steam-tradeoffer-manager` might help if not.

**Comment by MarvinGdt** [comment]
Yes it’s fixed. I was need install steam tradeoffer manager manually. This has not been explained in the tutorial. Thank you for your help :)
