### ISSUE TITLE
macOS: npm run compile:mac hangs

### ISSUE THREAD

**Issue by rajivshah3** [nodejs/help#791]
* **Node.js Version**: 8.4.0
* **OS**: macOS High Sierra Beta
* **Scope (install, code, runtime, meta, other?)**: npm run compile:mac
* **Module (and version) (if relevant)**: 

I'm probably doing something wrong, but when I try to run `npm run compile:mac` on a package, I assume it triggers electron-builder. The process starts, but seems to hang at "Building DMG". Is this a npm issue or electron builder issue?

**Comment by rajivshah3** [comment]
https://github.com/nodejs/node/issues/15018

**Comment by rajivshah3** [comment]
Here's the log it referenced as well:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'compile:mac' ]
2 info using npm@5.3.0
3 info using node@v8.4.0
4 verbose run-script [ 'precompile:mac', 'compile:mac', 'postcompile:mac' ]
5 info lifecycle iota@2.4.0~precompile:mac: iota@2.4.0
6 info lifecycle iota@2.4.0~compile:mac: iota@2.4.0
7 verbose lifecycle iota@2.4.0~compile:mac: unsafe-perm in lifecycle true
8 verbose lifecycle iota@2.4.0~compile:mac: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/rajiv/wallet/node_modules/.bin:/Users/rajiv/.rvm/gems/ruby-2.4.0/bin:/Users/rajiv/.rvm/gems/ruby-2.4.0@global/bin:/Users/rajiv/.rvm/rubies/ruby-2.4.0/bin:/Users/rajiv/.rbenv/shims:/Users/rajiv/anaconda2/bin:/usr/local/opt/qt/bin:/usr/local/opt/curl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/rajiv/.rvm/bin
9 verbose lifecycle iota@2.4.0~compile:mac: CWD: /Users/rajiv/wallet
10 silly lifecycle iota@2.4.0~compile:mac: Args: [ '-c',
10 silly lifecycle   'export CSC_IDENTITY_AUTO_DISCOVERY=false && electron-builder --mac --x64' ]
11 silly lifecycle iota@2.4.0~compile:mac: Returned: code: 130  signal: null
12 info lifecycle iota@2.4.0~compile:mac: Failed to exec compile:mac script
13 verbose stack Error: iota@2.4.0 compile:mac: `export CSC_IDENTITY_AUTO_DISCOVERY=false && electron-builder --mac --x64`
13 verbose stack Exit status 130
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid iota@2.4.0
15 verbose cwd /Users/rajiv/wallet
16 verbose Darwin 17.0.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile:mac"
18 verbose node v8.4.0
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 130
22 error iota@2.4.0 compile:mac: `export CSC_IDENTITY_AUTO_DISCOVERY=false && electron-builder --mac --x64`
22 error Exit status 130
23 error Failed at the iota@2.4.0 compile:mac script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 130, true ]
```

**Comment by shellberg** [comment]
Nothing to do with npm.

I suggest you report this as an Issue at [iotaledger](https://github.com/iotaledger/wallet), and they can probably identify what error number 130 is for you, or can help you through the installation steps/scripts (and any pre-requisites) that may have/be failing.

**Comment by rajivshah3** [comment]
Ok, thanks

**Comment by rajivshah3** [comment]
Ah it turns out that 130 is the code for SIGINT, this is when I cancelled the compiling because it took more than 30 min

**Comment by lordKnighton** [comment]
@rajivshah3 Did you get this working?

**Comment by rajivshah3** [comment]
Unfortunately no. I was able to get compile:win and compile:lin working by reinstalling npm, node, and electron-builder and re downloading the source I was trying to compile, but compile:mac still seems to get stuck.

**Comment by lordKnighton** [comment]
`npm run compile:mac` Try running `npm run compile --mac` Because i don't see it in electron docs to run `npm run compile:mac` I could be wrong,  If I'm wrong show me a source where your getting this CLI command from. Other than that it really depends on how you installed these things as well. Did you take the homebrew approach to installments along with npm?

**Comment by shellberg** [comment]
@lordKnighton : The instructions @rajivshah3 was following are totally consistent with trying to install and use the `iotaledger wallet`application as they instruct, as I identified in my first response.

@rajivshah3 : Did you raise your issue with that project?

**Comment by rajivshah3** [comment]
I told them about it, they said that they didn't know why it was happening. It worked on someone else's Mac I believe

**Comment by rajivshah3** [comment]
Hi, do you guys have any other suggestions or things I can try?

**Comment by gireeshpunathil** [comment]
@rajivshah3 - is this still outstanding? were you able to get further on this?

**Comment by gireeshpunathil** [comment]
closing due to inactivity, please re-open if it is still outstanding.

**Comment by rajivshah3** [comment]
@gireeshpunathil hi, I think it fixed itself somehow. Thanks!
