### ISSUE TITLE
Workaround for http "HPE_UNEXPECTED_CONTENT_LENGTH" error?

### ISSUE THREAD

**Issue by maenthoven** [nodejs/help#816]
* **Node.js Version**: 8+
* **OS**: Windows or Ubuntu 16
* **Scope (install, code, runtime, meta, other?)**: Runtime
* **Module (and version) (if relevant)**: All http clients

Running a simple http request in nodejs for web crawling purposes.

Unfortunately, one website we're trying to crawl is configured such that it has the Content-Length header twice.

This is throwing an error on nodejs:

```
Error: Parse Error
   at Error (native)
   at Socket.socketOnData (_http_client.js:363:20)
   at emitOne (events.js:96:13)
   at Socket.emit (events.js:188:7)
   at readableAddChunk (_stream_readable.js:176:18)
   at Socket.Readable.push (_stream_readable.js:134:10)
   at TCP.onread (net.js:548:20) bytesParsed: 239, code:'HPE_UNEXPECTED_CONTENT_LENGTH' },
  isOperational: true,
  bytesParsed: 239,
  code: 'HPE_UNEXPECTED_CONTENT_LENGTH' 
```

I'm trying to find a workaround that doesn't involve downgrading my nodejs server... Any ideas?

**Comment by gireeshpunathil** [comment]
$ cat 816.js
```js
var h = require('http')
require('net').createServer(c => {
    c.end('HTTP/1.1 200 OK \nContent-Length: 3495 \nContent-Length: 3495 \r\n')
}).listen(1234, () => {
  var q = h.request({port: 1234, method: 'GET'}, (s) => {
})
})
```
$ node 816.js
```trace
events.js:169
      throw er; // Unhandled 'error' event
      ^

Error: Parse Error
    at Socket.socketOnData (_http_client.js:412:20)
    at Socket.emit (events.js:184:13)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:248:11)
    at Socket.Readable.push (_stream_readable.js:205:10)
    at TCP.onread (net.js:603:20)
Emitted 'error' event at:
    at Socket.socketOnData (_http_client.js:418:9)
    at Socket.emit (events.js:184:13)
    [... lines matching original stack trace ...]
    at TCP.onread (net.js:603:20)
```
$ cat 816_good.js
```js
var h = require('http')
require('net').createServer(c => {
    c.end('HTTP/1.1 200 OK \nContent-Length: 3495 \nContent-Length: 3495 \r\n')
}).listen(1234, () => {
  var q = h.request({port: 1234, method: 'GET'}, (s) => {
})
  q.on('error', (e) => {
    console.log('error caught: ' + e)
  })
})
```
```trace
error caught: Error: Parse Error
```

Hope this helps. In short, you just need to install an error handler on the `request` object.

**Comment by gireeshpunathil** [comment]
closing as answered, please re-open if this did not help you.
