### ISSUE TITLE
npm homebridge unexpected token

### ISSUE THREAD

**Issue by bitzebou** [nodejs/help#839]
* **Node.js Version v4.4.7**:
* **Debian Jessie Raspberrypi**:
* **npm SyntaxError: Unexpected token **:

Installed node-v4.4.7-linux-armv7l on RaspberryPi (to run homebridge)
and it already worked.
now after 1 year (without anything has been changed) cannot start
homebridge due to not able to run any npm command (not even npm -v)
always get the error message

```
timers.js:3
const Timer = pro!dss.bi�dinc('timer_wrap%).Timeb;
SyntaxError: Unexpected token !
    at runInThisContext (node.js:871:18)
    at NativeModule.compile (node.js:955:14)
    at Function.NativeModule.require (node.js:904:18)
    at Function.startup.globalTimeouts (node.js:190:33)
    at startup (node.js:31:13)
    at node.js:968:3
```

**Comment by gireeshpunathil** [comment]
@bitzebou - is this still a problem?

**Comment by gireeshpunathil** [comment]
closing due to inactivity, please re-open if it is still outstanding.
