### ISSUE TITLE
Crypto.setEngine doesn't work on Windows

### ISSUE THREAD

**Issue by intesky** [nodejs/help#848]
* **Node.js Version**: 6.11.3
* **OS**: Windows
* **Scope (install, code, runtime, meta, other?)**: code
* **Module (and version) (if relevant)**: crypto

Hi,
we are trying to use crypto.setEngine and it fails with error 
"crypto.js:632
  return binding.setEngine(id, flags);
                 ^

Error: error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library
    at Error (native)
    at Object.setEngine (crypto.js:632:18)
    at Object.<anonymous> (C:\utils\nodejs\node-v6.11.3\Debug\test2.js:5:8)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)"

It might be because dynamic loading is not allowed for windows?
Setting from openssl.gypi:
'openssl_defines_all_win': [
      'DSO_WIN32',
      '_CRT_SECURE_NO_DEPRECATE',
      # following two defines are moved from openssconf.h
      'OPENSSL_NO_DYNAMIC_ENGINE',
      # to avoid build errors on Win. See openssl/engines/e_capi.c
      'OPENSSL_NO_CAPIENG',
    ],

What has to be changed in order to enable use of dynamic engine?

Appreciate your help,
Inna

**Comment by bnoordhuis** [comment]
Untested but I believe you need to set the `OPENSSL_ENGINES` environment variable to the directory where the engine DLL is located.

`OPENSSL_NO_DYNAMIC_ENGINE` is not related, it controls whether the builtin hardware engines use dynamic loading, but those are disabled in node.js anyway.

**Comment by intesky** [comment]
OPENSSL_ENGINES is added.
The problem not that engine is not found.
Node finds the engine, but fails in binding.

**Comment by bnoordhuis** [comment]
Can you be more specific?  What error do you get now?

**Comment by intesky** [comment]
Same error:

"crypto.js:632
return binding.setEngine(id, flags);
^

Error: error:25078067:DSO support routines:WIN32_LOAD:could not load the shared library
at Error (native)
at Object.setEngine (crypto.js:632:18)
at Object. (C:\utils\nodejs\node-v6.11.3\Debug\test2.js:5:8)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:389:7)"

**Comment by gireeshpunathil** [comment]
@intesky - is this still an issue for you?

**Comment by gireeshpunathil** [comment]
closing due to inactivity
