### ISSUE TITLE
streams testing not passing

### ISSUE THREAD

**Issue by benhalverson** [nodejs/help#852]
* **Node.js Version**:  v9.0.0-pre
* **OS**: OSX 10.12.6
* **Scope (tests)**:
* **Module (_stream_readable)**:

I'm working on this pull request. [#15042](https://github.com/nodejs/node/pull/15042) I've finished making my changes and now I'm having some trouble getting the tests to pass.

```js
'use strict';
const common = require('../common');
const stream = require('stream');
const assert = require('assert');

const readable = new stream.Readable();

assert.throws(() => readable.read(), common.expectsError({
  type: Error,
  message: 'ERR_STREAM_READ_NOT_IMPLEMENTED'
}));
```

The error I'm getting is this.
```
Path: parallel/test-stream-readable-with-unimplemented-_read
assert.js:44
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 'ERR_STREAM_READ_NOT_IMPLEMENTED' === undefined
    at Object.<anonymous> (/Users/benhalverson/projects/node/test/common/index.js:711:12)
    at Object.<anonymous> (/Users/benhalverson/projects/node/test/common/index.js:517:15)
    at expectedException (assert.js:650:19)
    at innerThrows (assert.js:684:21)
    at Function.throws (assert.js:701:3)
    at Object.<anonymous> (/Users/benhalverson/projects/node/test/parallel/test-stream-readable-with-unimplemented-_read.js:8:8)
    at Module._compile (module.js:600:30)
    at Object.Module._extensions..js (module.js:611:10)
    at Module.load (module.js:521:32)
    at tryModuleLoad (module.js:484:12)
Command: out/Release/node /Users/benhalverson/projects/node/test/parallel/test-stream-readable-with-unimplemented-_read.js
=== release test-stream-unshift-read-race ===
Path: parallel/test-stream-unshift-read-race
ok
```

The other test that is failing is this one... 
```js
assert.js:44
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: 'ERR_STREAM_PUSH_AFTER_EOF' === undefined
    at Object.<anonymous> (/Users/benhalverson/projects/node/test/common/index.js:711:12)
    at Object.<anonymous> (/Users/benhalverson/projects/node/test/common/index.js:517:15)
    at expectedException (assert.js:650:19)
    at innerThrows (assert.js:684:21)
    at Function.throws (assert.js:701:3)
    at pushError (/Users/benhalverson/projects/node/test/parallel/test-stream-unshift-read-race.js:71:10)
    at Timeout._onTimeout (/Users/benhalverson/projects/node/test/parallel/test-stream-unshift-read-race.js:64:25)
    at ontimeout (timers.js:474:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:258:5)
Command: out/Release/node /Users/benhalverson/projects/node/test/parallel/test-stream-unshift-read-race.js
[02:41|% 100|+ 1893|-   2]: Done
make: *** [test] Error 1

```

**Comment by Trott** [comment]
It sure *looks* like what indutny suggested in IRC: Tests are running with a version of Node.js that doesn't contain the changes to `lib/_stream_readable.js`. In IRC, you said you ran it with `./configure && make -j8 test`. Is it at all possible that you have the changes to the tests in your directory but not the changes to `lib/_stream_readable.js`?

**Comment by Trott** [comment]
I started a CI run for the PR. I'm not posting it to the issue because there are changes that mcollina requested that need to happen. But if they pass in CI, that would surely suggest that what's going on is what I wrote in the previous comment.

**Comment by refack** [comment]
You could "Step into" the lib code with [Chrome's devtools](https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27) and see the lib code.
```
out/Release/node --inspect-brk /Users/benhalverson/projects/node/test/parallel/test-stream-unshift-read-race.js
```
