### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by HERTYH** [nodejs/help#930]
I try use 2 version:
8.4.0
8.8.1
OS:
Windows 10 15063.608

My program worked, but after "death screen"(blue screen) I try to run my program and get this :

Error: spawn C:\Program Files\nodejs\node.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:655:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
C:\Program Files\nodejs\node_modules\npm\lib\npm.js:51
      throw new Error('npm.load() required')
      ^
Error: npm.load() required
    at Object.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:51:13)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:374:26)
Error: spawn C:\Program Files\nodejs\node.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:655:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
C:\Program Files\nodejs\node_modules\npm\lib\npm.js:51
      throw new Error('npm.load() required')
      ^
Error: npm.load() required
    at Object.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:51:13)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:374:26)
I also trying to reinstall node.js,install in different location, but I get this error all time and don't know what to do.I need help!My program don't work only on my computer(about 300 people don't have this problem).

**Comment by HERTYH** [comment]
At version 9.0 and LTS 8.9 same problem...

**Comment by arenacheck** [comment]
same for me

**Comment by HERTYH** [comment]
I delete nodejs using this https://stackoverflow.com/questions/20711240/how-to-completely-remove-node-js-from-windows

**Comment by gireeshpunathil** [comment]
@HERTYH - were you able to resolve your issue?

**Comment by gireeshpunathil** [comment]
closing due to inactivity, please re-open if it is still outstanding
