### ISSUE TITLE
node_modules\mysql\lib\protocol\Parser.js:82 throw err

### ISSUE THREAD

**Issue by albayco** [nodejs/help#957]
hello,
im getting this error.

* **Node.js Version* 8.9.0*:
* **OS* windows*:

node server.js
C:\laragon\www\node\node_modules\mysql\lib\protocol\Parser.js:82
        throw err;
        ^

TypeError: Cannot read property 'insertId' of undefined
    at Query._callback (C:\laragon\www\node\server.js:429:30)
    at Query.Sequence.end (C:\laragon\www\node\node_modules\mysql\lib\protocol
uences\Sequence.js:96:24)
    at Query.ErrorPacket (C:\laragon\www\node\node_modules\mysql\lib\protocol\
ences\Query.js:94:8)
    at Protocol._parsePacket (C:\laragon\www\node\node_modules\mysql\lib\proto
Protocol.js:274:23)
    at Parser.write (C:\laragon\www\node\node_modules\mysql\lib\protocol\Parse
:77:12)
    at Protocol.write (C:\laragon\www\node\node_modules\mysql\lib\protocol\Pro
l.js:39:16)
    at Socket.<anonymous> (C:\laragon\www\node\node_modules\mysql\lib\Connecti
s:96:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_nodeream_readable.js:263:12)

C:\laragon\www\node>node_modules\mysql\lib\protocol\Parser.js:82

server.js

line 419-440

```
function samur(datadad){
    var data=idKontrol(datadad);
    var varmi=gototogo[data];
    if(varsay){
        if(data!=0 && gototogo[data].durum==0){
            if(oyun==0){
                oyun=2;
                var post  = {saved1:"0",saved2:"0",final:"0",periot:winner,winto:wingo};
                var gus= cio.query('INSERT INTO game SET ?', post, function(e3, r3){
                    seans=r3.insertId;
                    io.sockets.in("gamescreen").emit("games",game,gamel,gamesx);
                });
            }
            gamemap+=1;
            gototogo[data].durum=1;
            gamelevel+=","+data;
            io.sockets.in("gamescreen").emit("source", data);
            gatpoint(data);
        }
    }
}

```

can you help me, thanks...

**Comment by bnoordhuis** [comment]
You need to check if `e3` is truthy.  If it is, it's an error object.

Not to sound harsh but you could have figured that out yourself, it's well-covered in node-mysql's documentation.
