### ISSUE TITLE
Watson Node SDK throwing error while post

### ISSUE THREAD

**Issue by SandipKumarKundu** [nodejs/help#969]
HI I am getting below error while calling watson.message service from office laptop .
{ Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' }

Though same code and service from home desktop.
Please guide me How to resolve same issue in Office.
I am new to node

**Comment by gireeshpunathil** [comment]
can you please try these recommendations from [npm](http://blog.npmjs.org/post/78165272245/more-help-with-selfsignedcertinchain-and-npm)?

**Comment by gireeshpunathil** [comment]
ping @SandipKumarKundu

**Comment by gireeshpunathil** [comment]
closing due to inactivity.
