### ISSUE TITLE
npm install appium gives ETIMEDOUT for chrome driver

### ISSUE THREAD

**Issue by Sriramkukkadapu-git** [nodejs/help#974]
* **Node.js Version**: 8.9.1
* **OS**: Mac OSX 10.11.6
* **Scope (install, code, runtime, meta, other?)**: install
* **Module (and version) (if relevant)**: appium

When i am trying to install appium via npm i am facing below error.

I am using below command to install appium.
```
sudo npm install -g appium@1.6.0 --unsafe-perm=true --allow-root
```
My proxy is set as below.
npm get proxy gives
`http://<domain>.com:80/`
npm get https-proxy gives
`http://<domain>.com:80/`

when i try to download chrome driver separately with curl command it downloads successfully. So i am not able to identify the root cause for this issue. Some people mentioned i should go out of business network (use personal or other network) to get this worked. But that seems a work around but not a solution.
```
info Chromedriver Install Downloading http://chromedriver.storage.googleapis.com/2.21/chromedriver_mac32.zip...
RequestError: Error: connect ETIMEDOUT 216.58.220.240:80
    at new RequestError (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/appium/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/usr/local/lib/node_modules/appium/node_modules/request/request.js:187:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/usr/local/lib/node_modules/appium/node_modules/request/request.js:813:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appium-chromedriver@2.9.2 install: `node install-npm.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appium-chromedriver@2.9.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Can someone pls suggest how do i proceed further.

Thanks

**Comment by bnoordhuis** [comment]
I'm going to guess that that install-npm.js from appium does not respect the `npm_config_proxy` environment variable - that's what npm sets when it executes the script.

Do you have `http_proxy` set in your environment?  If not, try that.  If yes, then you know it doesn't honor that either - time to open an issue with them. =)

**Comment by siddharthmittal97** [comment]
Hello 

I am facing similar Issue 

How to resolve this Issue ?

 ChromeDriver installation failed AxiosError: connect ETIMEDOUT
