### ISSUE TITLE
error: not found the ...cli.js after install express node_modules

### ISSUE THREAD

**Issue by coderlongren** [nodejs/help#982]
Node.js Version 9.8:
OS  windows10**:
Scope (install, code, runtime, meta, other?)**:
Module (and version) "express"
---
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by gireeshpunathil** [comment]
@coderlongren - node version 9.8 hasn't been released by this community. Where did you get that version from? or is it a typo?

can you please list down the commands you tried?

**Comment by laukstein** [comment]
@gireeshpunathil I recently experience same issue while running `npm-check -u -g`, shows

```
module.js:538
    throw err;
    ^

Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm-check\bin\cli.js'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Having latest Nodejs 8.9.1 LTS

```
> npm -g -v
5.6.0
```

**Comment by gireeshpunathil** [comment]
ping @coderlongren @laukstein - is this still an issue for you? If so, can you please list down the commands you tried?

**Comment by laukstein** [comment]
@gireeshpunathil I had no such issue on v9.3.0, and in recently updated NodeJS v9.7.1.
I don't remember what fixed it, it might be was missing Windows System environment variables

```
%USERPROFILE%\AppData\Roaming\npm
%USERPROFILE%\AppData\Roaming\npm-cache
```

**Comment by gireeshpunathil** [comment]
ok, closing then. Please re-open if it is still an issue. thanks!

**Comment by Vijayvilam** [comment]
simple restart will solve the issue
