### ISSUE TITLE
Error: Cannot find module 'node-linux-arm/package.json'

### ISSUE THREAD

**Issue by Judahh** [nodejs/help#986]
* **Node.js Version**:  9.2.0, 9.0.0, 8.9.1
* **OS**: Linux Raspbian 9
* **Scope (install, code, runtime, meta, other?)**: npm install
* **Module (and version) (if relevant)**: node-linux-arm@9.0.0

Every time I try to run npm install I got this error:

```sh
npm ERR! code E404
npm ERR! 404 Not Found: node-linux-arm@9.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-11-23T11_16_13_907Z-debug.log
module.js:544
    throw err;
    ^

Error: Cannot find module 'node-linux-arm/package.json'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.resolve (internal/module.js:18:19)
    at ChildProcess.<anonymous> (/home/projects/HorusSoftware/node_modules/node-bin-setup/index.js:18:27)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node@9.0.0 preinstall: `node installArchSpecificPackage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node@9.0.0 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2017-11-23T11_16_26_670Z-debug.log
```

**Comment by bnoordhuis** [comment]
Can you include the actual npm command you ran?

FWIW, the stack trace suggests an issue with node-bin-setup, which lives over at https://github.com/aredridel/node-bin-gen.

If you move the discussion there, please close this issue.
